### ISSUE TITLE
Content type for collection of exercises?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#100]
Collection of exercises should have an extra contentType if possible.
@Entkenntnis you said you could add that, or do we need to change the API for that?

Currently they show as `TaxonomyTerm`:
[Example](https://frontend.dal123.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten/addition/aufgaben-schriftlichen-addition-nat%C3%BCrlicher-zahlen
)

**Comment by Entkenntnis** [comment]
the type is currently not exposed yet, but you can add it, look at this lines:

https://github.com/serlo/frontend/blob/560c213266cbf7babb222a3be3a94fb0a8a1b9c7/src/fetcher/serlo-api.tsx#L456-L464

add `data.type = reqData.uuid.type` - now you have an additional field on `data` for the type of the taxonomy term and it should appear here: https://frontend.dal123.now.sh/api/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten/addition/aufgaben-schriftlichen-addition-nat%C3%BCrlicher-zahlen

collections of exercises have the type `topicFolder`

**Comment by elbotho** [comment]
Thanks!
