### ISSUE TITLE
Mobile shortcut icon

### ISSUE THREAD

**Issue by Knorrke** [serlo/frontend#1001]
Define an icon for mobile homescreen shortcut. Maybe also add a popup on mobile devices with instructions on creating such a shortcut.

Maybe this helps: https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by kulla** [comment]
@elbotho @Entkenntnis This is already implemented, right? If so, please close this issue :smile:

**Comment by elbotho** [comment]
We have icons in place. Not sure how easy it is to create a shortcut.
But I'd group this with considerations to turn Serlo into a PWA (technically not many steps left, but probably some ux work) which is not a priority atm.

(ps: Serlo Sustainability already has a PWA prototype https://plantbuddies.serlo.org/ :)
