### ISSUE TITLE
Resolve injections server side

### ISSUE THREAD

**Issue by Knorrke** [serlo/frontend#1002]
Problems with the current approach:
- Longer loading times and more data
- Google Analytics get's confused and measures this as (really early) switch to another site
- iframe resizing does work, but it's not as clean as the actual content (e.g. collapse animations of spoilers)

So instead of resolving the injections using an `iframe` and the content-API (as implemented in `@edtr-io/plugin-serlo-injection`) we should resolve these serverside.

**Comment by kulla** [comment]
@Entkenntnis @elbotho Is this still an issue in the new frontend?

**Comment by elbotho** [comment]
We are not using iframes for injections any more.
