### ISSUE TITLE
replace mathjax with katex

### ISSUE THREAD

**Issue by Knorrke** [serlo/frontend#1003]
In the new editor we'll be using [KaTeX ](https://github.com/Khan/KaTeX) for rendering math formulas, so it makes sense to get rid of mathjax altogether. Also we should check if the server side rendering to HTML by KaTeX is an option.

**Comment by kulla** [comment]
@elbotho @Entkenntnis In the new design we only have katex, right? Please close this issue, when it is not relevant any more

**Comment by elbotho** [comment]
✅
