### ISSUE TITLE
Refactor frontend ISR behavior

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1008]
next.js will allow purging SSG-sites programmatically in the future (https://github.com/serlo/frontend/issues/853#issuecomment-837510333). Depending on the concrete implementation, we can explore some further caching strategies.

**Comment by Entkenntnis** [comment]
Maybe next.conf will reveil some new features :grinning: ?

**Comment by elbotho** [comment]
Since nextjs 11 did not address this I will close this until we hear some news, okay?
