### ISSUE TITLE
Unknown paths turn into 500 instead of 404

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#101]
e.g. https://frontend.dal123.now.sh/woah!

**Comment by inyono** [comment]
API-wise, this should already work. For the 10% phase, this will probably be handled via Cloudflare Worker (since we also need to catch legacy backend routes), but we need an appropriate 404 in the future, of course.

**Comment by Entkenntnis** [comment]
Is #111 enough for now?

**Comment by inyono** [comment]
Follow up from my side: #112
