### ISSUE TITLE
Manual reload necessary after updating profile

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1013]
If you edit your publish profile (/user/settings) and save, the new frontend needs a manual refresh to show the latest change.

**Comment by inyono** [comment]
This is currently necessary because of https://github.com/serlo/serlo.org/issues/629. Basically: API rejects the cache update from legacy's listener because the value doesn't include roles yet.

**Comment by inyono** [comment]
Should be fixed now (staging & prod).

**Comment by elbotho** [comment]
Thank you for the fix. 
The redirect is still to fast so the frontend displays the old value at first. 
We have this issue in other places as well and "fix" it by e.g. adding a hash to the redirect so we can do a reload.
Long term a mutation will actually fix this :)

**Comment by Entkenntnis** [comment]
Maybe this is related to ISR caching behaviour - anyway, adding a hash would be a solution for the meantime.

**Comment by elbotho** [comment]
Okay, added a hack in above commit that should work for now until we have a mutation.
