### ISSUE TITLE
Show Comments without login in staging

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1016]
Currently comments are hidden for non authed users.

**Comment by Entkenntnis** [comment]
Any ideas why this is happening on staging? Can't reproduce in production and locally --- 

Note: Ok, it looks like the guard is blocking the comment form: renderContent is within a guard. Is this intended this way?

**Comment by elbotho** [comment]
See https://github.com/serlo/frontend/commit/697f9ba545a8fd492d6b4d38a72df53257ecaa34#r50743066

**Comment by Entkenntnis** [comment]
Fixed with 2a1d071f6cca18e2b9123f5bb5b3fb12e2fab4c6 - alright, I have probably forgot to delete something after a test ^^

**Comment by elbotho** [comment]
Seems to be working again, thanks!
