### ISSUE TITLE
Curious: Tax Link without href

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#102]
At this [site](http://localhost:3000/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten/addition) the link to _"Aufgaben Rechengesetze und Rechentricks der Addition"_ does not have a href.

**Comment by elbotho** [comment]
@Entkenntnis What do you think? 
Quickfix filter empty href's in frontend, or do you have an Idea where the problem could come from?

**Comment by Entkenntnis** [comment]
very good catch - in this case, the alias is missing, but we can fallback to id
