### ISSUE TITLE
Id 0 in revision url

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1022]
> example url https://frontend-git-fix-license-error-serlo.vercel.app/entity/repository/compare/0/3936
> The `0` in the url should be gone in staging/production I think.

That's an independent frontend issue. Not sure where you get the `0` from but this only happens on frontend.serlo.org (which isn't handled via CF Worker redirects).

_Originally posted by @inyono in https://github.com/serlo/frontend/issues/1010#issuecomment-838714935_

**Comment by elbotho** [comment]
Not sure this is really an issue since it works fine with CF in place.

**Comment by Entkenntnis** [comment]
Have you contructed the url https://frontend-git-fix-license-error-serlo.vercel.app/entity/repository/compare/0/3936 manually? In this case, I do agree, this isn't really an issue.

**Comment by elbotho** [comment]
No, it's a fallback.
It originates [here](https://github.com/serlo/frontend/blob/6bf7fb78f00b2e50802d49c5288a15e2b900c30d/src/fetcher/request-page.ts#L46) and it is only visible when you enter a revision id directly and CF worker is not active (e.g. https://frontend.serlo.org/162707).
Also the 0 or any other number is not used.

Basically a hack for dev.

**Comment by Entkenntnis** [comment]
Alright - in this case we can use the alias to handle it less hacky, see linked PR

**Comment by elbotho** [comment]
Nice, obviously way nicer now that we have the alias available. Thanks!
