### ISSUE TITLE
Test Subscription View and enable in CF

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1027]
If the new subscription view is stable enough we can enable it in cf. Can we do this without breaking existing behaviour?

~Related: https://github.com/serlo/api.serlo.org/issues/360~

**Comment by elbotho** [comment]
Apart from the `sendEmail` functions everything should work.
Currently [showing](https://github.com/serlo/api.serlo.org/issues/231)/[editing](https://github.com/serlo/api.serlo.org/issues/360) this setting is not supported by the API.

**Comment by Entkenntnis** [comment]
I'm closing this for the moment because we already have enough elements in the current release.

Reopen if we have officially prioritized this element.

**Comment by elbotho** [comment]
This is live and ready for testing in staging.

**Comment by Entkenntnis** [comment]
@kulla We can add `/subscriptions/manage` as route for the frontend.

**Comment by kulla** [comment]
> @kulla We can add `/subscriptions/manage` as route for the frontend.

Is live

**Comment by elbotho** [comment]
that was quick 😮
