### ISSUE TITLE
"Unexpected error" message on notification page

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1032]
Just let the page open for a bit. On staging, I get "unexpected error" with "m.data.map is not a function" in the console. (data is probably null)

**Comment by elbotho** [comment]
Can reproduce (sometimes).
Page not def. has a life of it's own 🦝. After the mutation to set the notifications to read it updates and then sets a new set to read after some time and so on. Why the data comes up empty? No clue.
