### ISSUE TITLE
Missing notification updates

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1033]
Listener are missing, which leads to following behaviour:

1. Login in window 1
2. Use window 2 and login with another account
3. Make change in window 2 for content that the user in window 1 has subscripted
4. Problem: Even after reload, window 1 will not show notification

But if you open legacy in window 1, e.g. while editing, the notification is shown. Afterwards, the notification is visible in the new frontend in window 1.

Correct behaviour: In step 4, new notification should be visible.

**Comment by elbotho** [comment]
deploy of fix is on the way.

**Comment by elbotho** [comment]
Mostly fixed ;)

(there seems to be a problem that threads are not registered, in legacy and sometimes notifications are delayed. but good enough for now imho.)
