### ISSUE TITLE
Thread form looks misaligned

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1034]
The start new thread form looks a bit of (padding-top too much?):

![grafik](https://user-images.githubusercontent.com/13507950/118261595-0e2ee780-b4b4-11eb-84dd-00591fff7451.png)

(I have doubled checked - it's not a regression of the tailwind refactoring)

@elbotho Is this intended? Otherwise, I would like to move the textarea a bit into the middle of the field.

**Comment by elbotho** [comment]
Oh dear, was not logged in in Firefox for a while.
If you work on this please use chromium as reference for how it is intended to look.
It's not perfect either, but pretty good. The idea is that the button is centered for the slim version and on the bottom right when the textarea size increases.

**Comment by Entkenntnis** [comment]
OK, it looks better in chromium:

![grafik](https://user-images.githubusercontent.com/13507950/118263028-04a67f00-b4b6-11eb-8df6-36c40e61d80f.png)

Will investigate what firefox is mising here.

**Comment by Entkenntnis** [comment]
"Web-Dev is a minefield" :)

It looks like a known issue and is a problem of unclear specs, etcs ...: https://github.com/Andarist/react-textarea-autosize/issues/316

Will investigate how this can be worked around.
