### ISSUE TITLE
Authorization: Login can't create new content

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1044]
In Taxonomy users should be able to create a new content (like an article).
Not sure if we have to solve this here or in the API.

**Comment by Entkenntnis** [comment]
Good question - should check this.

Creating new articles should be fine (it's something login is already able to do) - and review is still handled by legacy.

**Comment by elbotho** [comment]
~I see, I can create new content in staging but not production.
That's the issue here probably.
Authorization should work the same in production and staging, yes? (@inyono)~

**Comment by inyono** [comment]
Auth is pretty much the same in prod and staging (i.e. same Hydra setup etc.). Mind that the api version in staging is newer, not sure if the Sentry integration stuff broke something unintentionally.

**Comment by elbotho** [comment]
Okay, prod and staging have the same behaviour (might have been my error before).
But for role login `canDo(Uuid.create(customTypeToAuthorizationType(data.type)))` returns false for `TaxonomyTerm`s.

**Comment by inyono** [comment]
That's intended. You need a special role to create TaxonomyTerms.

**Comment by elbotho** [comment]
Than that is the frontend bug I think, because the question here should be: Can the user create Entities inside a TaxonomyTerm?
(currently then only users that can create TaxonomyTerms can create any entities)

**Comment by inyono** [comment]
From the point of view of permissions, the "inside a TaxonomyTerm" is not relevant. I.e. the only question is: can you create Entities.

**Comment by Entkenntnis** [comment]
Yes, I've messed up the semantics here - #1054 contains the correct code.
