### ISSUE TITLE
Render legacy latex in comments

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1059]
Example: http://de.serlo.org/mathe/2193/prozentrechnung-mittels-formeln

Convert %% - %% legacy latex comments into katex spans (for backward compatibility)

Not intended as full math feature.

**Comment by inyono** [comment]
Just a heads up: this feature might break with the new commenting system (and we also haven't discussed in detail how we are going to handle legacy comments).

**Comment by Entkenntnis** [comment]
Yes, math formulas need to be converted. This change was only intended as a "cosmetic" quickfix - there is no official support for math formulas in comments yet.
