### ISSUE TITLE
Menu: Add user profile image instead of icon faUser

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1062]
An idea: We can add the user profile image to the top menu bar:

![2021-05-31-151313_213x163_scrot](https://user-images.githubusercontent.com/1327215/120198928-f4670180-c222-11eb-86bc-98d309fdd4ba.png)

A quick investigation showed me that some refactorings need to be done before and thus I didn't directly create a PR. However for a reminder I created this issue.

**Comment by elbotho** [comment]
(off topic: is the + and number inside the bell always offset like this for you? what's you browser?)

**Comment by kulla** [comment]
> (off topic: is the + and number inside the bell always offset like this for you? what's you browser?)

Side-Effect from hacking the site with the web inspector of firefox in order to create the image. :smile:
