### ISSUE TITLE
Log out after 2h

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1090]
If logged in in the frontend, you will get logged out after 2h.

Needs investigation.

**Comment by Entkenntnis** [comment]
The frontend sometimes show that you are logged in, but you can't see the buttons -> authorization request is silently failing.

This often happens after a certain timespan (?) or after deployments. (server? api?)

**Comment by elbotho** [comment]
Does this also happen in production?

**Comment by Entkenntnis** [comment]
Yes, this happened twice for me on production - relogin solves the issue.

**Comment by Entkenntnis** [comment]
Botho found a failed refresh:

/auth-refresh -> Status 500 -> Token not valid

**Comment by Entkenntnis** [comment]
/api/auth/auth-refresh is the culprit here: This route is often very slow and fails to refresh to token sometimes, which leads to a messy state in the frontend.

Quickfix for the moment: As long as refresh is not working reliably, don't attempt to refresh, but delete token and refresh window -> avoid invalid states in the frontend and let user relogin.

https://github.com/serlo/frontend/blob/d82e6527e5a4bad85240b51d10f070be91be772b/src/auth/use-authentication.ts#L33-L45
