### ISSUE TITLE
Quickwin: Community Wall

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1096]
#1085 integrating the community wall into the existing website.

**Comment by elbotho** [comment]
We still need content for that:
- Who should be featured (and is okay with that) – at least 10 ppl
- They than have to add their profile pics
- What roles do we want to show for them?

TODO: 
- [x] Randomize positions
- [x] Maybe randomize persons too if we have a bigger pool
- [x] Limit to 7 on mobile

**Comment by Entkenntnis** [comment]
@kulla As far as I am informed you already have a list of people?

**Comment by kulla** [comment]
> @kulla As far as I am informed you already have a list of people?

No, Theresa should have the list. I'll send you a link I got from here some weeks ago via Slack...

**Comment by Entkenntnis** [comment]
I have all persons that have a suitable image -> we have a pool of 11 persons that are randomly selected for the community wall now.

**Comment by elbotho** [comment]
Thanks everyone, this is done and now part of #1121.
