### ISSUE TITLE
Representation error in math formula with ratios

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1099]
See https://de.serlo.org/mathe/2543/2543 in the new design:

![2021-06-08-193245_168x94_scrot](https://user-images.githubusercontent.com/1327215/121231124-51506080-c890-11eb-815f-c83ff473bf5e.png)

LaTeX-Code seem to be right (`f(x)=\frac{1}{\sqrt[3]{e^x}}`) and it should rendered as:

![2021-06-08-193346_120x69_scrot](https://user-images.githubusercontent.com/1327215/121231237-7644d380-c890-11eb-8807-28c527618cbc.png)

See also https://community.serlo.org/channel/software-features-and-bugs?msg=B2eD837hpma42MnGB

**Comment by Entkenntnis** [comment]
very mysterious, I can reproduce, but I have no idea yet why this is happening - needs investigation

**Comment by Entkenntnis** [comment]
another case: https://de.serlo.org/216910

**Comment by Entkenntnis** [comment]
Possible fix in #1144 , but needs some more testing
