### ISSUE TITLE
breadcrumbs styling when path is very long

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#11]
![grafik](https://user-images.githubusercontent.com/13507950/77004933-367a8f00-6960-11ea-9dea-2a69344edf9b.png)

Ideas how to prevent this?

**Comment by Entkenntnis** [comment]
Idea: Use a dropdown to show hierarchy

**Comment by elbotho** [comment]
With the current approach we already remove two of the items (always).
While we could offer a dropdown/other was of showing all content I'm pretty sure it's not helping the users – just too much information to process.

So I'd suggest to just hide the least relevant parts:
- Always display the first (subject) and the last item (next higher order).
- if there are more than e.g. 3 items hide some items starting after the subject.

**Example**
currently:
`Mathematik > Funktionen > Wichtige Funktionstypen und ihre Eigenschaften > Trigonometrische Funktionen > Aufgaben zum Verschieben und Strecken trigonometrischer Funktionen`

suggested:
`Mathematik > … > Trigonometrische Funktionen > Aufgaben zum Verschieben und Strecken trigonometrischer Funktionen`

**Comment by Entkenntnis** [comment]
Sounds good to me, lets try it
