### ISSUE TITLE
Not able to relogin as another user

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1100]
Sometimes it happens that after logout, clicking login is automatically using the last user. This makes it impossible to login as another account.

**Comment by Entkenntnis** [comment]
workaround: call https://de.serlo.org/auth/logout directly

**Comment by Entkenntnis** [comment]
related to #1090

**Comment by inyono** [comment]
> workaround: call https://de.serlo.org/auth/logout directly

Isn't that what should happen when you press log out? Or what do you mean, when you talk about "after logout"?

**Comment by Entkenntnis** [comment]
@inyono The frontend is using `/api/auth/logout` for logout and sometimes, this route is not able to logout the legacy system -> if you click login afterwards, you will get logged in as thw previous user immediately

**Comment by Entkenntnis** [comment]
Also a quickfix here: Call `/auth/logout` manually (as long as new auth system is not working reliably):

https://github.com/serlo/frontend/blob/d82e6527e5a4bad85240b51d10f070be91be772b/src/components/toast-notice.tsx#L32-L35
