### ISSUE TITLE
Links not rendering

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1104]
> Hi, wenn man nicht angemeldet ist, können wir auf der Nachhaltigkeits-Startseite zwar auf die einzelnen Unterordner klicken, aber die Ober-Themenübersichten (z.B. Was bedeutet Nachhaltigkeit?) sind nicht anwählbar

https://de.serlo.org/nachhaltigkeit
With frontend disabled the graphics (e.g. "Plastik") are linked, in the new frontend not.

**Comment by Entkenntnis** [comment]
Interesting - similiar linked images in https://frontend.serlo.org/mathe are rendered.

**Comment by Entkenntnis** [comment]
Fixed with 4fde53ab4dcd5fb3d0e5a53e2d87146905737efb

**Comment by elbotho** [comment]
Nice, thank you!
