### ISSUE TITLE
Make fetching authorization more robust

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1108]
Currently, there is following bug:

If the token is stale, there is a auth-refresh, and notifications are refetched, but authorization is not (it actually should) - this could help with #1090.

**Comment by elbotho** [comment]
(basically #851 ?)

**Comment by Entkenntnis** [comment]
I found the reason and it's different. The automatic refresh is only working if the query is returning the error "UNAUTHORIZED" - but when the token is invalid, the authorization query simply returns an empty object instead of an error, so the frontend assume everything is fine.

possible solutions: treat an empty object as error and do a refresh? or change the api to return unauthorized? or we add a field to the query to make sure we have valid response?

**Comment by Entkenntnis** [comment]
84e3dc5a713bc336811849e8297b687d7c7bc86c is an attempt so solve this: Also fetch notification count to trigger error if token is invalid (and avoid caching of bad response)
