### ISSUE TITLE
/user/public problem

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1114]
`/user/me` works fine.
`/user/public` works on localhost but not on staging or production.
-> Results in an cloudflare 502 gateway error

**Comment by elbotho** [comment]
Probably at least related to CF-Worker.
We do an redirect from /user/public to /user/me in the frontend.
Maybe the CF-Worker does not like that?

**Comment by kulla** [comment]
> Maybe the CF-Worker does not like that?

Yep, see https://github.com/serlo/serlo.org-cloudflare-worker/issues/173 Solution: We implement the redirect in the CF. Shall I do this?

**Comment by elbotho** [comment]
Sounds good 👍 
We then still have a (client side) redirect from `/user/me` to the `user/profile/username` that works fine and that we want to keep for now because we use it to trigger different behaviour when the user comes back from editing their profile in the legacy ui.

**Comment by kulla** [comment]
@elbotho See https://github.com/serlo/serlo.org-cloudflare-worker/pull/209
