### ISSUE TITLE
Discussion points about tailwind

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1118]
A place to collect problems we encoutered while working with tw.

**Comment by Entkenntnis** [comment]
Question 1

Tailwind has no built-in support for `content` and pseudo-elements, but we can add support for it https://smarative.com/blog/learn-pseudo-with-tailwind-css if we want to.

Useful for decorative elements (https://stackoverflow.com/questions/11834112/semantics-empty-div-for-background-image), but is worth it? (alternative: empty div)

**Comment by elbotho** [comment]
Question 

What are the upsides and downsides to using Tailwind for complex situations and edge cases?
How do we want to deal with those?
(quite complex example `landing-subjects.tsx`)

**Comment by Entkenntnis** [comment]
Question

One-off-values, e.g. for very specific width or height.

- Should we add them to the config -> better reuse and consistency
- Use the new jit feature and add them to the class name -> fancy
- Simply use inline styles

**Comment by kulla** [comment]
Since I am quite new in tailwind I miss understanding in the framework to be able to participate in this discussion. So I am happy with any solutions you find :smile:

**Comment by elbotho** [comment]
> Since I am quite new in tailwind I miss understanding in the framework to be able to participate in this discussion. So I am happy with any solutions you find 😄

Thanks @kulla but maybe it's a good starting point for another question:
How easy/hard is it to learn tailwind for newcomers?

**Comment by Entkenntnis** [comment]
And we shouldn't forget that tailwind has great advantages and features I don't what to miss anymore. This issue is just to make sure we are also handling edge cases properly.

Another factor here at play: removing sc will reduce bundle size by 15+ kb gzip instantly. This is quite a lot of improvement and allows us to utilies this for more interesting features.

Using next.js built-in methods like css modules or styled jsx is also very welcome if tailwind is not a good fit (and another reason why I want to move away from sc - because everything we need is already available in next.js without external dependencies)

**Comment by kulla** [comment]
> Using next.js built-in methods like css modules or styled jsx is also very welcome if tailwind is not a good fit (and another reason why I want to move away from sc - because everything we need is already available in next.js without external dependencies)

Can you point to tutorials / project sites / documentation for those features?

**Comment by Entkenntnis** [comment]
Official docs are a good place to get started: https://nextjs.org/docs/basic-features/built-in-css-support

**Comment by kulla** [comment]
> How easy/hard is it to learn tailwind for newcomers?

I only read https://adamwathan.me/css-utility-classes-and-separation-of-concerns/ and this gave me a pretty good introduction (besides the workshop of @Entkenntnis some days ago :smiley:  ). So it's a new concept but a beginner friendly one :smile:

**Comment by Entkenntnis** [comment]
A big factor here is also the personal design workflow: If you write css in the inspector, then it's easier to copy it into styled components. To use tailwind in this case, you need to use tailwind directly in the code.

Beside this, most technical issues are addressed by the evolving jit engine (https://tailwindcss.com/docs/just-in-time-mode) and tailwind is preparing for the next major release.

In the meantime, the agreement is to use tailwind and styled components side by side in the codebase. There is no urge to use one over another atm.
