### ISSUE TITLE
User-Profiles: Improvement from feedback

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1125]
From the feedback I got:

* [x] Note that the uploaded image need to be quadtratic
* [x] Investigate whether cache updates when profile is edited
* [x] Investigate what happens when new profile pic in rocket chat is uploaded

(ping @simonkoehl so that you get notified when I work on this issue)

**Comment by elbotho** [comment]
I might I have some info for point 2 and 3. Reach out if you have questions.

**Comment by elbotho** [comment]
> Investigate what happens when new profile pic in rocket chat is uploaded

it updates immediately but browser cache remembers the old image pretty reliably ;)
I added a fix in #1145 (annoying UX wise, but since this is an interim solution I'm fine with that).

**Comment by elbotho** [comment]
> Investigate whether cache updates when profile is edited

yes it updates, but not inside the `4000ms` window I guesstimated. 
Moved it up to `6000ms` in #1145 but this is definitely a hack that needs a mutation :)

**Comment by kulla** [comment]
> Investigate whether cache updates when profile is edited

API-Cache get's updated. However due to the second cache in the frontend a reload is necessary. However I am fine with ignoring this and we wait until we have a mutation for it.

**Comment by elbotho** [comment]
Ah I see, so the waiting time can probably be very short, there needs to be another refresh. 
We can hack that in.

**Comment by elbotho** [comment]
Jup, fixed with #1151 (ping @kulla)
