### ISSUE TITLE
Compare revisions: Possible improvements

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1132]
Community feedback and requests as collected by @yolo-bird and discussed with me.

- [x] resolve questions/comments in https://docs.google.com/document/d/1f3BTo6M2n7MNLuXix1kBPcH2mm9cIIrZddZu2jTLVQs/edit

## Backlog

- context quickfix for courses (lower prio)
- compare diff improvements (lower prio, preparations in progress)
- Exercise Groups: marked as connected? (not implemented yet, can't be solved in frontend atm.)
- Where is the content visible (feature needs some refinement)
- add one of the involved and better solution for "Missing context and multiple related revisions" (also needs a concept and might have some dependencies)
- idea: when the currently accepted version is loaded compare it to the latest accepted revision (if that exists it's very probably the last accepted one)

## Archive
----------------

## Missing context and multiple related revisions

**✅ Quickfix implemented for Exercises, Solutions, Exercise Groups, Grouped Exercises**
Rest is backlog for now.

- Courses (+Course Pages)
- Exercises (+Solutions)
- Exercise Groups (+GroupedExercises)

Revision view for those content types currently is not providing enough context to review properly. 
Also for Groups and Courses (e.g. on creating a new ex group) many related revisions have to be accepted manually one by one.

#### Possible solutions: 
- change data structure so Exercises and Solutions and Exercise Groups and it's GroupedExercises belong to the same UUID. (existing idea, find out if and when this will be implemented)
- Quickfix: Preview related content below (e.g. show whole ex when reviewing the solution)
- More effort: Always load the higher level content (e.g. Exercise Group for GroupedExercise) and check all children for new revisions.

## ✅ Smaller UI stuff

- [x] replace "Zurück zur Übersicht" with "Zum Inhalt"
- [x] move "Bearbeitungsverauf" to AuthorMenu
- [x] new line for compare tools 
- [x] after accepting a review: forward to content (test if cache is quick enough)
- [x] after accepting a review: do the same

## ✅ Hidden content

Currently some content is not visible in the compare view.
Some will be solved by adding custom fields (like interactive exercise options).
Image captions might be a bit trickier since they don't usually render.
List of hidden content by @yolo-bird: https://docs.google.com/document/d/1f3BTo6M2n7MNLuXix1kBPcH2mm9cIIrZddZu2jTLVQs/edit

## ✅ Side by side preview

Mode to show revision side by side with the current one (probably replaces the "accepted revision" mode)

## Bonus: Compare Diff Improvements

Since the more ambitious approaches are on hold here, maybe wen can find a quick fix to at least mark changed plugin blocks. Research: How much effort would forwarding the edtr.io ids be?
(Might still become backlog)

**Comment by ghost** [comment]
@elbotho Here is the list of hidden content : https://docs.google.com/document/d/1f3BTo6M2n7MNLuXix1kBPcH2mm9cIIrZddZu2jTLVQs/edit

**Comment by elbotho** [comment]
@yolo-bird I implemented everything but the backlog now.
The remaining things are either not so important or a lot more work.
Are you okay with this triage?

**Comment by elbotho** [comment]
Open while in feedback loop.
