### ISSUE TITLE
Follow ups of Landing page review

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1143]
Here I store follow up issues of the landing page review:

- [x] since `/user/public` redirects to `/user/me` we should remove all links like `/user/public` from the codebase
- [ ] Refactor src/components/landing/rework/menu-new.tsx
- [ ] Refactor src/components/pages/landing-de.tsx
- [ ] refactor src/components/landing/rework/search-input-new.tsx
- [x] make shuffleArray not an inplace operation
- [x] Can some divs be changed to more semantic tags or be removed?
- [x] Can `hidden md:inline-block` be changed to `mobile:hidden`? (maybe but we should not)

**Comment by elbotho** [comment]
I agree.
 It's not really used, but still cleaner to use `/user/me`.

**Comment by Entkenntnis** [comment]
Comment for the last point, see tailwind docs https://tailwindcss.com/docs/responsive-design#targeting-mobile-screens - I belief tailwind has a reason to do that this way, so maybe leave it as it is for now?

**Comment by elbotho** [comment]
> Can some divs be changed to more semantic tags or be removed?

Did convert some in fd94051da07fe889899cb6c7ff9ca2a0f087753e. Rest of the divs are ok imo.

**Comment by elbotho** [comment]
> make shuffleArray not an inplace operation

see b4061462

**Comment by Entkenntnis** [comment]
Closing this issue because remaining tasks are not actionable right now: The refactoring only makes sense if we have a decision about how to proceed with the brand design development.
