### ISSUE TITLE
Remove todo comments

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1149]
@inyono @kulla Do you remember what the intention was behind eslint warn about todo comments?

Should we convert them into issue or remove them from the code base? Any opinions?

**Comment by inyono** [comment]
The idea is just to make them visible. It's easy to add a TODO: comment and forget about it. It makes sense to check which of those TODOs are still relevant and possibly convert them into issues.

**Comment by elbotho** [comment]
Having those spots commented makes sense to me. And I agree, with checking if they are relevant from time to time.
But having warnings about them in every PR and whenever you run `lint` is not helpful for me and actually distracts from the errors. 
I'd vote to not display those warnings in the default conf for the frontend.

**Comment by inyono** [comment]
If that's an issue (and that's the reason they are warnings and not errors), I'd rather remove them from the codebase and move them into issues (so that the expectation before merging PRs is that one moves TODO comments into issues if they are still relevant). In this case, we could even make them errors to enforce that behavior.

**Comment by Entkenntnis** [comment]
Or change them from `todo:` to `note:`

**Comment by Entkenntnis** [comment]
@elbotho Could you take a look at #1155? I have removed all comments that sound outdated or added an issue if it's still relevant.

**Comment by elbotho** [comment]
Okay, I like your suggestion @inyono and I think warnings are enough.
E.g. we often push code to staging to test something.
Thank you @Entkenntnis for triaging 👍
