### ISSUE TITLE
refine TypeScript types

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#115]

**Comment by Entkenntnis** [comment]
most part of the code is already typed, but there are some places where we need some tweaking and polishing

**Comment by inyono** [comment]
At least the API fetching seemed like a big `any` (haven't looked too much into other stuff yet). I strongly recommend to add `strict: true` to the tsconfig so that any places using `any` need to be explicit about them (and therefore indicate that one needs to watch out or refine the types).

**Comment by Entkenntnis** [comment]
this issue looks stale, there has been a lot of changes in the meantime, therefore closing this

**Comment by inyono** [comment]
As long as we gradually resolve the current type issues, I'm fine with closing this.
