### ISSUE TITLE
title attribute of ReactTimeAgo is not typed

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1153]
In `time-ago.tsx`, there is a problem with typing: The title attribute is not available. There is an open PR for this: https://github.com/hustcc/timeago-react/pull/37

**Comment by Entkenntnis** [comment]
I mean, it's ~10 lines of code that is relevant for us from the package. Imho we can just copy the relevant bits (live render, I guess?) into our codebase.

**Comment by elbotho** [comment]
@kulla do you mind if I publish your branch as `@elbotho/ReactTimeAgo`? 
Not that it's that important. but than I can learn to publish packages to npm this way :)
(memo for me: https://brandontle.com/writing/forking-modifying-and-publishing-npm-packages/ )

**Comment by kulla** [comment]
> @kulla do you mind if I publish your branch as `@elbotho/ReactTimeAgo`?

That's okay
