### ISSUE TITLE
Review view: possible bug with non standard license

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1164]
https://www.loom.com/share/08d52fd578904d31b54c5f4ac2c09227

**Comment by elbotho** [comment]
Hmm weird one!
Can't reproduce or find another example.
Maybe example will be available in staging tomorrow.
 
([link](http://localhost:3000/entity/repository/compare/218733/218744))

**Comment by ghost** [comment]
Here's another example: https://de.serlo-staging.dev/entity/repository/compare/219356/219369

Seems to occur in grouped text-exercises...

**Comment by elbotho** [comment]
should be fixed in eab9a8b6eeca9448723f49bb964c1c2ab6e68f63
