### ISSUE TITLE
add yellow-200 to theme

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1170]
@elbotho yellow is currently not a built-in color, but a custom selected one instead, so `bg-yellow` is supported, but not `bg-yellow-200`. Can you check which hex-value you want for this color? Then we can add it to the theme, e.g. something like

```
'yellow-200': tint(0.8.., '#...')
```

**Comment by Entkenntnis** [comment]
Alternative would be to use tailwinds built-in yellow (https://www.themes.dev/tailwindcss-colors):

```
yellow: colors.yellow
```

but the hex values are a bit different (there is yellow and amber)

**Comment by elbotho** [comment]
I see, I thought custom colors get the `-xxx` shades automatically. Thanks.
