### ISSUE TITLE
More editing options for comments

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1175]
Mandatory options:
- latex-formulas
- links
- bold, italic

Nice to haves
- colours
- lists
- ping other authors (more complex and would need more planning)
- Emojis

Btw. can we easily transfer the editing options for the text plug-in of edtr.io to comments?

**Comment by ghost** [comment]
As the frontend for comments is already in the current sprint (on lower priority) I thought it would be nice to start the discussion to this issue.

**Comment by elbotho** [comment]
Infos from inyono:
We currently plan to use the edtr.io text plugin for this so this features would come out of the box:
`bold/italic, links, headings, colors, lists, quote, formula, code`

We can easily deactivate features.
Adding new ones (e.g. pings/emojiis) is a lot more work (but possible).

My suggestion would be pick from the existing features, build it and maybe add more advanced stuff later.
@yolo-bird could you tick the boxes for features that make sense in your opinion?

**Comment by ghost** [comment]
- [x] bold/italic
- [x] links
- [ ] headings
- [x] colors
- [x] lists
- [x] quote
- [x] formula
- [x] code

(now?)

**Comment by ghost** [comment]
Thx. Now it worked and I ticked the boxes. @elbotho

**Comment by Entkenntnis** [comment]
this issue is mostly ready, but we need a prioritization before we continue the work here.

**Comment by ghost** [comment]
What are the things that still need priorization?

**Comment by elbotho** [comment]
@yolo-bird It's currently not in the priorisation so other things will be favored.

**Comment by ghost** [comment]
Ok, when is the next priorisation meeting? I'm currently not aware what the other things on the agenda are and how important this would be compared to the other issues?

**Comment by elbotho** [comment]
sorry, this is not the place to discuss prios. 
as it stands we continue here if we have time. Prio overview: https://docs.google.com/spreadsheets/d/1mFCapHiTzViRlt8mlNUZewC9bEJw_ps9tw0U_3x1208/edit#gid=0

**Comment by Entkenntnis** [comment]
this issue is again not prioritized for the next 3-4 months
