### ISSUE TITLE
Events link to encoded threadId

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1188]
Events relating to threads link to their encoded id which does not seem to be recognized by cf-worker so we either need to change/remove the link or investigate the cf-worker.

e.g. `dDE1NDY4`

**Comment by inyono** [comment]
Sounds like the correct behavior. As an API consumer, you shouldn't even be aware that threads are UUIDs in the background (what they won't be anymore in a not-so-far future, by the way).

**Comment by elbotho** [comment]
well yes, from the frontend side this might be correct, but the links don't work.
The frontend has no idea what to do with that string and so does the cloudflare worker it seems.

**Comment by elbotho** [comment]
I'll investigate a bit more  and propose a solution.

**Comment by kulla** [comment]
@elbotho I guess you link to comments via `serlo.org/:commentId`. Can you directly link to them in the frontend via `serlo.org/:entityId#comment-<commentId>`?

**Comment by elbotho** [comment]
I guess we could, since you implemented `legacyObject: AbstractUuid!` [for the cf-worker](https://github.com/serlo/serlo.org-cloudflare-worker/issues/152).
Maybe even better: This only occurs since the event use the Thread-ID, which we don't use anywhere else. 
I'll try to use the first comment's id and then everything should be fine until the new commenting system :)

**Comment by elbotho** [comment]
done in 7a3ac255

**Comment by kulla** [comment]
@elbotho Actually we can discuss this the next time. I guess now we can remove the redirect from the CF worker since it was just a way to remove the single comment view.
