### ISSUE TITLE
up and down arrows in comments

### ISSUE THREAD

**Issue by kathongi** [serlo/frontend#1190]
In the comment field appear "up and down"-arrows with no noticeable function (e.g. here https://de.serlo.org/62055)

![Screenshot 2021-07-20 111057](https://user-images.githubusercontent.com/44167220/126319435-bed51bb1-8245-442d-9421-eb7897f4d996.png)

Browser: Google Chrome
Screen: **only visible on an external screen**, window size variation doesnt't change the appearance of the arrows

**Comment by elbotho** [comment]
@kathongi thanks for reporting.
Unfortunately I can't reproduce this in the most current and also older versions of chrome.
Since I already work on the replacement of this comment form for #1175 (which won't have this problem but probably many others ^^) I won't work on this problem.
