### ISSUE TITLE
/entity/unrevised: Changes in the checkout field in edtr.io

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1193]
![signal-2021-07-22-160640](https://user-images.githubusercontent.com/46370375/126653219-7be00b36-abe5-4a60-87e5-40e068c03fed.jpeg)

For saving a new revision we would like to have these options in the checkout field for authors with these properties: 
- Filling out at least one of the fields of "Rechtschreibung / Design / Neu erstellt / Weiteres is mandatory. 
- If one of the boxes Rechtschreibung / Design / Neu erstellt or "Inhalt noch nicht fertig" is ticked, the information is added to the changes field (ideally in form of a list). 

These information will help us to add appropiate filters to make live easier for reviewers on the /entity/unrevised page. 

(Not sure if this is the correct repo. Feel free to move it :-) )

**Comment by ghost** [comment]
ping @kathongi

**Comment by kulla** [comment]
why is there a different kind of check box field for "Inhalt noch nicht fertig. Bitte nicht überprüfen?" than for the other fields?

**Comment by ghost** [comment]
No particular reason. Can be the standard check box, too. :-)

**Comment by kulla** [comment]
> Filling out at least one of the fields of "Rechtschreibung / Design / Neu erstellt / Weiteres is mandatory.

@kathongi "Rechtschreibung" and "Design" are two different fields here, however they are together in https://github.com/serlo/frontend/issues/1194 Is this right?

**Comment by kulla** [comment]
@kathongi Am I right that one can only check one field or can one check multiple fields like "Rechtschreibung" and "new content" together?

**Comment by kulla** [comment]
@kathongi "Inhalt neu erstellt" can be determined automatically so we do not want to show it?

**Comment by kathongi** [comment]
> > Filling out at least one of the fields of "Rechtschreibung / Design / Neu erstellt / Weiteres is mandatory.
> 
> @kathongi "Rechtschreibung" and "Design" are two different fields here, however they are together in #1194 Is this right?

I would rather separate it.

**Comment by kathongi** [comment]
> @kathongi Am I right that one can only check one field or can one check multiple fields like "Rechtschreibung" and "new content" together?

You can check multiple fields. At least one must be chosen.

**Comment by kathongi** [comment]
> @kathongi "Inhalt neu erstellt" can be determined automatically so we do not want to show it?

We included this because as an author you need to specify your changes after every edit. If you just created a new article the changes field seems unsuitable because everything is new. Maybe we can automatically check this box, if a content is new.

**Comment by Entkenntnis** [comment]
This issue is not really actionable right now. I have transfered it into the [backlog](https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#) and linked it.
