### ISSUE TITLE
/entity/unrevised: Smaller UI stuff

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1195]
- [x] renamed top sections (remove all the other links)
![Screenshot 2021-07-22 at 16-43-27 Issues · serlo frontend](https://user-images.githubusercontent.com/46370375/126658622-4a6e69f7-593d-4428-9406-46c1dc1fea6b.png)

- ~~Rename "Verfasser" to "Autor*in" and "Zeitstempel" to "Wann?" and "Titel" to "Inhalt"~~ (different solution in current draft)
- ~~swap the columns of the table to "Inhalt | Bearbeitung | Typ | Autor:in | Änderung | Wann?"~~ (different solution in current draft)
- [x] mark "new authors" (= less than 5 edits) in some colour (maybe orange as it was in the old design). The marking should be only displayed on /entity/unrevised and not on other pages. 

**backlog ideas**
- In the column "Inhalt" display for exercises "Aufgabe aus `name of the exercise topic folder` (in which the exercise is embedded) instead of the uuid. 
- enable sorting of the columns "Wann?", "Typ", "Autor:in"

**Comment by ghost** [comment]
ping @kathongi

**Comment by kulla** [comment]
> enable sorting of the columns "Wann?", "Typ", "Autor:in"

@kathongi Let's say we have two authors `Alice` and `Bob`. Both have made an unrevised revision for the article "Rectangle" and Alice has made a change for another article `Circle` as well:

| Title     | Author | Uuid |
|-----------|--------|------|
| Circle    | Bob  | 4    |
|           | Alice   | 3   |
| Rectangle | Bob  | 2    |
|           | Alice   | 1    |

When one sorts the table for an author what shall the final result be? Is it right to "destroy" the grouping by entity? Shall the final result be:

| Title     | Author | Uuid |
|-----------|--------|------|
| Circle          | Alice   | 3    |
|  Rectangle         | Alice   | 1    |
| Circle    | Bob  | 4    |
| Rectangle | Bob  | 2    |

Now when one accepts the first unrevised revision of Alice in the first row, the newer edit by Bob with uuid `4` still is unrevised...

When the grouping of the entities shall not be altered: What does it mean to order by author when an entity has many unrevised revisions my multiple authors?

**Comment by kathongi** [comment]
(@yolo-bird already discussed the open questions. See also #1194)

**Comment by kulla** [comment]
Answer: It doesn't matter when the revisions for one entity are not together -> It is only important to see whether there older unrevised revisions before the current one.

**Comment by Entkenntnis** [comment]
this issue looks completed
