### ISSUE TITLE
Improvements history

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1196]
Here some improvements for the history for content: e.g. https://de.serlo.org/entity/repository/history/120628

- [x] name last two columns with "Ansehen" and "bearbeiten"
- [x] add hover text to the eye icon: "Schaue dir diese Bearbeitung an"
- [x] Add a new column "status". This helps authors to see what the history of the revisions is, i.e. which revision have been acceptet, rejected, etc. 
These are the options in the "status" column: 
:white_check_mark: with hover text: "Diese Bearbeitung wurde angenommen.", if the corresponding revision has been checked out
:x: with hover text: "Diese Bearbeitung wurde nicht angenommen.", if the corresponding revision has been rejected
:arrows_clockwise: with hover text: Diese Bearbeitung wurde nicht überprüft, weil eine neuere Bearbeitung akzeptiert wurde.", if there was no checkout for this revision
:fire: with hover text: "Dies ist die aktuell freigegebene Version.", for the current live revision. Another option might be to highlight the corresponding row in some other way.

All the icons are of course just suggestions. @elbotho Feel free to take the ones you like best. ;-)

**Comment by ghost** [comment]
ping @kathongi

**Comment by elbotho** [comment]
we simplified the last point for now.
