### ISSUE TITLE
Replace analytics tracking id

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#120]
Update GA_TRACKING_ID to the main Serlo one or build logic to use the real one in production

**Comment by inyono** [comment]
Should only be active in production anyways. We could use an environment variable for that.

**Comment by elbotho** [comment]
Right, would  `process.env.NODE_ENV === 'production'` be enough?

**Comment by inyono** [comment]
Nah, staging deployments fulfill the same property. We should use `process.env.GA_tRACKING_ID` (or similar name) instead and only include the GA stuff if this environment variable is set

**Comment by elbotho** [comment]
I use that already, but set it in `next.config.js` so it's always there.
If you feel like educating me :) Where is the place to put a condition?

**Comment by inyono** [comment]
We can set it in the ~ZEIT Now~ Vercel dashboard instead. So just assume that there might be such an environment variable and check `process.env.GA_tRACKING_ID !== undefined`

**Comment by elbotho** [comment]
Noice! make GA_TRACKING_ID and we have a deal :) 
@inyono Should we use the same approach the sentry dsn?
