### ISSUE TITLE
Hide "Inhalt überarbeiten" on Pages

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#122]
- [ ] Is not a link but a weird click handler
- [ ] Doesn't open the correct page

**Comment by inyono** [comment]
Still broken for pages

**Comment by Entkenntnis** [comment]
On serlo.org, if you are not logged in you don't see the edit pen. Should we follow this approach and hide "Inhalte überarbeiten" on Pages?

**Comment by inyono** [comment]
Fine by me until we add user authentication to the frontend
