### ISSUE TITLE
Move pdf export into separate microservice?

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1228]
The current pdf-export strategy is very decoupled from the frontend-repo, it's basicly one file with no dependencies.

I wonder if we can put this into a separate repository with a separate deploymen. This would help keeping the frontend build-times down.

**Comment by elbotho** [comment]
I thought about this as well. It would require some infrastructure work, that's why I did not do it yet.

**Comment by Entkenntnis** [comment]
done, see https://pdf.serlo.org
