### ISSUE TITLE
Status quo of styling methods

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1231]
Some updates und finding of the last 1-2 months researching styling methods (and mini follow-up for https://github.com/serlo/frontend/issues/1118)

### tailwind jit + styled-jsx finally working

Starting today, we can finally write styles like this:

```jsx
function Component() {
  return (
    <>
      <style jsx>{`
        .element {
          @apply flex justify-center text-2xl text-brand p-10;
        }
      `}</style>
      <div className="element">Hallo!</div>
    </>
  )
}
```

[styled-jsx v3/v4](https://github.com/vercel/styled-jsx) also has some improvements, so it feels more mature now.

Caveat: dev-server performance was *slightly* degraded while hot-reloading, to be investigated

### Using arbitrary styles with tailwind jit is fine

Using classes like `mt-[53px]` or `content-['hello']` is fine - production pages are using this feature (e.g. https://copilot.github.com/) and it allows us to write pixel-perfect css in situations we really need to (without changing the theme)

### Tailwind 3.0

tailwind is evolving very fast at the moment and is breaking features, especially within the JIT. Before we use more of these features, we should probably wait until there is an official 3.0 release

**Comment by inyono** [comment]
FYI: Next.js team recommends to enable JIT (even though it's a preview feature) since it works better with Next.js / Vercel.

**Comment by Entkenntnis** [comment]
Jup, we are already using the JIT.

I'd like to wait until the 3.0 release (e.g. JIT is stable) and then try again to migrate the remaining styled components either to tailwind or styled-jsx. I'm confident that this approach will give as the same level of flexibility as we have right now.

**Comment by kulla** [comment]
I question myself, what is the improvement of `<button class="bg-[#1da1f1]">Share on Twitter</button>` instead of `<button style="background-color: '#1da1f1'">Share on Twitter</button>` ?! :thinking:

**Comment by kulla** [comment]
Feedback: Used it in https://github.com/serlo/frontend/pull/1262 to remove `styled-components` in the equations plugins. Works really good :smile: :+1: :heart:

**Comment by Entkenntnis** [comment]
@elbotho here is a bigger example of styled-jsx, which is a solid replacement for styled components:

https://github.com/serlo/frontend/blob/04b24f578c80f66b9174e6daabf15ea99c9bcacf/src/components/pages/landing-de.tsx#L10-L221

This way, you can keep writing css directly in pages outside of [...slug] (but still use tailwind if suitable)

**Comment by Entkenntnis** [comment]
https://github.com/serlo/frontend/pull/1290 completes the main part of the refactoring

**Comment by elbotho** [comment]
So this is the end of the SC era?
No fireworks or something? ;)

**Comment by Entkenntnis** [comment]
Jup, it is. I expected something big or surprising - but nothing, it just happened ;)
