### ISSUE TITLE
Rename "Unterelemente sortieren"

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1236]
Rename "Unterelemente sortieren" to "Kursseiten sortieren"

![grafik](https://user-images.githubusercontent.com/46370375/129438295-90750859-74c3-4b66-805a-85dc3cdd14a3.png)

**Comment by elbotho** [comment]
The other place where this function is used is with exercises:
![image](https://user-images.githubusercontent.com/1258870/129438922-f85e69db-1362-40bf-bdf5-681e6d3187ff.png)

Should this also be renamed?

**Comment by ghost** [comment]
This should be renamed to "Teilaufgaben sortieren".

**Comment by elbotho** [comment]
solved in 2e3f09b259b392e9b3df760fd76e0b020502bff9.
translations and public probably tomorrow.
