### ISSUE TITLE
disable sentry in development mode

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#126]
well, let's try and err':

![grafik](https://user-images.githubusercontent.com/13507950/80029888-bd82d000-84e7-11ea-8518-86f4affa4ac0.png)

**Comment by elbotho** [comment]
what do you think, would [that](https://github.com/serlo/frontend/issues/120#issuecomment-617896231) work for this issue as well?

**Comment by Entkenntnis** [comment]
Yes, this would work here very well.
