### ISSUE TITLE
Investigate bundle size increase

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1268]
The bundle size of `[...slug]` has increased. Investigate the reason for this.

**Comment by elbotho** [comment]
```
currently:
├ ● /[...slug]                                            9.62 kB         203 kB

/serlo/frontend/pull/1250
├ ● /[...slug]                                            9.48 kB         192 kB

/serlo/frontend/pull/1261
├ ● /[...slug]                                            9.55 kB         193 kB

…
```
This seems to be the first PR with ~+10kb.
https://github.com/serlo/frontend/pull/1262

**Comment by inyono** [comment]
Kulla added an SVG to the bundle, that might be some kB?

**Comment by Entkenntnis** [comment]
Thanks for investigating. The last healthy bundle size seems to be https://github.com/serlo/frontend/commit/bcbef3f6fe710f8f4042177bd6997c74059ec892 with (Aug 13):
```
├ ● /[...slug]                                            12.2 kB         159 kB
```

**Comment by Entkenntnis** [comment]
This commit is one of the problem: https://github.com/serlo/frontend/commit/edda32b809b5829c3bfbe4df1dae818dd48ebaf7

@elbotho next.js is actually relying on the `typeof window === 'undefined'` to purge code from the client - I know that this is important for frontend-client-base - for the other places it could be fine to use  `isClient`

We should actually add a comment to avoid this in the future.

**Comment by elbotho** [comment]
Thanks 👍 
I'll revert this change and play around with the SVG.

**Comment by elbotho** [comment]
Completely right @Entkenntnis only the change in frontend-client-base did change the size.
But I replaced it everywhere just to make it easier. It's not as nice to read, but quite okay.
With that change we are at: 
`├ ● /[...slug]                                            9.8 kB          174 kB`

And without the svg it's:
`├ ● /[...slug]                                            9.81 kB         167 kB`

**Comment by Entkenntnis** [comment]
Can confirm after local testing that adding rewrites is increasing the client bundle by 4kb :thinking: 

Maybe we can use another solution here, we also have a pending issue for pdf creation: #1284

**Comment by elbotho** [comment]
weird!
When I remember correctly the pdf flow uses a redirect because then we can use the [download attribute](https://developer.mozilla.org/de/docs/Web/HTML/Element/a#attr-download) (which is nice 😄).

**Comment by Entkenntnis** [comment]
using styled-jsx with postcss-plugin is increasing the client by ~4-6kb, which would explain the remaining increase.

**Comment by Entkenntnis** [comment]
#1285 is converting styled-jsx to pure tailwind - at least for performance critical parts, we should stick to tailwind only.

**Comment by Entkenntnis** [comment]
with 42fd91688c8fe7243626d63c3fc7322373440a95 all increases are reverted and we are back at 159kb
