### ISSUE TITLE
Regex lookbehinds not supported in safari

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1304]
We use a regex lookbehind in `sanitize-latex.ts`, which only runs server-side atm.
Should we use it in the client we have to find an alternative.

https://caniuse.com/js-regexp-lookbehind

relevant code:
``` js
const regexComma = /(?<=[\d]),(?=[\d])/gm
```

**Comment by Entkenntnis** [comment]
7e6993be51d5b1ffc9366d5162dc60959a4974c3 simplifies regex
