### ISSUE TITLE
reduce number of languages bundled

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1305]
the code plugin currently loads ALL possible language. this can be optimized, maybe only add some common languages like:

java
javascript
python
html
css

**Comment by Entkenntnis** [comment]
@Knorrke do you have some more languages that you would like to support atm?

**Comment by Knorrke** [comment]
Aren't the languages lazy loaded if needed? Thought I had implemented that in edtr.io...

Is there a difference between html and xml in the bundle? We use xml e.g. here https://de.serlo.org/informatik/59135/59135
Otherwise, maybe tex for help-pages for LaTeX? That would be it, I guess... It's probably easy to add more, once needed?

**Comment by Knorrke** [comment]
just checked [supported languages](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md) - xml and html are the same.
So latex / tex would be the only consideration, if it doesn't affect bundle size to heavily :)

**Comment by Entkenntnis** [comment]
this is only concerning the frontend implementation

languages are lazy loaded, but the compiler has to create a separate bundle for *every* supported language -> there are some hundred assets that are bloating the build. As we don't need most of them, we can reduce the count -> adding more languages will be very easy.

thanks for the feedback

**Comment by elbotho** [comment]
those are the only languages that are suggested in edtr right now:
``` jsx
['c', 'javascript', 'jsx', 'markup', 'java', 'python']
```

**Comment by elbotho** [comment]
@Entkenntnis did you check if it handles aliases (like xml+html+svg, js+jsx+javascript) ?
Thanks!

**Comment by Entkenntnis** [comment]
I will check this as part of https://github.com/serlo/frontend/issues/1308
