### ISSUE TITLE
check code highlight languages in use

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1308]
do a quick survey of code plugins in use and find out with languages are actually in use.

**Comment by Entkenntnis** [comment]
survey of languages in use:

- not set: 167
- java: 91 (e.g. http://de.serlo-staging.dev/222284)
- sql: 68 (e.g. http://de.serlo-staging.dev/160256)
- text: 52
- python: 52 (e.g. http://de.serlo-staging.dev/222018)
- javascript: 40 (e.g. http://de.serlo-staging.dev/194448)
- xml: 5 (e.g. http://de.serlo-staging.dev/59135)
- html: 3 (e.g. http://de.serlo-staging.dev/208376)
- css: 3 (e.g. http://de.serlo-staging.dev/208379)
- bash: 2 (e.g. http://de.serlo-staging.dev/129914)
- LaTeX: 1 (e.g. http://de.serlo-staging.dev/90410)

**Comment by Entkenntnis** [comment]
@Knorrke this could interest you :)

can confirm: xml and html support is built-in

missing languages: sql, bash, latex (make sure string is lowercased)

**Comment by Entkenntnis** [comment]
@inyono we could maybe change the languages input into a drop-down menu to only list languages we support? This would also make it easier to discover supported languages.

**Comment by Entkenntnis** [comment]
d45b96e5218efe93097f716ef1c0e22b92459f5c adds sql and bash

**Comment by Knorrke** [comment]
Thanks @Entkenntnis :) Totally forgot about SQL, incredibly important to have that!

Can you send me a list for the code plugins with language 'text' or not set? Some should be pseudo code (no highlighting for that), but I'm sure there are some just missing the language declaration.

**Comment by Entkenntnis** [comment]
sure, here is the list with all code nodes that has no highlighting: https://gist.github.com/Entkenntnis/143794ba12d8745881d9a1da7e0c5de6

(id is added behind the object)

actually, most of them could be highlighted

**Comment by Entkenntnis** [comment]
work for frontend is done here atm
