### ISSUE TITLE
Investigate special chunk split

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1310]
This way of making sure we get a seperate tippy bundle for webpack might cause additional [ChunkLoadErrors](https://sentry.io/organizations/serlo/issues/2364241589/?environment=production&project=5206333&query=is%3Aunresolved).
(But could also be just more of the "usual" ChunkLoadErrors.

https://github.com/serlo/frontend/blob/staging/src/components/landing/rework/menu-new.tsx#L35-L57

``` jsx
  const [Tippy, setTippy] = useState<typeof import('@tippyjs/react') | null>(
    null
  )
  useEffect(() => {
    void import('@tippyjs/react').then((value) => setTippy(value))
  }, [])


  if (!Tippy) {
    return <MenuWithoutTippy {...props} />
  }
  return <MenuWithTippy {...props} Tippy={Tippy} />
}


function MenuWithoutTippy(props: MenuProps) {
  return <MenuInner {...props} />
}


function MenuWithTippy(
  props: MenuProps & { Tippy: typeof import('@tippyjs/react') }
) {
  const [source, target] = props.Tippy.useSingleton()
  return <MenuInner {...props} source={source} target={target} />
}
```

**Comment by Entkenntnis** [comment]
looking through the error messages of to last days, the chunk loading error happens with all kind of dynamically fetched chunks...

**Comment by Entkenntnis** [comment]
the amount of errors also doesn't seem to be related to releases...

**Comment by elbotho** [comment]
> the amount of errors also doesn't seem to be related to releases...

I agree. Those seem to be different issues.

**Comment by elbotho** [comment]
follow up in #1405
