### ISSUE TITLE
slow diff view for big revision

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1313]
interesting find in the wild: https://de.serlo.org/entity/repository/compare/1571/225401 is very slow if you switch to "Quelltext" - at least for me on FF, Linux

**Comment by elbotho** [comment]
Can reproduce. Chrome/chromium is a bit quicker. Maybe 4-5s on my laptop?
I think it's quite okay since it's usually a lot faster. Do you see any need to optimize?

**Comment by Entkenntnis** [comment]
upstream issue: https://github.com/praneshr/react-diff-viewer/issues/25

**Comment by elbotho** [comment]
I'll close this for now since there is nothing for us to do atm imo. 
I hope react-diff or js-diff will choose the faster package and this will be resolved with some updating in the future.
Reopen if you disagree :)
