### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#132]
Found [here](https://frontend.dal123.now.sh/mathe/funktionen/wichtige-funktionstypen-eigenschaften/lineare-funktionen---geraden/aufgaben-berechnung-schnittpunkten-geraden)

```
Topic
./src/components/content/Topic.tsx:43
  40 | export default function Topic({ data }: TopicProps) {
  41 |   //only show when description actually has content. probably better to filter upstream
  42 | 
> 43 |   const showDescription = !(
  44 |     data.description.length === 1 &&
  45 |     data.description[0].type === 'p' &&
  46 |     data.description[0].children[0].text === ''
```
![image](https://user-images.githubusercontent.com/1258870/80282853-fd2dff80-8713-11ea-8ebe-0e7bf900ddd6.png)

**Comment by Entkenntnis** [comment]
should be fixed by #141
