### ISSUE TITLE
redirect old alias

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#133]
- [x] `/:id` should redirect to `/:alias`, i.e. https://frontend.serlo.now.sh/1855 should redirect to https://frontend.serlo.now.sh/mathe/funktionen/wichtige-funktionstypen-eigenschaften/quadratische-funktionen---parabeln/funktionsterm-quadratischen-funktion/parabel
- [ ] /:old-alias should redirect to /:alias

**Comment by inyono** [comment]
This

**Comment by Entkenntnis** [comment]
see #142
