### ISSUE TITLE
Review breadcrumbs

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#134]
Seems like the default breadcrumbs picked by the algorithm aren't the expected ones, see e.g. https://frontend.serlo.now.sh/mathe/funktionen/wichtige-funktionstypen-eigenschaften/quadratische-funktionen---parabeln/funktionsterm-quadratischen-funktion/parabel (Picks some curriculum over the taxonomoy)

**Comment by Entkenntnis** [comment]
sometimes, the curriculum paths are short-circuit and missing some entries. #141 will detect theses short-circuits and avoid them which solves this issue.

**Comment by inyono** [comment]
> sometimes, the curriculum paths are short-circuited and missing some entries. #141 will detect theses short-circuits and avoid them which solves this issue.

What do you mean by that? Is that a bug in the API? Please provide an example.

**Comment by Entkenntnis** [comment]
Here: 
![grafik](https://user-images.githubusercontent.com/13507950/80581606-af641080-8a0d-11ea-8270-9ce668968983.png)

FOS & BOS is not a child of Mathematik, but is shown this way in the path.
