### ISSUE TITLE
fix missing fields from API

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1342]
cohesive on grouped exercises and position for taxonomy terms is missing. PRs in api are in progress.

**Comment by kulla** [comment]
Both information are now fetchable in staging (`TaxonomyTerm.position` is actually `TaxonomyTerm.weight` see https://github.com/serlo/serlo.org/blob/main/packages/public/server/src/module/Taxonomy/src/Entity/TaxonomyTerm.php#L273-L276 )
