### ISSUE TITLE
add permissions to edtr-io

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1350]
the field `mayCheckout` should be populated according to our new permission system

**Comment by elbotho** [comment]
@kulla Is every user with the authorization `Entity.checkoutRevision` able to skip review in the edtr?
Or is that another setting?

**Comment by elbotho** [comment]
Discussion: https://serlo.slack.com/archives/CEB781NCU/p1635865685002100
API Issue: https://github.com/serlo/api.serlo.org/issues/498

Quickfix in #1364
