### ISSUE TITLE
Investigate: Are there legacy interactive exercises left?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1351]

**Comment by elbotho** [comment]
> 2635 / 2970 Aufgaben konvertiert
> 1784 / 1790 Aufgabengruppen konvertiert
> 950/ 1796 Artikel konvertiert

last convo update I could find (end of september)

**Comment by inyono** [comment]
https://are-we-edtr-io-yet.serlo.org

**Comment by Entkenntnis** [comment]
I'm 100% sure that frontend + api are not supporting legacy exercises. (we haven't even got a `__typename` for them)

@kulla And I think we are also filtering them out in the api? Maybe there are some active uuids left over ...

**Comment by elbotho** [comment]
those numbers don't differenciate between interactive and and non-interactive exercises.

**Comment by elbotho** [comment]
Note: Could not find any Exercises that did not work with our implementation. If we find exercises that need that code (0cc1b7b8e53d337a9bc221c3ef5b7b7f0fa6217f) later, I'll suggest adding a warning and redirect to legacy.
