### ISSUE TITLE
improve GraphQL debugging experience

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#136]
If the GraphQL query fails for some reason (e.g. has an `error` property), there's just some generic 404 error. At least in Dev (and probably also in production with Sentry), we should expose the errors to the developer for a better debugging experience.

**Comment by Entkenntnis** [comment]
you can access the `/api` route directly to see the error message, which is a bit hidden, but works quite fine:

https://frontend.serlo.now.sh/api/woah

**Comment by inyono** [comment]
Should be fine for now. Doesn't cover production, yet, though.
