### ISSUE TITLE
should we hide trashed content from robots?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1369]
They are usually trashed for a reason, so it should make sense to hide them on e.g. google, right? @yolo-bird @kathongi

**Comment by kathongi** [comment]
That's right. Let's hide them. Sometimes I come across very old, deleted help sites for authors. It can be confusing.

**Comment by ghost** [comment]
Please hide them @elbotho

**Comment by elbotho** [comment]
alright, will be merged soon.
