### ISSUE TITLE
Add tool, that sysadmins can delete profiles without a description

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1389]
The tool serlo.org/___bot_or_not can only be used to delete spam accounts with a profile description. However I have found that some spam accounts in our chat do not have a description. Thus we also need a way to delete them (I suspect that some spammers are not native in English / German and just click random edit buttons in the profile page -> therefore they sometimes end in editing the motivation text or in our community chat).

I see one of two possibilities:

* We add a tool for sysadmins to delete profile pages (e.g. a delete button at user pages without with less than 2 edits / an extra text field at serlo.org/___bot_or_not where one can post the link to a user to be deleted)
* We add a documentation how one can delete spam accounts.

What do you think?

**Comment by elbotho** [comment]
@kulla simple proposed solution in https://github.com/serlo/frontend/pull/1395

Ah no preview. So: this would be added to the bot_or_not page:
![image](https://user-images.githubusercontent.com/1258870/140740287-22983412-257f-46a0-a0f6-c387ee70af89.png)
