### ISSUE TITLE
don't cache 500 pages

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1391]
I think we are currently generating static pages even for 500 results - better set it to error and don't cache them.

**Comment by elbotho** [comment]
what do you mean by `set it to error` ?

**Comment by Entkenntnis** [comment]
I was thinking of `notFound` ... but this may not be suitable for our use case.

(https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)

**Comment by elbotho** [comment]
I think `notFound` is only for 404 pages.
[This](https://nextjs.org/docs/advanced-features/custom-error-page#500-page) might be relevant.

**Comment by elbotho** [comment]
Also it seems like we could set `revalidate` to some seconds again if the query results in 50x.
