### ISSUE TITLE
footer (from redesign)

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#14]

**Comment by kulla** [comment]
## Feedback Botho
### Mobile

- [ ] Bisschen mehr Platz:

```
footer__LogoContainer
min-height: 54px;

footer__TopButton
top: 7px;

footer__Summary
padding: 32px 16px 16px;

footer__Support
padding-top: 16px;
padding-bottom: 16px;

footer__SupportButton
margin-top: 3px;

footernav__ColWithPadding
margin-top: 16px;

footernav__FooterNavGrid
padding: 8px 15px 40px;
```

- [ ] Link-Hover hat ein anderes Blau als die Button-Links unten. 
![image1](https://user-images.githubusercontent.com/1327215/77266155-f4728580-6c9e-11ea-895a-4bdf8713b165.png)

### Desktop

- [ ] früher auf 50% spalten wechseln 
![image2](https://user-images.githubusercontent.com/1327215/77266194-0fdd9080-6c9f-11ea-8297-ae483187001f.png)
- [ ] auf die gleiche linie 
![image3](https://user-images.githubusercontent.com/1327215/77266210-1bc95280-6c9f-11ea-9959-5db22cd1ec65.png)
- [ ] Ausprobieren, aber ich denk die größeren Paddings von Mobile würd ich auch hier lassen.
- [ ] Auf größeren Screens brauchen wir ein größeres Default-Padding.
Ich sag mal (40px). 
![image4](https://user-images.githubusercontent.com/1327215/77266244-36033080-6c9f-11ea-9e3e-c206b6089b7d.png)

**Comment by Entkenntnis** [comment]
Horizon ist momentan auf Mobile noch zu fett, vielleicht nur eins von drei anzeigen oder als Karussel?

**Comment by elbotho** [comment]
Feedback implemented in #22 

There are strings/content in `Footer.tsx` that need to come from athene
