### ISSUE TITLE
activity log of grouped exercise fails?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1410]
examples:
https://de.serlo.org/event/history/54213
https://de.serlo.org/event/history/61624
https://de.serlo.org/event/history/62976
https://de.serlo.org/event/history/116394
https://de.serlo.org/event/history/98101
https://de.serlo.org/event/history/62976

They are all redirected if we access them directly (probably cf worker then). 
But queried directly they return null from the api.

types: `multiple-choice-wrong-answer`, `input-number-exact-match-challenge`, ?, `single-choice-right-answer `

Not sure where those links come from (found them in sentry).

**Comment by Entkenntnis** [comment]
These types are not supported anymore. so a 404 response here is correct (the convo team has converted all entities to edtr-io, as far as I know)
