### ISSUE TITLE
exercise numbering beyond z

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1436]
after a, ..., z, move on with aa, ab, ...az, - then ba, bb, bc, ..., bz...

**Comment by ghost** [comment]
I don't think there is any sense in exercises with more than 26 subexercises. Not sure if we want to allow that. Would suggest splitting up the exercise.

**Comment by kathongi** [comment]
I would allow exercises with more than 26 subexercises. I think of exercises of the same kind where I want to practice e.g. an algorithm. The other questions is how we display such huge exercise groups, but that's another point. 
Additionally as an author I would be very frustrated if I start a huge exercise and reach exercise z) and can't go on. In https://de.serlo.org/community/222431/aufgaben-zu-den-hauptst%C3%A4dten-von-europa I want ALL capitals of Europe and wouldn't start again changing every subexercise to an exercise. Afterwards, we can always split up exercise groups.

**Comment by elbotho** [comment]
I added a quick fix for this. It solves the technical problem. 
Feel free to further discuss the guidelines etc.

**Comment by Entkenntnis** [comment]
@kathongi https://frontend-git-grouped-ex-serlo.vercel.app/222431
