### ISSUE TITLE
Finalize user-journey

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1438]
The backend code for the user-journey is ready (see https://github.com/serlo/api.serlo.org/pull/507). The API can be used as follow:

1. After the SSO create a random `sessionId` (any string is okay)
2. Call `https://api.serlo-staging.dev/enmeshed/init?sessionId=<...>&familyName=<...>&givenName=<...>` (POST-Request) with the given data from the SSO (@elbotho Tell me if we do not have `familyName` and `givenName` available, then I'll change the implementation). This request will return the QR code.
3. While showing the QR-Code: Make repeated requests to `https://api.serlo-staging.dev/enmeshed/attributes?sessionId=<...>` (GET request). It will respond with `{ "status": "pending" }` (200 status code) as long as the relationship is not set up. Otherwise you will get a `{ "status": "success", "attributes": { name: string, value: string }[] }` 200er response with the stored attributes. In the attributes you need to search for `{ name: "Lernstand-Mathe", value: ... }` in order to get the value.
4. To set an attribute you need to call (POST request)  `https://api.serlo-staging.dev/enmeshed/attributes?sessionId=<...>&name=<...>&value=<...>`. It will respond with 200er `{ status: "success" }` if the AttributeChangeRequest could be successfully send.

For (3) and (4): In case of an error (for example when you call the endpoint before making a successful relationship) you will get a 400er response with `{ status: "error", message: "..." }`.

**Comment by elbotho** [comment]
> Tell me if we do not have familyName and givenName available, then I'll change the implementation

Could we easily switch to the `name` field?
Seems to be `${given_name} ${family_name}`
 
Can the session ID just be a static string for our prototype?

**Comment by kulla** [comment]
> Could we easily switch to the name field?

Jep

> Can the session ID just be a static string for our prototype?

The session ID is used as a key for storing the information about the person (enmeshed ID, attributes of the person, ...). When we reuse the session ID, then at the second time, the connection is already set up and the attributes of the person are already stored. So it is easier when we generate a new sessionID each time https://lenabi.serlo.org/user-joruney is called. Thus we do not need to remove the cached data from the API. Also by using a static session ID only one user can use the user-journey at a time.

**Comment by kulla** [comment]
The result of `https://api.serlo-staging.dev/enmeshed/attributes?sessionId=<...>` is currently of the form `{ name: string, value: string }[]`. Will change this to a dictionary... Currently the code `attributes.find(x => x === "Lernstand-Mathe").value` can be used to obtain the current learning status.
