### ISSUE TITLE
Direct call to https://de.serlo.org/api/auth/login results in 500er response

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1439]
A direct call to https://de.serlo.org/api/auth/login (for example via `curl -I https://de.serlo.org/api/auth/login`) results in a 500er response. It works when a `Referer` is set (`curl -I https://de.serlo.org/api/auth/login -H "Referer: https://de.serlo.org/"`). It would be better if there is a 400er response with an error message.

**Comment by Entkenntnis** [comment]
@kulla can you elaborate a bit about the error message? The message is "Missing referer header" and I think it's quite clear.

**Comment by Entkenntnis** [comment]
the `-I` option of `curl` is suppression the message body. Try `curl https://de.serlo.org/api/auth/login` to see the warning.
