### ISSUE TITLE
Check for new / old editor for pages

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#1442]
Pages seem to be always opened in the old editor, even if the content has already been converted, see e.g. https://de.serlo.org/21468.

**Comment by elbotho** [comment]
Can't reproduce since this page seems to be blank in staging 😲 and I don't have the necessary rights in production.
And are you refering to the exerimental feature of using the editor in the frontend or the current approach of linking to legacy?

**Comment by inyono** [comment]
It's blank in staging because a new editor state was saved via legacy editor. The most recent edits by Wolfgang are broken (see also https://de.serlo.org/entity/repository/history/21468). The most recent edit by LeonieTrautmann works correctly in the new edotr but wrongly links to legacy editor. (See https://de.serlo.org/page/revision/create/21468/226096 respectively https://de.serlo-staging.dev/page/revision/create/21468/226096 which works correctly).

**Comment by inyono** [comment]
> And are you refering to the exerimental feature of using the editor in the frontend or the current approach of linking to legacy?

The latter, it's only about the link for now (since editing of pages isn't really supported in the frontend afaik)

**Comment by elbotho** [comment]
So basically we could always link to `/page/revision/create/…` and never use `create-old` and let the editor link to the old editor when needed. Any objections?
![image](https://user-images.githubusercontent.com/1258870/149302870-ac17acd2-67aa-4730-9fd6-46f3165ff86b.png)

**Comment by elbotho** [comment]
- the new editor will not be used for editiing pages for now
- we will investigate what we need to convert the pages and keep the needed layout possibilities
- Long term pages should be replaced by nextjs static pages

**Comment by Entkenntnis** [comment]
Nothing actionable right now. Will open new issues if we have decided how to move on.
