### ISSUE TITLE
Logout not working on staging and localhost

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1456]
Trying to logout on staging results in an error page. It looks like some parameter has changes.

![grafik](https://user-images.githubusercontent.com/13507950/151953075-db7e288d-805d-4de2-9eb5-e2496ee766a8.png)

**Comment by inyono** [comment]
Weird stuff, probably an issue with the infrastructure somehow. Will look into this.

**Comment by Entkenntnis** [comment]
also affects localhost.

Variation of this happens on production: #1479

**Comment by Entkenntnis** [comment]
@inyono any progress on this? I have to clear cookies to logout, which is working, but not ideal.

**Comment by inyono** [comment]
Should be fixed now.
