### ISSUE TITLE
can't login as another user

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1479]
on production, I am not able to login as new user. After clicking "Abmelden", trying to login results in automatically login as my last user.

**Comment by inyono** [comment]
Can't reproduce, works fine for me.

**Comment by hugotiburtino** [comment]
~Indeed, I had the same problem, but now it is working~.
~Maybe a browser update problem...?~
It ~should have been~ _may be also_ a bug of hydra

**Comment by Entkenntnis** [comment]
checked again, it's working now

**Comment by hugotiburtino** [comment]
Actually, you can reproduce the bug if you untick the "Eingeloggt bleiben"

**Comment by kulla** [comment]
> Actually, you can reproduce the bug if you untick the "Eingeloggt bleiben"

I remember having bugs with this already 2 years ago. Is a solution to just hide this button so that it is always checked? I would prefer this since this module will be changed with the new design anyways.

**Comment by Entkenntnis** [comment]
Here are some results of testing, maybe this helps to find the issue:

#### Working (with persistent cookie):

- visit de.serlo.org, clean browser (no php session)
- click "Anmelden"
- redirect to legacy login page (php session A)
- login with user/pass + "Eingeloggt bleiben", the route de.serlo.org/auth/hydra/login changes page to php session B
- frontend is logged in
- click "Abmelden"
- route de.serlo.org/auth/hydra/logout changes page to php session C
- legacy is logged out
- click "Anmelden" -> I see password prompt :heavy_check_mark: 

#### Not working (with session cookie):

- visit de.serlo.org, clean browser (no php session)
- click "Anmelden"
- legacy login page (php session A)
- login with user/pass
- **page remains in session A**
- click "Abmelden"
- **page still remains in session A**
- backend remains logged in

**Comment by Entkenntnis** [comment]
my best guess is that the problem is with `https://hydra.serlo.org/oauth2/sessions/logout`. The redirect should be to the legacy backend, e.g. `https://de.serlo.org/auth/hydra/logout`, but it's not.

@inyono don't know if there is an easy fix for this

**Comment by Entkenntnis** [comment]
@kulla can't speak for the users perspective, but from dev-wise, this would fix the issue.

**Comment by Entkenntnis** [comment]
closing this issue, as there is nothing the frontend can do to fix this.
