### ISSUE TITLE
empty highlight plugin causes error

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1483]
https://de.serlo.org/user/148805/julianbabl -> 500

reason: `{"plugin":"highligh",state:{}}` has empty state ???

![grafik](https://user-images.githubusercontent.com/13507950/157412874-ef4bc494-00a3-4aca-8071-d61cbdd9dd5a.png)

**Comment by inyono** [comment]
Not really, looks like a malformed state. Not sure how that happened.

**Comment by Entkenntnis** [comment]
hopefully this is just a one-time thing ...
