### ISSUE TITLE
equations: small display bug

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1486]
> Im Editorelement "Gleichungen und Terme" wird bei Ausfüllen des ersten Erklärungsfelds, der Text nicht über das Gleichheitszeichen gesetzt, sondern mittig zentriert (vmtl). Beispiel: [de.serlo.org/1773](http://de.serlo.org/1773)

**Comment by Entkenntnis** [comment]
for illustration:

![grafik](https://user-images.githubusercontent.com/13507950/157722289-f7416705-9813-4532-a864-1e2c1034dc39.png)
