### ISSUE TITLE
add edtr-io integration for taxonomy term

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1491]
some results:

- current integration already supports taxonomy terms.
- we need to add new routes `/taxonomy/term/create` and `/taxonomy/term/update`, then the edtr-io POST result to resp. url and we *should* be fine
- testing for save only possible on staging with csr, needs cloudflare support later

wait after merge of #1481

**Comment by elbotho** [comment]
sure this is deployed to staging already?

**Comment by Entkenntnis** [comment]
see https://frontend-git-staging-serlo.vercel.app/entity/repository/add-revision/200247

**Comment by elbotho** [comment]
ahh, now I understand. good catch. maybe we can use the new mutations. Let's check in with hugo tomorrow.
