### ISSUE TITLE
deleted discussion from frontend is still visible in /discussions

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1492]
Steps:

- delete a discussion in the frontend "Thread löschen" or "Thread archivieren"
- visit "/discussions" (legacy)
- comments are still visible, but they have no settings and can't be deleted (compare first two vs the last one) :

![grafik](https://user-images.githubusercontent.com/13507950/158128426-feea1e79-4ed0-4412-a4e0-2307c7362588.png)

**Comment by elbotho** [comment]
I think the best way to solve this would be to migrate `/discussions` then.

**Comment by elbotho** [comment]
This page should only be available to logged in users, maybe even only moderators. 
Then we can still decide if we should show the deleted comments.

**Comment by elbotho** [comment]
[API issue](https://github.com/serlo/api.serlo.org/issues/534)

**Comment by elbotho** [comment]
follow up in #1573
