### ISSUE TITLE
Migrate Content API

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1493]
we need to support (parts of) https://github.com/serlo/serlo.org/wiki/Content-API for edtr-io integration in the frontend

Idea: use CF to redirect to a separate `/embed/[...slug]` route

**Comment by Entkenntnis** [comment]
most important two parameters atm are `contentOnly` and `hideTopbar`

**Comment by elbotho** [comment]
https://github.com/serlo/serlo.org-cloudflare-worker/pull/280

**Comment by elbotho** [comment]
We decided on a **feature set**:
only `?contentOnly` will be supported and no height info will be sent. 
Others features/customization we will implement only when requested.

The **route** in the frontend:
`/content-only/[...slug]`

**Links**:
New tab or staying in the iframe: (pending)

**Comment by Entkenntnis** [comment]
Some thoughts about page types: content-only is available to entities like article, taxonomy or page. For other pages, like the landing page, we will drop support completely, right? In this case the frontend part is done and this can be handled in the cloudflare worker issue.

**Comment by elbotho** [comment]
> For other pages, like the landing page, we will drop support completely, right

We did not talk about this on monday, but yes that's my suggestion atm. 
Goes well with the choice to handle links in new tabs :)

**Comment by elbotho** [comment]
Can now be tested in staging:
https://de.serlo-staging.dev/mathe/36070/rechtwinkliges-dreieck?contentOnly

**Comment by Entkenntnis** [comment]
fixed an issue where csr links are not opened in new tabs: da775aad90f1ca015911196440bae12444bea100

Otherwise, I haven't noticed any technical issues

**Comment by kulla** [comment]
Live in production.
