### ISSUE TITLE
implement `Page.addRevision`

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1494]
https://github.com/serlo/api.serlo.org/issues/531

**Comment by Entkenntnis** [comment]
Not sure what the intention is here, @elbotho can  you add a small explaination? Just wondering, because we have postponed a lot of details in the discussion today. Do you mean edtr-io support for static pages in the frontend?

**Comment by elbotho** [comment]
sorry, got confused. 
nevermind. this might or might not be relevant later. def. closed for now.
