### ISSUE TITLE
link component not respecting new feature flags

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1495]
This code seems not to be aware of the new "legacyEditor" cookie:

https://github.com/serlo/frontend/blob/c37831ec941ab3a092f7426bfe9e38be9a58a489/src/components/content/link.tsx#L51-L58

Problem: Uses CSR even if legacyEditor ist activated

**Comment by elbotho** [comment]
uh nice catch. not sure how I missed that.
