### ISSUE TITLE
next.js eslint plugin

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1499]
"The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config"

Some rules seems useful, other are not relevant for us (e.g. Link or Image component). Check it someday.

**Comment by Entkenntnis** [comment]
I am a bit confused why we have `eslintrc.js` and `eslintrc-next.js` in our project and I don't really now with one is in use...

**Comment by elbotho** [comment]
you can use `yarn lint:next` to use `eslintrc-next.js` and `yarn lint:eslint` should use `eslintrc.js` that we basically share with the other repos.

**Comment by elbotho** [comment]
next basically just warns about `<img>` and `<a>` at this point so I never added it into our `yarn lint`.
