### ISSUE TITLE
Sharing menu

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#15]

**Comment by kulla** [comment]
## Feedback Botho
### Mobile

- [ ] Versteh ich als normaler User nicht: 
![image1](https://user-images.githubusercontent.com/1327215/77266453-c3468500-6c9f-11ea-907a-009d66b8b2a4.png)
- [ ] visuals__ToolLineButton
```
Font auch Karmilla,
font-size: 14px
margin: 0 0 0 10px;
```
![image2](https://user-images.githubusercontent.com/1327215/77266483-d48f9180-6c9f-11ea-8561-54908d9e78d8.png)
- [ ] Bearbeiten Button nicht anzeigen auf Mobile
- [ ] Allgemein Buttons in Karmilla und bisschen größere Schrift (13-14px)
* Generell
    - [ ]  Buttons ohne abstand nach links
    - [ ]  Kopieren Button immer neben url-input
    - [ ]  Zwischen den zwei Button-Zeilen das `<br>` raus, dafür buttons jeweils margin-top: 8px;
    - [ ]  Wenn möglich statt `button` lieber `a` und `href` benutzen.
![image3](https://user-images.githubusercontent.com/1327215/77266563-13bde280-6ca0-11ea-93cc-5e28fb9d7ac8.png)
* Überlegung: Toolbook auf mobile noch mal am Ende des Contents einbauen?

### Desktop

- [ ] Erst floaten, wenn genug platz da ist, dass es sicher nicht überlappt.
- [ ] Schriftgröße und Familie wie bei Mobile.
- [ ] Toolbox verschwindet zu früh vor dem Footer.
- [ ] Ideal wäre es, wenn sie über dem Footer dann absolut positioniert stehen bleibt. (also nie verschwindet)

**Comment by elbotho** [comment]
Very nice positioning at the bottom, love it!

**Comment by elbotho** [comment]
`position:sticky` solution broken in current chrome/chromium :(

**Comment by Entkenntnis** [comment]
should be working in theory: https://codepen.io/corysimmons/pen/QyBMXN?editors=1100
needs some investigation

**Comment by elbotho** [comment]
Okay, found the solution. It's expected behaviour if a parent has `overflow:hidden` or `overflow:auto`.
is the `overflow: hidden` on `<StyledMain>` necessary?

**Comment by Entkenntnis** [comment]
tested it again, `overflow:hidden` looks unnecessary now. You can fix it in #42
