### ISSUE TITLE
link to legacy editor not working

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1500]
https://de.serlo.org/entity/repository/add-revision-old/1893 is not showing the legacy editor, but redirects to the frontend. Probably more of a CF problem.

**Comment by elbotho** [comment]
another great catch…
we use `.startsWith('/entity/repository/add-revision')` to get the `/add-revision/…` links which obviouly also catches `/add-revision-old/…`. 
Affects both frontend and CF worker. Fixes in progress.
