### ISSUE TITLE
no trashed notice for exercise group and grouped exercise

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1502]
Try to trash an exercise: https://de.serlo-staging.dev/mathe/9291/9291

Entity is still visible and you can't restore it either.

**Comment by elbotho** [comment]
showing notice with 929fb8e14315f61279ca61756bbf397ed4844313

**Comment by elbotho** [comment]
currently we don't offer any tools in the menu for single exercises so restoring is still not possible

**Comment by elbotho** [comment]
ok #1504 should fix this. 

solutions have the same problem but I'm not quite sure if deleting only a solution is something we should offer at all?

**Comment by Entkenntnis** [comment]
Thank you for the fix! Follow up in https://github.com/serlo/frontend/issues/1505
