### ISSUE TITLE
create taxonomy term

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1511]
final place: `/taxonomy/term/create/[parent]/[id]`

is not reachable from the frontend, so we need cf support to test this

CF issue: https://github.com/serlo/serlo.org-cloudflare-worker/issues/274

**Comment by elbotho** [comment]
but we can develop locally, right?
so should we move this to the cf-worker repo then?

**Comment by Entkenntnis** [comment]
we will need both parts, so an issue in the cf-worker repo is also needed

**Comment by elbotho** [comment]
Ah, now I understand the purpose of the issue here :)

**Comment by Entkenntnis** [comment]
de.serlo-staging.dev/taxonomy/term/create/[parent]/[id] is now handled in the frontend, so we can move on with implementing the integration
