### ISSUE TITLE
strange redirect after editing taxonomy description

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1512]
it's now possible to edit a taxonomy description, but the redirect is not correct, investigate why this happens

**Comment by elbotho** [comment]
legacy actually returns this:
`{"success":true,"redirect":"\/"}`

so frontend behaviour is ok.
not sure if we should work on this now or wait/work on the [endpoints](https://github.com/orgs/serlo/projects/22/views/1).

**Comment by elbotho** [comment]
okay should be fixed with b05af2b45aedadf758ac5bfca5945f5f5027e39b
we just reload the page now which is okay for now.
now we only need the routes in cloudflare.
