### ISSUE TITLE
deploy box plugin for all users

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1520]
we are waiting for changes in the edtr-io core for this.

**Comment by elbotho** [comment]
related issues/prs:
- https://github.com/edtr-io/edtr-io/issues/369
- https://github.com/edtr-io/edtr-io/issues/359
- https://github.com/edtr-io/edtr-io/pull/368

**Comment by Entkenntnis** [comment]
things that are not working yet: adding a formula into the title breaks the plugin for me on staging:

![grafik](https://user-images.githubusercontent.com/13507950/164407653-9728f132-cc00-4988-97d1-6522cbc42866.png)

(not sure if related issues are fixing this)

**Comment by elbotho** [comment]
@Entkenntnis I have never seen this behaviour and can't replicate, could you add details? 
(type of box, only formula or other things, browser)

**Comment by Entkenntnis** [comment]
It's happening on `https://de.serlo-staging.dev/user/settings`, so that could be the reason. added math with strg-m

I tested with `add-revision` and the bug is not happening there

**Comment by elbotho** [comment]
Yeah, after some testing I think it's a problem with math on `user/settings` in general.
On `add-revision` we preload `<MathSpan formula="" />`.

Not sure if we should add this to settings as well or if we should disable math instead…

**Comment by elbotho** [comment]
this is not being tested in production

**Comment by Entkenntnis** [comment]
about the previous issue, I think adding `<MathSpan formula="" />` is fine and should solve the issue (or move this preloading into the editor component?

**Comment by elbotho** [comment]
Good idea. Done in 712f8c3c38755c51828e42c7339c302384f13f05

**Comment by Entkenntnis** [comment]
As far as I see all recent feedback is deployed in production already for testing. Only remaining task is to deploy this for all users. (will to this after testing is done)
