### ISSUE TITLE
formulas in equations explainations are not accessible

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1528]
> So sieht es aus, wenn man im Gleichungsplugin in den Zwischentexten Formeln einfügen will. Ein Teil der Eingabebox ist unsichtbar und hat auch nicht den Fokus, d.h. man muss erst reinklicken.

![grafik](https://user-images.githubusercontent.com/13507950/159226072-88986ff8-072b-4d27-b03c-0a27f04d5f1a.png)

**Comment by Entkenntnis** [comment]
Not a regression of the integration (this is also happening in legacy), but still annoying.

Check if this is a known bug and already in the backlog and/or moving it there ...

**Comment by elbotho** [comment]
should be [this one](https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.8o6gbe3yrbcl)?

**Comment by Entkenntnis** [comment]
closing this as it's part of the backlog
