### ISSUE TITLE
implement multimedia behaviour "central role"

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1535]
the frontend is ignoring the "illustrating" property of the multimedia element.

Intended behaviour: image has 100% width and the explaination is below the image.

Example: https://de.serlo.org/entity/repository/compare/48767/241060

**Comment by Entkenntnis** [comment]
source: https://community.serlo.org/channel/software-features-and-bugs/thread/fph9SisvmGbHc7z2g

**Comment by elbotho** [comment]
Needs more discussion, closed until actionable.
Added to backlog document.
