### ISSUE TITLE
Equation plugin: No input in visible mode for math equation in explanation

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1537]
See https://serlo.slack.com/archives/C0BMSC431/p1648198055919099

> Im Gleichungsplugin kann man in den Anmerkungstexten zwischen den Schritten im visuellen Mathemodus nichts tippen. Konkret aufgetreten in 242021 bei @Adonis (?) und mir (Chrome Browser v99...), kleine Violation-Meldungen in der Konsole zu diversen handlern, die zu lang brauchen.
Latex-Modus geht.

![image](https://user-images.githubusercontent.com/1327215/160091923-48e0810f-6716-456c-b56b-fd436f29e38c.png)

**Comment by Entkenntnis** [comment]
Beim letzten Testen ist dieses Verhalten auch schon in der legacy Integration aufgetreten, also kein regression beim Umzug, sondern ein offener Bug
