### ISSUE TITLE
saving does not work on staging

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1551]
not sure what the problem is (cf or frontend probably). 
investigate or merge #1532 instead.

**Comment by elbotho** [comment]
not sure what the actual problem is, but deleting browser cache or using incognito mode to log in fixes it at least for some time.

**Comment by Entkenntnis** [comment]
it's working for me atm (using legacy infrastructure). can you check if this is still the case for you?

**Comment by elbotho** [comment]
It's been a problem for ppl testing the new plugins, but seems to work atm.
I guess there is still something going on with cookies or smth.
Closing and focusing on the mutation instead.
