### ISSUE TITLE
review icon implementation

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1552]
Just adding font-awesome is using up 16kb gzipped bundle size, which is huge (and not even includes the icon data of ~10kb) for features we are barely using ...

https://github.com/FortAwesome/react-fontawesome/issues/232 is a start

**Comment by Entkenntnis** [comment]
another big factor is tailwind: this makes most features obsolete, because we can style icons extensively with tailwind...

**Comment by elbotho** [comment]
do we load all icon data or does tree shaking work here?

**Comment by Entkenntnis** [comment]
Tree shaking is working for icon data. The size is mainly caused by [fontawesome-svg-core](https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/fontawesome-svg-core/index.js)
