### ISSUE TITLE
converter crashes

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1563]
url: https://de.serlo.org/entity/repository/add-revision/73649

> TypeError: Cannot read property 'name' of undefined    at f (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:1926)    at /var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:1850    at Array.map (<anonymous>)    at g (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:1761)    at f (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:2197)    at /var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:1850    at Array.map (<anonymous>)    at g (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:1761)    at E (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:4381)    at S (/var/task/node_modules/@serlo/legacy-editor-to-editor/dist/legacy-editor-to-editor.cjs.production.min.js:1:4469)error while converting: [{"id":73649,"type":"article"}]

the state is malformed, even legacy is not working for this entity

**Comment by elbotho** [comment]
Okay, the legacy converter does trip over the ` ``` ` code blocks.
The revision before the current one does not have them (and works) and also manually removing them works.

We could add a hack (for legacy only) or ignore this. 
``` ts
const hack = JSON.parse(JSON.stringify(content).replaceAll('```', ''))
```

@Entkenntnis what do you think?

**Comment by Entkenntnis** [comment]
as this only relates to legacy content, I'm fine with a workaround here :+1:
