### ISSUE TITLE
activity not loading

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1569]
My notifications are not loading with this error:

> Error: Invalid value received from data source.: {"response":{"errors":[{"message":"Invalid value received from data source.","locations":[{"line":79,"column":7}],"path":["events","nodes",3,"entityRevision"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"errorContext":{"invalidCachedValue":{"id":193389,"trashed":false,"alias":"/nachhaltigkeit/193389/7-fakten-zum-klimawandel","__typename":"Video","instance":"de","date":"2021-02-09T10:25:18+01:00","licenseId":1,"taxonomyTermIds":[80267],"canonicalSubjectId":17744,"currentRevisionId":242880,"revisionIds":[242880,242879,193414]},"invalidCurrentValue":{"id":193389,"trashed":false,"alias":"/nachhaltigkeit/193389/7-fakten-zum-klimawandel","__typename":"Video","instance":"de","date":"2021-02-09T10:25:18+01:00","licenseId":1,"taxonomyTermIds":[80267],"canonicalSubjectId":17744,"currentRevisionId":242880,"revisionIds":[242880,242879,193414]},"decoder":"((Exact<(({ id: Uuid, trashed: boolean, alias: Alias } & { __typename: (\"AppletRe…
2 loading-error.tsx:26:11

I have edited the entity 193389 (7 Fakten zum Klimawandel) and now the notifications seems to be broken.

**Comment by elbotho** [comment]
Interesting, on staging your account now has the same problem but with the `1565` article in the error log.

**Comment by elbotho** [comment]
Did this happen on production at all?

(maybe related [558](serlo/serlo.org-database-layer#217))

**Comment by Entkenntnis** [comment]
activities are working fine on production, so maybe this is a staging only issue? unfortunately the frontend can't do much here either

**Comment by elbotho** [comment]
cool, if it's only staging it's likely this issue. serlo/serlo.org-database-layer#217
