### ISSUE TITLE
activity log is off by 2 hours

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1575]
Just created a revision and the activity log shows this:

![grafik](https://user-images.githubusercontent.com/13507950/162022317-7913e0b9-2ae4-4ff8-9e41-cb42c48ca673.png)

The time stamp is off by two hours (looks like a timezone thing ...)

**Comment by elbotho** [comment]
There is some [discussion on slack](https://serlo.slack.com/archives/CEB781NCU/p1648563369278359).

**Comment by elbotho** [comment]
[API Issue](https://github.com/serlo/serlo.org-database-layer/issues/204) (closed, but maybe not deployed)

**Comment by elbotho** [comment]
fixed in API 🎉
