### ISSUE TITLE
remove edtr-io state fixes in the frontend

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1581]
we have some code to "normalize" edtr-io content, which includes:

- converting new lines to paragraphs: https://github.com/serlo/frontend/blob/ea14168365352c26803dd8efa0af66ae2ee3447c/src/schema/convert-edtr-io-state.tsx#L457

- converting single paragraph with inline-math to math block: https://github.com/serlo/frontend/blob/ea14168365352c26803dd8efa0af66ae2ee3447c/src/schema/convert-edtr-io-state.tsx#L442

Theses fixes has been added to improve content in some places, but can cause confusion in others. As the edtr-io integration is moving forward, I would suggest to remove these fixes from the frontend and let the edtr-io handle normalization in the future.

**Comment by elbotho** [comment]
do you remember some of the cases that made those fixes useful?

**Comment by Entkenntnis** [comment]
most use cases are related to legacy as far as I remember - edtr-io state is much more reasonably. I will keep the logic for legacy stuff, but remove it for edtr-io
