### ISSUE TITLE
infinite redirect

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1584]
interesting bug: https://de.serlo.org/46019/biologie

resolution is somehow broken

**Comment by elbotho** [comment]
where did you find this link?

**Comment by Entkenntnis** [comment]
I was playing around with simpleanalytics logs and stumbled open this

**Comment by Entkenntnis** [comment]
the uuid is a page revision, the frontend is redirecting to `/entity/compare/...`, but the cloudflare worker is redirecting back to the frontend...

on localhost, frontend opens `http://localhost:3000/entity/repository/compare/0/46019` which is fine.

@kulla do you know why is the cf is redirecting back to the alias?

**Comment by Entkenntnis** [comment]
the source of this issue is related to the cf-worker and page revisions: https://github.com/serlo/serlo.org-cloudflare-worker/issues/290

the frontend is working fine
