### ISSUE TITLE
Font options

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#159]
Karmilla is in some ways not ideal:
- letter spacing is quite big, kerning not perfect
- there should be a new release of Karla at some point, but it' still not here -> development is not very active
- not many weight options

_It's a great os font with readability and some character but we might consider switching to a more professional font._

#### my options:

---

**Version 1: [System Font Stack](https://frontend-git-font-chooser.dal123.now.sh/1565?font=system-ui&spacing=0.02)** 
- Pro:
functional (great readability, no load time), great language support, progressive (e.g. [GitHub](https://markdotto.com/2018/02/07/github-system-fonts/) uses this solution)
- Con:
Rather Eher sober, plain, less control over the design, not extra friendly, less character, not a great branding-solution.
The design would have to be adapted to take over those things to some degree.

_if we go for plain/functional i'd prefer this solution to similar fonts like Public Sans, Roboto etc.
from a technical point of view maybe the best choice. looks great, but lacks character_

[Demo for modern browsers](https://frontend-git-font-chooser.dal123.now.sh/1565?font=system-ui&spacing=0.02). Looks different on different operating systems!

---

**Version 2: [Karmilla](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Karmilla&spacing=-0.02) / Karla**
- Pro:
Imo: friendly/approachable, has character, kind of trendy atm, readable. Well suited for our brand as well. Looks great on posters as well.
- Con:
Technically not as good as other options, letter-spacing too large, not as fully developed.

_still my favorite, good enough for now if we tweak the letter-spacing and I still hope for a reworked Karla at some point. My choice is Karmilla, because it has that certain something, gives the whole page some individuality and makes it look like more than a math book and can be used for branding as well._
Alternatives might be [Work Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Work%20Sans) (also a "variable font" – interesting) or [Barlow](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Barlow)

---

**Version 3: Humanist ([Lato](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Lato) & [PT Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=PT%20Sans))**
I put them  in one group because they type of font is related.

- Pro:
Well developed, professional fonts, high readability, some character

- Con:
Imo not as fancy/nice, a bit noisy overall impression, not a great branding font.

_In a way a good compromise, could live with them, but would have to find a way to make it work for the brand._

---

#### List of previews.
[Karmilla (current)](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Karmilla&spacing=-0.02)
[Source Sans Pro](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Source%20Sans%20Pro)
[Barlow](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Barlow)
[PT Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=PT%20Sans)
[Poppins](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Poppins&spacing=0.02)
[Chivo](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Chivo)
[Archivo](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Archivo)
[Fira Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Fira%20Sans)
[Noto Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Noto%20Sans&spacing=-0.007)
[Roboto](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Roboto)
[Public Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Public%20Sans)
[HK Grotesk](https://frontend-git-font-chooser.dal123.now.sh/1565?font=HK%20Grotesk)
[Rubik](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Rubik)
[Work Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Work%20Sans)
[Vremena Grotesk](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Vremena%20Grotesk)
[Nunito](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Nunito)
[Lato (khan ac)](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Lato)

---

#### Other considerations (Simon)
- mobile first, how well does it work on small screens
- ease and friendliness important to counterbalance the gravity of math/school in general.
- what are learners used to? (maybe look at popular apps)
- clear contrast between regular/bold important for learning-content

**Comment by kulla** [comment]
Reminder: The privacy revision might need to be updated (the section for the Google Web Fonts might be deleted).

**Comment by Entkenntnis** [comment]
At the current point, we have more or less settled with version 2 and fallback to version 1 for other language fonts.

**Comment by elbotho** [comment]
another option that is somewhat similar to karmilla but a little bit better developed: https://frontend-git-font-chooser.dal123.now.sh/1707?font=DM+Sans&spacing=0.01 .

closing this because:
> At the current point, we have more or less settled with version 2 and fallback to version 1 for other language fonts.
