### ISSUE TITLE
Migration: Editing and creating of entities

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1590]
Blocker:

- [x] https://github.com/serlo/api.serlo.org/issues/400
- [x] https://github.com/serlo/api.serlo.org/issues/531
- [x] https://github.com/serlo/api.serlo.org/pull/537
- [x] https://github.com/serlo/api.serlo.org/pull/532
- [x] https://github.com/serlo/api.serlo.org/issues/576
- [x] https://github.com/serlo/api.serlo.org/issues/595

**Comment by Entkenntnis** [comment]
code is deployed in staging and ready for testing.

**Comment by elbotho** [comment]
Saving pages is currently not supported.

**Comment by hugotiburtino** [comment]
> Saving pages is currently not supported.  

Do you mean: saving in browser for later? Or the new page  endpoints are buggy?

**Comment by elbotho** [comment]
@hugotiburtino 
- The endpoints we not implemented in the frontend. 
- The endpoints are probably also buggy, but I'll create API issues for that :)

**Comment by Entkenntnis** [comment]
The initial implementation is complete, so there is nothing to do in this issue anymore :tada: 

For bugs, etc. we can open follow-up issues
