### ISSUE TITLE
Migration: Sorting children (entities + taxonomy terms) in taxonomy terms

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1595]
## where

After click "Other tools > sort content":

![2022-04-15-230614_469x404_scrot](https://user-images.githubusercontent.com/1327215/163631917-636c4beb-a52e-4962-9240-3062e0f5de07.png)

Link `https://en.serlo-staging.dev/taxonomy/term/sort/entities/:taxonomyTermId`

## New behavior

In the overview next to entities also children taxonomy terms shall be able to be sorted. The best solution is that they are already grouped by type and the sorting is done in each group separately. 
![2022-04-19-201951_688x625_scrot](https://user-images.githubusercontent.com/1327215/164070647-4b7ef2c1-e837-4b01-bac2-af052e466b28.png)

## Old Design:

![2022-04-15-230742_864x521_scrot](https://user-images.githubusercontent.com/1327215/163632032-1fb6435c-023b-45b0-a96f-db97ad4aa14b.png)

## mutation

See https://github.com/serlo/api.serlo.org/issues/582 with `taxonomyTermId = parentId of entities` and `childrenIds = new list of children` (can be the list of each group concatenated) 

## Blocker:

- [x] https://github.com/serlo/serlo.org-database-layer/issues/214
- [x] https://github.com/serlo/api.serlo.org/issues/582

**Comment by elbotho** [comment]
@kulla just to make sure: I have provide a list of all uuids in the term to the mutations in the order I want to display them.
This way `Applets` will always be before `Courses`, because I display the category first, right?
