### ISSUE TITLE
Add button "Move to recycling bin" + "undeleting from recycling bin" for taxonomy terms

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1597]
Also for taxonomy terms there shall be a new button "move to recycling bin" similar to entities: 
![2022-04-20-125715_414x344_scrot](https://user-images.githubusercontent.com/1327215/164216756-a63648fe-9499-4d91-bc8a-a033254e304b.png)

Also #1596 shall be implemented for this issue.

**Comment by elbotho** [comment]
@kulla can we savely use the `setUuidState` mutation for that as well?

**Comment by kulla** [comment]
> @kulla can we savely use the setUuidState mutation for that as well?

Yes.
