### ISSUE TITLE
Migration: Recycle-Bin

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1598]
Create a view listing the recently deleted entities via https://github.com/serlo/api.serlo.org/issues/586 (links are sufficient since on the view of the entity they can be restored...)

Blocker:

- [x] https://github.com/serlo/api.serlo.org/issues/586
- [x] https://github.com/serlo/serlo.org-database-layer/issues/215

**Comment by elbotho** [comment]
**Legacy:**
Current route: https://de.serlo.org/uuid/recycle-bin
View:
![image](https://user-images.githubusercontent.com/1258870/164708689-48252c68-8771-42aa-a35d-aac954866423.png)

**Comment by elbotho** [comment]
blocker:
- serlo/serlo.org-database-layer#257

nice to have: 
- https://github.com/serlo/api.serlo.org/issues/627
