### ISSUE TITLE
check height of math span within table

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1609]
new: https://frontend-git-1581-remove-edtr-io-state-fixes-in-th-321d1e-serlo.vercel.app/223935

old: https://de.serlo.org/mathe/223935/wahrheitswerttabellen-in-arbeit

(mt had some issues)

**Comment by elbotho** [comment]
Maybe it makes sense to wait for the new table plugin with this one?

**Comment by Entkenntnis** [comment]
already fixes (was introduced by another change of mine)
