### ISSUE TITLE
editing taxonomy not possible

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1612]
![grafik](https://user-images.githubusercontent.com/13507950/165052611-a3dc60ef-1087-4719-ac7d-d420a4e56123.png)

**Comment by Entkenntnis** [comment]
problem introduces with https://github.com/serlo/api.serlo.org/commit/98f59e86f2787ca8aa92acaebea8c387468918ca (probably)

**Comment by elbotho** [comment]
The multiple entries only shows on the lowest hierarchy.
e.g. https://de.serlo-staging.dev/mathe/1288/geometrie

-> see #1613

**Comment by Entkenntnis** [comment]
and this: https://github.com/serlo/api.serlo.org/commit/5d8fbc6927f24f7d937759b407d3487b24f38016

**Comment by Entkenntnis** [comment]
`addChild` renamed to `moveChild` renamed to `change`
