### ISSUE TITLE
Feeback: iPhone usertest simon

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#162]
_by @simonkoehl, checked on iPhone_

generally smooth experience

--- 

- [x] **maybe align sharing button left or put it next to the headline**
Headlines might be longer than that and I's like to keep it out of the flow of the content. 
Now displays next to headline on larger screens.
---

- [x] **white overlay over arrow in mobile meta navigation**

---

- [x] **No distinction between line break and next link**

---

- [x] Landing Page: Subject-Icon animation does not work while scrolling.

---

- [x] Taxonomy Icons without explanation probably not clear to users.

**Comment by simonkoehl** [comment]
Thx @elbotho ! One remark regarding "distinction between line break and next link": I wouldn't say bullet points are my preferred solution. But in the screeshot with the bullet points there is a different distance distinction between line break and next link.

**Comment by elbotho** [comment]
@simonkoehl about the animation issue, you mean that touching&scrolling does not trigger the animation, the animation is only visible if you keep your finger still on the link?
If yes that is expected behaviour since there is no hover on most touch devices it only triggers on a click.
