### ISSUE TITLE
Handle legacy backend routes correctly

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#164]
There are a couple of routes that are handled by the legacy backend instead of the aliasing, including:
- [x] de.serlo.org/spenden
- [ ] ...

We should either handle those via the Cloudflare Worker or add own pages in the frontend (which we definitely need to do in the long-term)

**Comment by Entkenntnis** [comment]
I would be happy if the cloudflare worker could take care of this for the moment (or maybe deleting the obsolete alias /spenden so that the worker will not recognize it as a uuid path?) What do you think?

I'll open a new issue for the donation page.

**Comment by kulla** [comment]
Sorry, wrongly linked fix in https://github.com/serlo/serlo.org-cloudflare-worker/pull/16...

**Comment by Entkenntnis** [comment]
should be fine closing this issue! #170 is the follow up
