### ISSUE TITLE
Migration: Move navigation into frontend

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1640]
The main side navigation (see picture) shall be stored in the config of the navigation: 
![2022-05-09-082935_251x252_scrot](https://user-images.githubusercontent.com/1327215/167352802-583ce693-d2a3-4eb8-81c1-48fcdeb4a08d.png)

**Comment by elbotho** [comment]
waiting for https://github.com/orgs/serlo/projects/21#card-81669970

**Comment by kulla** [comment]
@elbotho Here is the first data for the pages (will do the taxonomy terms next). Do you have any wishes in which form you want to have the data? https://github.com/serlo/evaluations/blob/962243abde4cb0f08b6cd64d7699d34c029dcc65/src/2022/2022-05-16%20Navigation-Export.ipynb

**Comment by kulla** [comment]
@elbotho Here is the script also with the data for all subjects: https://nbviewer.org/github/serlo/evaluations/blob/fbe62bc3e1c979af6529188edc534e530d9e63ad/src/2022/2022-05-16%20Navigation-Export.ipynb Do you need something more / else?

**Comment by elbotho** [comment]
> Do you need something more / else?

I'll try and let you know. Thank you!
