### ISSUE TITLE
editor not loading

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1648]
see https://de.serlo.org/entity/repository/add-revision/94593/94594
and
https://de.serlo.org/entity/repository/add-revision/132836/133894

**Comment by elbotho** [comment]
all ids in those links return 

```
{
  "data": {
    "uuid": null
  }
}
```

where did you find those links?

**Comment by Entkenntnis** [comment]
server side log of vercel - very weird behaviour - they don't even have a typename ...

maybe added a handler for this case and show a message like "this uuid does not exist" is the best why to handle this.

**Comment by Entkenntnis** [comment]
404 will work out for the moment
