### ISSUE TITLE
Footer inconsistencies

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#165]
There are a couple of inconsistencies compared to the current footer:
- [x] GitHub link in footer should be `https://github.com/serlo`
- [x] Github -> GitHub
- [x] Mitmachen and Spenden links are swapped
- [ ] Add Twitter
- [ ] Add Facebook

**Comment by elbotho** [comment]
Thanks for thorough checking! 👍 
I think we left out facebook and twitter because they are not actively maintained atm.
Could you elaborate on the "Mitmachen and Spenden links are swapped"?

**Comment by inyono** [comment]
The Mitmachen icon links to /spenden, the Spenden Icon links to /mitmachen

**Comment by elbotho** [comment]
Thanks :D
