### ISSUE TITLE
adding exercise folder in language versions is not working

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1673]
video: https://www.loom.com/share/51039928afab449ab53debc37ae37a1b

the current implementation still uses legacy endpoints to save. Investigate why this bug happens.

**Comment by elbotho** [comment]
(ping @CarolinJaser)
report in https://docs.google.com/document/d/1XtbBHgp9zarJUBQHaSA_tXtwtebaxVCFMJqeVZbVDb0/edit#

**Comment by Entkenntnis** [comment]
best fix is implementing #1628 - legacy endpoint behaviour is deprecated

**Comment by kulla** [comment]
Here is the full table

```
mysql> select taxonomy.id, instance.name, type.name from taxonomy join type on taxonomy.type_id = type.id join instance on taxonomy.instance_id = instance.id where type.name in ("topic", "topic-folder");
+----+---------+--------------+
| id | name    | name         |
+----+---------+--------------+
|  4 | Deutsch | topic        |
| 16 | English | topic        |
| 33 | Tamil   | topic        |
| 42 | French  | topic        |
| 48 | Spanish | topic        |
| 53 | Hindi   | topic        |
|  9 | Deutsch | topic-folder |
| 19 | English | topic-folder |
| 36 | Tamil   | topic-folder |
| 45 | French  | topic-folder |
| 51 | Spanish | topic-folder |
| 56 | Hindi   | topic-folder |
+----+---------+--------------+
```

**Comment by kulla** [comment]
BTW: The bug needs to be fixed also in DB layer https://github.com/serlo/serlo.org-database-layer/issues/258 However https://github.com/serlo/frontend/issues/1628 indeed will be a fix for the frontend

**Comment by Entkenntnis** [comment]
after some digging, the fastest solution is to disable the buttons in other language versions, which I have done in b9b0c619db7767c84104df9bc5f815a48d92fa71

Moving to API will need a bigger rework of how taxonomy term types are handled.
