### ISSUE TITLE
Migration: Static pages: View of all static pages

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#1679]
In backend there should be a place to list all static pages (they can be filtered by instance), so that admins can find them.

Current design:
![Image](https://user-images.githubusercontent.com/45924645/168973475-78ba6149-25f8-4b1e-af94-9a2e3857f414.png)

Blockers:  
- [x] https://github.com/serlo/api.serlo.org/issues/623
- [x] https://github.com/serlo/serlo.org-database-layer/issues/241

**Comment by elbotho** [comment]
legacy url: `/pages` ([Link](https://de.serlo-staging.dev/pages))
