### ISSUE TITLE
Footer showing twice

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1682]
Example:
- https://de.serlo.org/lerntipps/186900/lernen-mit-eselsbr%C3%BCcken
- https://frontend-git-navigation-data-frontend-serlo.vercel.app/community/neue-f%C3%A4cher-themen

I did not see it first, now it's on all pages.

@Entkenntnis I looked into it a bit already but have no clue what is happening. 
It's probably something in the last deploy?
Do you have an idea?

![image](https://user-images.githubusercontent.com/1258870/169117982-783440e4-1d10-4b9a-a5f5-c559ddc8dc94.png)

**Comment by Entkenntnis** [comment]
Can confirm. It's not on every page, but on most. My guesses: hydration is failing? duplicated keys? I don't know how this can happen

**Comment by elbotho** [comment]
I can confirm that this does not happen when js is disabled and probably happens when hydrating.

**Comment by elbotho** [comment]
more results:
- the second component is outside of the `__next` wrapper 😲
- any component or tag I put into the footers place in `header-footer` get's duplicated
- notification wrapper from ToastNotice is also in the dom twice
