### ISSUE TITLE
non-uniform flex behaviour

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1696]
chromium only: https://de.serlo.org/entity/repository/compare/2027/245765 (within solution at the end)

flex boxes are not splitted 50/50: (only legacy content?)

![grafik](https://user-images.githubusercontent.com/13507950/169783305-8ce46e1a-8c74-467d-85bf-e25c38a90546.png)

**Comment by Entkenntnis** [comment]
The problem is not appearing in the content directly: https://de.serlo.org/mathe/14023/14023

not high prio but an interesting edge case ...

**Comment by elbotho** [comment]
looks like the added url-notes (orange) might change the layout because of their length?

**Comment by Entkenntnis** [comment]
yeah, it's because of the long urls, a `break-all` seems to solve the issue. Any objections?

**Comment by elbotho** [comment]
No, thats great. Thank you.
