### ISSUE TITLE
User management: add/remove role

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#1727]
Admins may add or remove a role to/from a user

We can imitate the current implementation:
![image](https://user-images.githubusercontent.com/45924645/172801527-70048c5f-06c2-498e-afd9-08db44e2171d.png)

Notes:
- Use authorization `user:addRole` and `user:removeRole`
- We can't - like in the current implementation - list all the permissions from a role, that may have to be implemented yet.
- Different to the current implementation, we do not send to the api the id of the role, but the role name and the scope (if the role should be global, use the scope `Serlo`).

Blocker:
- [x] https://github.com/serlo/api.serlo.org/issues/663
- [x] https://github.com/serlo/api.serlo.org/issues/702

**Comment by elbotho** [comment]
@hugotiburtino listing users by their role is also not possible atm. right?

**Comment by hugotiburtino** [comment]
No it isn't, let us do it first

**Comment by hugotiburtino** [comment]
Ok, @elbotho it is done: now you can list users by role. 
We've done it very strict, only admins can list them. Please let us know if we have to make it available for other roles.

**Comment by elbotho** [comment]
waiting for https://github.com/serlo/api.serlo.org/pull/712

**Comment by hugotiburtino** [comment]
https://github.com/serlo/api.serlo.org/pull/712 was finally deployed
