### ISSUE TITLE
Some formulas don't render

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#173]
e.g.
https://frontend.serlo.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/zahlenmengen,-rechenausdr%C3%BCcke-allgemeine-rechengesetze/zahlen/gro%C3%9Fe-zahlen/aufgaben-runden-absch%C3%A4tzen-nat%C3%BCrlicher-zahlen

and 
https://frontend.serlo.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/quersumme,-durchschnitt-betrag/durchschnitt/aufgaben-berechnung-durchschnitts

```
%%\begin{array}{l|c|c|c|c}\text{Zahl}&\text{gerundet auf}&\text{gerundet auf}&\text{gerundet auf}&\text{gerundet auf}\\\;&\text{Zehner}&\text{Hunderter}&\text{Tausender}&\text{Zehntausender}\\\hline\\\;8\,951&\;&&\;&\;\\\hline\\25\,499&\;&&\;&\;\\\hline\\\;24\,999&\;&&\;&\;\\\hline\\4\,785\,934&\;&&\;&\;\\\hline\end{array}%%
```

**Comment by Entkenntnis** [comment]
In this two cases, the author has written latex formulas in plain text using `%% ... %%`. This is working on the existing system, because we have MathJax installed and it wiill render this formulas.

These formulas should be written using the "math"-mode in the new edtr-io

**Comment by elbotho** [comment]
@yolo-bird is that something that the Convo-Team does currently?

**Comment by yolo-bird** [comment]
This behaviour is known in the Convo-team and we will fix it when we convert these entities.

**Comment by elbotho** [comment]
Okay, will close this, because it's a known problem and should not be fixed in the frontend.
