### ISSUE TITLE
Updates for subjects

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1735]
After investigating https://github.com/serlo/api.serlo.org/issues/642 the following changes should be done:

- [ ] In root folders like https://serlo.org/3 instead of displaying `Add topic folder` the string in the menu shall be `Add subject`
- ~[ ] In the metadata title of subjects one can can change the logic which folder is a subject to: `taxonomy_term.type === "subject" || (taxonomy_term.type === "topic" && rootIds.includes(taxonomy_term.parent_id)`~

The root taxonomy ids can be hardcoded in the frontend since they do not change often (only when a new instance is added). They are:

```
mysql> select id from term_taxonomy where parent_id is null;
+--------+
| id     |
+--------+
|      3 |
|  23590 |
| 140404 |
| 140438 |
| 140439 |
| 141572 |
+--------+
```

**Comment by elbotho** [comment]
@kulla just to make sure: Are you planning to you remove `taxonomyTerm.type`s  `subject` and `root` in the API?

(see https://github.com/serlo/api.serlo.org/issues/642#issuecomment-1152881186)

**Comment by elbotho** [comment]
- [x] for now we rely on root and subject being provided by the api
- [x] prepare for `folder` to be renamed to `exerciseFolder` (make sure it works for both while we transition)
- [x] for creating taxonomy terms we don't have to change anything
