### ISSUE TITLE
Some formulas render partially

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#175]
![image](https://user-images.githubusercontent.com/1258870/81410908-d2936c00-9141-11ea-96fa-6ea4c4d9eab2.png)

` \pmatrix and \pmatrix` appear unexpectedly.

e.g. 
https://frontend.serlo.now.sh/mathe/geometrie/analytische-geometrie/grundbegriffe-vektorrechnung/vektorbegriff/vektor

**Comment by elbotho** [comment]
This also breaks in the new editor, so I guess this will be solved by the Convo-Team.
@yolo-bird could you confirm?

**Editor Screenshots**
![image](https://user-images.githubusercontent.com/1258870/81948359-efc4b080-9601-11ea-9fea-b1e00fd63b64.png)
![image](https://user-images.githubusercontent.com/1258870/81948343-eb989300-9601-11ea-9eff-73c2ef4d7b67.png)

**Comment by kathongi** [comment]
Hey botho, we'll fix such problems in the convo project. There we find weird LaTeX Code quite often :D \pmatrix works. But changing the font doesn't.

**Comment by elbotho** [comment]
@kathongi nice! But could you confirm that \pmatrix does work?
In the editor (and the new frontend) I see the `\pmatrix` code in red. Maybe there is still a bug hidden somewhere?

**Comment by kathongi** [comment]
pmatrix is used wrong here. To create a vector or matrix you use \begin{pmatrix}...\end{pmatrix}. That was the problem.

**Comment by elbotho** [comment]
thank you @kathongi and convo heroes
