### ISSUE TITLE
convert `table` to `serloTable` automatically

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1770]
- [x] use fixed edtr version [when available](https://github.com/edtr-io/edtr-io/pull/395)
- [x] fix hidden formula overlay bug (part 1 done, [part 2 pending](https://github.com/edtr-io/edtr-io/pull/396))
- [x] next round of tests
- [x] prepare mutation
- [ ] test mutated data in edtr
- [ ] run and test mutation results

===

[Uuid links and convo status](https://docs.google.com/spreadsheets/d/1RbAtIWYoJoHlFyLG96LgcTn8w7WTfplXtNUe715TJCo/edit#gid=348922671)

====

(ping @CarolinJaser )

**Comment by elbotho** [comment]
deployed in production, up next: migrating the old plugins

**Comment by Entkenntnis** [comment]
relevant pr: https://github.com/serlo/frontend/pull/1771

Basically we want to create a bot that automatically converts all tables to serloTable

**Comment by Entkenntnis** [comment]
not urgent and not important -> closing for now
