### ISSUE TITLE
"Boxen ohne Inhalt werden nicht angezeigt" when content is only a formula

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1776]
minor issue: somehow the hint is shown even if there is content (formula):

![grafik](https://user-images.githubusercontent.com/13507950/177149585-57c61cb9-c6a5-46f9-84ab-9e44834c4fb1.png)

**Comment by elbotho** [comment]
Since we rely on a editor function here I'll close this in the frontend.

``` js
import { isEmptyRows } from '@edtr-io/plugin-rows'
// … 
isEmptyRows(content.get())(store.getState())
```
