### ISSUE TITLE
Migration: Find a way that frontend does not use `Navigation.path` anymore

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1783]
Currently the frontend still uses `Navigation.path` from the API in order to render the side navigation / breadcrumbs. This leads to bugs like https://github.com/serlo/api.serlo.org/issues/701 -> We still need to change the legacy navigation when we make changes in the DB (like adding a new subject). We need to find a way that the navigation can be rendered without using the legacy navigation information any more...

**Comment by elbotho** [comment]
followed up in https://github.com/serlo/api.serlo.org/issues/703
