### ISSUE TITLE
semantic image filenames

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1785]
Currently we use image names like:
`https://assets.serlo.org/${uuidv4}.png`

But the CF-Worker makes sure this link would also work:
`https://assets.serlo.org/${uuidv4}/semantic-name.png`

(see: https://github.com/serlo/serlo.org-cloudflare-worker/blob/main/__tests__/assets.ts#L64)

This would be a small but easy benefit for users and SEO. I suggest we either use the current entity title or parts of the caption/alt text to create this filename.

**Comment by kulla** [comment]
Together with https://github.com/serlo/api.serlo.org/pull/709 the url can be constructed via

```ts
const semanticName: string // The semantic name, encoded

const { urlAfterUpload, fileNameWithoutExtentsion, fileExtension } = data.media.newUpload
const url = new URL(urlAfterUpload)

if (semanticName) {
  url.pathname = `/${fileNameWithoutExtension}/${semanticFilename}.${fileExtension}
}
```

BTW: Currently we need to update CF worker to support this

**Comment by elbotho** [comment]
`semanticName` is still something we make up in the frontend in this case?

**Comment by kulla** [comment]
> `semanticName` is still something we make up in the frontend in this case?

Yep, can be any string which is stripped by the CF-Worker -> can also change any time

(BTW: Issue in CF is fixed with https://github.com/serlo/serlo.org-cloudflare-worker/pull/309)
