### ISSUE TITLE
Should we implement hotjar?

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#180]
The current system has support for hotjar, which I didn't got in touch much.

Can somebody maybe explain, for what we use hotjar and how much effort it would be to include it into the frontend? Is hotjar still relevant (e.g. compared to Matamo?)

**Comment by elbotho** [comment]
@yolo-bird Question to you: Is hotjar still relevant for you?

**Comment by yolo-bird** [comment]
Hotjar is still relevant as it is used for surveys, heatmaps and other stuff. So it has features that Analytics and Matamo do not offer. However priority is quite low (unless you wanna use it to collect feedback for the redesign). This could in fact be nicely done with hotjar.

**Comment by Entkenntnis** [comment]
We can implement hotjar into the frontend as the need arises.
