### ISSUE TITLE
Newsletter-Popup

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#181]
While surfing the site, at some points a popup for the newsletter will pop up:

https://github.com/serlo/serlo.org/blob/6983e369dff10dadd6b3832bf9be489f4619435d/packages/public/server/src/module/Ui/templates/layout/partials/popup.phtml

This is currently missing in the frontend.

**Comment by elbotho** [comment]
@simonkoehl how high would you prioritise this?

**Comment by simonkoehl** [comment]
post release, but important
