### ISSUE TITLE
Don't display "Assign to taxonomy" for GroupedExercise

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1816]
The GroupedExercise (aka "Teilaufgabe") https://de.serlo.org/mathe/207169/207169 has the menu entry "Zuweisung zu Themen und Lehrplan zuordnen" which shall not be visible since those uuids shall not be assignable to a taxonomy, see https://de.serlo.org/mathe/207169/207169

**Comment by elbotho** [comment]
Hmm, this is not as easy to fix as I thought.
Since GroupedExercises won't exist any more after refactoring I'm inclined to not fix this and focus on migration stuff instead. (also this is quite an old bug that was reported now for the first time)
Reopen if you object.
