### ISSUE TITLE
Improve Page Performance

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#182]
Some notes from Lighthouse Audits by elbotho:

**Ideas**
- ~~Images: Different sizes, webp~~ (moved to #253)
- ~~Images: Encourage SVGs (guidelines, extra editor plugin, …?)~~
- Amount of DOM elements: Do we lazy load formulas currently? (Maybe even defer katex-font loading with rel="prefetch")
- Main thread work: Any ideas?
- TTFB sometimes quite long?

**Comment by elbotho** [comment]
@yolo-bird are SVGs explicitly encouraged in the guidelines atm?

**Comment by yolo-bird** [comment]
Not at the moment. Is the technical reason for preferring SVG's that they adapt better to different screen sizes and resolutions? Or why are the better than the other image formats?

**Comment by elbotho** [comment]
For Images that are exported from vector-graphic software (e.g. inkscape) and all images that mostly consist of shapes, lines, color-areas and text SVGs are vastly superior: 
- Smaller file size
- only one file needed for all screen sizes (lossless scaling) 
- resulting file is still editable and could be improved/translated by another author

**Comment by yolo-bird** [comment]
Habe das in die Richtlinie aufgenommen: https://de.serlo.org/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken

Passt das so? (Der Absatz ist ganz oben im Bereich Bilder auf serlo.org einbinden)

**Comment by elbotho** [comment]
@yolo-bird thank you! I like it, only one concern: now it sound like it's always a good idea to use SVG, but e.g. for photos it's a terrible choice.

**Very Simplified:**
Photos: JPEG
Vectors: SVG
In-between: PNG

**Comment by yolo-bird** [comment]
@elbotho
Thanks for the feedback! Do you mind editing the guideline yourself? Your technical understanding is more profound than mine. Also a practical and simplified approach as above is probably the best for authors.

**Comment by yolo-bird** [comment]
Just gave it anonther shot myself @elbotho 
-> https://de.serlo.org/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken

**Comment by elbotho** [comment]
Thank you @yolo-bird I like it!

**Comment by Entkenntnis** [comment]
the remaining points are getting less important as we will have client-side-navigation soon :tada:
