### ISSUE TITLE
Wrong indent for headings in some articles in rendering mode

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1826]
In https://de.serlo.org/mathe/229014/zwei-kugeln-mit-gemeinsamen-inneren-ber%C3%BChrpunkt a heading is rendered with an indent in the normal view: 
![read](https://user-images.githubusercontent.com/1327215/191037345-3373be99-2ee8-4aa7-aa87-266f44c6a459.png)

In the editing view there is no such bug: 
![write](https://user-images.githubusercontent.com/1327215/191037510-bac0f665-79f9-444a-8d35-ef1727b27065.png)

**Comment by elbotho** [comment]
I fixed this in the edtr. Not sure how but there were nested paragraphs. 
Imho this is an upstream issue.
