### ISSUE TITLE
Wrong margins in article https://de.serlo.org/mathe/2057/sinussatz-und-kosinussatz-im-allgemeinen-dreieck

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1839]
In the rendering mode of https://de.serlo.org/mathe/2057/sinussatz-und-kosinussatz-im-allgemeinen-dreieck there are strange margins: 
![read](https://user-images.githubusercontent.com/1327215/191039581-82bbbec2-40ba-4edd-878d-2c1c817afccd.png)
There is no such bug in the editing mode: 
![write](https://user-images.githubusercontent.com/1327215/191039650-0334a3f3-4ec9-4990-9502-41cc9acac452.png)
Maybe related to #1838

**Comment by elbotho** [comment]
did not see the same problem in staging and adding a paragraph in prod also solved the problem. not sure what happened.
