### ISSUE TITLE
Move legal pages to frontend

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1844]
Currently our legal pages are rendered by the CF-Worker. These are the sites:

* https://de.serlo.org/imprint
* https://de.serlo.org/privacy
* https://de.serlo.org/terms

It would be great when we move those sites to the frontend. The rendering is done by the module https://github.com/serlo/serlo.org-cloudflare-worker/tree/main/src/legal-pages Refactoring of the source code there would be also nice :-)

**Comment by elbotho** [comment]
ping @inyono since I remember you were against this change in the past.

**Comment by kulla** [comment]
> ping @inyono since I remember you were against this change in the past.

I already have asked him: He is okay with it :smile:

**Comment by Entkenntnis** [comment]
@kulla Do you know what the status of this issue is?

**Comment by elbotho** [comment]
@Entkenntnis it's unlikely that this will be worked on in the next months and we can take it over or backlog it again

**Comment by Entkenntnis** [comment]
moved to backlog
