### ISSUE TITLE
Fix subtle react warnings

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#186]
~~`<div>` within `<p>`:~~

~~http://localhost:3000/mathe/funktionen/wichtige-funktionstypen-eigenschaften/quadratische-funktionen---parabeln/scheitelpunkt/aufgaben-berechnung-scheitelpunktes~~

Missing key prop:

http://localhost:3000/mathe/zahlen-groessen/grundrechenarten/rechnen-negativen-zahlen/addition-subtraktion-ganzer-zahlen

http://localhost:3000/mathe/zahlen-gr%C3%B6%C3%9Fen/prozent--zinsrechnung/aufgaben-grundwert,-prozentwert-prozentsatz

~~Prop ID did not match:~~

~~http://localhost:3000/mathe/zahlen-gr%C3%B6%C3%9Fen/gr%C3%B6%C3%9Fen-einheiten/aufgaben-umrechnen-zeiteinheiten~~

(only visible during development)

**Comment by Entkenntnis** [comment]
@elbotho The last warning is caused by this line:

https://github.com/serlo/frontend/blob/a78a9adb25e5a80e377d78c51d77856df5a13358/src/components/content/ScMcExercise.tsx#L34

I see what you are trying to accomplish and this actually rely on random numbers ... well, needs some thoughts, but is not critical atm

**Comment by elbotho** [comment]
jup, was a quick fix at that point, now that I know that this annoys next and we forward the ex numbers I can find a different solution.

**Comment by Entkenntnis** [comment]
The first warning will be fixed by #214
