### ISSUE TITLE
kratos: auth/* pages don't update

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1887]
> update /auth/* pages if in other tab session changed (example: one tab at /auth/verification, other at / and in this last one you log out)

**Comment by hugotiburtino** [comment]
While testing #1898, I noticed this bug occurs also in other paths.   
We lost this feature in some of the past refactorings.  
That means: I'm logged in two tabs in any path, I log out in one of them, the other remains the same.

**Comment by elbotho** [comment]
> We lost this feature in some of the past refactorings

I'm pretty sure this never worked. This is also the case in the current (legacy) implementation.
The logged in state updates on the next route change but not before.
I worked on this a little bit already but have not found a great solution yet. I'd argue it's not a blocker.

**Comment by hugotiburtino** [comment]
Solved at #1900
