### ISSUE TITLE
Don't show empty course displays in Taxonomy

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#189]
Last course on this page ("Parameterdarstellung einer Ebene") does not have any pages but is still displayed here:
http://frontend.serlo.now.sh/mathe/geometrie/analytische-geometrie

**Comment by Entkenntnis** [comment]
This behaviour also appears on the existing page, its probably "intended" and can be fixes by changing the content.

**Comment by elbotho** [comment]
Vote to keep open as question since this is irritating an unexpected for users.

**Comment by elbotho** [comment]
@yolo-bird what do you say, is that intended? 
Should we only show empty courses for logged in users or with a special label?

**Comment by yolo-bird** [comment]
Maybe with the exception of the sandbox I would vote that it should not be possible to save empty content (articles, course, etc), as it only irritates the user. 

There should be at least one sentence like "Dieser Kurs ist noch in Bearbeitung". 

I just deleted the course. But good catch @elbotho

**Comment by elbotho** [comment]
okay closed in favour of https://github.com/serlo/serlo.org/issues/420 than, thank you @yolo-bird !
