### ISSUE TITLE
kratos: test language versions

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1903]
make sure other language versions work fine as well

**Comment by hugotiburtino** [comment]
Problems found:

- [x] serlo/frontend#1907
- [x] serlo/frontend#1908
- [x] serlo/cloudflare-worker#340

**Comment by elbotho** [comment]
Current behaviours:
- in legacy it's completely instance specific. I can be logged in as one user on de.serlo.org and as another on en.serlo.org
- in the current production it's a bit unstable and cause of some bugs where frontend and legacy are not in sync

**Comment by hugotiburtino** [comment]
> in legacy it's completely instance specific. I can be logged in as one user on de.serlo.org and as another on en.serlo.org

I think the community would prefer to just be logged in as only one user . We could implement that already and it seems actually easier to do so.
