### ISSUE TITLE
kratos: instance login

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1908]
> Login among instances is not working. If you login in en, you go to de, press 'Anmelden', you get the info that you are already logged in, but you can't do anything a logged in user usually does.
(by @hugotiburtino )

We prefer logging in once and using that session for all instances if possible.

**Comment by elbotho** [comment]
probably fixed with #1906

**Comment by hugotiburtino** [comment]
Thanks, it solves the problem, unless you are entirely in local machine, but I think I'm the only that does that 😆 .

**Comment by hugotiburtino** [comment]
But before closing it, take a look at #1910 

edit: 😆 I was one minute too late

**Comment by hugotiburtino** [comment]
Actually @elbotho, it doesn't work when you are developing with localhost (also using staging infrastructure), since the auth-session cookie is set to serloDomain.
