### ISSUE TITLE
Kratos: fix logout

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#1910]
Somehow the logout is not entirely working in staging.
After logging out, the `ory_kratos_session` cookie gets removed, but the `auth-session` persists.
It works in localhost and it worked in staging before, when it was not proxied by cloudflare. (So, we may need to transfer this issue to CF worker).

But we had some refactorings in the mean time, and we should check if https://github.com/serlo/frontend/blob/kratos/src/auth/fetch-auth-session.ts may be causing it (or at least not helping us), before transfering this issue to cloudflare-worker repo.

If the user is in the same instance, they don't notice the difference. But as long as they are in different ones, they can't have the visual effect that they are logged out unless they remove cookies.

**Comment by elbotho** [comment]
>But we had some refactorings in the mean time, and we should check if https://github.com/serlo/frontend/blob/kratos/src/auth/fetch-auth-session.ts may be causing it (or at least not helping us), before transfering this issue to cloudflare-worker repo.

Since it works fine on localhost I'd guess it's not related to the frontend changes.


> If the user is in the same instance, they don't notice the difference. But as long as they are in different ones, they can't have the visual effect that they are logged out unless they remove cookies.
Not sure what you experienced here. If the local `auth-session` cookie persists while `ory_kratos_session` does not the frontend will still show a logged in state even in the same tab.

**Comment by elbotho** [comment]
solved in de8c1650bc4b2327301c0873efe789c35bbadc60
(Cookies.remove only work if you provide the same config you used to create it)
