### ISSUE TITLE
kratos: rocket chat problems with new users

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1945]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1258870/206128866-8daecc01-1040-4577-ae33-b78ad7e1c5cf.png">

- using a new user that is logged into serlo but not into rocket chat and does not have a rocket chat acc
- After a manual reload and I'm logged in without a problem
- The second time I try the flow it works fine

**Comment by elbotho** [comment]
if the user is new and not logged into serlo before trying oauth I get this error in the frontend
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/1258870/206130934-7c3c044b-3b6a-4c1e-b5c0-722c2a75b0e8.png">

(might also be temporary deployment problem)

**Comment by hugotiburtino** [comment]
> (might also be temporary deployment problem)

I don't think so, it happened sometimes with me, we have to investigate it

**Comment by hugotiburtino** [comment]
Regarding loader at first login, results of the investigation so far:

~There are no logs from rocket chat and couldn't find a way to enable it.~ found logs!

Old problem
https://github.com/RocketChat/Rocket.Chat/issues/4241
> When logging in to rocket.chat via Oauth, intermittently users get hung on the loading /home screen with the icon-spinner active forever. There are no console errors, in addition refreshing the page will always simply log the user in. This happens on mobile as well.

It happened in a version near to the one it is deployed now (3.18.7)
https://forums.rocket.chat/t/the-login-screen-is-not-working/11656

It still happens with SAML
https://github.com/RocketChat/Rocket.Chat/issues/23569

**Comment by hugotiburtino** [comment]
Found the following error:
1. not logged in in serlo
2. go to rocket chat and try login with serlo
3. first attempt with wrong password
4. second with right password
5. stay at serlo (not get redirected)

But if at 3 I use the right password, I get correctly redirected.

edit: will be handled at #1951

**Comment by hugotiburtino** [comment]
~Regarding endless loader at first login, I'm not sure what solved, but it is now resolved.~

~Hypothesis one: smtp wasn't indeed disabled as I first thougth, leading to error, what consumed a lot of memory, shutting down the pod. After disabling it, the error persisted since there was too little memory available for the last pod. Deleting the terminated pods released the memory it needed.~

~Hypothesis two: Enabling the debug log level specified a callback method for the login method. This method is now cached, even though we reset the log level to just error.~

~update: it happening again.~
Now (I hope) it is solved, see better explanation below.

**Comment by hugotiburtino** [comment]
I could finally reproduce the most alarming issue in this issue, namely the Internal Server Error `Something went wrong while getting the login request`.

Steps to reproduce:
1. Log in in serlo as user A
2. Go to rocket chat and try login with serlo
3. You will get redirected to serlo and afterwards to rocket chat, having access to it.
4. Logout from rocket chat
5. Logout from serlo
6. Go to rocket chat and try login with serlo
7. Now log in as user B, leading to internal server error

Log from Hydra
> reason:Field 'subject' does not match subject from previous authentication.

@elbotho Should we care about users that have more than one account now? Anyway, I will enable it for now.

Possible solution https://community.ory.sh/t/subject-from-payload-does-not-match-subject-from-previous-authentication/1192/4
Set remember flag to false

Fun fact: this explains why in prod users couldn't log in with another account.

Anyway, it is now api issue

**Comment by hugotiburtino** [comment]
remember = false was deployed, it should be working now (at least worked for me).

The only thing that remains a mystery is to get the user to get in into rocket chat in the first attempt...

**Comment by hugotiburtino** [comment]
News from rocket chat logs:

```
2022-12-11 15:16:03.264 CET
message: '{"msg":"result","id":"1","result":{"id":"Ek3CnQNeZTKYN9L5M","token":"2p-zuuxkiu_nZ5t38E6hrVawUv1oM2qZTvqfQ-wi25I","tokenExpires":{"$date":1678544163250},"type":"serlo"}}',
2022-12-11 15:16:03.264 CET
success: true
2022-12-11 15:16:03.264 CET
}
2022-12-11 15:16:03.264 CET
}
2022-12-11 15:16:03.264 CET
API ➔ info 10.0.0.36 - undefined [2022-12-11T14:16:03.264Z] "POST /api/v1/method.callAnon/login" 200 - "https://community.serlo-staging.dev/home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" |
2022-12-11 15:16:03.305 CET
Meteor ➔ publish null -> userId: null, arguments: []
2022-12-11 15:16:03.396 CET
Callbacks ➔ debug Executing callback with id 2fa for hook onValidateLogin
2022-12-11 15:16:03.402 CET
Callbacks ➔ debug Executing callback with id EeTjnZStiPWZsoYdf for hook afterValidateLogin
2022-12-11 15:16:03.412 CET
API ➔ debug Success {
2022-12-11 15:16:03.412 CET
statusCode: 200,
2022-12-11 15:16:03.412 CET
body: {
2022-12-11 15:16:03.412 CET
message: '{"msg":"result","id":"1","result":{"id":"Ek3CnQNeZTKYN9L5M","token":"TT3t_xuyzfUfQpjLek7iEMLlecBSnHVj4WdjsgAUkNs","tokenExpires":{"$date":1678544163401},"type":"serlo"}}',
2022-12-11 15:16:03.412 CET
success: true
2022-12-11 15:16:03.412 CET
}
2022-12-11 15:16:03.412 CET
}
```

**Comment by hugotiburtino** [comment]
Now I could correctly jump in into rocker chat general channel with newly create user hugotest14, in the very first attempt, with no endless loader. It was the counterintuitive wrong configuration that I've made in staging rocket chat: I didn't want to 2fa serlo users, so I've disabled 2fa at all. It caused the missing method for 2fa. Enabling it, although we actually don't do 2fa for them solved the issue. (Although counterintuitive, I'm probably just getting wrong what it means in rocket chat). Please test it yourself.

**Comment by elbotho** [comment]
solved by @hugotiburtino 🎉
