### ISSUE TITLE
Missing Feature: Lightbox

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#195]
serlo.org has a simple lightbox to enlarge small images: [Example](https://de.serlo.org/nachhaltigkeit/anbau/gelaende-anbauplanung/pflanzenfamilien)

**Comment by elbotho** [comment]
@yolo-bird can you confirm, that this is not working with new-editor content anymore at the moment? 
(I mean in the old design)

**Comment by yolo-bird** [comment]
@elbotho Currently there is no plugin that allows to to put two or more images next to each other. 
Does that solve your question?

**Comment by elbotho** [comment]
Ahh, very good point @yolo-bird :)

**Comment by elbotho** [comment]
Closed until there is support for image columns in the new editor.
