### ISSUE TITLE
deleted taxonomies don't show up anywhere

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1950]
if so deletes a taxonomy term it's not in the activity logs or the `recycle-bin` and can't really be restored
adding this to the activity logs as an event would probably be the best solution

**Comment by hugotiburtino** [comment]
Fair enough.
How was it before? Were entities mixed with taxonomies?
Anyway, the simplest way to do it now in backend is having another tab/section/... for deleted taxonomies.

**Comment by hugotiburtino** [comment]
@elbotho , when you have time, just confirm that it is ok to have another query, like 'getDeletedTaxonomies'.

If you think it is important to mix deleted entities with taxonomies (something like 'getDeletedEntitiesAndTaxonomies'), please give me a sign. Depending on this decision I'll have to make some changes in backend...

**Comment by elbotho** [comment]
@hugotiburtino having another query like `getDeletedTaxonomies` is fine, they don't have to be mixed.
But having an event is not really optional in the long run imo.

**Comment by hugotiburtino** [comment]
> But having an event is not really optional in the long run imo.

Sure, it is supposed to happen already. It is maybe a bug that wasn't reported yet. Tracked at https://github.com/serlo/database-layer/issues/348

**Comment by hugotiburtino** [comment]
As discussed in our meeting, there will be in the future something like uuid.deletedUuids, but for now we're going just to fix the event.

**Comment by hugotiburtino** [comment]
Fix for taxonomy trash event is deployed
