### ISSUE TITLE
Bug: Exercises don't load

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#198]
First Ex loads, rest not.
http://frontend.serlo.now.sh/nachhaltigkeit/gartenkurs/anzucht-aussaat/57185

**Comment by Entkenntnis** [comment]
The first and last exercises show up correctly, but the remaining exercises are fetches as legacy content - which it should not, as all exercises appear as edtr-io content an the existing page. :/

Needs some more investigation ...

**Comment by elbotho** [comment]
So how is it not a bug?
Can this be solved by updating the content?

**Comment by Entkenntnis** [comment]
Some investigation: take the second exercise of the group, "Tagetes", [ID 57201](https://de.serlo.org/entities/57201?format=json), requested from legacy system results (correctly) in edtr-io content:

![grafik](https://user-images.githubusercontent.com/13507950/81919178-c98a1b00-95d7-11ea-9209-695369b048fb.png)

Doing the same request through graphql results in legacy content:

![grafik](https://user-images.githubusercontent.com/13507950/81919375-1241d400-95d8-11ea-9586-876a19b8c32f.png)

(you see the interactive element missing)

@inyono This looks like a bug in the api server.

**Comment by inyono** [comment]
Yep, created an issue for that: https://github.com/serlo/api.serlo.org/issues/11

**Comment by elbotho** [comment]
Thanks for investigating @Entkenntnis  and @inyono  👍

**Comment by inyono** [comment]
Will be fixed in the next server update.
