### ISSUE TITLE
remove .babelrc

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1985]
there are only a way places we actually use `@apply` within styled-jsx.

If we remove them, we can finally remove `.babelrc` and switch to SWC for the main project

**Comment by elbotho** [comment]
Isn't postcss (nesting) the reason we can't switch?

**Comment by Entkenntnis** [comment]
ah right, this was the other reason I completely forgot ...

so no easy fix, unfortunately, see https://github.com/vercel/styled-jsx/issues/782
