### ISSUE TITLE
Recycle bin crashes

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1987]
atm. if I load more entries on https://de.serlo-staging.dev/uuid/recycle-bin the page crashes

**Comment by elbotho** [comment]
There is a 405 error that might be related

**Comment by hugotiburtino** [comment]
The firefox debbuger led me to TimeAgo Component, where it gets stock in a loop. 
When I use the production branch it works indeed fine (BTW already checked: both production and staging have the same version of timeago-react and timeago.js) .

**Comment by elbotho** [comment]
Thanks hugo! That's a helpful discovery.

**Comment by elbotho** [comment]
closing in favor of #1995
