### ISSUE TITLE
timeago get's stuck in infinite loop

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1995]
affects recycle bin (load more) and notifications (set to read) and probably more.
~likely related to #1987 and might be a problem with SWR or the changes in the API?~
Affects localhost and staging.

(15 broken tabs make my computer go 🔥)

notes:
- updating to swr 2.0 did not solve the problem (#1996)
- `api/localhost-graphql-fetch` seems to work and returns success
- Notification is actually set to read (so server side works as expected)
- just the tab completely freezes (without error or logs) so I expect some loop?

**Comment by elbotho** [comment]
notes:
- updating to swr 2.0 did not solve the problem
- `api/localhost-graphql-fetch` seems to work and returns success
- Notification is actually set to read (so server side works as expected)
- just the tab completely freezes (without error or logs) so I expect some loop?

**Comment by hugotiburtino** [comment]
- It breaks also when using local dev environment
- The firefox debugger leads indeed to a loop related to TimeAgo Component. (Firefox offers to open the debugger if you open dev tools before clicking the button)
- Deleting the component TimeAgo makes it work fine

**Comment by elbotho** [comment]
Should be solved in 8721cbdedeb8908a29f9deeb26dee0debec69eb5.
There was a useEffect missing.
The loading of the language data is less than pretty here. But since I did not find a way to check if the locale data is already loaded this fix includes no refactoring.

**Comment by hugotiburtino** [comment]
Could you discover why it worked in production branch and not in staging?

**Comment by elbotho** [comment]
I guess it had something todo with the updates. React 18 or smth.
