### ISSUE TITLE
Feedback: Exercise groups

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#200]
From wolfgang und kathi:

- [x] Über Aufgabengruppen steht in blau "Aufgabengruppe", das sollte weg.
- [x] Uns beiden gefällt der hellblaue strich links nicht
- [x] Bei Aufgabengruppen würden wir die horizontaelen Striche wegmachen und statt dessen ganz - traditionell mit a,b,c, nummerieren. Das aktuell schaut schon iwie fancy aus, aber wir finden es nicht übersichtlich
- [x] Um die Nummerierung 1,2,3 der Aufgaben fänden wir einen Kreis schick
- [x] Wenn man über das cc-Icon hovert, ist der Kreis nicht zentriert.

---

Das grün bei einer richtigen Antwort hebt sich farblich nicht stark vom blau und dem schwarz ab. Ich habe zwar erkannt, dass es eine andere Farbe ist, aber nicht sofort, dass es grün ist und dass meine Antwort deshalb richtig ist.
Zudem ist hier noch ein Bug: Statt des Feedbacks wird bei SC/MC Aufgaben nur die Ausgewählte Antwort rot oder grün angezeigt. Soll ich hierzu ein Issue erstellen oder reicht die Nachricht hier :-)

**Comment by kulla** [comment]
- [x] In der mobilen Ansicht wünsche ich mir auch Nummern neben den Aufgaben, damit andere leichter darüber reden können -> Lehrer sagt: "Löse Aufgabe XY auf der Seite ..."
