### ISSUE TITLE
successful saving still triggers leave warning

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2000]
I did a lot of refactoring on the edtr io implementation in the frontend.
Renamed variables to make them ambiguous, removed some legacy code, moved code into hooks, etc…

Most things seem to work fine but I'm running into an annoying problem.

the edtr check to see if there are unsaved changes (`useScopedSelector(hasPendingChanges())`) still has the old value `true` ("has changes") when I check if I should warn the user before changing the route.

@kulla do you have an idea if I can check this as a function (not a hook) instead or if I need to keep track of that myself in the frontend?

**Comment by Entkenntnis** [comment]
There is most likely a stale value somewhere - this is also quite annoying to fix, because the edtr core is not exposing the current state as a function atm (run into a very similiar problem in the equations plugin yesterday)

A fix in the frontend will probably be the fastest way - I hope you don't have to do too many hacks for it ...

**Comment by elbotho** [comment]
Working:
- [ ] Entity save
- [ ] Page save
- [ ] Profile description save
- [ ] Taxonomy save

Unfortunately local dev is pretty broken right now (https://github.com/serlo/cloudflare-worker/issues/361) and testing is postponed (or we do it on staging).

I'll have to wait for that.

**Comment by hugotiburtino** [comment]
Sorry for taking so long on the cloudflare issue, you can go on now.

**Comment by elbotho** [comment]
Thanks @hugotiburtino!

False warning gone locally now. Testing again on staging.

**Comment by Entkenntnis** [comment]
@elbotho the linked PR is already deployment. Is this issue still happening?
