### ISSUE TITLE
Events don't load

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#201]
On https://de.serlo.org/community/veranstaltungen/veranstaltungs%C3%BCbersicht and I think everywhere else where events are integrated, they are not displayed in the new design

**Comment by Entkenntnis** [comment]
Thank you for reporting this issue! This will be implemented soon!

**Comment by Entkenntnis** [comment]
This is how it looks like: https://frontend-git-fetch-events.serlo.now.sh/community/veranstaltungen/veranstaltungs%C3%BCbersicht
