### ISSUE TITLE
refactor css

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2012]
Unfortunately, there is no way of using styled-jsx with postcss without relying on babel -> this is a opt-out for the new swc compiler. The only way in the meanwhile is to remove unsupported features from styles:

### tailwind `@apply`

- set classname directly or
- use arbitrary selector to set style on multiple elements

### nesting

- use css modules?
- manually unnest
- ...?

I would like to finish this in the next 1 - 2 month, if we work on this now and then it should be doable. I can take care of the tailwind stuff, @elbotho can you take a look at the nesting situation? we would also like to use turbopack, and they have postcss support (https://nextjs.org/blog/next-13-1#turbopack-improvements)

**Comment by elbotho** [comment]
`@apply` inside `styled-jsx` is only used in some places and we should be quite easy to get rid of. 

The nesting is a bit more annoying but the manual unnest would also work

**Comment by Entkenntnis** [comment]
@screen needs to be replaced as well

**Comment by elbotho** [comment]
what about nesting?

**Comment by Entkenntnis** [comment]
ups, shouldn't be auto-closed
