### ISSUE TITLE
RFC: remove initialProps

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#203]
I propose to remove the `getInitialProps` from our pages in frontend for a couple of reasons:
- It mixes fixtures for testing purposes with production code
- It hides some potential issues (namely when you don't pass required props and it the default value is used instead)

Instead, I'd rather move fixtures (intended for testing purposes) into the storybook. This way, we have one location for our "fixtures" and devs can develop their components with the storybook (and the same fixtures) without having to go through the nextjs stack. Additionally, we might add e2e tests that also test that the nextjs toolchain works correctly (e.g. rehydration etc.), maybe as part of serlo/serlo.org#222.

**Comment by kulla** [comment]
@Entkenntnis I moved this issue to the frontend repository. Is this still an issue or can it be closed?

**Comment by Entkenntnis** [comment]
This is related to our previous setup and can be safely closed
