### ISSUE TITLE
Blank column when opening menu in mobile

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2030]
In Android, DuckDuckGo Browser (version 5.145.5, based on Firefox)

<img src="https://user-images.githubusercontent.com/45924645/211762020-efef4df7-4c29-4758-a9a1-2d966de321e1.jpg" width=300 />

**Comment by elbotho** [comment]
should be closed by 1f2fd54b
@hugotiburtino maybe you can check it on staging in 5-9999 minutes :)

**Comment by hugotiburtino** [comment]
works wonderfully
