### ISSUE TITLE
check new sentry errors

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2036]
going a bit crazy since deploy

**Comment by Entkenntnis** [comment]
mostly hydration errors, hm ...

**Comment by Entkenntnis** [comment]
going down the rabbit hole: there are some slate plugins with block-math inside, the paragraph is rendered as `<p>`, and the block-math as `<div>`, therefore there is a dom validation error and then the hydration failure.

we have not changed anything here? so why is the error surfacing now?

**Comment by Entkenntnis** [comment]
the issue is already present from 11th of january, so it's not related to the current deployment - I was able to reproduce on previous deployment

But still stumbled because I can't find any related change we made

**Comment by elbotho** [comment]
> from 11th of january

you mean before?

**Comment by Entkenntnis** [comment]
I can see a div inside a p already in https://github.com/serlo/frontend/pull/1724 ... so the bug itself is present since quite a while.

It's only now that it surfaced.

**Comment by Entkenntnis** [comment]
e.g. https://frontend-b8hlcimud-serlo.vercel.app/1533, this formula:

![grafik](https://user-images.githubusercontent.com/13507950/212283966-6d4fbb9c-1617-46ee-ac6f-091df474cb88.png)

is a math-div inside a slate-p ...

**Comment by Entkenntnis** [comment]
yeah, this one's on me, I've introduced this bug 9 months ago in  #1602 :cry:, this is the exact commit where it happened: https://github.com/serlo/frontend/pull/1602/commits/28522d88a6c50eac28b72010487defc4bfed3b9f

**Comment by elbotho** [comment]
All good, probably did not even cause problems.
I think the error reporting of hydration errors changed in the new next version that's why we get spammed by sentry now 😅

**Comment by Entkenntnis** [comment]
at least the root cause is located
