### ISSUE TITLE
Integrate compilation of patch into toolchain

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#204]
Currently, we commit both `patch/next/dist/index.tsx` and `patch/next/dist/index.js`. Instead, we should commit only `patch/next/dist/index.tsx` and compile that webpack, too.

**Comment by kulla** [comment]
@Entkenntnis I moved this issue to the frontend repository. Is this still an issue or can it be closed?

**Comment by Entkenntnis** [comment]
Fortunately, we don't need to patch next.js anymore
