### ISSUE TITLE
edtr-io: persist last working state in localStorage

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#2041]
Seems like there currently is an issue where one can't input changes (sometimes, possibly after long edit sessions... Could be any uncaught error, though). We should persist the last working state always in localStorage (not only when saving fails) so that one can restore that.

**Comment by elbotho** [comment]
(this is a legacy issue, but is still relevant imho)

**Comment by Entkenntnis** [comment]
we can listen to `onChange` in `serlo-editor.tsx` and store data in local storage

@elbotho Do you know if the existing localStorage logic is part of the frontend or core? It would be best if we can reuse the same code.

**Comment by elbotho** [comment]
It's part of the frontend code and your suggestion would be easy to try.
We might have to tinker with performance on big states. Most solutions (for server-side storage though) I saw save changes not the whole state.

**Comment by Entkenntnis** [comment]
deployed
