### ISSUE TITLE
Add polyfill for `Object.hasOwn`

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2042]
It causes the problem

(edit: expanded logs)
```
instrument.ts:125 TypeError: Object.hasOwn is not a function
    at s (get-translated-type.ts:15)
    at subject-landing-featured.tsx:49
    at Array.map (<anonymous>)
    at O (subject-landing-featured.tsx:35)
    at ak (react-dom.production.min.js:168)
    at i (react-dom.production.min.js:291)
    at uI (react-dom.production.min.js:281)
    at react-dom.production.min.js:281
    at uO (react-dom.production.min.js:281)
    at u_ (react-dom.production.min.js:272)
    at ux (react-dom.production.min.js:269)
    at x (scheduler.production.min.js:14)
    at MessagePort.T (scheduler.production.min.js:15)
(anonymous) @ instrument.ts:125
instrument.ts:125 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
(anonymous) @ instrument.ts:125
instrument.ts:125 Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (react-dom.production.min.js:294)
    at uI (react-dom.production.min.js:281)
    at react-dom.production.min.js:281
    at uO (react-dom.production.min.js:281)
    at u_ (react-dom.production.min.js:272)
    at ux (react-dom.production.min.js:269)
    at x (scheduler.production.min.js:14)
    at MessagePort.T (scheduler.production.min.js:15)
(anonymous) @ instrument.ts:125
instrument.ts:125 Error rendering page:  Error: Cancel rendering route
    at l (index.js:405)
    at index.js:396
    at new Promise (<anonymous>)
    at es (index.js:394)
    at index.js:281
(anonymous) @ instrument.ts:125
DevTools failed to load SourceMap: Could not load content for https://sa.serlo.org/latest.js.map: Connection error: net::ERR_CONNECTION_CLOSED
```

which affects the a user that can't get newer Chrome updates , since her OS is quite outdated.

**Comment by Entkenntnis** [comment]
This is the list of supported browsers: https://nextjs.org/docs/basic-features/supported-browsers-features

I'm quite sure that nextjs is correctly polyfilling `Object.hasOwn` - `instrument.ts` is not a file of the frontend. Could it be that the script is from some external file? OR some browser extension?

**Comment by hugotiburtino** [comment]
It seems to be a file of sentry (https://github.com/getsentry/sentry-javascript/blob/master/packages/utils/src/instrument.ts). 
How is sentry integrated to frontend?

**Comment by Entkenntnis** [comment]
Thank you for investigating this. we are self-hosting the bundle here: https://github.com/serlo/frontend/tree/staging/public/_assets/sentry

Probably a good time to upgrade.

**Comment by elbotho** [comment]
Pretty sure this is not related to sentry.
I moved from hasOwnProperty to Object.hasOwn and the error actually occurs in the frontend `get-translated-type.ts` in this case but we use hasOwn all over the place.

**Comment by elbotho** [comment]
thoughts:
- unfortunate that there seems to be no auto polyfill
- the support should honestly be ok: https://caniuse.com/?search=Object.hasOwn
- the users chrome is 2-3 years old and should be updated for the sake of security

**Comment by Entkenntnis** [comment]
this is the official list of polyfills: https://github.com/vercel/next.js/blob/canary/packages/next-polyfill-nomodule/src/index.js

If we want to use `hasOwn`, we could use `import 'core-js/es/object/has-own' (not tried yet).

I would suggest at least to try to support all browsers that nextjs is supporting.

**Comment by Entkenntnis** [comment]
https://www.npmjs.com/package/object.hasown also looks good
