### ISSUE TITLE
Polishing Sharing Menu 

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#205]
There are two remaining issues with the sharing menu:

- [x] Mebis-Link is broken. Anyway: I do somehow remember, that there is no link, but you have to just copy the link over to mebis? Maybe disable this button as long as its not functional
- [x] Is it useful to show the sharing menu also on taxonomy pages? Any opionions? Does not look like a blocker.

**Comment by Entkenntnis** [comment]
See #210

**Comment by elbotho** [comment]
added simple mebis logic in #222
and you added sharing to the tax pages: I like it. 
Vote to close 👍

**Comment by Entkenntnis** [comment]
should be done by now
