### ISSUE TITLE
empty box warning is always visible

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2056]
![grafik](https://user-images.githubusercontent.com/13507950/213176774-10d077d8-f49e-4a2e-8e36-e4505fa54d80.png)

maybe a regression of another fix here

**Comment by elbotho** [comment]
if you edit something or otherwise make sure the box get's focused it works as expected. 
Annoying upstream issue. The only solution at the time was not to show the warning, which is also not a solution.
Wontfix from me.
