### ISSUE TITLE
copy & pasting links should work

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2058]
> Wenn ich einen Link aus einem Textplugin kopiere und im Quellenplugin als Quelle einfüge, wird der Anzeigetext des Links eingefügt, aber die Url des Links nicht. Die Url geht einfach verloren.

Investigate if we can do something about it in the frontend

**Comment by elbotho** [comment]
tbh. I'm not sure if collecting the various edtr bugs here is a good idea

**Comment by Entkenntnis** [comment]
-> needs priorisation
