### ISSUE TITLE
Exercises aren't displayed on "Lehrplan"-path in taxonomy

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#206]
See for an example here: https://de.serlo.org/mathe/deutschland/bayern/mittelschule/klasse-5/koordinatensystem-achsenspiegelung
This happens also on some other taxonomy pages, that you access via the "Lehrpläne"

**Comment by jakobwes** [comment]
Remarked it first on "Lehrplan"-pages (don't want to exclude that it could happen somewhere else). But is also not always the case for example here displaying the "Aufgaben" works:
https://de.serlo.org/mathe/deutschland/bayern/gymnasium/klasse-5/nat%C3%BCrliche-zahlen

**Comment by Entkenntnis** [comment]
Thank you for reporting this pages! There is definitively something wrong with the presentation.

**Comment by Entkenntnis** [comment]
@jakobwes Could you check again:

https://frontend-git-fix-curriculumfolder.serlo.now.sh/mathe/deutschland/bayern/mittelschule/klasse-5/koordinatensystem-achsenspiegelung

and

https://frontend-git-fix-curriculumfolder.serlo.now.sh/mathe/deutschland/bayern/gymnasium/klasse-5/nat%C3%BCrliche-zahlen

**Comment by jakobwes** [comment]
Now it is displayed, but I see it two times (one time as folders, one time as tasks):

![Screenshot from 2020-05-12 21-10-07](https://user-images.githubusercontent.com/13718882/81735250-0f8a9600-9495-11ea-8853-957eee1efa22.png)

And this is a bit weird: 

![Screenshot from 2020-05-12 21-11-10](https://user-images.githubusercontent.com/13718882/81735287-1fa27580-9495-11ea-90be-aaea4d681380.png)

But the first link works perfectly now!

Also just one thing that I noticed: the order of the content is reversed in comparison with the old design (there for ex. courses where always displayed first). Don't know if this is intended.

**Comment by Entkenntnis** [comment]
Thank you for checking again! The empty exerciseGroup is stored this way in the db (and is also displayed on the old page), so not related to this issue (still hope that some author could fix this). And yes, the new order is intended, as articles and exercises are the most often used entities in the lab school.
