### ISSUE TITLE
thread: add edit feature

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2062]
User should be allowed to edit their own comment.
When the current viewer is the comment author, it should appear a pencil icon or any sort of info that they can edit it.

Blockers:
- [x] https://github.com/serlo/api.serlo.org/issues/762
- [x] https://github.com/serlo/database-layer/issues/351

**Comment by hugotiburtino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kommentare nachbearbeiten](https://trello.com/c/mL4FkyEG/9-kommentare-nachbearbeiten)

**Comment by hugotiburtino** [comment]
We are almost there in the api.

Question: Does frontend need a `record: Comment` as a result field of the `thread.editComment mutation` (similar to the record in the response of `thread.createComment`)? 
For the context: it is common to have a record when creating, but not when editing (see v.g. setState mutations), but maybe you need it?

**Comment by elbotho** [comment]
@hugotiburtino pretty sure we don't need a `record` in the response. Atm. we don't use it in `createComment` and `createThread` and instead revalidate the whole section.

**Comment by hugotiburtino** [comment]
@elbotho thanks for your answer. We've done so.
It is now deployed in staging.

**Comment by hugotiburtino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic Bearbeitungsfunktionen in Kommentare](https://trello.com/c/lXN1rdTh/66-basic-bearbeitungsfunktionen-in-kommentare)

**Comment by hugotiburtino** [comment]
Notice that the id encoding of comments were not made yet. You don't have to bother with it in this issue

**Comment by Entkenntnis** [comment]
Thank for the work in the backend, I will probably start working in this in 1 - 2 weeks.

One question: It would be probably important to show a small "(bearbeitet)" hint to make it transparent that the comment is edited, so we would need some support for this in the backend

**Comment by hugotiburtino** [comment]
> It would be probably important to show a small "(bearbeitet)" hint to make it transparent that the comment is edited, so we would need some support for this in the backend

Sure, it is also the wish of the community, but they accept to live without it for while (in backend we need to do somethings before enabling it).
