### ISSUE TITLE
Missing white space after bold text

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#207]
At the site https://de.serlo.org/mathe/funktionen/ableitung-funktionen/ableitung-allgemein/ableitung there is after a bold text the whitespace missing (seen with chromium):

![2020-05-12-201311_384x176_scrot](https://user-images.githubusercontent.com/1327215/81730618-1b268e80-948e-11ea-9897-57076cc2b118.png)

The bug is that the whitespace is missing after the `<b>` tag:

![2020-05-12-202223_134x74_scrot](https://user-images.githubusercontent.com/1327215/81730821-6640a180-948e-11ea-9a84-a77e882ade34.png)

In the old design there is a whitespace:

![2020-05-12-201255_371x168_scrot](https://user-images.githubusercontent.com/1327215/81730687-31344f00-948e-11ea-87f4-fb4d096899e9.png)

**Comment by Entkenntnis** [comment]
Thank you, @kulla! This is indeed a bug in our legacy handler, nice catch.
