### ISSUE TITLE
`?contentOnly` is not passed further on the link `next course page` -> needed for integration

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#2073]
Steps to reproduce:

1. Got to https://de.serlo.org/mathe/162013/%C3%BCbersicht?contentOnly
2. Click on "Next page"
3. You will be on the normal serlo.org website

**Comment by Entkenntnis** [comment]
As far as I can remember we decided for a minimal solution, e.g. all links are opened in new tabs, so this behaviour is intended, but not optimal for this situation.

**Comment by Entkenntnis** [comment]
@kulla this would be a new feature (or mini-feature) and needs prioritization
