### ISSUE TITLE
'Archivierte Diskussionen anzeigen' has no animation

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2074]
The pointer is always pointing down, even when it is not showing the archived thread.
See for example https://de.serlo.org/mathe/2171/lineare-gleichung#comment-15560
![image](https://user-images.githubusercontent.com/45924645/214937430-196e891b-b890-4ad6-a72d-b6b14c8de820.png)
![image](https://user-images.githubusercontent.com/45924645/214937495-4cb058ec-da58-4a93-8e10-2fa33548ca97.png)

**Comment by Entkenntnis** [comment]
thank you!
