### ISSUE TITLE
refactor breadcrumbs: only depend on taxonomy term parents

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2075]
previous issue: https://github.com/serlo/frontend/issues/1783

api issue: https://github.com/serlo/api.serlo.org/issues/703

One of the last blockers for legacy migration. After reviewing the technical details, here is a plan:

The frontend will generate the breadcrumbs depending on the taxonomy parents. It will not use `navigation` anymore. This will need a slightly hacky query (see api issue) and our existing choice algorithm for multiple assignments.

This will allow the api the remove all depencies to legacy and we can disable legacy in staging soon.

In a follow up, we could move this logic into the API.

**Comment by hugotiburtino** [comment]
That is quite helpful @Entkenntnis. Thanks for making efforts in this direction!

Let me know if you want to try to implement it directly in the api. Backend team can help you with it...
