### ISSUE TITLE
second edit not visible

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2078]
This bevahiour is a bit surprising, not sure if it's intended:

1. Add revision and save it for review e.g. /entity/repository/add-revision/74888
2. Reopen editor /entity/repository/add-revision/74888
3. Save second revision -> it's not visible in "Bearbeitungsverlauf"

@hugotiburtino  Do you know if new revisions of the same author on the same article are ignored?

**Comment by hugotiburtino** [comment]
If there is no real change in content, it returns success but not actually creates a new revision. Was there any changes?

**Comment by Entkenntnis** [comment]
both edits make the same change, this could be the reason -> i'lll test it again

**Comment by Entkenntnis** [comment]
Thank you, after testing it again: making a different change is working.

So if we want to solve this, we would probably add a warning to the ui

**Comment by hugotiburtino** [comment]
Let me know if you think it is more suitable to throw an error instead. In that case, please transfer this issue to db layer

**Comment by hugotiburtino** [comment]
> Let me know if you think it is more suitable to throw an error instead

We decided back then to not throw an error, because we thought the most probable case would be that someone clicks twice to save. We could throw an error instead, what could confuse users in such a situation. What shouldn't occur at no rate is that two revisions have the same content (bad experience for reviewers).

**Comment by Entkenntnis** [comment]
I have changed the test to make a random edit so that revisions are different, the current behaviour is fine
