### ISSUE TITLE
Sorting children of some taxonomies is not working

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2080]
# What is wrong?

In some taxonomies the sorting feature is not working.

# Steps to reproduce
can log in in staging as a user with this rights, go to [219731](https://de.serlo.org/mathe/219731/jahrgangsstufentest) and click to sort elements: no element is shown.
It affects many taxonomies in https://de.serlo-staging.dev/83249/mathematik-pr%C3%BCfungen

# How should it behave?
After clicking sort button you should be able to sort it like in https://de.serlo-staging.dev/taxonomy/term/sort/entities/91252

_Reported by Karin_

**Comment by hugotiburtino** [comment]
Frontend is not recognizing some children categories in 
https://github.com/serlo/frontend/blob/staging/src/pages/taxonomy/term/sort/entities/%5Bid%5D.tsx#L38-L46

Adding ` TopicCategoryType.exercises,` made it render it for http://localhost:3000/taxonomy/term/sort/entities/219731.

@elbotho @Entkenntnis could you take it up from here? I don't know the context that led you to exclude this and other categories.

**Comment by Entkenntnis** [comment]
@hugotiburtino your analysis and fix is spot on, the topic category type was missing.

The naming convention here is confusing, because it's sometimes called "exercise folder", and other times "exercises" and we also have the "folders" type ... as far as I know this was not intended
