### ISSUE TITLE
retry running tests tomorrow

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2093]
the uuid on staging is somehow broken ...

**Comment by hugotiburtino** [comment]
Indeed, we changed something in the backend and that may be reason why you got errors. I'll investigate it

**Comment by hugotiburtino** [comment]
Maybe solved by https://github.com/serlo/api.serlo.org/pull/784

Could you test it again now?

**Comment by Entkenntnis** [comment]
It's working reliable if I run it from my computer, but the CI is struggling with saving the article.

**Comment by Entkenntnis** [comment]
Ok, the problem is the CI, and I got the following console warning: "No authorization context provided!" => the CI can't save, because auth context got lost somewhere :/

Update: Will investigate this further, there seems to be other factors as well.

**Comment by Entkenntnis** [comment]
Ah, a flaky selector was causing the problems (only failing in headless mode ...) - the test now works

@hugotiburtino thank you for investigating the api issue
