### ISSUE TITLE
fix warning comment in use-handle-save.ts

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2096]
in [src/edtr-io/plugins/types/helpers/use-handle-save.ts](https://github.com/serlo/frontend/pull/2091/files#diff-9a60a200677aed05c07faf170176be439a9a8f9775e03b22b6498ab7723e62fa)

**Comment by elbotho** [comment]
We should just try to remove and test with some cohesive `type-text-exercise-group`s. 
Are you planning to deploy soon? Otherwise I'd put this in staging.

**Comment by Entkenntnis** [comment]
I'd like to deploy tomorrow, then we can test new stuff on staging.

**Comment by Entkenntnis** [comment]
deployment is completed, you can start testing on staging

**Comment by elbotho** [comment]
Okay, actually this does not work when removing the hack. I'll add this to our dev-meeting to ask some backend ppl about this :)
