### ISSUE TITLE
production build on localhost should use local config

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2097]
currently, it uses staging kratos and login fails (e.g. interesting for running e2e tests on localhost)

retry e2e tests after fixing this

**Comment by hugotiburtino** [comment]
I'm not sure if I understand the issue, but have you checked out [serlo/local-dev-env](https://github.com/serlo/local-dev-env)? It makes it possible to use local kratos for logging in in local frontend

**Comment by Entkenntnis** [comment]
It's only related to production builds on localhost - they are using env settings of vercel environment instead of localhost setting, so you can't login if you run a production build on localhost.

We could check for e.g. VERCEL_URL or something similiar
