### ISSUE TITLE
exercises in course pages are not remounted

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2100]
interesting case where excercises on page 2 & 3 are very similiar and not remounted (input is still visible):

https://de.serlo.org/community/266414/parameter-a

-> add e2e test for this

**Comment by elbotho** [comment]
this is a nasty one. 
I was pretty confident it's related to this hack: https://github.com/serlo/frontend/blob/staging/src/components/content/exercises/exercise.tsx#L53 (that we don't really need) but I could not get it to work as of now.

**Comment by Entkenntnis** [comment]
true. have you tried to add `entityId` to idBase so that different course pages will generate different ids?

**Comment by elbotho** [comment]
> true. have you tried to add entityId to idBase so that different course pages will generate different ids?

Nice idea, but also does not solve the bug. 
Maybe it's because we inject the exercises somehow?

**Comment by elbotho** [comment]
nicely done!
