### ISSUE TITLE
<div> in <p> dom validation error

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2104]
opening a lightbox in https://de.serlo.org/1555 is causing a validation error

**Comment by elbotho** [comment]
Could not reproduce on staging just now. Which image did you click?

**Comment by Entkenntnis** [comment]
it only happens the first time if you click any image for me

**Comment by elbotho** [comment]
Weird, can't reproduce in FF, Chrome (tried staging and prod). 
So… I can't work on this one ;)

**Comment by Entkenntnis** [comment]
it was localhost for me - maybe only visible in dev server?
