### ISSUE TITLE
Bearbeitungsverlauf border styling

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2107]
current:
![image](https://user-images.githubusercontent.com/1258870/218694414-3c8aa1c6-36be-4b18-87c5-46bd83fd18e4.png)

old (and intended):
![image](https://user-images.githubusercontent.com/1258870/218694448-a90b75bc-3aa8-4369-8760-76f8088383c3.png)

**Comment by Entkenntnis** [comment]
styled jsx probably changed behaviour for default styles...

Do you remember which tag, tr or td? you were targeting with this?

 https://github.com/serlo/frontend/blob/3f69ceb98ee9fd41feb45c062bfc9f45fdbb096c/src/components/pages/revision-history.tsx#L120-L122

-> I would then add it as tailwind classes

**Comment by elbotho** [comment]
weird syntax anyway, not sure why that worked at all ^^
