### ISSUE TITLE
native lazy image loading

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2109]
Lazy loading attributes for images are now quite well supported and don't break things on older browsers.
We should consider replacing `react-lazyload` at least for the images.

https://caniuse.com/loading-lazy-attr
https://web.dev/browser-level-image-lazy-loading/

**Comment by elbotho** [comment]
@Entkenntnis if you agree I'll start a PR.

**Comment by Entkenntnis** [comment]
sound good, always nice to use native tech. You can start a PR.
