### ISSUE TITLE
images still not picked up as cc licensed by google

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2112]
searching for cc-images with "site:serlo.org" finds three images.
Not quite sure why this is happening since we mark articles as cc-by using the recommended syntax.

#2111 is another try but i'm not very hopeful. 
Maybe we have to consider https://wiki.creativecommons.org/wiki/XMP or do some more research.

**Comment by Entkenntnis** [comment]
thank you for looking into this, quite an impactful aspect, hope we can find a solution

**Comment by Entkenntnis** [comment]
@elbotho anything actionable that we can do here right now? otherwise I would close this issue

**Comment by elbotho** [comment]
I left it open as a reminder to check if my fix works ones it's deployed, but I make a note instead.
