### ISSUE TITLE
notify.js: ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2124]
happens if notification is triggered

investigate if library can be upgrades

**Comment by elbotho** [comment]
created upstream issues:
https://github.com/jesusoterogomez/react-notify-toast/issues/85
https://github.com/jesusoterogomez/react-notify-toast/issues/86

**Comment by Entkenntnis** [comment]
last updated 4 years ago, I don't see much hope this will be fixed upstream.

- `ReactDOM.render` only affects the notification, this will have no negative impact on other parts of the code base ... it's probably safe it ignore for now
- other options are forking / copying / replacing: more involved and I don't thing it's valuabe at the moment

@elbotho I would recommand that we move that into backlog and close this issue for now, as it's not actionable
