### ISSUE TITLE
List does not work in column plugin

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2128]
Lists work in text plugin, but when they are in a column, they don't.

See https://serlo.slack.com/archives/C0BMSC431/p1676903106682029

Please transfer the issue if it doesn't belong to serlo plugins.
(and please tell me where can I find a list of the respective plugins, in order to put future similar issues in the right place)

**Comment by elbotho** [comment]
This does not seem to be a general issue of the columns plugin.
It works fine with newly created lists. 
Somehow the lists in this page got corrupted, will repopen when it happens gain (and maybe can be reproduced)
