### ISSUE TITLE
Side-menu on topics

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#213]
For some reason for example in https://de.serlo.org/informatik the "Papierkorb" and "Taxonomy Bearbeiten" are displayed in the side-menu (while they are not in the old design). Not all users have access to these pages, so they shouldn't be displayed.
Also in /biologie the side-menu is far longer than in the old design (probably also is the case for some other topics)

**Comment by Entkenntnis** [comment]
See #149, these entries are hidden behind a dropdown and are now flatten out as a quick solution:

![grafik](https://user-images.githubusercontent.com/13507950/81745294-dbb76c80-94a4-11ea-986d-c85b96571889.png)

You can even go two levels down:

![grafik](https://user-images.githubusercontent.com/13507950/81745392-0dc8ce80-94a5-11ea-9581-97b80f15e66b.png)

I honestly don't know if or how to organize this properly, especially on mobile ...

**Comment by elbotho** [comment]
Can only speak for Nachhaltigkeit but there it's not important and badly maintained.
A page titled "Bei Serlo-Nachhaltigkeit mitmachen" that links to the other parts in the content might actually be better.

**Comment by elbotho** [comment]
And everything that is only useful for authors (e.g. Papierkorb) should def. only display for logged-in users.

**Comment by Entkenntnis** [comment]
Who is actually maintaining this part of Serlo? It would be cool if this person could look into this and clean this up a bit...

**Comment by elbotho** [comment]
@Entkenntnis I **think** it's maintained by the Redaktion.
@yolo-bird could you take a look here?
I think we need a quick fix and a long term solution :)

**Comment by yolo-bird** [comment]
Quite a nice conicidence. Yesterday @jakobwes  and I hat a look at this topic and decided to solve it this way: https://de.serlo.org/biologie
So basically on the side menu there will be the taxonomy, curricula (if existent) and on button "bei Fach xy mitmachen". 

We will take this approach to all other subjects next weel, so that the second level of the side navigation will be completely vanish. 

Is there anything else bothering you with the side navigation right now?

**Comment by elbotho** [comment]
(changes by @yolo-bird currently not visible in the new frontend for some reason)
Nice! Looks great. 
Let's see if changes will be updated soon and what happens with "Papierkorb" und "Taxonomie bearbeiten".

**Comment by inyono** [comment]
@elbotho: created an issue for that: https://github.com/serlo/api.serlo.org/issues/12

**Comment by yolo-bird** [comment]
For all main subjects the side navi has been reduced to one level now.

**Comment by Entkenntnis** [comment]
Thank you all for working on this! This looks resolved now.

**Comment by inyono** [comment]
FYI: we decided to handle the purging of the navigation cache manually for now (since we don't have updates very often and the changes are small, so annoying to cache). Let me know if I should reset the cache.

**Comment by yolo-bird** [comment]
Resetting the cache would be quite nice, as I altered the side navi of 5+ subjects. Thanks!
