### ISSUE TITLE
Edit and share button appear and are cropped when serlo content is embedded via iframe using url param contentOnly

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#2136]
Opening `https://de.serlo.org/mathe/12345/12345?contentOnly` just shows the content. Not the share and edit buttons. 

Opening the same url inside an iframe shows edit and share button but they are cropped at the edge of the iframe. See image. 

Embedding like this is used in the integration of the Serlo Editor in RLP. 

![image](https://user-images.githubusercontent.com/59921805/221421095-4c023092-c9bc-4590-abd5-9aa1c4d53c3f.png)

**Comment by elbotho** [comment]
Thanks for reporting.
The problem ist not the iframe but window size.
Seems we forgot to to test smaller screen sizes in contentOnly mode.

**Comment by LarsTheGlidingSquirrel** [comment]
Thank you for the quick fix! 💚
