### ISSUE TITLE
Modals (e.g. image zoom) can be offscreen when serlo content is embedded within an iframe

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#2140]
When clicking on an image a modal displaying the image is shown in the center of the browser window. This works fine outside an iframe. Within an iframe however, the modal is displayed in the center of the whole iframe, which might be offscreen, when the iframes height is large enough.

**Comment by elbotho** [comment]
Do you have an example of iframe sizes where this happens? Or a link?

**Comment by LarsTheGlidingSquirrel** [comment]
You can open a file containing this html and then click the image: 
``` html
<html>
  <body>
    <iframe style="width: 100%; height: 5000px" src="https://de.serlo.org/2075?contentOnly"></iframe>
  </body>
</html>
```

**Comment by Entkenntnis** [comment]
https://jsfiddle.net/wymcr4gq/

modal is positioned correctly, but because the iframe is so big, the center is way off ... 

Most of the time, you would fix the size of the iframe and scroll the content instead of scrolling the iframe, though?

**Comment by LarsTheGlidingSquirrel** [comment]
We currently use such iframes in the RLP project: The height of the iframe is set to the total height of the embedded content. That way, we do not get nested scrollable areas. 

Imo this is better than nested scrollable areas but it creates issues like this.

**Comment by elbotho** [comment]
Thanks for the example and explanation. Sorry, but this is a #wontfix from me.
If you don't want double scrollbars I think there are better solutions. I'm not quite sure I understand the problem well but with  a wrapper with `overflow-x: hidden` and some positioning I think you might be better of.

**Comment by elbotho** [comment]
Get in touch if you want some frontend support with your iframe solution :)

**Comment by LarsTheGlidingSquirrel** [comment]
> I'm not quite sure I understand the problem well 

It is just bad UX currently: The image modal appears offscreen when you click the image to enlarge it. 

I don't have a strong opinion on how important this is, so I think it is completely fine to not focus on this issue now. Just wanted to forward it because it popped up in the user testing we did. :)
