### ISSUE TITLE
comment edit: new content is only shown after tab switch

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2141]
From the beta testing document

> Bearbeitung wird nur angezeigt, wenn man den Tab wechselt und zurück kommt, aber nicht, wenn man auf der Seite bleibt, auch Antworten, aber nicht bei ersten Kommentaren

Windows 10, Chrome 110

![image](https://user-images.githubusercontent.com/45924645/221868517-a5f5a025-f004-437c-87b2-cad4d9013f0d.png)

[Sentry error](https://serlo.sentry.io/issues/3881707119/?environment=staging&project=5206333&query=is%3Aunresolved&referrer=issue-stream)

Any idea of why it happens only with this user?

**Comment by Entkenntnis** [comment]
can't reproduce the problem with tab change (windows 10, chrome)

the #421-error is not related to this. I had some problems with auth the last couple days.

Can you see if clearing cookies and logout/login solves the issue?

**Comment by hugotiburtino** [comment]
It was asked

**Comment by Entkenntnis** [comment]
@hugotiburtino please reopen if you can reproduce bahaviour

**Comment by hugotiburtino** [comment]
alright, by the way, clearing the cookis and logout/login didn't work
