### ISSUE TITLE
user background dropdown: triangle is not clickable

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2151]
Minor thing from the beta testing group.

![image](https://user-images.githubusercontent.com/45924645/222147658-d0a138bc-fbbc-412c-94e3-9e276e8cbd40.png)
![image](https://user-images.githubusercontent.com/45924645/222147685-4946287f-39b2-4eb0-b91b-b95f24cc7aea.png)

**Comment by Entkenntnis** [comment]
@hugo I have prepared a PR
