### ISSUE TITLE
improve sharing menu

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#216]
![image](https://user-images.githubusercontent.com/3379377/81811066-55db0600-9524-11ea-888a-30538849c595.png)

Suggestion for improvement:

![image](https://user-images.githubusercontent.com/3379377/81811463-f3363a00-9524-11ea-9983-2cf5ae7718a9.png)

And btw. you could do the distance between icon and text with margin instead of blank character ;)

**Comment by elbotho** [comment]
> And btw. you could do the distance between icon and text with margin instead of blank character ;)
Where and why?

**Comment by simonkoehl** [comment]
The string is "[ ]Kopieren" and there seams to be no margin between text and icon

![image](https://user-images.githubusercontent.com/3379377/81820686-39919600-9531-11ea-92e3-63d67af0448c.png)

**Comment by elbotho** [comment]
Okay, and why is that a problem?

**Comment by simonkoehl** [comment]
May be it's not. I just noticed it is different with the other buttons and thought it might become a problem with translations if the translater misses the blank character.
