### ISSUE TITLE
suggestion: improve user orientation with icons

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#218]
![image](https://user-images.githubusercontent.com/3379377/81814586-40b4a600-9529-11ea-9294-0564b10cd7ff.png)

... and respective with
- Exercises
- Videos
- Courses
- Appletts

imo that would help to better distinguish between:
a) taxonomy and content
b) articles and course pages

**Comment by elbotho** [comment]
Part of original design draft, so I like it ;)

**Comment by simonkoehl** [comment]
suggestion: put icon behind the title?

![image](https://user-images.githubusercontent.com/3379377/83130153-2b6d7900-a0de-11ea-8416-d6600d0f0d84.png)

**Comment by simonkoehl** [comment]
And two issues regarding the taxonomy icon:
1) the titel "Zahlen und Größen" seams to have the wrong icon. It's thw one for topic-folders, but it should be the one for "Bereiche"
2) Logically "Grundrechenarten" should have an icon. too. But imo we should get rid of icons for topics - which also helps to distinguish them from learning content. That would als solve 1)

![image](https://user-images.githubusercontent.com/3379377/83130381-843d1180-a0de-11ea-987b-6290ddd28c5f.png)

**Comment by simonkoehl** [comment]
consequently, this

![image](https://user-images.githubusercontent.com/3379377/83131532-404b0c00-a0e0-11ea-8d4a-1ee76752b4d5.png)

would look like this:

![image](https://user-images.githubusercontent.com/3379377/83131686-843e1100-a0e0-11ea-8b6b-61220d8a108f.png)

**Comment by elbotho** [comment]
@simonkoehl d'ac­cord with smaller icons, check out:
https://frontend-git-content-type-icons-minor.serlo.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/prozent--zinsrechnung
https://frontend-git-content-type-icons-minor.serlo.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/prozent--zinsrechnung/prozent

**Comment by simonkoehl** [comment]
looks goo! (realy cool, how fast you we can build these live previews now)

except one thing: The topic folder (Aufgaben) icon should also be behind the title. e.g.: https://frontend-git-content-type-icons-minor.serlo.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/quersumme,-durchschnitt-betrag/durchschnitt/aufgaben-berechnung-durchschnitts
