### ISSUE TITLE
broken solution button

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#220]
Windows 10, Brave

![image](https://user-images.githubusercontent.com/3379377/81816229-575bfc80-952b-11ea-964b-97619527cc48.png)

**Comment by elbotho** [comment]
please add links.

**Comment by simonkoehl** [comment]
in my browser this is with every solution button, e.g. on https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras/aufgaben-satzgruppe-pythagoras

**Comment by elbotho** [comment]
super weird, can't reproduce in any browser on mac (even brave).
do you have the current version?
can anyone else reproduce?

**Comment by Entkenntnis** [comment]
I can reproduce it on win10 brave, chrome and firefox

related to the font (cambria math) and word-wrap: break-word...

I would suggest to use &nbsp; in https://github.com/serlo/frontend/blob/b38760947f897f3d955ee10f49516d386a39aec1/src/components/content/exercise.tsx#L97
