### ISSUE TITLE
missing margin

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#221]
![image](https://user-images.githubusercontent.com/3379377/81816867-36e07200-952c-11ea-8e3c-8a37e60f5604.png)

**Comment by elbotho** [comment]
never seen this before, could you add a link?

**Comment by simonkoehl** [comment]
https://de.serlo.org/mathe/geometrie/dreiecke,-vierecke,-kreise-andere-ebene-figuren/kreise-kreisteile/aufgaben-kreisen-kreisteilen

2a) and type in anything in the input field

**Comment by elbotho** [comment]
@simonkoehl thanks! will be fixed soon.
