### ISSUE TITLE
text in notifications shows wrong comment

### ISSUE THREAD

**Issue by MoeHome** [serlo/frontend#2210]
https://community.serlo.org/channel/software-features-and-bugs?msg=QToTfuEqhLe7Hhvqo

I investigated a bit and could reproduce the issue.

1. Someone answers on a thread to which you subscribed (comment1).
2. You get the notification (it is shown correctly).
3. Anyone also answers on that thread (comment 2).
4. The above notification shows the text of comment1 but the author of comment2.

I guess there is some bug that for the text it is just looked at the thread and the newest comment is fetched.

**Comment by elbotho** [comment]
Thanks for the investigation.

I might have found the problem.
For some reason (my fault) we currently only query the last comment of a thread which works fine for threads with one answer or if it's actually the last comment but breaks for all other cases.

``` gql
comment: comments(last: 1) {
          nodes {
            id
            content
          }
        }
```

**Comment by Entkenntnis** [comment]
@MoeHome @elbotho The linked PR solves the issue, but I encounter another small thing:

The notification take about 3 min to arrive (staging). Hard refresh in the frontend is not helping. Is this intended behaviour or is it a bug somewhere?
