### ISSUE TITLE
404 for /_assets/img/meta/mathematik.png

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2218]
Found in server-side logs.

The actual file name is called `mathe.png`.

Wasn't able to search for the actual cause yet.

**Comment by elbotho** [comment]
thanks, probably due to changes I made here

**Comment by elbotho** [comment]
Good catch, the logs are actually full of unexspected stuff. 
I could not find the root of the mathematik.png issue so far. 
there are also requests to `/de/assets/images/meta_serlo.jpg` that do not make sense to me.

**Comment by Entkenntnis** [comment]
huh, we changed the path a very long time ago ...

**Comment by Entkenntnis** [comment]
after double checking all meta image tags, I can confirm that they are currently set correctly.

So we have ghosts of past times that still visit us, which is a bit spooky. Ghosthunter skills needed xD

Otherwise I can't really explain who all these old urls end up in our log.

**Comment by elbotho** [comment]
👻
just checked. It's not legacy either.
