### ISSUE TITLE
injection background is blue

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2228]
Found on https://de.serlo.org/mathe/1555/zylinder?contentOnly=1

![grafik](https://user-images.githubusercontent.com/13507950/226958946-3ac4b613-7067-4557-8b52-7c01a3e00692.png)

The body-background color is visible, because html collapses the margin with h1, related to current change.

@elbotho Any ideas? My suggestion/quickfix would be to add a global style to content-only to make body white for this route.

**Comment by elbotho** [comment]
Uh, interesting. Never had that happen.
Your suggestion sounds good. Reverting is also an option.

**Comment by elbotho** [comment]
Should I do it?

**Comment by elbotho** [comment]
`padding-top` on body does the trick and is probably a good idea anyway.

**Comment by Entkenntnis** [comment]
Yes, you can do it and select the best method, I don't have a strong opinion here
