### ISSUE TITLE
landing page overflows

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2237]
on smaller screens, some element is overflowing on the right, causing the page either to scroll or will display a small blue gap:

![grafik](https://user-images.githubusercontent.com/13507950/227456937-a811a2e4-0294-45c8-9cbb-5648e9393fe4.png)

As far as I see, this is only concerning the landing page and below ~400px.

I'm thinking about adding a `overflow-x:hidden` here.

**Comment by elbotho** [comment]
@Entkenntnis did this occur on a real device?
I don't really think we need to consider viewports below `320px` and for that it works for me.
(edit: just checked usage [here](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide) and they don't even track below 360px)

I'll add an PR with some responsive improvements anyway :)

**Comment by Entkenntnis** [comment]
This issue occured on my phone, which has a viewport of `360px`. (android, chrome 106). I was able to reproduce it in FF and Chrome on desktop

#2239 fixes the issue for desktop, thank you.

I can still see a small gap on my phone in #2239. I noticed that my phone is not respecting `hyphens:auto`, and the word "Bildungsgerechtigkeit" is not fitting the screen -> so this is another issue ...

**Comment by Entkenntnis** [comment]
my phone is too old for hyphens, I don't think we need to support this android 6.0
