### ISSUE TITLE
Missing spaces after links

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#224]
![image](https://user-images.githubusercontent.com/1258870/81911827-18cb4e00-95ce-11ea-97bb-5bd5dee4635c.png)

from:
https://de.serlo.org/37455/uebersicht

**Comment by Entkenntnis** [comment]
interesting, will investigate this

**Comment by Entkenntnis** [comment]
Never be lazy and take shortcuts :grinning: , is fixed now
