### ISSUE TITLE
editor: find and implement the most useful behavior for stepping in and out of links

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#2276]
When the user selects a link and tries to step out of it using the arrow keys, we can:
1. Step out of the link **and** over the next character/empty space. This makes for a smoother flow through the text and hides the difference between a link and normal text from the user.
2. Step out of the link, **but** not over the next character/empty space. This allows for more control, as the user can choose to continue typing inside the link, or step just outside the link and then continue typing.
3. Use the first approach when there is an empty space outside the link, otherwise use the second approach.
4. Go for the first approach, but when the cursor is at the edge of the link, make the link unselected.
5. Something else?

Note: There is a relevant Chromium bug which makes the behavior of the second approach inconsistent between Firefox and Chrome. Here is how to fix it: https://github.com/ianstormtaylor/slate/blob/main/site/examples/inlines.tsx#L241

**Comment by Entkenntnis** [comment]
For reference: The current version is using approach 4, which I find pretty ok - not sure how difficult it would be to implement

(these are the nerdy discussions you engage in if you are creating rich text editors 😎)
