### ISSUE TITLE
editor: selection moving

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2277]
I select a text via keyboard or with the mouse and then use the arrow keys: The selection moves.
Expected behaviour after using the arrow keys: No selection, cursor moves position.
![selection-problem](https://user-images.githubusercontent.com/1258870/230139710-4ba296fb-4b52-4785-886b-f36d427bd86d.gif)

OSX, Chrome

**Comment by hejtful** [comment]
I can't reproduce it on OSX, Chrome :( Any more hints?

**Comment by elbotho** [comment]
@hejtful pretty sure the revert just fixed it again.
