### ISSUE TITLE
editor: Internal server error on viewing article revision, possibly involving missing property "type" in text plugin state

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#2281]
On staging, 
- open the editor on this article: https://de.serlo-staging.dev/entity/repository/add-revision/27801
- make some minor change in the article introduction, I made the first word 'Um' bold. 
- save revision
- open the revision in view-mode, not edit mode. 

This gave me a frontend error page, internal server error. 

Comparing the content fetched from the api of the broken revision and the non-broken revision (one revision before that) shows a difference in the image caption of the article introduction.

Non-broken:
```
"plugin": "text",
"state": [{ "type": "p", "children": [{}] }]
```

Broken:
```
"plugin": "text",
"state": [{ "children": [{ "text": "" }] }]
```
Most notably, the property "type": "p" is missing in the broken revision. Other occurrences of the "plugin": "text" always have a "type".

Modifying other articles in the same way did not reproduce the error.

**Comment by Entkenntnis** [comment]
@LarsTheGlidingSquirrel Thank you for the thorough testing.

@hejtful It looks like #2257 is doing it's work, but it confuses the frontend.

Looking at it, I think #2257 should keep the type of the previous plugin, e.g. the state should be 

`[{ "type": "p", "children": [{ "text": "" }] }]`

**Comment by hejtful** [comment]
Good point, I just missed adding the type there.
