### ISSUE TITLE
SSO: Put single sign-on into an experiment

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2299]
SSO should be disabled by default until we need it. See discussion https://github.com/serlo/frontend/issues/2292#issuecomment-1506963969 and https://serlo.slack.com/archives/CEB781NCU/p1681308459785569?thread_ts=1681304582.199229&cid=CEB781NCU

Note that experiments the way they are currently implemented might not be a viable solution. See comment https://github.com/serlo/frontend/pull/2303#issuecomment-1521682746

**Comment by elbotho** [comment]
I guess we don't need this any more.
