### ISSUE TITLE
broken exercise tools

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2311]
"Inhalt zu anderer Textaufgabe verschieben" leads to https://de.serlo.org/entity/link/move/link/10747/undefined and is not working.
but also "move to other group" is broken atm.
Needs investigation.

Example: https://de.serlo.org/mathe/10747/10747

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1258870/232770321-5f848d39-2773-4cf2-9572-ca18cbf47728.png">

**Comment by hejtful** [comment]
Could this be connected to the editor, should I also investigate?

**Comment by elbotho** [comment]
@hejtful pretty sure it's not. thanks.

**Comment by Entkenntnis** [comment]
not implemented

#2313 will be the replacement

We will remove theses functions from the menu.
