### ISSUE TITLE
https://en.serlo.org/math/41707/exercises-addition-and-subtraction-of-decimal-fractions responds with 503

### ISSUE THREAD

**Issue by silvia-br** [serlo/frontend#2314]
[https://community.serlo.org/channel/software-features-and-bugs?msg=t92JhmenXEJPNj4ni](url)

<img width="953" alt="image" src="https://user-images.githubusercontent.com/127129431/233022958-500f224e-2bc3-4b49-b7be-89a0224b3b99.png">

**Comment by Entkenntnis** [comment]
Fixed with 87f8a22e00904aff73f243717b97f7bdf3373976

The content contains the invalid id `4129341293` which causes a exception to be through, added  safe guard
