### ISSUE TITLE
Applet title and text not loading

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#233]
**Examples:**
https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras/satz-pythagoras---zusammenhang-fl%C3%A4chen-seiten
http://localhost:3000/mathe/geometrie/konstruktion-geometrischen-objekten/konstruktion-regul%C3%A4ren-sechsecks

**Comment by Entkenntnis** [comment]
Huch :grin:, will take a look at this

**Comment by Entkenntnis** [comment]
Very good catch, the title and the content were indeed missing in the fetcher.
