### ISSUE TITLE
investigate bundle size analyzer

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2330]
currently, the bundle size analyzer is showing an increase of +19kb, but I don't know if it's actually related to changes (vercel output looks good) or is an issue with CI.

Needs investigation.

**Comment by Entkenntnis** [comment]
#2324 needs a dynamic import

**Comment by elbotho** [comment]
Whoops sorry, because this was for testing I did not check the bundle.

**Comment by Entkenntnis** [comment]
No problem, this is why we have a staging environment :)
