### ISSUE TITLE
investigate failed e2e tests

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2332]
two e2e test cases are broken:

![grafik](https://user-images.githubusercontent.com/13507950/233476129-ab645b13-48cd-4798-9f5f-b438e528f35b.png)

could be related to auth changes

**Comment by Entkenntnis** [comment]
probably staging issues...

**Comment by hugotiburtino** [comment]
See #2333, it was making impossible to focus and edit

**Comment by Entkenntnis** [comment]
thank you for investigation!
