### ISSUE TITLE
Finish and release import uuid

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2336]
Code is testable on staging.

@elbotho How is the feedback so far? Any bigger issues?

**Comment by elbotho** [comment]
I think testing has not really started yet.

**Comment by elbotho** [comment]
Since there is nothing actionable here rn I will close this and reopen issues when the PO (Lina) comes back with bugs or requests for changes.

([trello](https://trello.com/c/6O1DIGFK/59-vorhandenen-lerninhalt-duplizieren))
