### ISSUE TITLE
In staging changing tabs leads in add-revision to reset changed content

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2338]
It is probably caused after #2324
We had this problem after releasing the new user management: user edits, change tab, when they go back to serlo tab, the changes are gone

**Comment by Entkenntnis** [comment]
Ah, this again.

Good moment to add e2e tests for this.

**Comment by elbotho** [comment]
This only affects firefox and logged in users (so I agree, it's very likely connected to the single logout change).

**Comment by elbotho** [comment]
> Good moment to add e2e tests for this.

since this is firefox only we could not catch this atm. right?

**Comment by hugotiburtino** [comment]
> since it is firefox only

It happens to me also when editing a solution in Chrome 
v.g. https://de.serlo-staging.dev/entity/repository/add-revision/9491

**Comment by elbotho** [comment]
Can't reproduce.
Did you play around with auth at the same time?
What version of Chrome/Chromium are you on?

**Comment by hugotiburtino** [comment]
> Did you play around with auth at the same time?

Just using the normal staging, but indeed I'm logged in.

> What version of Chrome/Chromium are you on?

version 112.0.5615.138 of Chrome

**Comment by Entkenntnis** [comment]
So, this is the e2e test that I came up with. It works on staging.

@elbotho Is this a complete reproduction of the bug?
@hugotiburtino Does this match your problem?

![grafik](https://user-images.githubusercontent.com/13507950/233988909-253d4ac9-e210-437b-8957-9c1917896623.png)

source: https://github.com/serlo/frontend-e2e-tests/pull/27

**Comment by Entkenntnis** [comment]
Hm, ok, if I do this manually in firefox, then the state is not reset ... (using incognito mode and login as kulla)

**Comment by Entkenntnis** [comment]
@hugotiburtino please reopen if it persists for you.

I will test on staging right now again if I can reproduce.

**Comment by hugotiburtino** [comment]
> @hugotiburtino Does this match your problem?

I think so

> @hugotiburtino please reopen if it persists for you.

No it doesn't, problem solved. Thanks you both!
