### ISSUE TITLE
title attribute on FontAwesomeIcon results in warning

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#234]
```
Warning: Prop `id` did not match. Server: "svg-inline--fa-title-nl3yhQQDX4a8" Client: "svg-inline--fa-title-9OZE5D5NvIix"
```

how could I solve this?

**Comment by Entkenntnis** [comment]
Ok, fontawesomeicon is also creating random ids that are not stable across server and client - and is only using them when you add a title ...

Would it suffice to wrap the icon in a span and add the title to the span?

**Comment by elbotho** [comment]
prefect quickfix, thank you!

**Comment by MrJadaml** [comment]
I was also running into this. Seems like the api updated to use `titleId` prop instead.
