### ISSUE TITLE
links to assets.serlo.org break

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2344]
Link components normalizes links that go to *.serlo.org and currently breaks links to e.g. `https://assets.serlo.org/legacy/54f4b0afc6f69_4b0ec3ca403a3f1e5dd3293ca52a5b98d4c7f2e2.pdf` by turning it into `https://de.serlo.org/${target}`. 

Some Examples on https://de.serlo.org/transparenz.

**Comment by Entkenntnis** [comment]
good catch. I'm out of house tomorrow afternoon, you can make a deployment yourself.

If you want you can also add a test case to e2e ...

**Comment by Entkenntnis** [comment]
@elbotho [7887c5f9ae2210aad542ee2a2ecabf267df7d27c ](https://github.com/serlo/frontend-e2e-tests/commit/7887c5f9ae2210aad542ee2a2ecabf267df7d27c) tests for these links

**Comment by elbotho** [comment]
Thank you @Entkenntnis for being faster than me with the tests 😌
