### ISSUE TITLE
feat: merged plugin selection menu (editor)

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2360]
- merge the two existing plugin menus (click-overlay and keyboard popover) into one reworked menu
- keep plugin filter by name
- use new custom icons for the plugins ~(bonus points for optimised svgs)~

### design & layout
- focus on function for now, use old or new design elements/colors
- for now do not use an additional input field. The text plugin is basically the input. (So the text plugin content would be `/bild` when using the keyboard or just `bild` when using the mouse.)
- each plugin is displayed with the new icon, title and short description (note: we'll need to shorten these if we actually want to keep them in one line)
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1258870/234593385-c8c077c0-fa35-41c2-9895-38ad3425157a.png">

### usage details
- clicking a plus button should create an empty text plugin with the selection popover menu open and focused
- the filter function should immediately be focused after clicking or typing `/` (typing letters will directly filter plugin list without further interaction)
- edge case: If the user is already focused on an empty text plugin when clicking the plus no new text plugin should be inserted
- full keyboard interaction should work here: arrows for navigation, esc for closing, enter for selecting plugin, etc.

**Comment by elbotho** [comment]
[editor-icons-svg.zip](https://github.com/serlo/frontend/files/11333570/editor-icons-svg.zip)

**Comment by hejtful** [comment]
@elbotho What do we do about the arrow of the overlay? Do we remove it completely, or maybe adjust its color?
<img width="426" alt="Screenshot 2023-05-02 at 16 55 04" src="https://user-images.githubusercontent.com/13198821/235704914-ba80e8a9-ee9c-4d7d-8646-db016f7f0324.png">

**Comment by hejtful** [comment]
@elbotho Another question, sorry. Do we still want to have highlighting for filtered suggestions? And if so, do we have the design for that somewhere already?
<img width="402" alt="Screenshot 2023-05-02 at 17 07 52" src="https://user-images.githubusercontent.com/13198821/235707547-23822884-09e0-4b6b-a1b8-39f3e917765e.png">

**Comment by elbotho** [comment]
Hmm. Thanks for the question. Let's keep it simple for now: No arrow and no highlighting.

**Comment by elbotho** [comment]
Here's a fallback icon:
![Fallback Plugin Icon](https://user-images.githubusercontent.com/1258870/235885180-0ad8f4f5-9efe-4783-9fbc-534da114a349.svg)
