### ISSUE TITLE
No friendly message anymore when try to registering with invalid username

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2367]
![image](https://user-images.githubusercontent.com/45924645/234968677-89a152a7-57b7-4201-9fe4-d213c1047ea2.png)
Note: Umlaute are not allowed from legacy until now.

Before that we had a better error message like "Your username may only contain letters, digits, underscores (_) and hyphens (-). Please use a different one." in the English instance. But we are getting this error message in English also in de.serlo.org. See legacy for [English](https://github.com/serlo/serlo.org-legacy/blob/main/packages/public/server/src/lang/en_US.UTF-8/LC_MESSAGES/default.po#L740) and [German](https://github.com/serlo/serlo.org-legacy/blob/main/packages/public/server/src/lang/de_DE.UTF-8/LC_MESSAGES/default.po#L741) messages.

This is the [place](https://github.com/serlo/frontend/blob/248244886046594a844e8e1ee122d1dda3fe542e/src/components/auth/message.tsx#L29) where it should be working.

Chorme 112, but it should be unrelated to browser.

**Comment by Entkenntnis** [comment]
@CodingDive Can you take a look at this?
