### ISSUE TITLE
Investigate possible memory leak

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#2369]
https://trello.com/c/Z36akMeR/125-bug-performance-problems-editor

**Comment by Entkenntnis** [comment]
I quick profile in chromium shows no obvious problems: there are many allocations, but GC is able to keep usage low.

![grafik](https://user-images.githubusercontent.com/13507950/235681663-58e077b9-aba5-4f89-b00b-6c31d12115b9.png)

it's notable that the editor is quite allocation-heavy though: usage grows to ~80 - 100MB regularly and needs gc-collects to shrink again

**Comment by hejtful** [comment]
When inserting an image plugin, the following error appears. Could be a memory leak, worth investigating and fixing

<img width="1038" alt="Screenshot 2023-05-08 at 13 41 37" src="https://user-images.githubusercontent.com/13198821/236814909-b97802e2-d25f-4e7b-9ee5-f9af0017d342.png">

Edit: Fixed by https://github.com/serlo/frontend/pull/2399

**Comment by Entkenntnis** [comment]
closed in trello
