### ISSUE TITLE
differentiate learning content from sub-folders in taxonomy

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#237]
For user orientation it might help to differentiate how
a) learning content 
b) sub-folders 
are designed within the taxonomy, so that user can tell them appart more easily.

Unfortunately I have no suggestion, how to do that..

**Comment by Entkenntnis** [comment]
@simonkoehl Is this still relevant in the current version of the frontend? We now have explicit labels for every content type, e.g "Artikel" vs "Bereich".
