### ISSUE TITLE
Features for authenticated users (overview)

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#238]
Here is an overview of additional features that are necessary to support authenticated users in the frontend:

- Authentification itself can be handled by the legacy system, but the frontend needs to know which permissions it has, so it can show/hide the appropriate menu entries.

- The header menu needs a additional notification icon, profil entry and "anmelden" should turn to "abmelden": (and change link to https://de.serlo.org/auth/logout)

![grafik](https://user-images.githubusercontent.com/13507950/82206551-bbeed100-9908-11ea-9be2-4eadd7e08faa.png)

- Articles, Pages and Taxonomies need additional tools, like "Element kopieren", "Lehrplan zuordnen", etc... (pagewise):

![grafik](https://user-images.githubusercontent.com/13507950/82206534-b4c7c300-9908-11ea-8fb0-23450e4ea86d.png)

- In addition, every exercise and solution need tools to access it ("Bearbeiten", "Papierkorb verschieben", ...):

![grafik](https://user-images.githubusercontent.com/13507950/82206492-9f529900-9908-11ea-959d-2a90e51219b2.png)

That's it so far. All backend pages can be served by the legacy system for now.

**Comment by elbotho** [comment]
What about the notifications?

**Comment by Entkenntnis** [comment]
@inyono Do you have some ideas how we would handle this? Or can you estimate how much effort it would be to support these two features?

**Comment by inyono** [comment]
Basically the same approach for all user-specific features:
- Generate a OAuth Token via Hydra (Anna and I can implement the basic workflow and someone else can make it pretty)
- Include the token when talking to the API, add specific queries / mutations (eg notifications, createRevision, ...). We need a prioritized list of desires features that we can implement one after another

**Comment by Entkenntnis** [comment]
The plan is to implement #289 and then #290
