### ISSUE TITLE
implement survey prototype

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2416]
result of todays design thinking process: we want to show a popup with a mini-survey question:

![grafik](https://github.com/serlo/frontend/assets/13507950/d0379002-cb76-4378-a8fc-a109cead2b75)

show condition:
- 20 seconds on page
- show only once within week on device

target day: tuesday (15. Mai 23)

**Comment by elbotho** [comment]
Personally I'd prefer a less intrusive option.
I know it does not happens max. one a week but waiting 20s basically makes sure we interrupt and block the learners.

Maybe a popover sliding up and using the column next to the content on larger screens?

**Comment by Entkenntnis** [comment]
best option to discuss this is in the feature-team channel on slack, as we have decided it together in the team.
