### ISSUE TITLE
react-lazyload not working in iframe

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#2436]
# Steps to reproduce

Store a HTML file with the following content

```html
<!DOCTYPE html>
<html>
  <head>
    <title>IFrame Test</title>
  </head>
  <body>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.2/iframeResizer.min.js"
      integrity="sha512-dnvR4Aebv5bAtJxDunq3eE8puKAJrY9GBJYl9GC6lTOEC76s1dbDfJFcL9GyzpaDW4vlI/UjR8sKbc1j6Ynx6w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <iframe
      src="https://de.serlo.org/1857?contentOnly"
      width="500"
      height="800"
    ></iframe>

    <script>
      iFrameResize({ log: true }, "iframe");
    </script>
  </body>
</html>
```

## Result

Some formulas are not rendered:

![2023-05-23-135602_581x871_scrot](https://github.com/serlo/backlog/assets/1327215/b359fc2e-5516-4dcd-bc34-53d6a044b03f)

## Expected behavior

The formulas should be rendered:

![2023-05-23-135638_659x770_scrot](https://github.com/serlo/backlog/assets/1327215/fd21acb3-58f1-444f-8312-e401fc02d939)

Not that the formulas will be rendered when `iFrameResize()` is omitted.

# Possible reason

I noted that the not shown formulas are hidden when you look at them with the browser inspector:

![2023-05-23-135820_440x131_scrot](https://github.com/serlo/backlog/assets/1327215/e0fb116d-f800-4c26-90db-4da7f7eac364)

Since we have lazyloading with KaTeX we seem to have issues for KaTeX together with iFrameResize to see that the formula needs to be rendered...

**Comment by Entkenntnis** [comment]
the problem is related to react-lazyload (e.g. https://github.com/twobin/react-lazyload/issues/164)

Quickfix: disable lazyload if content is request via embedding. The performance implication is not that big (and not so bad as not showing the content at all)
