### ISSUE TITLE
missing polyfill for array.at

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2442]
not supported by next.js or polyfilled - causes page crash in older browsers, found in donation-banner

**Comment by elbotho** [comment]
Sorry about this one. I love to use the shiny new ways of doing things and usually they are just polyfilled…

I found another place where I used it in `comment-area-all-threads.tsx`:
`const latestCommentId = thread.comments.nodes.at(-1)?.id`

**Comment by elbotho** [comment]
([upstream PR with some discussion](https://github.com/vercel/next.js/pull/44436))

**Comment by elbotho** [comment]
@Entkenntnis what would you prefer? A polyfill ([1](https://www.npmjs.com/package/array.prototype.at),[2](https://github.com/tc39/proposal-relative-indexing-method#polyfill)) or rewriting?

**Comment by Entkenntnis** [comment]
you can add it to our polyfill-section in `_app` right now - it's only a matter of time that we can start using this.

**Comment by Entkenntnis** [comment]
this looks fine: https://github.com/tc39/proposal-relative-indexing-method#polyfill
