### ISSUE TITLE
Code is not displaying, Informatik somewhat unusable

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#245]
Subject Informatik uses code-blocks from the old editor, e.g.
https://de.serlo.org/informatik/algorithmen/robot-karol/wiederholungen

Currently those are not displayed in the new design, which makes a lot of content currently unusable.
@yolo-bird do you know if and when those will be converted?

---

Also there is a course that uses inline-code, which is currently not supported in the new editor:
https://de.serlo.org/informatik/internet-dinge-circuitpython/anf%C3%A4ngerkurse/grundlagen-1/mu-starten
@yolo-bird who could rework this one?

**Comment by kathongi** [comment]
We are converting codes in the convo project one by one depending on the content type. At the moment we're only converting exercises and exercise groups. Following that, we will focus on articles and later courses. So it can take some time until we have converted all code boxes.

Today I converted https://de.serlo.org/73016 which contains code blocks. But even this code doesn't display correctly in the new design. Converting doesn't fix the problem I guess.

(Everytime we found inline code in the convo project, it was changed automatically to normal text. So we left it this way.)

**Comment by Entkenntnis** [comment]
Code blocks are indeed missing, I will add them soon

**Comment by elbotho** [comment]
@Entkenntnis tell me when I can support.

**Comment by Entkenntnis** [comment]
@elbotho Do you want to take over #254?

**Comment by elbotho** [comment]
jup! (and thanks for saving informatics :) )
