### ISSUE TITLE
edtr-io converter wraps ul in paragraph

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#249]
This happens on the page http://localhost:3000/jobs at "Praktikum für (Lehramt-) ..." and results in a react dom validation warning

**Comment by inyono** [comment]
This seems to be a Frontend-only issue, https://de.serlo.org/jobs works fine.

**Comment by Entkenntnis** [comment]
it can be reproduced on serlo.org:

![grafik](https://user-images.githubusercontent.com/13507950/82663718-83b10080-9c30-11ea-9b8c-3bb22662a3fb.png)

A list is wrapped in a paragraph, causing dom validation warning - but it's visually not noticable

**Comment by inyono** [comment]
I don't get a validation warning on https://de.serlo.org/jobs, also `p ul` gets no match.
