### ISSUE TITLE
implementation of equations plugin

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#250]
A new equation plugin arrived:

https://de.serlo.org/2327
https://de.serlo.org/2369
https://de.serlo.org/2589
https://de.serlo.org/7073

~~Will add the basic scaffolding for it (https://github.com/serlo/serlo.org/blob/master/packages/private/edtr-io/src/plugins/equations/renderer.tsx)~~ done

**Comment by Entkenntnis** [comment]
Ok, the basic implementation is done, previews:

https://frontend-git-equations-plugin.serlo.now.sh/2327
https://frontend-git-equations-plugin.serlo.now.sh/2369
https://frontend-git-equations-plugin.serlo.now.sh/2589
https://frontend-git-equations-plugin.serlo.now.sh/7073

2327:

![grafik](https://user-images.githubusercontent.com/13507950/82665446-1901c400-9c34-11ea-86b1-e161bf1f4f91.png)

2369:

![grafik](https://user-images.githubusercontent.com/13507950/82665486-2e76ee00-9c34-11ea-9714-6341662ec143.png)

@elbotho This is the current state of the plugin, do you want to take over #252?

**Comment by elbotho** [comment]
@Entkenntnis okay! Could you write 1-2 sentences what I should do here?

**Comment by Entkenntnis** [comment]
I would envision something like this (taken from KA):

![grafik](https://user-images.githubusercontent.com/13507950/82668969-d8f20f80-9c3a-11ea-96a3-77a8fe0480f5.png)

For the start, some more horizontal space is probably all we can do...

**Comment by Entkenntnis** [comment]
@yolo-bird @kathongi Do you have ideas or drafts how to improve the equations-plugin?

**Comment by yolo-bird** [comment]
@Entkenntnis We will have a session in the first week of june to discuss further improvements of the equations-plugin. Currently there is a poll in p_convo on slack for the exact date. So feel free to join if you are interested.
To avoid unnecessary work I think you should postpone further work until the session takes place.

**Comment by elbotho** [comment]
Okay I will only add some spacing for now.

**Comment by elbotho** [comment]
Looks okay for me.
@Entkenntnis can't reproduce the bugs in your screenshots (other ID's I guess)
