### ISSUE TITLE
save modal keeps text across entities

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2520]
https://trello.com/c/AHtWUAnj/183-saving-maintaining-latest-description

it might be enough to pass the id to the useEffect deps here:
https://github.com/serlo/frontend/blob/af0d9eb5b77af1c3d159b7d7bdc6ded13446b05d/src/serlo-editor-integration/components/save-modal.tsx#L71-L75

**Comment by Entkenntnis** [comment]
reproduction:

1. Login
2. visit https://de.serlo-staging.dev/mathe/26407/aufgaben-zum-graphischen-differenzieren
3. click "Aufgabe hinzufügen" > "Aufgabe"
4. Do minor edit
5. Open save modal and type something
6. Save and wait for entity history
7. Click "Zum Inhalt"
8. Click "Aufgaben zum graphischen Differenzieren" in the breadcrumbs
9. click "Aufgabe hinzufügen" > "Aufgabe" again
10. Do minor edit
11. Open save modal

expected: description is empty
actual: description of previous entity is visible

@elbotho we consistently use CSR, so the modal is not remounted all the time, even on entity pages. This is interesting and something I wouldn't expect.

**Comment by Entkenntnis** [comment]
I can't reproduce it on localhost (probably due to page refreshes)

I'll move this to backlog
