### ISSUE TITLE
Performance: Responsive Image sizes, webp support

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#253]
Imo we need at least 1-2 optimized "thumbnail"-sizes and webp support to have good performance.

My idea to make it as easy as possible for us is to use some combination of cloudflares [image resizing](https://developers.cloudflare.com/images/) and [Polish(image optimization)](https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images) to provide the images that we need and use the frontend to then do lazy loading, and the responsive logic/webp fallbacks.
I like the idea because it would need not changes to the editor / upload / api etc if I understand the flow correctly.

@inyono @Entkenntnis  how does that sound? any objections / improvements / better alternatives?

Update: Current Lighthouse report as motivation ;)
![image](https://user-images.githubusercontent.com/1258870/83240759-1fdf8800-a19a-11ea-8236-cf0e4e3f4165.png)

**Comment by inyono** [comment]
> Image Resizing is available today for Business and Enterprise Customers.
Not feasible right now, since Business is already at 200$/month/domain.

Probably need to handle that ourselves for now (e.g. API route that gets the original image and uploads original + some optimized variants)

**Comment by elbotho** [comment]
@inyono Thanks for checking, was not sure what tier we were on.

Then we could start with Polish for lossy and webp image optim. That would be a very good start and should be available to us:
https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images

**Comment by elbotho** [comment]
@inyono you are def. right about the timeline. 
That's why I was exploring things were I could do most of the work. I will investigate polish and check if we can have webp support with little work.

For sizes there are also options with the Google Cloud, that we could look into but a bit more involved so something for the future for sure. 

Starting points for that approach: [1](https://blog.albert-chen.com/resize-images-on-google-cloud-storage/) [2](https://gist.github.com/codediodeio/d4cdcfc16f02d369d6943471727c6062) [3](https://fireship.io/lessons/image-thumbnail-resizer-cloud-function/) [4](https://medium.com/google-cloud/google-cloud-storage-downsizer-af0048591e40)

**Comment by elbotho** [comment]
Okay! Polish is indeed active. Nice.

@inyono Now if you find the time you could also flip the switch for webp support.
https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images#12345685
(by default only for browser that support it, no changes in the old or new frontend should be needed)
should be super easy only there is a warning I don't fully understand:
>To ensure WebP is not served from cache to a browser lacking WebP support, disable WebP at your origin web server when using Polish.

**Comment by inyono** [comment]
@elbotho was already enabled. This is only active for `serlo.org` though, since this is the only domain we have on a Pro plan.

**Comment by elbotho** [comment]
@inyono thanks for checking.
Weird! The only pages where I could find webp images being served were static pages on serlo.org old frontend (landing page/donations page, just the partner logos) and the icons that are loaded via jquery in the profile MVP (e.g. [this](https://packages.serlo.org/serlo-org-static-assets@2/feature-prototypes/donation-profiles/reviewers.png))

One (weak) theory: The cache was never updated for basically all image since activating the support.
> Images in the cache must be purged or expired before seeing any changes in Polish settings.

Or something else is going on, no clue. Probably need investigation at a later stage.

**Comment by elbotho** [comment]
Okay found the problem:

> vary_header_present: The origin web server has sent a Vary header with a value other than accept-encoding. If the origin web server is attempting to support WebP, disable WebP at the origin web server and let Polish perform the WebP conversion.
([source](https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images#12345685))

**Comment by Entkenntnis** [comment]
Is there an update on this? Do I understand correctly that the aim is to let cloudflare convert images into webp?

**Comment by inyono** [comment]
Seconding this: what is the plan (since I'm apparently assigned ^^)?

**Comment by elbotho** [comment]
We should have WebP images already, but they don't get delivered. I'm pretty sure I found the problem ([see here](https://github.com/serlo/frontend/issues/253#issuecomment-632884343)) but I have now idea what that actually means for us :) @inyono maybe you can tell me if that is something we can change?

**Comment by elbotho** [comment]
@inyono will contact CF support, let's see.

**Comment by inyono** [comment]
Works now. I hope that deactivating CORS doesn't break stuff ^^'
