### ISSUE TITLE
Informatic community page does not load

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#255]
check:
https://de.serlo.org/informatik-community-neu-hier

No content visible:
![image](https://user-images.githubusercontent.com/1258870/82697402-27b69e00-9c69-11ea-919f-38c637829f7f.png)

**Comment by Entkenntnis** [comment]
@yolo-bird This page is splish-me. Can you open it in the editor once and convert it?

**Comment by yolo-bird** [comment]
Converted @elbotho

**Comment by elbotho** [comment]
Thank you both!
Nice, works now.
