### ISSUE TITLE
different vertical spacing between frontend/editor

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2565]
Editor:
<img width="266" alt="image" src="https://github.com/serlo/frontend/assets/1258870/3ca5d0c5-3e5d-48e7-a5c5-6472ac58bb31">
Frontend:
<img width="303" alt="image" src="https://github.com/serlo/frontend/assets/1258870/e15a15b0-d885-4e1f-a0e5-37215d09770a">

@Entkenntnis the difference is the `mb-block` on the `slate-container` and tbh I don't understand the `slate-container` thing fully so maybe we can discuss this quickly :) and then I can fix it since I work on styles and spacing atm anyway.

**Comment by Entkenntnis** [comment]
I added the `slate-container` stuff to handle new lines within slate (that use a different spacing then paragraphs). That's the reason we need to know when a slate blocks ends.

**Comment by elbotho** [comment]
ok, to make this fully consistent we would need a bigger refactoring.
leaving as is for now.
