### ISSUE TITLE
Update all dependencies https://github.com/serlo/frontend

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#2568]
- [x] https://github.com/serlo/frontend/pull/2583
- [x] https://github.com/serlo/frontend/pull/2607
- [ ] Update `prettier` when no pull requests are open to avoid lots of merge conflicts.
- [ ] Update `eslint` dependencies and fix new errors when running `yarn lint`

## Dependencies not updated
- `react-markdown` & `remark-gfm`: Markdown related. Markdown should disappear hopefully soon. 
- `styled-components`: Should be replaced fully by tailwind as we go. 
- `htmlparser2`: Used to handle legacy content. Hopefully not needed any more in the future.

**Comment by Entkenntnis** [comment]
@LarsTheGlidingSquirrel I have created two independent new issues for the remaining two tasks (#2628 #2629) - this way we can have separate conversations about it when we tackle them. I think overall we are in a good place now with our dependencies.
