### ISSUE TITLE
Plugin 'spoiler' cannot be collapsed

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#2590]

**Comment by elbotho** [comment]
in editor, frontend or edusharing rendering mode?

**Comment by LarsTheGlidingSquirrel** [comment]
> in editor, frontend or edusharing rendering mode?

Apparently only broken in editor. Or is this intended? 
https://de.serlo-staging.dev/entity/repository/add-revision/277232 <- does not work
https://de.serlo-staging.dev/community/277232/alle-plugins <- does work

**Comment by elbotho** [comment]
jup, that's expected. 
It's a compromise/quickfix but this was the easiest way to get an at least consistent ux immediately.

**Comment by LarsTheGlidingSquirrel** [comment]
Ah alright, thanks! I just remembered that this worked in the past. Nevermind, I'll close the issue.

**Comment by elbotho** [comment]
yeah, maybe it will again in the future :) 
Thanks.
