### ISSUE TITLE
upgrade graphql related dependencies

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2601]
some examples:

![grafik](https://github.com/serlo/frontend/assets/13507950/0058351d-fcf9-4693-b13e-d16d9a7701d2)

**Comment by LarsTheGlidingSquirrel** [comment]
Maybe `msw` is also connected to these.

**Comment by elbotho** [comment]
https://www.npmjs.com/package/msw only used in tests, but I can take it up in my PR
