### ISSUE TITLE
investigate empty solution revision

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2614]
https://de.serlo.org/entity/repository/compare/279880/279881
https://de.serlo.org/entity/repository/compare/279225/279750
https://de.serlo.org/entity/repository/compare/279753/279754
https://de.serlo.org/entity/repository/compare/279738/279739

solutions are shown as empty, even if there is actual content behind it. Investigate it.

**Comment by elbotho** [comment]
usual things: 
- caused by a refactoring I did 🙈
- related to separation of exercises and solutions
