### ISSUE TITLE
course broken

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#262]
Reported by Nish:

Not all pages of the course "Vektoren" https://de.serlo.org/43174 are loading.

More explizit, the pages:

Was ist ein Vektor? (1/4) (https://de.serlo.org/mathe/geometrie/analytische-geometrie/grundbegriffe-vektorrechnung/vektorbegriff/einf%C3%BChrung-vektorbegriff-(vektoren-ebene-)/vektor?-(1/4))
Was ist ein Vektor? (2/4) (https://de.serlo.org/mathe/geometrie/analytische-geometrie/grundbegriffe-vektorrechnung/vektorbegriff/einf%C3%BChrung-vektorbegriff-(vektoren-ebene-)/vektor?-(2/4))

are not loading and lead to a 404.

**Comment by elbotho** [comment]
There is a `?` in the url that is not escaped.
(potential security issue?)
`/vektor?-(1/4)` should be `vektor%3F-(1/4)`

Could that be a bug in the API @inyono ? 

Also the URLs are a mess anyway :)

**Comment by Entkenntnis** [comment]
@inyono Is it intended that an alias is allowed to contain question marks? If this is the case, I would look through the api fetcher and add proper escaping. (I hope, slashes are forbidden :eyes:  )

**Comment by inyono** [comment]
That's currently possible, yes. Seems like we don't handle that correctly in the API so far, we should probably url-encode the alias.

**Comment by inyono** [comment]
cc https://github.com/serlo/api.serlo.org/issues/19

**Comment by inyono** [comment]
Okay, just checked: `document.location` also reports the url-encoded path. Is it fine for you, if I expect the url-encoded alias as input & output the url-encoded alias, always?

**Comment by Entkenntnis** [comment]
This would be fine! (Just to clearify: this means the graphql request will expect the alias to be url-encoded and will only output the alias as url-encoded?)

**Comment by inyono** [comment]
Fixed, API can work both with url-encoded and non-url-encoded stuff, so this needs no changes to frontend at all :)
