### ISSUE TITLE
fix application error in staging

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2623]

**Comment by Entkenntnis** [comment]
fixed by staying on nextjs 13.4.9 (13.4.10 and 13.4.11 not working for us)

**Comment by elbotho** [comment]
@LarsTheGlidingSquirrel any idea why?

**Comment by Entkenntnis** [comment]
The usual "don't use software that are only released some weeks ago" I hope ... we will investigate further if this persists into the next minor upgrade. Right now it's not yet worth it to investigate further

**Comment by LarsTheGlidingSquirrel** [comment]
> @LarsTheGlidingSquirrel any idea why?

Not really. Only some more information when running the production build locally: 
TypeError involving `e.title` in `src/components/landing/subjects/subject-landing-topic-overview.tsx` line 115
