### ISSUE TITLE
Simplification of role management: How shall it be?

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#263]
what is the current state of the role management? Do we want to simplify it, especially in regard of implementation in the new frontend?

**Comment by elbotho** [comment]
Current roles.
https://de.serlo.org/107863

@yolo-bird any opinion from the redaktion?

**Comment by yolo-bird** [comment]
Already talked about this with @kulla half an hour ago. We want to simplify it, in the sense that we are going to reduce the number of roles and make them more modular. We will talk about it in the next meeting of u-begleitung in three weeks and then can come to you with more concrete ideas. Does this suit your plans?

**Comment by kulla** [comment]
@Entkenntnis @inyono An addition to the comment by @yolo-bird: The current idea for the new role system is

![roles](https://user-images.githubusercontent.com/1327215/82908418-3b634c80-9f68-11ea-95d9-921fb9d5a986.png)

This is only a first idea and it is probable that it changes in the next meeting by U Begleitung. However now we have an idea how the new role system might be. Note that the roles in the middle are independent of the other roles in the middle.

**Comment by Entkenntnis** [comment]
There is a draft for the new role management, but it needs to be implemented on the backend first. The frontend will stick with the current implementation of the role system and try to adapt to it as much as possible.
