### ISSUE TITLE
horizon maintainance

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#264]
The horizon is currently hard-coded, and some entries are missing. Should be complete it or are there other plans for the space below pages?

**Comment by kulla** [comment]
I have got the following feedback from the lama meeting: The horizon shall stay. It might be the case the place will be used differently (for example to make the community more visible in the project community upgrade). However, this will be discussed in the projects and is nothing we have to care about yet. Also the horizon can be hard coded in the frontend. A management tool is not necessary. Follow ups:

* https://github.com/serlo/serlo.org/issues/439
* #280
