### ISSUE TITLE
e2e testing (plugin-toolbar): Setting url of image plugin fails

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2646]
link: https://frontend-git-feat-plugin-toolbar-serlo.vercel.app/entity/create/Article/1337

![grafik](https://github.com/serlo/frontend/assets/13507950/1ca66bf4-81c3-4fff-a59f-3804def39120)

Typing any letter in this input field leads to unexpected behaviour: The plugin loses focus, I can't edit url anymore:

![grafik](https://github.com/serlo/frontend/assets/13507950/4c90a0f2-f6aa-4644-9fcc-4777325a80a6)

**Comment by elbotho** [comment]
nice one botho 🤦

**Comment by hejtful** [comment]
@elbotho Added a proposal PR, but if you have another idea, that's totally fine with me.
