### ISSUE TITLE
Open entity links in /discussions in new tab

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2658]
This should allow people to go back to the discussions page more easily.

**Comment by elbotho** [comment]
To be honest: I don't really support this change from my old-school webdesign perspective (and also from a ux perspective :)
Bit of context in https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by Entkenntnis** [comment]
unfortunately, the back-button is broken in this situation and you will loose your scroll position on /discussions.

It's always about tradeoffs :/

**Comment by Entkenntnis** [comment]
closing it for now as there are on-going discussions

**Comment by elbotho** [comment]
> unfortunately, the back-button is broken in this situation and you will loose your scroll position on /discussions.

I'm mean that's a good point. If we can't find a feasible fix for that I'm okay with a hack.

**Comment by Entkenntnis** [comment]
(will reopen if we decided on it within the feature team)
