### ISSUE TITLE
Don't remove license of exercises

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#266]
see https://github.com/serlo/frontend/blob/master/src/fetcher/createLicense.tsx#L1

This won't work since the exercise license might be different to the license of the solution. In fact, this is pretty much the only place where we won't have CC BY-SA for everything (e.g. exercise itself has a custom license because it's an exam exercise, solution is CC BY-SA because it was created by us).

**Comment by Entkenntnis** [comment]
Oh, this line has some context that is unfortunately not explained there: The default behaviour for injections is to render a license if present. Because exercises render license by themself, the fetcher exludes the license so that the page is not showing the license twice.

**Comment by inyono** [comment]
Okay, makes sense :)
