### ISSUE TITLE
breadcrumbs separators missing

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2660]
e.g. https://de.serlo.org/mathe/1555/zylinder

<img width="725" alt="image" src="https://github.com/serlo/frontend/assets/1258870/ccb0ed11-c5aa-44c1-95c9-0367f48d6180">

⁉️

**Comment by Entkenntnis** [comment]
caused by this deployment: https://github.com/serlo/frontend/pull/2587

(works in previous deployment)

**Comment by Entkenntnis** [comment]
very likey this commit: https://github.com/serlo/frontend/pull/2587/commits/3d5e582ad02092c9d92ccfd9ef5a41ab06713904#diff-eb3c5dd123eddf79a1c77f84b4a1a5e677189c3973c18f7aff5aaf662707e700

**Comment by elbotho** [comment]
thanks for investigating 🎉
