### ISSUE TITLE
editor: link suggestion arrow keys don't work any more

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2670]
<img width="488" alt="image" src="https://github.com/serlo/frontend/assets/1258870/b6f69991-e068-4c00-aa92-16fd52bfd1d1">

e.g. https://de.serlo-staging.dev/entity/repository/add-revision/1555 but also in production.

Up/down arrows don't do anything. Pretty sure this worked at some point.

**Comment by elbotho** [comment]
@CodingDive thanks for taking this on. Not sure it's caused by the hotkey changes or something else btw.

**Comment by CodingDive** [comment]
If I had to guess, I screwed it up :sweat_smile: Taking a look now
