### ISSUE TITLE
editor: activating Equations plugin breaks the editor

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#2691]
Doesn't happen on production or staging, but happens in local on `staging` branch, so it's probably related to React strict mode.

<img width="986" alt="Screenshot 2023-08-03 at 16 02 12" src="https://github.com/serlo/frontend/assets/13198821/37950c6d-2750-4f75-acc6-e9df7652af8c">

**Comment by elbotho** [comment]
one `?` does the trick :)

**Comment by hejtful** [comment]
@elbotho In [the page that Mikey shared](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development), it says that this is probably an indicator of having impure functions in our effects.

For me, the `?` quick fix is fine. But maybe @CodingDive would like to dig deeper into the potential impure function?

**Comment by CodingDive** [comment]
Refs in general are a little bit of an escape hatch from Reacts usual state management. I also ran into this but thought it was related to new local changes of mine 😁🤦 
I think the question mark solution is great. Maybe the ref is not yet attached, I'll open a PR for it quickly.
