### ISSUE TITLE
Running yarn dev and yarn build at the same results in errors

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2698]
The build process usually fails during SSG with an error like

```
- info Collecting page data ...PageNotFoundError: Cannot find module for page: /___design
    at getPagePath (/home/mikey/Documents/dev/frontend/node_modules/next/dist/server/require.js:145:15)
    at requirePage (/home/mikey/Documents/dev/frontend/node_modules/next/dist/server/require.js:150:22)
    at /home/mikey/Documents/dev/frontend/node_modules/next/dist/server/load-components.js:71:84
```

I don't know if it's worth fixing as it's not a big deal to stop the dev server before running the build.  :man_shrugging: 
That being said, usually I like to test things locally while the long build process is running and then subsequently, run the tests.

**Comment by Entkenntnis** [comment]
https://github.com/vercel/next.js/issues/37825#issuecomment-1295717517

Nothing actionable here unfortunately, running these things in parallel is not possible.
