### ISSUE TITLE
Page load leads to ory and api recompilation and full reload when running dev server

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2699]
Steps to reproduce 
1. Run `yarn dev` 
2. Visit an article like http://localhost:3000/entity/repository/add-revision/277232
3. Make changes to the source code
4. Observe fast refresh/hot module replacement in the browser
5. Trigger a new page load / refresh
6. Ory and parts of the API recompile, triggering multiple page reloads and a compilation cascade.

The terminal looks like this
```
- wait compiling...
- event compiled client and server successfully in 3.3s (3537 modules)

// trigger new page load here
- wait compiling /api/frontend/preview (client and server)...
- wait compiling /api/locale/[lang] (client and server)...
- wait compiling /api/.ory/[...paths] (client and server)...
- event compiled successfully in 1740 ms (1011 modules)
- wait compiling...
- event compiled client and server successfully in 3.1s (3431 modules)
- wait compiling /[...slug] (client and server)...
- event compiled client and server successfully in 3.5s (3538 modules)
```

One can see that after the api recompiles, the slug is next which causes 2 page reloads and everything in total takes more than 10 seconds. 

I have identified this as the main reason why the tests typically fail upon running them against the dev server. Some page reloads or visits cause ory and other parts of the API to recompile.

**Comment by Entkenntnis** [comment]
I wouldn't mind if you can improve the situation here and make it possible to run tests agains dev server (more reliably)

**Comment by elbotho** [comment]
not quite sure but this probably the same issue that slows down dev work in the editor quite a bit (especially when I'm just fine-tuning design stuff.

Any ideas on how to fix this?

**Comment by CodingDive** [comment]
> Any ideas on how to fix this?

I have done a little bit of googling and the best bet right now seems to be precompile the pages that you're going to visit. I have added a primitive fix for this https://github.com/serlo/frontend-e2e-tests/pull/60 here (first commit) but it would require us to hardcode the pages upfront. Therefore even when running a single test with .only, you end up precompiling multiple pages that your test may not even visit :upside_down_face: 
The second commit tries to do it dynamically and only compile the pages of the tests that are run, on the fly. This seems to work great with the `I.amOnPage` calls, but completely fails when clicking on a link to a page that has not yet been compiled. I'm trying to find a way to dynamically increase the timeout, when clicking a link that causes a page to be compiled, but it's not that trivial to know within the `I.click` actor what a link is, and what is not. I'd appreciate any pointers, as I'm a little bit stuck. Maybe trying to patch this in the tests is also a bad approach and just patches the symptoms and not the cause. I should also investigate the dev server of this repo and how the compilation can be prevented (especially when nothing has changed in the API).

> not quite sure but this probably the same issue that slows down dev work in the editor quite a bit (especially when I'm just fine-tuning design stuff.

Yes, I think this problem is exactly what you're describing, fast refresh doesn't do anything here. Next.js thinks the API or something has changed and recompiles, then performs a full reload and it takes at least 10-20 seconds after every small change in the editor. I'll continue to investigate this and hoping to stumble upon a magic setting :grinning:
