### ISSUE TITLE
Double click into the LaTeX editor closes the modal

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2700]
It's common to double click to highlight some text. However, when doing that within the Math editor, the modal is closed.

![double_click_in_LaTeX_closes_menu](https://github.com/serlo/frontend/assets/28842311/8a498564-d0e4-4fd0-ab1e-1102766029e9)

**Comment by elbotho** [comment]
Interesting. Double click works fine for me (mac/chrome) but triple click closes it… 🤷

ps: in firefox triple click also closes it but opens it up immediately again.
