### ISSUE TITLE
Plugin toolbar layout breaks within table + image plugin

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2709]
As usual, the nested plugins are always tricky to get right. The layout of the plugin toolbar breaks when having an image within a table.

![image](https://github.com/serlo/frontend/assets/28842311/424874c0-5456-4c84-9e32-4728da6a1a15)

**Comment by elbotho** [comment]
This only happens when the caption is focused. Interestingly the toolbar appears nicely on top of table otherwise.
(table > image > caption)

**Comment by CodingDive** [comment]
Cross linking https://github.com/serlo/backlog/issues/155 although I think it's not that related as this issue is about the plugin toolbar and the other one about the images themselves.
