### ISSUE TITLE
x-robots-tag: noindex

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#271]
Currently Vercel (I guess) sends out a `x-robots-tag: noindex` for the redesign, even on `serlo.org`
@Entkenntnis Is that on purpose? When should we change that?

**Comment by inyono** [comment]
That's not intended. Seems like `frontend.serlo.now.sh` is not considered as the production domain. I'm gonna add `frontend.serlo.org` as the production domain (which will not add the custom header)

**Comment by inyono** [comment]
Fixed

**Comment by elbotho** [comment]
Nice! 
@inyono You are awarded with a nice 💯SEO!
![image](https://user-images.githubusercontent.com/1258870/83244852-3852a100-a1a0-11ea-8128-9ad715ef4fb0.png)

**Comment by inyono** [comment]
cc https://github.com/serlo/serlo.org-cloudflare-worker/issues/22
