### ISSUE TITLE
Weird: wrong images get loaded

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#272]
In this table the colors are different from the same table in the old design:
https://de.serlo.org/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken#SerloFarben

**Comment by inyono** [comment]
Seems like SSR is okay, but something is wrong on the client side (or caching, who knows): If I make a hard reload, I notice that the correct colors are shown shortly and then change to the wrong colors.

**Comment by inyono** [comment]
Yep, deactivating JS has the same effect.

**Comment by Entkenntnis** [comment]
Interestingly, this does not happen when you open the page directly in the frontend.

correct: https://frontend.serlo.now.sh/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken#SerloFarben

![grafik](https://user-images.githubusercontent.com/13507950/83805376-0fef0900-a6b0-11ea-8b15-2186105d7155.png)

wrong (frontend enabled): https://de.serlo.org/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken#SerloFarben

![grafik](https://user-images.githubusercontent.com/13507950/83805419-28f7ba00-a6b0-11ea-8cc4-7a7a85146330.png)

That's quite weird ...

**Comment by inyono** [comment]
You need to check https://frontend.serlo.org/community/hilfe-bearbeitung/richtlinien-inhalten/bilder-grafiken#SerloFarben since that is the production domain (frontend.serlo.now.sh uses staging). But still the same behavior ^^

**Comment by elbotho** [comment]
I think it's curious that it's the only render function in `article-renderer.tsx` that explicitly sets the key:

``` tsx
export function renderTable({ attributes = {}, children = null }: any) {
  const { key, ...otherAttribs } = attributes
  return (
    <TableWrapper key={key}>
      <StyledTable>
        <tbody {...otherAttribs}>{children}</tbody>
      </StyledTable>
    </TableWrapper>
  )
}
```

@Entkenntnis  do you think this would make sense to test?
I don't see what attributes would need to go to tbody anyway.
(currently attributes only contains the key)
``` tsx 
export function renderTable({ attributes = {}, children = null }: any) {
  // const { key, ...otherAttribs } = attributes
  return (
    <TableWrapper {...attributes}>
      <StyledTable>
        <tbody>{children}</tbody>
      </StyledTable>
    </TableWrapper>
  )
}
```

**Comment by elbotho** [comment]
PR here: #272

**Comment by elbotho** [comment]
Okay, so strange. I'm out out of ideas.

**Comment by inyono** [comment]
Mh... for one thing: we don't let React handle stuff but rather do it ourselves (e.g. we create JSX nodes ourselves instead of rendering react components; also passing down keys ourselves). This looks like an anti-pattern to me...

**Comment by Entkenntnis** [comment]
I found a possible cause: Diffing the HTML obtained from frontend.serlo.org and de.serlo.org reveals that Cloudflare cleans up the HTML and especially removes all comments.

These comments are there to help react to hydrate the page (see https://github.com/facebook/react/issues/14725), because the comments are missing, the hydrating leads to dom mutations (which it shouldn't!) and a corrupt dom.

On the left is the cloudflare result, you can see the comments missing from the table:

![grafik](https://user-images.githubusercontent.com/13507950/84058184-269ba580-a9b9-11ea-9636-569127173196.png)

@inyono Do we have "minify html" activated? This could cause this issue.

**Comment by inyono** [comment]
Nice catch! This seems to be the problem, indeed. I deactivated the Minifier from Cloudflare and purged the cache for that page. Seems to work now.

**Comment by elbotho** [comment]
nice!
