### ISSUE TITLE
editor(text-plugin): pasting image url works, but leaves url string

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2743]
at least in https://github.com/serlo/frontend/pull/2742
<img width="491" alt="image" src="https://github.com/serlo/frontend/assets/1258870/2c093de8-e1d8-44a0-ac8c-88bb00071028">

**Comment by elbotho** [comment]
weird because it does not happen for videos

**Comment by LarsTheGlidingSquirrel** [comment]
Closed issue because this appears to be solved on staging after doing some testing. Also, I did not find any other issues with pasting images & videos.
