### ISSUE TITLE
Error while loading articles

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#277]
Trying to load articles on localhost results in this error message:

![grafik](https://user-images.githubusercontent.com/13507950/83725333-0cbd3400-a642-11ea-806a-6ff88bfe0a78.png)

It happens with any article, e.g.

http://localhost:3000/1627

**Comment by elbotho** [comment]
Linked to https://github.com/serlo/api.serlo.org/issues/17 
@inyono will take a look at it

**Comment by elbotho** [comment]
(but you can too obviously :) )

**Comment by inyono** [comment]
Was a problem with the cache in staging. Still: we should probably handle such errors more gracefully and don't fail completely.

**Comment by Entkenntnis** [comment]
the issue itself is resolved now
