### ISSUE TITLE
Multimedia plugin should respect width-setting

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#278]
Due to some history reasons, the multimedia is not respecting the width setting, but now this should be easy to add:

![grafik](https://user-images.githubusercontent.com/13507950/83725859-ee0b6d00-a642-11ea-9039-286f21321706.png)

This image should be 50% instead of the hard-coded 25%

**Comment by Entkenntnis** [comment]
Fixed in #281 

@inyono Is it possible, that the content of serlo-staging.dev differs from our live data? Because I am getting different content on localhost for `/jobs`

**Comment by inyono** [comment]
Yes, see serlo-staging.dev. Data is reset nightly to an anonymizes version of the production data. I probably need to also reset the cache nightly, then (which isn’t done yet)

**Comment by inyono** [comment]
cc https://github.com/serlo/api.serlo.org/issues/18
