### ISSUE TITLE
editor: focus refactor umbrella

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2799]
wip. 

list of focus experiments PRs:

- https://github.com/serlo/frontend/pull/2786
- https://github.com/serlo/frontend/pull/2785
- https://github.com/serlo/frontend/pull/2780
- https://github.com/serlo/frontend/pull/2693
- kullas draft: https://github.com/serlo/frontend/pull/2837
- latest approach: https://github.com/serlo/frontend/issues/2877

focus issues:
- https://github.com/serlo/backlog/issues/111
- https://github.com/serlo/frontend/issues/2895
- https://github.com/serlo/frontend/issues/2916
- https://github.com/serlo/backlog/issues/257
- https://github.com/serlo/frontend/issues/2887

**Comment by Entkenntnis** [comment]
#2877 as latest approach of fixing the current store.

**Comment by elbotho** [comment]
closing the umbrella. It's still raining but we are soaked anyway ☔️
