### ISSUE TITLE
Implement wizard of automated exercise generation 🤖

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2873]
https://serlo.slack.com/archives/C04QBBT4DQC/p1694530709872979?thread_ts=1694530709.872979&cid=C04QBBT4DQC

**Comment by Entkenntnis** [comment]
branch: https://github.com/serlo/frontend/tree/feat/generate-exercise-from-openai-api-output

@CodingDive is this the correct branch? I'm not seeing your changes in it.

**Comment by CodingDive** [comment]
That was the old branch. I just pushed [feat/ai-exercise-generation](https://github.com/serlo/frontend/compare/feat/ai-exercise-generation) and am merging staging into it, integrating the new changes
