### ISSUE TITLE
Confirming column removal removes serlo-table plugin focus

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#2887]
Steps to reproduce:
1. Focus a serlo-table plugin
2. Add a column in order to see the "remove column" button
3. Press the "remove column" button
4. A pop-up appears, where you need to confirm the removal action
5. Confirm the action
6. Plugin has lost focus

Since undo/redo works for the serlo-table plugin, do we really need the native browser confirmation pop-up for this case? Just removing the confirmation step seems like an easy solution here. @elbotho

**Comment by elbotho** [comment]
> Since undo/redo works for the serlo-table plugin, do we really need the native browser confirmation pop-up for this case? Just removing the confirmation step seems like an easy solution here. @elbotho

I agree with you but I'm pretty sure I added it because people asked for it :) 
Would it actually solve the focus problem? It could also be because the focused cell is not available any more?

**Comment by hejtful** [comment]
> It could also be because the focused cell is not available any more?

The focus is lost even if we cancel the prompt.
