### ISSUE TITLE
First focus after loading

### ISSUE THREAD

**Issue by anbestCL** [serlo/frontend#2895]
Currently, after loading a page nothing is focused. 

Preferred behaviour:
* If the title field is empty, the first focus should go to the title field
* Otherwise the first text plugin should be focused

(Moved from edtr-io: https://github.com/edtr-io/edtr-io/issues/407)

**Comment by elbotho** [comment]
> Problem 1: when creating a new article, the first position of the cursor in the article is not in the title, but in the field below (normally in the caption of the picture in that field) that. This can lead to leaving the title field blank and, after saving, getting an error message.
> 
> Problem 2: when opening the editing window of some contents, the first position of the cursor is in the caption of the last image. This happens for example [here](https://de.serlo-staging.dev/entity/repository/add-revision/19869) and [here](https://de.serlo-staging.dev/entity/repository/add-revision/133457).
> 
> Request: define a better position for the cursor when opening contents
> 
> Source: old backlog document
