### ISSUE TITLE
client side routing 

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2902]
steps to reproduce:

- visit https://de.serlo.org/mathe/26394/aufgaben-zu-funktionen-und-relationen
- click 3 > Überarbeiten
- go back
- click ~5~ 4 > Überarbeiten

expected: exercise 4 is loaded in editor

actual: exercise 3 is loaded in editor

hard reload (F5) as workaround.

**Comment by elbotho** [comment]
could not reproduce just now.
how do you "go back"? 
did you test in FF?

**Comment by Entkenntnis** [comment]
Investigation result: Because of #2903, the deserialization fails. The editor will fallback to the previous valid state, which was the last edited exercise. In addition, the editor will never attempt to deserialize new states, so no matter which exercise you open, you will see the last edited exercise until you hard refresh the page.

@elbotho we could maybe add some safe-guards, but imho it's ok to wait for #2903 to fix this.

**Comment by elbotho** [comment]
(just tested in staging and this is indeed fixed by the migration)

**Comment by Entkenntnis** [comment]
fixed
