### ISSUE TITLE
can't open editor for exercise

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2903]
this page is not loading: https://de.serlo.org/entity/repository/add-revision/6521

**Comment by elbotho** [comment]
`{uuid(id:6521){... on ExerciseGroup{currentRevision{}}}}`
``` json
{
  "data": {
    "uuid": {
      "currentRevision": {
        "content": "{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Begründe, ob es sich bei der gegebenen Relation \"},{\"type\":\"math\",\"src\":\"f\",\"inline\":true,\"children\":[{\"text\":\"\"}]},{\"text\":\" um eine Funktion handelt und beantworte die Zusatzfragen.\"}]}]}]}"
      }
    }
  }
}
```

**Comment by LarsTheGlidingSquirrel** [comment]
I can have a look into this in the afternoon.

**Comment by LarsTheGlidingSquirrel** [comment]
Trying to deserialize this fails: 

```typescript
{
  "id": "668d9de9-d8db-4abf-8d35-41e0cf1baca0",
  "plugin": "equations",
  "state": {
    "steps": [
      {
        "left": "f",
        "sign": "equals",
        "right": "\\left\\{\\left(x\\vert y\\right)\\;\\vert\\;x=y^3\\;;\\;{\\mathit W}_\\mathit f=\\left[-2;2\\right]\\right\\}",
        "transform": "",
        "explanation": {
          "plugin": "text",
          "state": [
            {
              "type": "p",
              "children": [
                {}
              ]
            }
          ]
        }
      }
    ]
  }
}
```

Notable differences to what a working equation plugin looks like: 
- `state.firstExplanation` is missing
- `state.transformationTarget: "equation"` is missing

Adding these two manually resolves the error. 

@elbotho How would you go about fixing this? Database migration? Migrate on the client after fetching the content? Make the deserialization work somehow?

**Comment by elbotho** [comment]
@LarsTheGlidingSquirrel thanks for investigating 👍 
I think/hope this will be resolved when https://github.com/serlo/db-migrations/pull/139/files runs.
Sounds like:
- addFirstExplanationToEquation
- addTransformationTargetToEquation
might do the trick :D

**Comment by Entkenntnis** [comment]
@elbotho Do you know who is working on this or when this migration will run again? I seem not be able to find a trello-card for it.

**Comment by elbotho** [comment]
@Entkenntnis it's part of this one: https://trello.com/c/A74gO1Hu/309-letzte-table-und-layout-plugins-migrieren

**Comment by Entkenntnis** [comment]
👍  i've added a note to the card

**Comment by elbotho** [comment]
(just tested in staging and this is indeed fixed by the migration)

**Comment by Entkenntnis** [comment]
fixed
