### ISSUE TITLE
improvements such as focus, placeholder and default answers in input-exercise plugin

### ISSUE THREAD

**Issue by anbestCL** [serlo/frontend#2916]
Improvements for the input-exercise:

<img width="780" alt="grafik" src="https://github.com/serlo/backlog/assets/43368821/b62c7104-a8cb-4fdf-8aec-c4a6f5cbb4c8">

- [x] Put cursor in answer field instead of feedback field upon adding of new answer
- [x] First answer should/could be correct per default
- [x] #2976

(Moved from edtr-io: https://github.com/edtr-io/edtr-io/issues/293)

**Comment by Entkenntnis** [comment]
last remaining task moved to new issue
