### ISSUE TITLE
broken urls

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#292]
escaped urls break everything for me, e.g.:
https://de.serlo.org/mathe/zahlen-gr%25C3%25B6%25C3%259Fen

**Comment by inyono** [comment]
Were did you get that url?

**Comment by inyono** [comment]
nvm, found one... Gonna check that out

**Comment by inyono** [comment]
Reverted the API changes in production for now, going to look into that tomorrow in detail...

**Comment by Entkenntnis** [comment]
So we are back at the original issue, that these two pages are not loading:

Was ist ein Vektor? (1/4) (https://de.serlo.org/mathe/geometrie/analytische-geometrie/grundbegriffe-vektorrechnung/vektorbegriff/einf%C3%BChrung-vektorbegriff-(vektoren-ebene-)/vektor?-(1/4))
Was ist ein Vektor? (2/4) (https://de.serlo.org/mathe/geometrie/analytische-geometrie/grundbegriffe-vektorrechnung/vektorbegriff/einf%C3%BChrung-vektorbegriff-(vektoren-ebene-)/vektor?-(2/4))

**Comment by inyono** [comment]
Yeah, I'm aware, it's on my list 👍

**Comment by Entkenntnis** [comment]
I have fixed some bugs in the frontend regarding url-encoding, now the frontend is expecting the API to return alias as url-encoded (and is not doing any additional encoding) (details: https://github.com/serlo/frontend/pull/286/commits/f54209f27e542eaa3521fdee7f406b45b5a9a9c6)

Maybe we can test this on staging again?

**Comment by inyono** [comment]
Wait, so the URL-encoding was actually fine from API side (i.e. it works with staging now)? ^^'

**Comment by Entkenntnis** [comment]
Jup 😁

**Comment by inyono** [comment]
Oh nice. Then I'll go over that in detail (we might have the same problem at Cloudflare Worker level). When everything works, I push that to production again :)

**Comment by Entkenntnis** [comment]
One thing I noticed: Some urls in the secondary menu that are not using ID have a trailing 'undefined':

![grafik](https://user-images.githubusercontent.com/13507950/84991638-1917b580-b147-11ea-8da0-f3a65fed2688.png)

Found here: https://frontend-git-menu-routing.serlo.vercel.app/community/neue-f%C3%A4cher-themen

**Comment by inyono** [comment]
Seems to work fine, production API is now at latest version, too :)
