### ISSUE TITLE
highlight renderer: server client mismatch warning

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2951]
Warning: Prop `className` did not match. Server: "token control-flow" Client: "token" e.g. on http://localhost:3000/277232

**Comment by Entkenntnis** [comment]
can't reproduce locally on dev server, ff and chromium - any more hints?

**Comment by elbotho** [comment]
Hmm interesting. No more hints unfortunately:
I start up dev server (staging branch) and visit http://localhost:3000/277232 with FF or Chrome and get this error in the console. 
![image](https://github.com/serlo/frontend/assets/1258870/5e53513d-20cf-4da2-8fb0-a66bb870dcab)

**Comment by Entkenntnis** [comment]
still not reproducable, i tried:

- remove node_modules, new install
- remove .next
- create build and start it

I'm using windows (but this shouldn't make the difference) - maybe you can remove your .next and/or reinstall modules to see if error persist?

**Comment by elbotho** [comment]
thanks for investigating.
I could not get rid of the error in this setup so far, but could also not reproduce it in a completely independent install.
confusing… closing.
