### ISSUE TITLE
JsonLd error in safari

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2955]
This error only seems to happen in safari and mostly spams sentry a lot.
I did some digging and found out it's caused by the `<JsonLd />` component.

[**Sentry**](https://serlo.sentry.io/issues/1706510233/?project=5206333&query=&referrer=project-issue-stream)

**Error**
```
TypeError: r["@context"].toLowerCase is not a function. (In 'r["@context"].toLowerCase()', 'r["@context"].toLowerCase' is undefined)
```

**Comment by Entkenntnis** [comment]
@elbotho https://github.com/ymmooot/nuxt-jsonld/issues/1280

**Comment by elbotho** [comment]
It's not the serializing.
Safari throws this error because of this syntax (providing array for syntax).
``` js
'@context': [
    'https://w3id.org/kim/lrmi-profile/draft/context.jsonld',
    {
      '@language': 'de',
      '@vocab': 'http://schema.org/',
      type: '@type',
      id: '@id',
    },
],
```

 It's valid and we need it. It's probably best to prevent sentry from triggering here.

**Comment by elbotho** [comment]
Ignoring sentry works for now. Issue seems to be with Safari and I could not find an easy solution. Closing for now.

**Comment by kulla** [comment]
This would be also fine BTW:

```
'@context': [
    {
      '@language': 'de',
      '@vocab': 'http://schema.org/',
      type: '@type',
      id: '@id',
    },
],
```

**Comment by elbotho** [comment]
thanks @kulla, from my testing everything but a single string throws an error unfortunately.
