### ISSUE TITLE
Custom links in horizon data

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#296]
In the horizon we use links like: 
https://de.serlo.org/horizon/34/out

@inyono This is so we can easily track clicks here, I guess? 
Can I use them in the frontend as well?

**Comment by inyono** [comment]
Nope, since we indent do remove the horizon backend. Since we need no tracking anyway, you can just use the URL that the out link redirects to.

**Comment by elbotho** [comment]
okay! Thanks.
Also: Do they use some kind of probability? If yes, could you kindly point me to that values?
