### ISSUE TITLE
sorting entries does not work in dev mode

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2986]
e.g. http://localhost:3000/taxonomy/term/sort/entities/234582
dragging does not work when running with `yarn dev`, `yarn build / yarn start` works fine.

**error message:**
```
react-beautiful-dnd
Unable to find draggable with id: 234893
👷‍ This is a development only message. It will be removed in production builds.
```

**Comment by Entkenntnis** [comment]
I can reproduce.

Known upstream issue, this thread has some more details and potential fixes: https://github.com/atlassian/react-beautiful-dnd/issues/2407

(no, we are not going to disable strict mode 😓)

**Comment by elbotho** [comment]
Thank you for investgating!
not super important anyway. 
https://github.com/atlassian/react-beautiful-dnd/issues/2407#issuecomment-1648339464 might be worth a try.
We should at least write a comment :)

**Comment by elbotho** [comment]
ended up using `@hello-pangea/dnd` (fork)
