### ISSUE TITLE
page header

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3]

**Comment by kulla** [comment]
## Feedback of Botho

### Mobile

- [ ] Slogan, Logo, Infobox und Content auf eine Linie:
![image1](https://user-images.githubusercontent.com/1327215/77263886-9000f780-6c99-11ea-8009-7b01a319cee3.png)
* Sucheinstellungsicon:
     - [ ] Hellblau statt grau
     - [ ] klein bisschen mehr abstand nach links
     - [ ] bzw: Wie wichtig sind die Einstellungen, wäre es auch denkbar, dass die erst angezeigt werden, wenn die Suche aktiv ist?
- [ ] active/focus lieber über die farbe des icons (oder auch mit einem Kreis drum rum): 
![image2](https://user-images.githubusercontent.com/1327215/77264096-f6861580-6c99-11ea-88f8-f840e7ab904c.png)
- [ ] schaut ein bisschen gestaucht aus (weniger breit als es sein sollte) kann das sein? 
![image3](https://user-images.githubusercontent.com/1327215/77264128-0867b880-6c9a-11ea-885d-d921b0af8424.png)
* Menü:
     - [ ]  Linktexte sind nicht vertikal mittig.
     - [ ] Community, Fächer und Spendenicons könnten bisschen kleiner
     - [ ] Nach dem einklappen sollte der Bereich nicht mehr fokusiert (dunkler hintergrund) sein.
![image4](https://user-images.githubusercontent.com/1327215/77264208-2df4c200-6c9a-11ea-85d3-78f24a738e8b.png)
* Submenü:
     - [ ] Weißer Hintergrund, damit abgesetzt vom restlichen Menü
     - [ ] nach dem letzten Submenü-Punkt eine leerzeile mit halber höhe.
![image5](https://user-images.githubusercontent.com/1327215/77264245-41a02880-6c9a-11ea-9037-f73b22aa8c33.png)

### Desktop

- [ ] Wenn genug Platz: Slogan einrücken, dass “Serlo” und “Die …” auf der gleichen Linie beginnen. 
![image6](https://user-images.githubusercontent.com/1327215/77264293-57ade900-6c9a-11ea-905a-392e152369e9.png)
- [ ] Ausklappmenüs bei Hover schon öffnen.
* Submenü (damit man nicht ins leere klicken kann):
     - [ ] `li` ohne margin-bottom     
     - [ ] `a` auf display block und mit mehr padding oben und unten
* Menülinks:
     - [ ] selbe idee, möglichst große clicktargets, am besten so, dass man nicht über die links klicken kann.
     - [ ] (also weniger padding-top: aufm header und mehr padding-top auf den link)

**Comment by Entkenntnis** [comment]
Sucheinstellungen haben low prio, sind momentan mehr nur eine Idee

**Comment by Entkenntnis** [comment]
Button-Hover für Menü einheitlich zu anderen Buttons

**Comment by kulla** [comment]
> Sucheinstellungen haben low prio, sind momentan mehr nur eine Idee

Heißt, dass die Sucheinstellungen erst einmal raus können?

**Comment by kulla** [comment]
> Button-Hover für Menü einheitlich zu anderen Buttons

Was meinst du damit?

**Comment by elbotho** [comment]
@kulla fyi: in e2231f5800257ce5e0f222346bc1c911e17e896f I changed the default paddings.
you can now use the same paddings via the csshelper `${makeResponsivePadding}` or get the value directly via `props.theme.defaults.sideSpacingMobile` or `props.theme.defaults.sideSpacingLg`

PR will be merged soonish.

**Comment by Entkenntnis** [comment]
@kulla Sucheinstellungen kannst du wieder raustun, bei dem Hover geht es darum, auch beim Menü ein Hover mit rundem Kasten wie bei den Button zu implementieren
