### ISSUE TITLE
Performance suffers in large articles

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#3039]
### Problem:
As @elbotho reported, editing large articles is noticeably slow, and makes the editing experience pretty bad. Example big article: https://de.serlo.org/entity/repository/add-revision/287109

### Investigation so far:
**React Profiler shows no issues** - there are no super long renders, or unnecessary renders in general.

**Chrome DevTools Performance** tab shows that "**Scripting**" takes a few seconds, when the user types in a text plugin, while "Rendering" takes only several milliseconds. Following this clue, we can notice that certain event listeners increase the scripting time drastically, while the operation that these event listeners have in common seems to be our own `getChildTree` function (which is used as a helper function for `selectChildTree` and other Redux selectors).

### Possible solutions:
1. Moving the selectors inside conditions, even if it means more code. This way, the selectors would potentially only be called when they are strictly necessary.
2. Instead of calculating the "child tree" when we need to `get` it, we can think of calculating it when we `set` it. Especially if we omit the content, like setting the children to `null` when children are not other plugins.
3. _Probably some other solutions_

**Comment by elbotho** [comment]
Closing this with the quickfix in https://github.com/serlo/frontend/pull/3038.
@hejtful or should I move it to the backlog for further investigations/improvements?
