### ISSUE TITLE
Exercise can't be open in editor

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3062]
url: https://de.serlo.org/entity/repository/add-revision/114126

**Comment by elbotho** [comment]
somehow the solution state seems to be corrupt.
https://github.com/serlo/frontend/commit/acb23cbe99b7a78d5dba63bf68c74f05b09a7127 at least makes the content load, 

but I'm not sure how this state could appear:
![image](https://github.com/serlo/frontend/assets/1258870/13f1a01b-7223-43f8-9104-a7caa2f1c12b)
