### ISSUE TITLE
geogebra regression: compat for full URL is missing

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3066]
This fix is missing and should be readded. (https://de.serlo.org/chancenwerk/279769/geogebra-applets, first applet is not loading)

![grafik](https://github.com/serlo/frontend/assets/13507950/5a7426e5-990c-4a7b-8af5-b15c49aa8dba)

expected behaviour: If you use `https://www.geogebra.org/m/j87ktrpc` as URL, the applet should still load.

**Comment by Entkenntnis** [comment]
@elbotho Ha, just found that you have already prepared a `parseId` function but haven't called in in src\serlo-editor\plugins\geogebra\renderer.tsx

**Comment by Entkenntnis** [comment]
![grafik](https://github.com/serlo/frontend/assets/13507950/25a4c72f-b99b-4f5a-bc01-8e68954c268e)

ok, you are calling it, but this should be `url` instead of `id`?

**Comment by Entkenntnis** [comment]
last update: ok, this is the root cause: 

![grafik](https://github.com/serlo/frontend/assets/13507950/757212f1-a5d0-493b-940d-d0345908ed49)

**Comment by Entkenntnis** [comment]
fixed in 2a716297895b5d59d73cb20ff7896d7fbd0c7de1

**Comment by elbotho** [comment]
Nice, thank you for the quick fix 🎉
