### ISSUE TITLE
add client-side-navigation to menus

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#308]
Client-side-navigation is not yet implemented for:

- main menu
- secondary menu
- course menu
- footer

Not all links there should be routed client-side, though (like legacy-links ...)

**Comment by elbotho** [comment]
maybe not exclusive, but here are some of the urls that we should not be using client side navigation for:
https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/static-pages/config.ts
https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/frontend-proxy.ts
https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/index.ts

**Comment by inyono** [comment]
Possible approaches:
- We wrap the API call in the Cloudflare Worker and possibly pass the info that this should be handled via legacy system.
- We expose the logic in the Cloudflare Worker as an npm package and import that in the frontend (problem: need to keep that package up-to-date)
- Duplicate the logic from Cloudflare Worker (meh)

I'd prefer the first approach to be honest. This way, we'd only need to redeploy the Cloudflare Worker when the config changes and we can wrap the client-side logic once on front-end side.

**Comment by elbotho** [comment]
@Entkenntnis and @kulla what do you think?

**Comment by Entkenntnis** [comment]
We can split this issue into two parts: static and dynamic links. For static links, we can set manually set the navigation state and this would work for menu and footer (a first attempt here: #317)

For dynamic links (secondary nav, course nav), another possibility would be to use the same logic as the pretty link part and only add client-side-navigation to the links that can be prettyfied.

**Comment by Entkenntnis** [comment]
#317 and #319 add client-side-navigation to header, footer and courses.

Only remaining menu is secondary navigation, this has a separate issue now: #320

**Comment by kulla** [comment]
> Possible approaches:
> 
>     * We wrap the API call in the Cloudflare Worker and possibly pass the info that this should be handled via legacy system.
> 
>     * We expose the logic in the Cloudflare Worker as an npm package and import that in the frontend (problem: need to keep that package up-to-date)
> 
>     * Duplicate the logic from Cloudflare Worker (meh)
> 
> 
> I'd prefer the first approach to be honest. This way, we'd only need to redeploy the Cloudflare Worker when the config changes and we can wrap the client-side logic once on front-end side.

@inyono How would the first solution look like? Can we talk about this next monday?

**Comment by inyono** [comment]
@kulla. Actually, I consider this a good learning opportunity since you are already quite familiar with the Cloudflare Worker: I'd prefer it if you try to sketch a solution / alternative for the first approach :)

**Comment by inyono** [comment]
Reopened since I'd still like to keep Cloudflare Worker & Frontend in sync. Or do you want a seperate issue for that @Entkenntnis?

**Comment by Entkenntnis** [comment]
@inyono A new issue would be great! This issue is somewhat overloaded ...

**Comment by inyono** [comment]
Okay, discussion continued in #328
