### ISSUE TITLE
Show warning when event of a notification is null

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#3086]
See https://trello.com/c/zSfG9Twd/372-null-events-shall-not-break-notifications: I changed the api that the event object of a notification can be null. We need to update frontend that it shows a warning when an event is null. 

Blocker: https://github.com/serlo/api.serlo.org/pull/1105 need to be deployed in `staging`

**Comment by Entkenntnis** [comment]
@kulla do you have a concrete reproduction url? This would be very helpful

**Comment by elbotho** [comment]
As of yesterday my account had an invalid event in the "read" tab on staging

**Comment by kulla** [comment]
> @kulla do you have a concrete reproduction url? This would be very helpful

Event id 382819 cannot be loaded. In sentry: https://serlo.sentry.io/issues/4576054260/?referrer=github_integration -> You can find it when you log into my account and go through my notifications

**Comment by kulla** [comment]
@elbotho Okay, API in staging is updated with https://github.com/serlo/api.serlo.org/pull/1105

**Comment by Entkenntnis** [comment]
@kulla As of right now, in botho's account I still can't see notifications

![grafik](https://github.com/serlo/frontend/assets/13507950/93ce68a9-e6b6-4eee-8d52-d9b080ae411a)

Are the changes deployed or is this another problem?

**Comment by kulla** [comment]
> Are the changes deployed or is this another problem?

Another problem. See https://serlo.slack.com/archives/C062ZPYDM36/p1699566309096189

**Comment by Entkenntnis** [comment]
summary: some events are not deleted yet, @hejtful is working on it right now

**Comment by Entkenntnis** [comment]
progress: notifications are now loading and we can continue the work in the frontend

reproduction: close to the end of kullas notifications, there is this:

![grafik](https://github.com/serlo/frontend/assets/13507950/aec5cd7a-5796-4922-a8ab-da7df2f57dac)
