### ISSUE TITLE
latex styling is wrong in editor

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3091]
reproduction: https://de.serlo.org/entity/repository/add-revision/291361/291362

Expected: Formula is displayed once

Actual: Formula is duplicated

![grafik](https://github.com/serlo/frontend/assets/13507950/48affd57-0c99-42cf-9636-8e3d9347085c)

Rendered output is working: https://de.serlo.org/mathe/291361/291361

**Comment by elbotho** [comment]
<img width="508" alt="image" src="https://github.com/serlo/frontend/assets/1258870/c8512db5-83dd-4b1d-89ad-8a810de85a9c">

both spans are displayed, but should not be…

**Comment by Entkenntnis** [comment]
it looks like that MathSpan-Styles are not loaded

**Comment by LarsTheGlidingSquirrel** [comment]
I wasn't related to what I was thinking during the weekly. Who wants to continue?
