### ISSUE TITLE
bug: opening menu crashed page (ai feature)

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#3105]
steps: 
- visit https://de.serlo-staging.dev/mathe/1555/zylinder
- login
- try to open the "weitere optionen" menu
- page disappears (blank)
- error in console: `Error: attempted to use ai wizard context outside of provider!`

ping @CodingDive

**Comment by CodingDive** [comment]
Yeah, this will be fixed with the refactoring I'm working on right now. Already removed the context 👍 
Thanks for reporting!

**Comment by Entkenntnis** [comment]
@CodingDive If you have already fixed this part, could you open a small PR for it? This is currently a blocker for frontend deployments - best today or tomorrow.

**Comment by elbotho** [comment]
quickfixed this in https://github.com/serlo/frontend/commit/cf6430555b3f94e0f4dc6251ecfe2e63f8ce79d1
