### ISSUE TITLE
client-side-navigation struggles with special characters (%, ?)

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#312]
https://de.serlo.org/mathe/funktionen/wichtige-funktionstypen-eigenschaften

![grafik](https://user-images.githubusercontent.com/13507950/84639256-6a7e3580-aef8-11ea-90c8-077131ef6766.png)

'%' is breaking client-side-navigation

Also page 2 and 3 of this course: https://de.serlo.org/43180/uebersicht

Will have to lookup how next router expect the url to be (decoded or not, etc...) and change it to it.

**Comment by inyono** [comment]
ping #292

**Comment by elbotho** [comment]
https://github.com/vercel/next.js/issues/10080

**Comment by elbotho** [comment]
Puh, this might go way upstream. [Next.js Bug](https://github.com/vercel/next.js/issues/12145), [related PR](https://github.com/vercel/next.js/pull/12154) that might fix it and [a node bug](https://github.com/nodejs/node/issues/33892).

**Comment by inyono** [comment]
Okay, how do we approach this? Is there an easy way for us to disable client-side navigation for urls containing those characters?

**Comment by elbotho** [comment]
Maybe @Entkenntnis could take a look if we can fix it on our end somehow.
But then yes: Not using CSR for those urls is easy, we might even fall back to the id for those urls and still use CSR.
