### ISSUE TITLE
fix e2e tests failing after modal refactoring

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3129]
@elbotho @CodingDive I'm pretty sure it's related to the refactoring, we relied on `button.rounded-full` to locate the close button.

I'll take a look tomorrow, but if somebody is quicker ..

**Comment by Entkenntnis** [comment]
hopefully this does the trick: [a093f5e62a3e7cb952caef3f6079cc51e7e154eb](https://github.com/serlo/frontend-e2e-tests/commit/a093f5e62a3e7cb952caef3f6079cc51e7e154eb)

**Comment by Entkenntnis** [comment]
ok, now it works

**Comment by elbotho** [comment]
Thank you 🙏
