### ISSUE TITLE
non-standard property "zoom"

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3140]
I'm encountering some warnings about non-standard property "zoom" and we actually use it in one place here:

https://github.com/serlo/frontend/blob/6bb7d770455ee107cdb7bf6b34300c2b1898f5ef/src/components/content/donations-banner-experiment/donations-banner.tsx#L330-L335

@elbotho even if it's only a minor thing, it's still [recommand not](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) to use it. Tailwinds `scale-125` should do the trick - if you don't mind I could go ahead an refactor this.

**Comment by elbotho** [comment]
alternatively we could remove the experiment that should have ended more than one year ago 😁 
but of course feel free to change it.

**Comment by Entkenntnis** [comment]
removing and cleaning up would be also nice :) do you know if anybody is still using this? Can we safely remove the `donations-banner-experiment`-folder?

**Comment by elbotho** [comment]
Simon wants the banner to stay, so we keep it in "do-as-little-as-possible" mode for now I'd say.

**Comment by Entkenntnis** [comment]
easiest solution: e06a3286ae3c451746a00837e6d26b81e78b7165 (was not working in ff so far anyway)
