### ISSUE TITLE
author tools not loaded for exercise

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3162]
~https://de.serlo.org/mathe/76757/nachtermin-teil-b~

faulty content moved, direct link https://de.serlo.org/mathe/75989/75989

**Comment by CodingDive** [comment]
They seem to load for me.

![image](https://github.com/serlo/frontend/assets/28842311/6264abdb-e706-4eff-8f64-6f5118804dab)

**Comment by Entkenntnis** [comment]
@elbotho Any idea how it could happen that the exercise plugin is missing?

![grafik](https://github.com/serlo/frontend/assets/13507950/b623de7b-aa76-4229-9471-3f7940a11009)

As we want to delete this content anyway, if this is not happening more often, it's enough to just delete the content.
