### ISSUE TITLE
update prisma setup for workspaces

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3179]
Where should we store our env strings, in root or in app?

also update readme

**Comment by elbotho** [comment]
> Where should we store our env strings, in root or in app?

so far I did not put any `.env` files into the root and I guess until we don't share them across packages or apps it does not really matter.

**Comment by Entkenntnis** [comment]
Make it compile:

`yarn build:prisma` in root (no database string necessary)

**Comment by Entkenntnis** [comment]
next.js env:

`apps/web/.env.local`

**Comment by Entkenntnis** [comment]
- `yarn prisma studio`, `yarn prisma db pull`, `yarn prisma db push` should preferably use the same env file. only way seems like using custom scripts: https://www.prisma.io/docs/guides/development-environment/environment-variables/using-multiple-env-files

adding scripts would help anyways (and alias to root)
