### ISSUE TITLE
add documentation for forks

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3180]
- https://github.com/Entkenntnis/tmp-react-mathquill
- https://github.com/Entkenntnis/tmp-react-notify-toast

**Comment by hejtful** [comment]
This is a very nice idea! I remember having to work with the Mathquill one when I just joined, and I had no idea why we used a custom fork.

**Comment by Entkenntnis** [comment]
reason for tmp-react-mathquill: https://github.com/Entkenntnis/react-mathquill-dist (outdated version of dependency)

**Comment by Entkenntnis** [comment]
reason for react-notify-toast: no support for react 18

**Comment by Entkenntnis** [comment]
- [x] add wiki page
- [x] link page from readme
- [x] explain reasons for both forks

**Comment by elbotho** [comment]
Thank you 🎉 
I changed / added some links to the wiki entry.
