### ISSUE TITLE
mobile menu broken

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#3185]
always expanded, can't be closed

**Comment by Entkenntnis** [comment]
a simple overlook in 176b33184858e737f422338236df5ed14c884e0a:

![grafik](https://github.com/serlo/frontend/assets/13507950/9a87b577-bbbc-4f6b-8ff7-1e751b7ef0c6)

This need e2e test coverage with something like [resize-window](https://codecept.io/helpers/Playwright/#resizewindow).

**Comment by Entkenntnis** [comment]
fixed in 6f74a61fb6f1538bc0d5113af635654a55b0d4ab, awaits deployment

**Comment by Entkenntnis** [comment]
fix deployed

**Comment by elbotho** [comment]
🙏 Thank you for the quick fix.
I'm surprised nobody told us about that. I guess the users who are in direct contact with us mostly use desktops.
Follow up: https://trello.com/c/8FkvNNj8/437-e2e-test-for-smaller-screens

**Comment by Entkenntnis** [comment]
I am equally surprised - this is quite a blind spot in our team.
