### ISSUE TITLE
blank-exercise: Toggle of blank when selection is not collapse does not work

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#3192]
## Steps to reproduce

1. Create a gap exercise with several blanks
2. Make a selection over many blanks: 
![2023-12-11-185543_560x252_scrot](https://github.com/serlo/frontend/assets/1327215/55ef5d80-da1d-424f-a067-6cccbe4ca304)
3. Click "toggle blank"
4. Result: Selected non blank text is deleted:  
![2023-12-11-185645_359x221_scrot](https://github.com/serlo/frontend/assets/1327215/83d878dd-2bb0-4182-beab-f994d826866f)

## Expected behavior
Either (1) The whole selection becomes a blank or (2) all blanks in the selctions are toggled.

## Fast workaround
Do not allow toggling for uncollapsed selections

**Comment by LarsTheGlidingSquirrel** [comment]
Found a solution that works in all cases (I think)
