### ISSUE TITLE
simplify env-system

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3199]
- [ ] move public constants out of .env - applying changes to them will need a redeployment anyway, so we can just store them as code
- [ ] identify necessary env vars, confirm there value on build for better debugging
- [ ] fix VERCEL_GITHUB_COMMIT_SHA (renamed)
- [ ] deprecate `.env.production` - at this point it contains no important things anyways.

**Comment by elbotho** [comment]
I made a quick overview of all the vars:
https://docs.google.com/spreadsheets/d/1CvOyJYv9J8eD29FmnOsJw0IyLygv3et3GkQNAoGQi7w/edit#gid=0
