### ISSUE TITLE
Export Serlo editor for RLP repo as NPM package

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#3213]
### Build editor as `.tgz` file
* Go into branch https://github.com/serlo/frontend/pull/3220
* Find a new version number in https://github.com/serlo/frontend/blob/5f8a348c23d3462b75fe6aa9ec7a0aab10058cd1/package.json#L3
* Run `yarn build && npm pack` inside `packages/editor`
* You will find a `serlo-editor-0.0.x.tgz` in the directory of the frontend

### Use the editor in RLP repo
* Go to branch https://github.com/serlo/serlo-editor-for-edusharing/pull/303
* Update path https://github.com/serlo/serlo-editor-for-edusharing/blob/test-editor-package/package.json#L56 to your local path for the package
* Run `yarn`
* Run `yarn start:mongodb && yarn dev`
* Open editor via http://localhost:8100

BTW: For each change in the frontend you need to add a new version number. Due to caching updating the `.tgz` file is not enough.

## Open todos

- [x] Review and merge https://github.com/serlo/frontend/pull/3183
- [x] fix types etc. in https://github.com/serlo/frontend/pull/3220
- [x] Add GitHub action or package.json script to deploy and publish https://github.com/serlo/frontend/tree/editor-package/packages/editor as `@serlo/editor-beta`
- [x] Fix merge conflicts and merge https://github.com/serlo/frontend/pull/3229
- [x] Add `@serlo/editor-beta` in https://github.com/serlo/frontend/pull/3136
    * Make sure that textarea input for exercises is added as well
- [x] Make all CI tests pass / Fix lint errors / Merge all PRs
- [x] Add README + website URL to @serlo/editor
- [x] Fix SVGs in Box plugin in edu-sharing
- [x] [Test Styles in edusharing repo](https://github.com/serlo/serlo-editor-for-edusharing/issues/326)

**Comment by Entkenntnis** [comment]
first draft is working, open new issues for further improvements.
