### ISSUE TITLE
Extract focus management tests in a separate suite

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#3219]
An action item from the focus management retro. In order to test focus management feature more easily, all focus management related tests should be in their own suite.

Best started after https://github.com/serlo/frontend-e2e-tests/pull/81 is merged, to avoid conflicts.

**Comment by hejtful** [comment]
Not worth it for now, as there seems to be only one focus management related tests. Leaving the issue open as a reminder for when we add more focus management related tests.

**Comment by elbotho** [comment]
moving to backlog for now since I'm going to archive this repo.
