### ISSUE TITLE
multimedia: allow geogebra id to be shorter

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3261]
if the geogebra id is only `nv5wNx9R`, the isEmptyCheck shows true, even if the plugin is existing:

![grafik](https://github.com/serlo/frontend/assets/13507950/85c03088-a767-4908-89f6-d013c725f292)

@elbotho any objections to setting it to a lower value, like 5?

Context: I noticed this bug while debugging geogebra in edusharing integration

**Comment by elbotho** [comment]
No objections. I might have copied this code and know nothing about the requirements for a valid geogebra Id string :) 

Could they be even shorter that five? 
Check could also just check if it's empty.

**Comment by Entkenntnis** [comment]
Alright, I removed the check in 91c884a791814cf9329176d99c2c235d92ae79bd as I currently cannot think of a proper use case for it.
