### ISSUE TITLE
Add storybook for Components that are annoying to test otherwise

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#327]
E.g. OAuth workflow needs running Hydra at the moment (which needs a running serlo.org instance). Would be nice to have a storybook to test components with different states (e.g. logged in / as guest) without needing the server structure.

**Comment by Entkenntnis** [comment]
Some advantages of the storybook (by inyono):


- It forces us to decouple the components from the actual token implementation.
- "Mock" code is not part of the production code, w/o us having to watch out for that.
- We could also use the stories for unit / e2e tests.

**Comment by Entkenntnis** [comment]
The biggest issue with hydra is solved now, so we will not implement this for the upcoming milestone.
