### ISSUE TITLE
Routing configuration: problems, approaches, etc.

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#328]
See #308:

Possible approaches:
- We wrap the API call in the Cloudflare Worker and possibly pass the info that this should be handled via legacy system.
- We expose the logic in the Cloudflare Worker as an npm package and import that in the frontend (problem: need to keep that package up-to-date)
- Duplicate the logic from Cloudflare Worker (meh)

I'd prefer the first approach to be honest. This way, we'd only need to redeploy the Cloudflare Worker when the config changes and we can wrap the client-side logic once on front-end side.

**Comment by Entkenntnis** [comment]
One thing we should keep in mind with the first approach are possible performance implications, e.g. possible loading times. Wrapping calls with cloudflare is unfortunately not "free", but it can be solved with proper caching ...

**Comment by inyono** [comment]
> One thing we should keep in mind with the first approach are possible performance implications, e.g. possible loading times. Wrapping calls with cloudflare is unfortunately not "free", but it can be solved with proper caching ...

Not necessarily. Note that every request to the API (even the one that is cached via Vercel) goes through the Cloudflare worker. So we can easily wrap those responses without additional overhead (except a slightly larger body including a boolean or something).

**Comment by kulla** [comment]
How about the following solution? We move the logic to decide which resource the frontend can handle to `api.serlo.org`. There we add the following endpoint:

```
type Query {
  pathInfo(instance: Instance, path: string) {
    canUseFrontend: Boolean!
    currentPath: string!
  }
}
```

In the cloudflare worker we need to access the api anyways so that we can query for the current alias and the type name of the resource. The frontend can use the above endpoint next to `uuid(...)` when it wants to access the content of a page. In case the resource cannot be handled by the frontend the result would be something like

```
data: {
  uuid: null,
  pathInfo: {
    canUseFrontend: false,
    currentPath: "..."
  }
}
```

This can be used to open a new page in the frontend with `currentPath`. What do you think?

**Comment by Entkenntnis** [comment]
This would take some effort to implement in the frontend, because it expects the data to be static. It would be easier to have the data in the frontend and let the cloudflare worker make a query to the frontend to get this information.

**Comment by Entkenntnis** [comment]
It could be a single API endpoint with a list of all urls that the frontend can't handle.

**Comment by inyono** [comment]
> This would take some effort to implement in the frontend, because it expects the data to be static. It would be easier to have the data in the frontend and let the cloudflare worker make a query to the frontend to get this information.

We should really handle the logic in the Cloudflare Worker or API. Otherwise, we introduce a request flow that goes against our API / services approach, which makes reasoning about the behavior more annoying.

Can't we do something like Kulla suggests and handle the logic in our fetcher? Namely something like:
- We handle every route `*.serlo.org*` route in the frontend.
- In the Page component, we do the API request. If the API response suggests that we shouldn't handle the request in the frontend, we redirect to the backend (e.g. via browser refresh or document.location).

This way, we don't need to handle CSR-links in any special way (they are also handled via Next.js routing) and it can be dynamic.

**Comment by Entkenntnis** [comment]
Another possibility would be to resolve all links in the fetcher (like our prettylinks) and decide while fetching where to route each page. This would allow data to be fetched from the API and keep the low latency.

Tthere is an advantage of knowing before-hand how to route a page: If we know its a frontend page, we can directly access the frontend and use the Vercel cache. We have performed some benchmarks for this:

![](https://raw.githubusercontent.com/invidiae/check-website-speed/master/C%26F.svg)

Blue is direct access to the frontend, orange is through the cloudflare worker. Routing through the cloudflare-worker is increasing load times by 3x (for cached pages) and strongly increases variance.

We would give up this latency reducement if we force every request to go through the cloudflare worker.

**Comment by inyono** [comment]
How do you avoid the Cloudflare Worker? Even `frontend.serlo.org` goes through the Cloudflare Worker.

Furthermore: since you get the information via the API, it doesn't matter if the request goes through the Cloudflare Worker or not.

**Comment by elbotho** [comment]
I vote to implement whatever is easiest, because this is a temporary fix anyway, right?

**Comment by Entkenntnis** [comment]
Let's go back to the root issue. We have two pieces of code, on is in the frontend:

https://github.com/serlo/frontend/blob/30932a666f07d4e2b339798a20c351f9c82d5ba8/src/components/content/link.tsx#L17-L34

These links are not routed with CSR, and it's a static set of links that rarely change.

Then we have a similar code in the cloudflare worker:

![grafik](https://user-images.githubusercontent.com/13507950/89170451-ef441200-d57f-11ea-8712-2e368402854c.png)

This is another set of rules about how to route several paths.

The easiest solution is to keep it as it is, because the current milestone is not depending on this issue.

For the long-term, these exceptions would vanish, because we handle most routes in the frontend.

**Comment by inyono** [comment]
Not too sure about that. While it is rather simple at the moment, it will change over time:
- Currently, we show the profiles in the old system since we don't have a view for Users yet.
- There will be more (dynamic!) routes that need to be handled by the legacy system: e.g. creating a new revision, etc.. And these will change over (a long) time, as we reimplement the views in the frontend.

Especially the second point is rather annoying without a sync, though: If we want to activate a feature (e.g. new Editor in new frontend), we need to change the URLs at the same time in both Cloudflare Worker and frontend. Also, if we need to rollback for some reason (buggy first release), we need to redeploy both services.

Putting it in the API, on the other hand, allows us to handle such inconsistencies in the url at one place (even long-term stuff like `/imprint` that are handled by the cloudflare worker). 

Also: something like "redirect the course to the first course page" is also simpler if we have some sync in place. Otherwise, CSR is also some extra special case you need to cover.

Sorry, third edit: If we want to go away from the invariant, that every request goes through the Cloudflare Worker (e.g. to achieve the optimizations of going directly through Vercel), we should definitely sync them. Otherwise, every time we change something in the Cloudflare Worker (some redirects or rewrites or whatever), we need to cover it in the frontend, too.

**Comment by Entkenntnis** [comment]
Can we agree that we can achieve the current milestone without this feature, but we will need to solve this issue for upcoming features? Your points are 100% valid and show that implementing this needs thought and time.

I would like to focus our current energy on the 100% roll out.

**Comment by inyono** [comment]
Yep, sure, I don't care much about when we do it (although it would need the changes regarding URLs we add to the hover menus e.g.). Was more a counter point to @elbotho and your comments regarding that it won't matter in the future. 😄 We still should do it sometime because there is quite some error-potential here when we don't keep them in sync.

**Comment by elbotho** [comment]
follow up here #690
