### ISSUE TITLE
Refactor Links

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#329]
We now have some duplication and slightly different implementations of links for content and the different menus.

I'd love a smart Link component that handles PrettyLinks and can decide if a link should be routed client-side or with reload.
Related: #320, #308, #328 …

**Comment by Entkenntnis** [comment]
Love this idea very much!

**Comment by elbotho** [comment]
Discussion with @Entkenntnis

Todo: 
- Also check for absolute links in content (`de.serlo.org/[id]`) and use CSR for them
- Check error handling if a CSR fails (could it be fixes with a redirect?)

Currently there are following exceptions to client-side-routing:
- external links
- legacy pages (like auth and privacy)
- frontend pages that are not using `[...slug]` (index, search, donations)

Results:
- Legacy stuff should be handled by cloudflare worker to avoid duplication etc. like @inyono suggested
- Idea for the frontend pages (index, search, donations): Also use `[...slug]` and dynamically load to load those. This way we can use CSR for all links in the frontend that are not external or legacy.

**Comment by elbotho** [comment]
this is currently the result when I try client side routing with an absolute link
![image](https://user-images.githubusercontent.com/1258870/85285202-c44ea480-b490-11ea-9daa-676b79009ecd.png)

**Comment by elbotho** [comment]
result when I force CSR to (`/auth/login`)
``` js
{"error":
    "Error while fetching data: Cannot read property 'path' of null:
    {
    "response":{
    "errors":[{
    "message":"Cannot read property 'path' of null","locations":[{
    "line":3,"column":5}],"path":["uuid"],"extensions":{
    "code":"INTERNAL_SERVER_ERROR"}}],"data":{
    "uuid":null},"status":200},"request":{
        …
        }
    }
}
```

CSR to `/impressum` etc actually load the content in the redesign.

**Comment by elbotho** [comment]
I found a `ref/21654` link that breaks. What's the deal with those, how should we handle them?

**Comment by inyono** [comment]
`ref/<id>` is equivalent to `/<id>`. We don't really use them anymore (and while there probably was a reason for the ref links at some point, we encourage users to use `/</id`).
