### ISSUE TITLE
grouped exercises not shown

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3299]
https://de.serlo.org/mathe/294322/294322

expected: grouped exercises are visible
https://de.serlo.org/entity/repository/compare/294324/294325
https://de.serlo.org/entity/repository/compare/294326/294327
https://de.serlo.org/entity/repository/compare/294328/294329
https://de.serlo.org/entity/repository/compare/294330/294331
https://de.serlo.org/entity/repository/compare/294332/294333

actual: grouped exercises are not visible

**Comment by Entkenntnis** [comment]
root cause was a save with empty revisions ("Oberstrich einfügen" by Karin) - this could be a fault in the save logic...

**Comment by Entkenntnis** [comment]
@elbotho Have you noticed any cases where the editor would save empty revisions (instead of the content) or could you imagine something like that is happening?

**Comment by elbotho** [comment]
> Have you noticed any cases where the editor would save empty revisions (instead of the content) or could you imagine something like that is happening?

Hmm, I did not notice something like that. But the save code is a bit of a mess and I can imagine that happening. 
Probably hard to debug/reproduce. 

Since we want to refactor GroupedExercises (and Courses) soonish I'd honestly wait for an example on an entity without children.
