### ISSUE TITLE
Another URL Problem

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#333]
follow up of #292
(sorry to continue this 😓)

**Problem:**
https://de.serlo.org/mathe/zahlen-gr%25C3%25B6%25C3%259Fen

**Steps to reproduce:**
Navigate to https://de.serlo.org/mathe using the new frontend.
Click on the "Zahlen und Größen" image.
tries to navigate to https://de.serlo.org/1385 comes out at https://de.serlo.org/mathe/zahlen-gr%25C3%25B6%25C3%259Fen

- [ ] Obviously Image links should also be prettified (I'll check that)
- [ ] but links to `/id` should still work

PS: On localhost this works.

**Comment by inyono** [comment]
This seems to be a problem in the frontend itself, API responds with the correct alias. Going to look into that.
