### ISSUE TITLE
https://serlo.org/community results in 404

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#335]
https://serlo.org/community is still or again unaccessible,
API request returns:
```{"error":"Error while fetching data: Expected type Int, found NaN.: {\"response\":{\"errors\":[{\"message\":\"Expected type Int, found NaN.\",\"locations\":[{\"line\":74,\"column\":22}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Expected type Int, found NaN.\",\"locations\":[{\"line\":86,\"column\":22}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Expected type Int, found NaN.\",\"locations\":[{\"line\":98,\"column\":22}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}],\"status\":400},\"request\":{\"query\":\"{\\n    uuid145470: uuid(id:145470) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid88059: uuid(id:88059) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid106081: uuid(id:106081) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid106082: uuid(id:106082) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid88061: uuid(id:88061) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid145470: uuid(id:145470) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuidNaN: uuid(id:NaN) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuidNaN: uuid(id:NaN) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuidNaN: uuid(id:NaN) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid19875: uuid(id:19875) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  ,\\n    uuid87993: uuid(id:87993) {\\n        ... on Entity {\\n          alias\\n        }\\n        ... on Page {\\n          alias\\n        }\\n        ... on TaxonomyTerm {\\n          alias\\n        }\\n      }\\n  }\"}}","alias":"/community"}```

**Comment by inyono** [comment]
I'd look at the pretty link fetching:
```
 uuidNaN: uuid(id:NaN)
```
Seems like you try to fetch the pretty alias of something that isn't a number.

**Comment by elbotho** [comment]
Will investigate 🔍 
Thanks 👍
