### ISSUE TITLE
Add prettylinks to linked images

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#337]
On https://de.serlo.org/mathe are images used to link to content (e.g. "Zahlen und Größen") 
![image](https://user-images.githubusercontent.com/1258870/85297428-054fb480-b4a3-11ea-88d9-8803e831fdf9.png)

```{"type":"img","src":"https://assets.serlo.org/legacy/55533eeeb56b8_8b7ea5f93ff53cab80557b4d4a9ab4c250e30789.png","alt":"Zahlen und Größen","href":"/1385"}```

currently those don't get the prettyLinks and therefore also no client-side-routing, because my extractor only looks for `obj.type === 'a'`. 

**Question:**
Is that the expected behaviour of the new editor? Are there other types that can have "href" set?

**Comment by inyono** [comment]
Currently, we already specify the rendering completely, so you should be able to use a `PrettyLink` component in the image renderer (if we implement #328). If you want to handle it at state level, you probably need to go over all possible plugins with links (and I think that images are the only other case compared to richt text, IIRC)

**Comment by Entkenntnis** [comment]
As images are the only other type with href (currently) I would include it in extractLinks.

**Comment by elbotho** [comment]
Should be fixed in #339
