### ISSUE TITLE
hydration error for gaps

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3379]
![grafik](https://github.com/serlo/frontend/assets/13507950/13f1f0c3-4e0f-4739-9c71-f2353c3654ab)

Disable ssr for rendering the DnDWrapper is solving the issue for me (as in https://github.com/serlo/frontend/pull/3370/commits/28bb898f7dbbb620b402f73fa61a488747e48908)

**Comment by CodingDive** [comment]
Could this help? 
https://nextjs.org/docs/app/building-your-application/rendering/client-components

It does mean however, that all of the `children` also get rendered on the client. https://github.com/serlo/frontend/pull/3370/commits/0e4da688c49f3ff45b6f576961bee14b932a4d2f#diff-863725af8892afe1d072e43d326269900c8bd6966cd589ae348fbbb0d1fe4f6dR1

**Comment by elbotho** [comment]
> Could this help?
https://nextjs.org/docs/app/building-your-application/rendering/client-components

We are not using the app router so this is not relevant to us right now.

**Comment by CodingDive** [comment]
Good to know. https://react.dev/reference/react/use-client is still in canary so we can't or shouldn't use it outside of Next.js.

**Comment by Entkenntnis** [comment]
problem is not present on staging anymore after #3370
