### ISSUE TITLE
The "Serlo in other languages-link" is broken in the new frontend

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#340]
The link in the footer redirects to "en.serlo.org.org/global" instead of "serlo.org/global". Don't know if this is also the case for other links between language-versions of serlo.

**Comment by jakobwes** [comment]
The Api-link, which links also to an English-page works, so this is probably a singular problem

**Comment by Entkenntnis** [comment]
Thank you for reporting this, a fix is on the way! (#339 should solve this)

**Comment by inyono** [comment]
I commented in the PR. There is a double .org because serloDomain already contains .org.
