### ISSUE TITLE
replace ts-expect-error with any?

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#341]
In `src/content/exercise.tsx`, we have two ts-expect-error that show up as warnings. Can we use `as any` here to avoid the warnings?

Or is the warning expected here?

**Comment by elbotho** [comment]
My understanding: We use `@ts-expect-error` instead of `any` because those lines are actually missing correct types, so the warnings are a good reminder of that :)

**Comment by elbotho** [comment]
I see @inyono already commented.

**Comment by Entkenntnis** [comment]
Well, is there a rule where to use which? Because in other places (schema, fetcher) we are using any with an TODO annotation

**Comment by inyono** [comment]
Basically: if there are no types yet, we use any. If we have types and they result in an error, we use ts-expect-error. If a specific location is really hard to type or it’s hard to get TS to understand why the typing works, we can use something like foo as unknown as CorrectType. This is a last resort, though.
