### ISSUE TITLE
launch exams landing page

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#3432]
current state: https://de.serlo-staging.dev/pruefungen

- [x] wait one more day for feedback
- [x] change path from `pruefungen` to `mathe-pruefungen` again
- [x] change redirect in cf-worker to `mathe-pruefungen`
- [x] change link on math landing page
- [x] ask hugo to remove old alias at `mathe-pruefungen`
- [x] wait for old alias to be removed
- [x] deploy frontend
- [x] deploy cf-worker to production

optionals:
- [x] add info boxes in exams-taxonomies that links to the exams landing page
- [x] maybe hide the side menu in exams-taxonomies

later (when we have more finished content):
- [ ] add to serlo.org landing
- [ ] add to subject menu

**Comment by CodingDive** [comment]
"Lauch" 🧅😄
