### ISSUE TITLE
article 1885 has no alias

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#344]
requesting the alias of `1885` results in null. @inyono So we have entities without alias?

Found here: https://frontend-git-fix-eslint-warning.serlo.vercel.app/mathe/zahlen-groessen/bruchrechnen-dezimalzahlen/umformen-bruechen-dezimalbrueche/umrechnen-bruechen-dezimalzahlen
(Link Zehnerpotenz)

See: https://de.serlo.org/1885

Nothing to do here, just wondering ...

**Comment by inyono** [comment]
There are definitely UUIDs without alias (e.g. users). Entities should probably have an alias, maybe old ones don’t have it. Re-Saving should generate one. Still: you shouldn’t rely on it to be defined :)

**Comment by Entkenntnis** [comment]
Thank you for the clarification!

**Comment by elbotho** [comment]
the reworked link component (#339) should still route those links client side, so this can be closed?
