### ISSUE TITLE
math-skills: review data format

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3441]
Maybe put history in a separate prop (for later) and focus on score/skill-level right now

**Comment by elbotho** [comment]
> focus on score/skill-level

fully agree on this one, just wanted the data to be there and having one place for execise data made sense to me.

**Comment by Entkenntnis** [comment]
I'm not seeing any bigger problems in the short term.

We use urls as ID, changing url will reset score, this is something we have to keep in mind.

**Comment by elbotho** [comment]
> We use urls as ID, changing url will reset score, this is something we have to keep in mind.

true, I liked this simplification because … sessionStorage ;) but an object with all the exercises and an id might make sense in the long term :)
