### ISSUE TITLE
math-skills: add checkbox to persist

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3442]
Minimal solution which is sufficient for this iteration

**Comment by elbotho** [comment]
like it.
I thought about a (probably additional) popup after you first get three points in an exercise.
(congratulating and then asking if you want to persist to this device)

**Comment by Entkenntnis** [comment]
> congratulating and then asking if you want to persist to this device

also a good option

**Comment by Entkenntnis** [comment]
minimal version implemented
