### ISSUE TITLE
math-skills: number line on mobile

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3444]
Add slightly bit more margin x, because gesture can easily be interpreted as page back

**Comment by elbotho** [comment]
did that happen to you?

**Comment by Entkenntnis** [comment]
quite often on chrome / android

**Comment by elbotho** [comment]
maybe something like this could work without loosing a lot of valuable horizontal space
https://stackoverflow.com/a/56071966 (or https://stackoverflow.com/a/60519484)

**Comment by elbotho** [comment]
quickfix: 415b8cb3a9bdb22664b891125c6bbe99d7475f5b
