### ISSUE TITLE
math-skills: finish "Vorgänger und Nachfolger"

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3457]
- polish ui
- write generators

**Comment by elbotho** [comment]
worked on ui a bit:
<img width="441" alt="image" src="https://github.com/serlo/frontend/assets/1258870/4873b0ef-3eb2-47a5-b869-db45e82e99b3">
<img width="313" alt="image" src="https://github.com/serlo/frontend/assets/1258870/b0d8a6df-80c1-4a84-92e8-cfb8a9227954">

**Comment by elbotho** [comment]
also: mixed feedback.
<img width="580" alt="image" src="https://github.com/serlo/frontend/assets/1258870/6dfbc5e0-be99-4c23-b81f-ac071f0bebe4">

**Comment by Entkenntnis** [comment]
last two generators written in https://github.com/serlo/frontend/pull/3425/commits/e73f12c41e387ef67c30a86f253826b60a5733bc
