### ISSUE TITLE
Idea: Use service worker for caching

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#347]
This might actually be a useful thing (offline access etc) and would be a big step towards PWA.

**Comment by elbotho** [comment]
Might be relevant:
https://github.com/shadowwalker/next-pwa/

**Comment by inyono** [comment]
Good idea. Would put that into the backlog for now, though, since this adds more complexity and I'd rather get client-side routing / other critical features working before we add this. Might also be nice to have a testing suite before that. What's your opinion on that?

**Comment by elbotho** [comment]
Jup, backlog is good. 100% is more important than new (experimental) features.
The "session-cache" works surprisingly well.

**Comment by Entkenntnis** [comment]
I will close this issue as we already have an issue for this topic in product management: https://github.com/serlo/serlo.org-rfcs/issues/39
