### ISSUE TITLE
GroupedExercise feature overview

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#3483]
### status / assessment of currently supported features

☑️ = should work, need testing
🙅 = will be removed at least for now, and should not be a big problem ( check for vetos)
⚠️ = not sure / needs testing / investigating

**Context Menu GroupedExercise:**
- **has own context menu**: ☑️ (should be removed, on groupedEx has one)
- **Notifications** (on/off) 🙅 (only via group)
- **Edit** (opens the GroupedExercise in Editor) ☑️ (can be edited via editor)
- **History** ☑️ (should be merged in with the existing)
- **Sort** (order of groupedEx in ExGroup) ☑️ (quite untested)
- **Assign to Topics / Syllabus** (was actually broken, removed) 🙅
- **License** (change license of Grouped Ex) ☑️  (test especially if it's shown correctly)
- **Activity log** 🙅
- **Delete** ☑️ (moves to editor)
- **Direct link** (opens preview of only that exercise) ⚠️ (frontend client side still shows those)

**In Editor (in der ExerciseGroup):**
- **Saving**: (saves to GroupEx editor state, does not change other uuids)
- **Load other version** of that GroupedEx 🙅 (only for whole group)
- **Generate ExGroup with AI** ☑️/⚠️ (changed some code, but untested)
- **Import content** of existing GroupedEx into new GroupedEx 🙅
- **Add new** GroupedEx ☑️
- **Delete** GroupedEx ☑️

**Comment by elbotho** [comment]
<img width="265" alt="image" src="https://github.com/serlo/frontend/assets/1258870/b638aa24-ad66-4b69-906b-ea64736e4191">

**Comment by elbotho** [comment]
### Bugs:
- (editor: loading from history works and then refreshes the page to the current state… probably general bug?)
- AI generation: after generation the modal class is still on the body so scrolling is blocked. Does not work in Prod at all, so this is still better (no blocker)

**Comment by kulla** [comment]
> Notifications (on/off) 🙅 (only via group)

After deleting the grouped exercises those notifications will also be deleted from our backend

> Assign to Topics / Syllabus (was actually broken, removed) 🙅

should not be possible for grouped exercises anyway

> Activity log 🙅

will be working on exercise group level

> Direct link (opens preview of only that exercise) ⚠️ (frontend client side still shows those)

should be removed for now
