### ISSUE TITLE
math-skills: euro-kommaschreibweise

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3494]
Problem if cent is null -> solution is undefined

**Comment by elbotho** [comment]
> Problem if cent is null -> solution is undefined

Could you elaborate?
In this context I'm not sure if you mean `null` or `0` and what you mean by solution ^^

**Comment by Entkenntnis** [comment]
@elbotho very weird edge case 😅 

![grafik](https://github.com/serlo/frontend/assets/13507950/f46512c7-044e-44f9-a28d-a98c252ea3ef)

**Comment by elbotho** [comment]
Thanks, fixed in a4e42d88b
