### ISSUE TITLE
translations (i18n)

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#35]
There are strings/content in footer, header and probably other components that need to come from athene instead of being hardcoded (for translations etc).

**Comment by Entkenntnis** [comment]
i18n will be added soon.

**Comment by Entkenntnis** [comment]
@inyono Do you have an opinion about where to implement i18n? On the backend server or within the frontend?

**Comment by inyono** [comment]
Definitely in the frontend repo.I recommend i18next it fits with our Crowdin Workflow. You can check out [my PR that adds i18next to the serlo.org client](https://github.com/serlo/serlo.org/pull/302)

**Comment by Entkenntnis** [comment]
this is getting some motion in #188
