### ISSUE TITLE
Search stops working 

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#350]
when I use the search, then use client side routing (e.g. click in the menu) the searchbar does not respond any more.

**Steps:**
- navigate to any page (e.g. https://de.serlo.org/serlo)
- enter term in search bar (search results load)
- now click on e.g. the logo (client side routing to https://de.serlo.org/ happens)
- now I enter another term into the search bar
-> url changes, but results don't show

**Comment by Entkenntnis** [comment]
Can not reproduce yet, can you describe the steps?

**Comment by elbotho** [comment]
added them above

**Comment by Entkenntnis** [comment]
@elbotho Could you check if you are still encoutering this issue?

**Comment by elbotho** [comment]
Nope, works fine here now.
