### ISSUE TITLE
RFC: add staging environment to frontend

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#354]
Currently, the frontend gets redeployed on any push to master. A redeployment also purges the cache from Vercel-side. IMHO: we should add another stage so that we can bundle a couple of changes and deploy them together and possibly delay deployment of commits that aren't critical so that we don't purge the cache every couple of hours. E.g., we could do something like:
- `staging` branch which would be the default branch that PRs are based to. `serlo-staging.dev` would use that one by default.
- `production` branch, which gets deployed to production by Vercel (i.e. same behavior as the current `master` branch). To deploy, we'd merge `staging` into `production` (this could also be a `yarn` command)

Furthermore, we can think about how often we'd want to deploy (and when). Some possible approaches:
- "Nightly" deployments by default? (could even be a cron job via GitHub actions that merges staging into production every night)
- Manual review? Bundle changes together and when they well together and we want to deploy them, merge.

Thoughts?

**Comment by Entkenntnis** [comment]
If github supports this workflow (PR are on staging on default, ...), then I think this would be a improvement, especially the serlo-staging.dev part.

Note: I have merged #348 and #352, because they are quite small, but I thing we can start with staging in future PRs.

**Comment by inyono** [comment]
Yes, that works. Basically `staging` will become Git’s default branch and `production` will become Vercel’s production branch. I can set that up in the next days :)

**Comment by inyono** [comment]
Okay, seems like I missed something: Vercel seems to also use the default branch for production deployments (instead of another one we could configure). So in this case, production needs to be the default branch, and staging would be just a "special" branch that PRs are based onto. So basically:
- Devs creating a PR need to specify staging as the base branch for the PR
- If they forget that, someone else can change the base branch to staging (Edit PR). We could also enforce that PRs directly to master can only be merged by admins.

Still the way to go? It basically moves the responsibility to the one that merges to make sure that the branch is correct (i.e. production, if you want to deploy it directly, or staging, if you want to delay the deployment).

**Comment by Entkenntnis** [comment]
I'm fine with doing this in 2 phases:

1. Create the staging branch, let serlo-staging.dev point to it, base all PR to this branch manually and deploy manually to master as necessary.

2. Evaluate this workflow and decide how well this works out and where we would need automation or something.

The staging-environment would be a valuable addition and optimally we would want to test every PR on staging anyway ...

**Comment by inyono** [comment]
Agreed. Will implement that, then :)

**Comment by inyono** [comment]
Looks good so far.

- [x] `staging` is the new (protected) branch that PRs should be based onto.
- [x] `production` is the new default branch. It is also protected and requires a PR + Code Review before merging.
- [x] Use `frontend-git-staging.serlo.vercel.app` for staging environment.
- [x] Add PR template that tells users to specify `staging` as the base branch.

**Comment by inyono** [comment]
Done :)
