### ISSUE TITLE
How to handle the session-cache for logged-in users

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#355]
Just to keep track of this:

We should probably
- skip the local "session-cache" for people who are editing and reviewing just to make sure content-edits are actually visible
- or find a smart way to decide when to skip and when to use the cache
- or use cached and check for changes in the background

**Comment by inyono** [comment]
We could also take a look at https://swr.vercel.app/ which solves some of this issues and also has good Next.js support.

**Comment by Entkenntnis** [comment]
A good next step would be to add reproducable steps for unwanted behaviour of this issue.

**Comment by inyono** [comment]
> A good next step would be to add reproducable steps for unwanted behaviour of this issue.

Not sure what you mean here.

**Comment by elbotho** [comment]
Two scenarios I can think of right now:
- I edit/accept an article and want to see the changes
- Somebody just accepted a revision and wants to show me the changes

in both cases I could end up seeing the old version.

**Comment by Entkenntnis** [comment]
If a revision is accepted, it takes two reloads for the page to show the new content. This works quite reliably, so I hope this will not annoy users.

Let's create separate issues if we encouter annoying situations in our test runs...
