### ISSUE TITLE
Add licence info to images (and more?)

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#358]
Waiting for the changes in the Image plugin for this, but I'm exited for that :)

Tutorial
https://developers.google.com/search/docs/data-types/image-license-metadata#microdata_1

Testtool:
https://search.google.com/test/rich-results

**Comment by inyono** [comment]
ping @kulla regarding "Quellen-Plugin"

**Comment by elbotho** [comment]
@kulla what is the status this plugin, is it being worked on atm.?

**Comment by kulla** [comment]
> @kulla what is the status this plugin, is it being worked on atm.?

We have made a mock and we have a general idea how it shall work. However I haven't started the implementation yet. I will do it after I have finished https://github.com/serlo/serlo.org/issues/400

**Comment by Entkenntnis** [comment]
Ok, lets close this issue as there is no work for the frontend here at the moment.
