### ISSUE TITLE
secondary navigation missing in preview deployments (staging api)

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#362]
The secondary menu is missing in preview deployments, probably related to the staging backend server:

![grafik](https://user-images.githubusercontent.com/13507950/86403069-41f28b80-bcad-11ea-862b-3a1a079915bb.png)

**Comment by inyono** [comment]
Hm... Staging is down at the moment (together with some other pods). Seems like some node replacement failed. Going to look into that later.

**Comment by inyono** [comment]
That's definitely weird. We had that problem recently and I purged the cache for the navigation. Somehow, it is set to `null` again (although we don't have any logic in place to update the cache value of the navigation). Have to look into that, not sure what's causing this.

**Comment by inyono** [comment]
Navigation cache is correct again (for now). Still need to look into what causes this.

**Comment by Entkenntnis** [comment]
The first time this issue happened to me was when I tried to load a page in another language instance, tamil. Can this cause the navigation cache to break?

**Comment by inyono** [comment]
> The first time this issue happened to me was when I tried to load a page in another language instance, tamil. Can this cause the navigation cache to break?

That pointed me in the right direction, thanks!
