### ISSUE TITLE
Block level math in spoiler title?

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/frontend#3638]
Currently, it is possible to create block level math elements in the spoiler title: 
![image](https://github.com/serlo/frontend/assets/59921805/34e0a077-d2dc-41a3-8369-c8d56ca23c6f)

Should this maybe be prevented? ping @elbotho

**Comment by elbotho** [comment]
closed in favor of https://github.com/serlo/backlog/issues/321

**Comment by elbotho** [comment]
Indeed this is a long standing bug that also affects box titles. Feel free to work on it if you feel like it :)
