### ISSUE TITLE
wrong title

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3643]
![grafik](https://github.com/serlo/frontend/assets/13507950/b4e2908e-f988-4441-9005-9f14e3490785)

Somehow the page https://de.serlo.org/mathe/76750/abschlusspr%C3%BCfungen-mathematik-mit-l%C3%B6sungen-zweig-ii-und-iii has the wrong title tag set, not sure where this is coming from ...

The content is actually from "Realschule".

**Comment by Entkenntnis** [comment]
@elbotho related to recent api changes?

**Comment by Entkenntnis** [comment]
My bad, I just confused "Mittlere Reife" with "Mittelschule" - still I would expect "Realschule" in the title...

**Comment by elbotho** [comment]
It's actually one of the manually overwritten titles (see `math-exams-taxonomies.ts`).
