### ISSUE TITLE
Language subdomains and subfolders

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#365]
Serlo.org is currently using subdomains to distinguish between languages. Unfortunately, our next.js-setup is not able to use different subdomains (easily), so we have to use subfolders (e.g `/de/...` or `/en/...`) instead.

This is not the 100% clean solution, but should work out for our system. Some thoughts:

1. The frontend only looks at the subfolder to decide with language to use. If no subfolder is given, the frontend defaults to `de` .

2. The cloudflare-worker will translate requests and add the subdomain to subfolders, before it makes the request to the frontend.

3. The client will look at the environment to decide how to handle routing. If the client is on a language subdomain, it will use CSR for links within the language only, if the link is for another language, the client makes a full pageload to change the subdomain. If the client is not on a language subdomain (direct access to vercel, preview, local development), the client can route all links using subfolders and with CSR.

4. It would make sense to let the cloudflare-worker handle redirects (id -> alias, old-alias -> new-alias), because the frontend would not be able to redirect to another subdomain.

@kulla (2.) and (4.) are related to the cloudflare-worker, if there is no objection in the next week I would start to implement (1.) and (3.) in #353

**Comment by inyono** [comment]
We can ignore 1. (except maybe for dev) because the Cloudflare Worker already handles `serlo.org` correctly (by redirecting to de.serlo.org, which we could later change to some language-detection or something).

**Comment by Entkenntnis** [comment]
implemented in #423
