### ISSUE TITLE
math-skills: "Einführung Glücksrad" not accepting correct answer

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#3717]
Last bug fix was still not successful

**Comment by Entkenntnis** [comment]
![grafik](https://github.com/serlo/frontend/assets/13507950/c29fec5c-da8f-4d05-afec-a4af6709d0ec)

**Comment by Entkenntnis** [comment]
fixed by a0b48c6c92e589a56b98b86e89ca4ec1c127502b

**Comment by elbotho** [comment]
Thank you!
