### ISSUE TITLE
Idea: Use swr cache for frontend html response

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#383]
With our two-pass rendering approach, we can actually completely cache the frontend html response with stale-with-revalidation, bringing subsequent page load times down by factor of 3-4x.

**Comment by inyono** [comment]
I'd also consider [Relay](https://relay.dev). I heard good things about Relay and they also handle pagination (via GraphQL cursors) quite well. I can compare the approaches when implementing notifications, since we definitely want pagination there.

**Comment by inyono** [comment]
Wait. Why do we want to cache the **HTML**? Isn't Next.js CSR working on the API response? And SSR is already covered by Vercel's Edge Caching.

**Comment by Entkenntnis** [comment]
The SSR html response is not cached yet by Vercel, it's currently rerender for every request (we haven't set any cache headers).

So this issue is not about CSR (these are cached already), but requests to the frontend. I think, it would make sense to set the same headers also to `[[...slug]].tsx`:

https://github.com/serlo/frontend/blob/7389ab2128fda4999994e620643bb6780657cda3/src/pages/api/frontend/%5B...slug%5D.ts#L17

**Comment by inyono** [comment]
Okay, I completely misunderstood the issue xD. Gonna move my comments somewhere else later.
