### ISSUE TITLE
editor(blanks-exercise): adding incorrect answer using Enter doesn't work as expected

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#3854]
When the focus is on an existing incorrect answer and the user presses the Enter key, a new incorrect answer input appears, but it's not focused. Clicking on the new incorrect answer makes it disappear.

Expected behaviour: The newly added incorrect answer will automatically be focused.

Relevant lines:
- [Where inserting the new answer happens](https://github.com/serlo/frontend/blob/staging/packages/editor/src/plugins/blanks-exercise/components/extra-incorrect-answers.tsx#L72). The new answer isn't explicitly focused like [when clicking the button](https://github.com/serlo/frontend/blob/staging/packages/editor/src/plugins/blanks-exercise/components/extra-incorrect-answers.tsx#L32).
- [Where removing an empty answer on blur happens](https://github.com/serlo/frontend/blob/staging/packages/editor/src/plugins/blanks-exercise/components/extra-incorrect-answers.tsx#L79). Something seems to be triggering this blur on Enter key press.

**Comment by shn-srl** [comment]
Seems to be working now

[Screencast from 25.06.2024 11:20:27.webm](https://github.com/serlo/frontend/assets/161819227/5f85760b-b625-45d8-a708-1d9025bf6545)

**Comment by shn-srl** [comment]
Issue occurs in drag/drop mode, reopening

**Comment by shn-srl** [comment]
https://github.com/serlo/frontend/pull/3908
