### ISSUE TITLE
some content where h5p is not loading any more

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#3872]
broken h5p plugins:
- https://de.serlo.org/mathe/30678/aufgaben-zur-satzgruppe-des-pythagoras
- https://de.serlo.org/mathe/31911/aufgaben-zu-linearen-funktionen-als-geraden-im-koordinatensystem

found because they might influence [Interaction to Next Paint](https://web.dev/articles/inp?hl=de) negatively, but that might also be unrelated :)

@Entkenntnis could you tell me if that is a content problem or something in the plugin?

**Comment by Entkenntnis** [comment]
lumi updating there api regularly it seems

**Comment by Entkenntnis** [comment]
will look into it
