### ISSUE TITLE
editor: remove showToastNotice apps/web dependency

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#3927]
The editor is still importing this error handling helper function from serlo.org website.
```typescript
import { showToastNotice } from '@/helper/show-toast-notice'
```
For now, it's alright to make the `react-hot-toast` package a dependency for the editor and duplicate the helper. Afterwards, the editor might get its own redesigned error handling.

**Comment by elbotho** [comment]
imho one of the nicer handlers we have :) 
nice dx and only 29 lines of code aside from the `react-hot-toast` dependency. 
Would be no problem to duplicate this in the editor if it helps.
