### ISSUE TITLE
breadcrumbs (from redesign)

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#4]
Definition of breadcrumbs in the redesign prototype: https://github.com/serlo/serlo.org/blob/17a3847a6666a4f9d82790d2c1babc7585c6a9b5/packages/public/frontend/src/breadcrumb.component.tsx

Prototype in action: https://athene2-blue-gum.netlify.com/?path=/story/example-page--test

**Comment by Entkenntnis** [comment]
#10 
#11
