### ISSUE TITLE
Tests for fetcher

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#401]
@inyono suggested to first have some tests in place before refactoring and finishing types in those places.

(follow up of #382)

**Comment by inyono** [comment]
IMHO, in this order:
- [ ] Add unit tests for all supported page types.
- [ ] Add unit tests for all compat cases.
- [ ] Refactor fetcher types (using @serlo/api + concrete types for every supported page type).

**Comment by inyono** [comment]
Grabbing this as a potential issue for Caro (at least the unit tests).

**Comment by Entkenntnis** [comment]
There is some work going on in #429, maybe Caro likes to take this over?

**Comment by inyono** [comment]
We'll see. But as far as I understood #429, you didn't want to write tests in this PR, right?

**Comment by Entkenntnis** [comment]
We have `yarn test` now.
