### ISSUE TITLE
This taxonomy page is not loading

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#402]
https://de.serlo.org/mathe/zahlen-und-groessen/grundrechenarten/ 
results in `Error while fetching data: Cannot read property 'path' of null`
([source](https://de.serlo.org/api/frontend/mathe/zahlen-und-groessen/grundrechenarten/))

**Comment by Entkenntnis** [comment]
https://de.serlo.org/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten is loading. Where have you found the link?

And this is also loading: https://de.serlo.org/mathe/zahlen-groessen/grundrechenarten

**Comment by Entkenntnis** [comment]
Edit: ~~Ok, but it is definitively also a bug in the fetcher~~

**Comment by elbotho** [comment]
@Entkenntnis woah, interesting! Just clicked on it somewhere in the content. Unfortunately can't find the article again. Damn I thought the taxonomy entry itself was the problem. So probably an error in the content, but I will keep this open for the fetcher bug?

**Comment by Entkenntnis** [comment]
After some investigation, the error happens already on API side.

**Comment by inyono** [comment]
> After some investigation, the error happens already on API side.

Namely?

**Comment by Entkenntnis** [comment]
It results in this error message: https://github.com/serlo/frontend/pull/420#discussion_r461637014

**Comment by elbotho** [comment]
closing this, works now and problem is tracked here: https://github.com/serlo/api.serlo.org/issues/50
Thanks guys!
