### ISSUE TITLE
Differentiate error types [api]

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#403]
Always failing with 404 is misleading for users and possibly search engines.

**Comment by Entkenntnis** [comment]
@elbotho Could you give same example of possible other error codes? The only error code I know is 500.

**Comment by inyono** [comment]
Off the top of my head (feel free to extend):
- 404 only if the page really doesn't exist
- 500 if renderer throws an unexpected error (+ log via Sentry)
- 301 if we redirected (e.g. stale alias, or /:id)
- 401 resp. 403 in the future when the user is required to be logged in / hasn't the needed rights.

**Comment by elbotho** [comment]
If we want more: https://de.wikipedia.org/wiki/HTTP-Statuscode#4xx_%E2%80%93_Client-Fehler

But I think the most important distinction for the users are:
client:
- Is the content not there? (404)
- Is the content not available for me? (401/403)
server:
- Is the server having a (probably) temporary problem (eg. api unresponsive)? (502/503/504)
- Is there an error that probably takes some time to fix or is unknown?(i guess 500)

And we should definitely implement 418!

**Comment by Entkenntnis** [comment]
OK, this sounds good. The first step useful step would be to separate 404 errors from 50X errors. Would need some investigation how to detect this from the API-Response, but it's doable.

**Comment by Entkenntnis** [comment]
#419 is an attempt to improve this.

**Comment by Entkenntnis** [comment]
If some request is failing, e.g. alias not existing, than the data in this line is null:

https://github.com/serlo/api.serlo.org/blob/0f512ab809301777e890b5264b51cc8b50fbc1ae/src/graphql/data-sources/serlo.ts#L291

This will lead to a very generic `property ... of null is undefined...` exception further down in the code. If would be great if the server would throw an error with a clear message, like: requesting this path failed

**Comment by elbotho** [comment]
~@Entkenntnis probably worth an issue in https://github.com/serlo/api.serlo.org~

This is probably the same as https://github.com/serlo/api.serlo.org/issues/50, right?

**Comment by Entkenntnis** [comment]
4b7a7741f0ee7c4efe02aa5f5cb33e1a921c7657 now handles 404 from the API properly.
