### ISSUE TITLE
Tests and types for convert-edtr-io-state

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#404]
Follow up of #382.

IMHO, in this order:
- [x] Add unit tests for all supported plugins / frontend nodes.
- [x] Add unit tests for all compat cases.
- [ ] Refactor types (using Edtr.io types).
- [x] Refactor types (use concrete types for every supported frontend node)

**Comment by inyono** [comment]
Grabbing this as a potential issue for Caro (at least the unit tests).

**Comment by Entkenntnis** [comment]
edtr-io integration is not part of the current milestone. Let's revisit this on the next milestone.

**Comment by inyono** [comment]
Just for clarification: this is prerequisite work for any "major" changes to the converter, independent of Edtr.io integration. I'm fine with delaying this as long as we don't have any major changes in the current milestone.

**Comment by elbotho** [comment]
Ah sorry, didn't see the grab and was eager to hone my new testing skills ;)

**Comment by Entkenntnis** [comment]
Off-topic: Best issue number of all.

**Comment by Entkenntnis** [comment]
Follow up in #552.
