### ISSUE TITLE
Link to Exercise in topicFolder

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#410]
Allow users in a topic folder to view an exercise separately.

**Comment by inyono** [comment]
What's the reasoning behind this?

**Comment by Entkenntnis** [comment]
With this one addition, users can share single exercises with our existing share modal.

**Comment by elbotho** [comment]
we try to have as little hidden submenus as possible and want to try to only offer editing/sharing options for exes in "single view"
