### ISSUE TITLE
Improve breadcrumbs

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#415]
As suggested in https://github.com/serlo/frontend/issues/92#issuecomment-620837363, there are two possible improvements to the breadcrumbs:

- [x] Don't highlight parent element in breadcrumbs on taxonomy page.
- [x] Highlight breadcrumbs on content page more: Put into new line and add back arrow icon:

![grafik](https://user-images.githubusercontent.com/13507950/88551495-36cc1a80-d023-11ea-9949-74b790ae8128.png)

This could be worth a draft.

**Comment by elbotho** [comment]
@Entkenntnis didn't you do something here in the last days?

**Comment by Entkenntnis** [comment]
I've refactored some code, but haven't added this feature.

**Comment by elbotho** [comment]
Implemented with some other changes in #431.
Opted not to put the Button in a new line, because imo it's harder to understand the structure this way.
