### ISSUE TITLE
Ensure keyboard navigation

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#416]
Make the frontend accessible with keyboard: Check that every interactive element has a tabindex and the action can be triggered with the keyboard (enter key down). Also make sure that outline is visible.

Issues:

- [x] User Tools are not accessible (mobile and desktop version)
- [ ] 'hide solution' button has no outline
- [x] check share menu
- [x] check all content types

**Comment by elbotho** [comment]
we should use `tabindex` only when it's really necessary to change to default order.

**Comment by Entkenntnis** [comment]
But it's ok to use `tabIndex={0}` to add elements into the tab order, right? (e.g. spans that are used as buttons).

**Comment by elbotho** [comment]
Right! 
Even though we should try to avoid that and use an `<button>` instead :)

**Comment by elbotho** [comment]
Some docs:
- https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#Building_keyboard_accessibility_back_in
- https://developer.mozilla.org/en-US/docs/Learn/Accessibility/CSS_and_JavaScript

**Comment by elbotho** [comment]
@Entkenntnis 
> 'hide solution' button has no outline
Can't reproduce, got a link/screenshot?

**Comment by Entkenntnis** [comment]
Ok, the hid solution button has a outline now in #432
