### ISSUE TITLE
serlo.org/beitreten does not render if visited from homepage.

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#424]
If you are on the homepage and click on the button "Mitglied werden" you get forwarded to https://de.serlo.org/beitreten. This site does forward to the google-survey if visited directly, but gives a 404-error if visited via the button on the homepage.

**Comment by inyono** [comment]
@Entkenntnis Probably need to disable CSR for that URL.

**Comment by elbotho** [comment]
@jakobwes thank you for reporting, fix will be online soon!
