### ISSUE TITLE
Cookie Banner needs two clicks to disappear

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#428]
Accepting the cookie banner takes two clicks.

**Comment by elbotho** [comment]
I def. had this, but can't reproduce now.
Can you reproduce it right now?

**Comment by Entkenntnis** [comment]
I'll try to document the steps if I encounter this the next time (or if you see it again). Its weird because its not always happening ...

**Comment by Entkenntnis** [comment]
My steps to reproduce this: Delete consent from localstorage, start dev server and visit landing page. Then it takes to clicks to close the cookie banner.

Is not happening in #428 anymore.
