### ISSUE TITLE
Video injections broken

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#452]
See https://de.serlo-staging.dev/mathe/zahlen-groessen/bruchrechnen-dezimalzahlen/brueche/brueche:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1508477/89875111-1c667500-dbbd-11ea-8cb0-da583d08cd70.png">

(btw: the other two injections are math puzzles and it's currently fine that they fail)

**Comment by Entkenntnis** [comment]
Traced the problem down to this:

![grafik](https://user-images.githubusercontent.com/13507950/90000943-1641c880-dc91-11ea-8b54-11fc78ac27f9.png)

On production, I get the correct url.

**Comment by inyono** [comment]
Might be a bug in the API, then. Going to investigate.

**Comment by inyono** [comment]
Well, this is fixed in staging but the wrong values are still cached. For improved loading times in Dev, I don't want to purge the cache again. This will soon be solved by https://github.com/serlo/api.serlo.org/issues/41
