### ISSUE TITLE
Review assets

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#453]
Importing from `public/_assets` doesn't make sense since imports will be handled by Webpack. So either add assets to `public/_assets` and use them via absolute url or import them from somewhere in `src/`

Also: especially small SVGs can be React components (so we don't have the overhead of another HTTP request), see e.g. https://github.com/gregberge/svgr.

**Comment by Entkenntnis** [comment]
yes, mainly svg files

**Comment by elbotho** [comment]
That's what I'd so:

- We currently use `@svgr/webpack` for many svgs. So for them we should create a e.g. `/src/files` folder.
- Also our font css are `imported` from `/public` so we _could_ also move them out of there (but in this case I'd leave them to have all the font stuff in one place and they are tiny)
- There are also some SVGs that we directly access via their urls in `/public/_assets` or the old serlo-org static assets. Here I'd check if it makes sense to move them to `/src/files` and import them via svgr as well.

Does that make sense @inyono?

**Comment by inyono** [comment]
Yes, except maybe the second one:
- Can we also import the font families (in the CSS we import) so that we can move the fonts together into `src/fonts` or something?

**Comment by inyono** [comment]
Actually, if I understand https://webpack.js.org/guides/asset-management/#loading-fonts correctly, this should already be the case, i.e. the fonts should already be processed by webpack, anyways.

**Comment by elbotho** [comment]
nice, will test.
thanks!
