### ISSUE TITLE
Review meta images

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#454]
Doesn't seem like we return the correct meta image at the moment. E.g. https://frontend.serlo.org/api/frontend/1855 returns the global serlo meta image (instead of math meta image) although the article is in subject math. According to our tests in https://github.com/serlo/frontend/blob/8031617813237d9cc8a7bb797e7db776c9c473b6/__tests__/serlo-api.ts, it seems like only `Course` is handled correctly.

**Comment by Entkenntnis** [comment]
can confirm, this is a bug in the fetcher: https://github.com/serlo/frontend/blob/0a7cccbcc83d79ffd2c9d931122ba095dce62464/src/fetcher/fetch-page-data.ts#L71

`alias` -> `uuid.alias`

(also affects the cache key two lines above)

**Comment by Entkenntnis** [comment]
fixed by https://github.com/serlo/frontend/commit/dff06423c99d09710666df1c42d8b012d86b9e1b
