### ISSUE TITLE
Check if user has subscribed content [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#458]
The author menu needs to know if a user has subscribed an entity or not, this would be a separate API request.

Do we already have something for that?

**Comment by inyono** [comment]
Nope, subscriptions aren't exposed via api.serlo.org, yet.

**Comment by inyono** [comment]
https://github.com/serlo/api.serlo.org/issues/54

**Comment by Entkenntnis** [comment]
Update: We can now get a list of all subscribed contents with

```gql
{
  subscriptions{
    nodes {
      id
    }
  }
}
```

**Comment by Entkenntnis** [comment]
@kulla 
This is working, but I was wondering about the caching: If I add new subscription, when can I expect it to show up?

**Comment by kulla** [comment]
> @kulla
> This is working, but I was wondering about the caching: If I add new subscription, when can I expect it to show up?

When https://github.com/serlo/serlo.org/issues/514 got implemented -> after the subscription the cache will be updated. Currently there is no update. However with https://github.com/serlo/api.serlo.org/pull/115 we have an update in the background each hour.

**Comment by Entkenntnis** [comment]
follow up in #647
