### ISSUE TITLE
Use mutations to trash/restore content [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#459]
Currently, the trash menu entry is a form that makes a POST request. Should we replace this button with a graphql mutation?

**Comment by inyono** [comment]
Yep, definitely.

**Comment by inyono** [comment]
https://github.com/serlo/api.serlo.org/issues/53

**Comment by Entkenntnis** [comment]
Interim solution with 02a252556ce6f51405e12e57c1de5e58e84f7c97, using CSRF token from cookie, so we can lower the priority of this.

**Comment by Entkenntnis** [comment]
The linked PR is merged and it's available in staging, so I think we can start working on this.

**Comment by elbotho** [comment]
Had a go at this, but mutation does not work at this point.
>Error: 404: Not Found: {"response":{"errors":[{"message":"404: Not Found","locations":[{"line":4,"column":13}],"path":["uuid","setState"],"extensions":{"code":"INTERNAL_SERVER_ERROR","response":{"url":"http://de.serlo.localhost/api/set-uuid-state/188292","status":404,"statusText":"Not Found","

Will probably wait for https://github.com/serlo/api.serlo.org/pull/189 and check again.

**Comment by elbotho** [comment]
Follow up in #853
