### ISSUE TITLE
Adapt Design Template for Comments

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#466]
We have a design template located here: https://github.com/serlo/athene2-blue-gum/tree/master/src/comments

There is a rough prototype for comments in the frontend, you can view it e.g. here: https://frontend-git-comments-ui.serlo.vercel.app/physik

It would be great if we can extract the relevant styles and implement them in the frontend.

**Comment by elbotho** [comment]
ping @Entkenntnis 
Okay, moved design. 
Functionality need some work, but it's probably useful to wait and see how the API will work.

- we also wait for #472
- and translations could be done.
