### ISSUE TITLE
Author Menu: Show entries depending on role [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#472]
The Author Menus are complete now (all possible entries are visible).

The next step is to hide all entries (also in user tools) that are not accessible to less priviledged users. The only additional information necessary is the role of the user.

**Comment by elbotho** [comment]
Menu in the comments also needs this info.

**Comment by Entkenntnis** [comment]
Let's collect this information in a document:

https://docs.google.com/document/d/1WVES9v9rlWjMB-NXAeO4ZOxJ3EbEbt1H254D4bpkLrE/edit?usp=sharing

**Comment by elbotho** [comment]
@Entkenntnis could you list what needs to happen to make this work?

**Comment by Entkenntnis** [comment]
Serlo.org issue: https://github.com/serlo/serlo.org/issues/451

@inyono can probably give more information about this.

**Comment by elbotho** [comment]
User roles will be provided via auth (@inyono will add this) but we can get started on the code to adapt the menus.

**Comment by elbotho** [comment]
possible roles, would suggest following strings for now:
``` js
['guest','login','moderator','reviewer','taxonomy-manager','page-builder','admin','sys-admin']
```

note: multiple roles possible!

**Comment by inyono** [comment]
Looks good at first glance. Please add an enum for that so we can easily change that later.

**Comment by Entkenntnis** [comment]
We plan to add an API query to get the list of permissions
todo: link related issue

**Comment by Entkenntnis** [comment]
Another update: We plan to use a npm package that provides a interface to query permissions. This way, the frontend doesn't need to know the actually implementations.

**Comment by Entkenntnis** [comment]
All permissions are available now.
