### ISSUE TITLE
Error 500 when loading this ex group

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#489]
https://de.serlo.org/mathe/funktionen/ableitung-funktionen/produktregel,-quotientenregel-kettenregel/aufgaben-quotientenregel
works on localhost and [staging](https://de.serlo-staging.dev/mathe/funktionen/ableitung-funktionen/produktregel,-quotientenregel-kettenregel/aufgaben-quotientenregel).

**Comment by Entkenntnis** [comment]
This bug is fixed by #467, which causes some exercises with empty prerequisites to throw a graphql error. The link will work after the next deployment.
