### ISSUE TITLE
Load text exercises with new frontend  [cf-worker]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#490]
On staging, currently all exercises are loaded with the legacy backend, e.g. https://de.serlo-staging.dev/mathe/funktionen/ableitung-funktionen/tangente-normale/aufgaben-tangente/13799

@kulla Could you please take a look at this and update the cloudflare worker? Thanks!

**Comment by Entkenntnis** [comment]
Localhost is not affected, but #410 will not work on staging (yet).

**Comment by elbotho** [comment]
should work because of CSR, but I'll create a PR in minute so we can test.

**Comment by Entkenntnis** [comment]
This occurs if you are editing exercises: If you switch from legacy system (e.g. editor) to an exercise, the exercise is shown in the legacy system.

But you have a point: If we are using CSR, this will not happen.

**Comment by kulla** [comment]
The type `Exercise` is not in the list of allowed types for the frontend. See https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/wrangler.toml#L41

@Entkenntnis What is the current list of types which are supported?

**Comment by Entkenntnis** [comment]
We can add Exercise and ExerciseGroup to the list of allowed types, they are fully supported now.

Maybe we can test it on staging?

**Comment by elbotho** [comment]
a little aside, but I thought its interesting what other types are therefore not supported atm:
With your addition @Entkenntnis that leaves:
- Event (✔️ )
- GroupedExercise (✔️ )
- Solution (in progress ✔️ ))
- User _(#476 )_

and the revisions: AppletRevision, ArticleRevision, CourseRevision, CoursePageRevision, EventRevision, ExerciseRevision, ExerciseGroupRevision, GroupedExerciseRevision, PageRevision, SolutionRevision, VideoRevision

**Comment by Entkenntnis** [comment]
Event and GroupedExercise will work, but are rarely link to. We can add them to the allowed types.

Solutions are not supported.

**Comment by kulla** [comment]
Staging & dev: Event, Exercise, ExerciseGroup

**Comment by kulla** [comment]
See https://github.com/serlo/serlo.org-cloudflare-worker/pull/48 for the fix. In Staging and Dev this is already deployed. See 

* Exercise: https://de.serlo-staging.dev/mathe/funktionen/ableitung-funktionen/tangente-normale/aufgaben-tangente/13799
* ExerciseGroup: https://de.serlo-staging.dev/mathe/analysis/ableitung/quotientenregel/6763

**Comment by elbotho** [comment]
if #515 is merged, solutions can be added, too.

**Comment by Entkenntnis** [comment]
@kulla Can you also add `GroupedExercise` to staging for the moment? Thanks! (e.g. https://de.serlo-staging.dev/mathe/geometrie/dreiecke,-vierecke,-kreise-andere-ebene-figuren/kreise-kreisteile/aufgaben-kreisen-kreisteilen/54749/54799)
