### ISSUE TITLE
Submit comments [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#493]
The new comments UI will use a graphql mutation to submit new comments.

**Comment by elbotho** [comment]
this got merged: https://github.com/serlo/api.serlo.org/pull/166

**Comment by elbotho** [comment]
(leaving this open since it's implemented, but api endpoint will change soonish and legacy endpoint does not work atm)

**Comment by Entkenntnis** [comment]
Waiting for https://github.com/serlo/api.serlo.org/issues/191

**Comment by elbotho** [comment]
This is more or less done in the Frontend.
Sorting will be fixed soon: https://github.com/serlo/api.serlo.org/pull/233
Performance would hopefully be ok in production and soonish even in staging: https://github.com/serlo/serlo.org-database-layer/pull/67

**Comment by elbotho** [comment]
Okay, comments work pretty nicely. 
Ordering is fixed in API.
Threads are for some reason very slow. But work as well.
🎉

**Comment by elbotho** [comment]
Now uses db layer - much better response time! 🚀
