### ISSUE TITLE
Tools for logged in users

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#5]
In the current dropdown menu the following items are missing:

* Subscribe
* History
* Log
* Manage related items

These are only relevant for logged in users. Where shall we add them?

![2020-03-11-193725_208x247_scrot](https://user-images.githubusercontent.com/1327215/76451695-1848e800-63d0-11ea-9c72-70ca44c9c85e.png)

**Comment by elbotho** [comment]
I'd planed one something like this: 
![image](https://user-images.githubusercontent.com/1258870/77779568-0794a500-7053-11ea-9d50-1b1b59d59243.png)

A small menu only visible for logged-in users on larger screens below the header to the right of the content.
But now that I think about it:
Another button below "Teilen!" it would probably be nicer and way easier to implement.
Something like "Tools" that opens another Modal or Dropdown.

**Comment by kulla** [comment]
> I planned something like this:
> ![image](https://user-images.githubusercontent.com/1258870/77779568-0794a500-7053-11ea-9d50-1b1b59d59243.png)
> 
> A small menu only visible for logged-in users on larger screens below the header to the right of the content.
> But now that I think about it:
> Another button below "Teilen!" it would probably be prettier, easier to implement and functional enough.
> Something like "Tools" that opens another Modal or Dropdown.
> 
> @kulla what do you think?

Yes, another button below "teilen" would be the best solution, I guess... :-)

**Comment by Entkenntnis** [comment]
closing this for the moment, because features for logged in users are very low prio now
