### ISSUE TITLE
Show button "neuen Inhalt hinzufügen" only on the lowest topic level

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#502]
We want articles, course, etc. only to be created in the "topic" which is on the lowest taxonomy level. 
We want exercises and exercise-groups only to be created in a topic folder. 

Thus it would be nice to have the corresponding buttons shown only in the respective folders.

**Comment by elbotho** [comment]
@yolo-bird or @kathongi:
Just to be sure I understand it correctly.
_Only_ in topic (topic or curriculumTopic) we show:
- Artikel
- Kurs
- Video
- Applet
- Ereignis

_Only_ in folders (topicFolder and curriculumTopicFolder)
- exercises 
- exercise-groups

Therefore there are no content types to add anythere else. 
So e.g. on `/mathe` there is option in the menu to add new content entities.

Correct so far?

--- 

What about the second level (like `/mathe/zahlen-gr%C3%B6%C3%9Fen`).
This is a `topic` so authors could add articles, is this correct?

**Comment by kathongi** [comment]
Almost right. The button to create events/Veranstaltung should only be showed in /community. (If possible more specific only in /community/veranstaltungen)

--- 
It's also correct that authors could add articles etc. at the second level. That's fine.

**Comment by kathongi** [comment]
> So e.g. on /mathe there is option in the menu to add new content entities.

What option do you mean?

![image](https://user-images.githubusercontent.com/44167220/91829825-3c300c80-ec42-11ea-8d7b-f0f0e6fd1592.png)

**Comment by elbotho** [comment]
@kathongi thanks!
Sorry about the last one, that way a typo. No option to add anything on `/mathe`. Check.
Added special case for Events. On `de.serlo.org` they will only be visible on `/community/veranstaltungen` and only inside of `/community` for other languages.

**Comment by ghost** [comment]
Just a quick note:
@elbotho regarding your first post. This is almost correct except for curriculum topic folders. 

Actually the only subelements there should be topic and topic folders.
