### ISSUE TITLE
Topic folders not visible in frontend

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#504]
The page https://frontend.serlo.org/mathe/deutschland/bayern/mittelschule/klasse-8/regelklasse/prozentrechnung is empty, but should show four topic folders, e.g. https://frontend.serlo.org/mathe/deutschland/bayern/mittelschule/klasse-8/regelklasse/prozentrechnung/aufgaben-promillerechnung

**Comment by Entkenntnis** [comment]
It's visible in on staging, though.

**Comment by Entkenntnis** [comment]
If I add or edit elements in "Baumstruktur bearbeiten", then they are not visible, even after several reloads.

Workaround: Edit taxonomy term once, save, then changes are visible.

**Comment by inyono** [comment]
This was fixed in serlo.org recently. Depends on a newer API version, though, so this is only live in dev/prod.
