### ISSUE TITLE
Adding new topics in "Baumstruktur bearbeiten" not visible [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#509]
If I add or edit elements in "Baumstruktur bearbeiten", then they are not visible, even after several reloads.

According to https://github.com/serlo/frontend/issues/504#issuecomment-678795217, this should work in development and production, but unfortunately its still an issue on staging.

Keep this issue as an reminder and close it when its working on staging.

**Comment by Entkenntnis** [comment]
Related fix in serlo.org: https://github.com/serlo/serlo.org/commit/2d4d5163a19069e127842730d4a1be31ee80649f

**Comment by Entkenntnis** [comment]
Now we have SWR in the API, and https://de.serlo.org/mathe/deutschland/bayern/realschule/abschlusspr%C3%BCfungen-l%C3%B6sung,-zweig is finally showing the entry for 2020, thanks for this fix. :tada: 

I am wondering why this is not working on staging: https://de.serlo-staging.dev/mathe/deutschland/bayern/realschule/abschlusspr%C3%BCfungen-l%C3%B6sung,-zweig is missing 2020, regardless of how often I reload the page :face_with_head_bandage:

**Comment by elbotho** [comment]
@Entkenntnis If it helps: I can see it in production:
https://de.serlo.org/mathe/deutschland/bayern/realschule/abschlusspr%C3%BCfungen-l%C3%B6sung,-zweig

**Comment by inyono** [comment]
It's visible now. The `maxAge` is rather long at the moment. It worked in production earlier because I purged some of the cache for other reasons.

**Comment by Entkenntnis** [comment]
Changing priority, updated issue: #645
