### ISSUE TITLE
Lots of 500 errors

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#513]
I often discover 500 errors while testing. 
Also I found a lot of them while checking the pages where #359 (or to be more exact [FRONTEND-6](https://sentry.io/organizations/serlo/issues/?groupStatsPeriod=14d&project=5206333&query=is%3Aunresolved&statsPeriod=14d)) occurs. 
I'm not quite sure how they relate, but it seems odd how many of the pages turned out to be 500ers. 

I checked some and they seem to work on staging, so maybe this is already fixed or … SW?

[Example](https://de.serlo.org/mathe/zahlen-gr%C3%B6%C3%9Fen/proportionalit%C3%A4t-dreisatz/gemischte-aufgaben-proportionalit%C3%A4t-dreisatz), [Example](https://de.serlo.org/mathe/sonstiges/zahlensysteme/zahlensysteme)

Here is the list: https://docs.google.com/document/d/1mluAH8u_ev2Hy8whghYieh9Dg1i8dl1nt9iX-2FUp6Q/edit?usp=sharing

This issue is too keep track of this.

Also I think we could really use a list of urls that return 500 errors. Is there an easy way to have them listed in sentry?

(ping @Entkenntnis)

**Comment by Entkenntnis** [comment]
#464: most tables resulted in 500, fixed (in staging). If you look at https://de.serlo.org/api/frontend/mathe/sonstiges/zahlensysteme/zahlensysteme, you see "Error while fetching data: Cannot read property 'text' of undefined"

#467: solutions that has an empty prereq id resulted in 500, fixed in staging. If you look at the API route there is a graphql validation error.

**Comment by elbotho** [comment]
Okay, with the new updates live we could reduce the list quite a bit 😄 

Those three are currently left:

**`Error while fetching data: Syntax Error: Cannot parse the unexpected character \"/\".`**
- https://de.serlo.org/mathe/deutschland/bayern/mittelschule/klasse-6/fl%C3%A4cheninhalt---oberfl%C3%A4cheninhalt-quadern/aufgaben-oberfl%C3%A4che-volumen-w%C3%BCrfel-quader
- https://de.serlo.org/mathe/zahlen-gr%C3%B6%C3%9Fen/prozent--zinsrechnung/aufgaben-prozentdarstellung


**`Error while fetching data: GraphQL Error (Code: 413): …Payload Too Large… `**
- https://de.serlo.org/mathe/funktionen/wichtige-funktionstypen-eigenschaften/polynomfunktionen-beliebigen-grades/aufgaben-polynomfunktion

**Comment by inyono** [comment]
Also: https://de.serlo.org/mathe/funktionen/wichtige-funktionstypen-eigenschaften/lineare-funktionen---geraden

**Comment by Entkenntnis** [comment]
@elbotho Your three links are fixed by #526 
@inyono I have opened a separate issue for your link (#525)
