### ISSUE TITLE
Implement `Solution`

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#514]
As in #513 I discovered those via sentry.

https://de.serlo.org/mathe/universitaet/grundlagen-mathematik/relationen/aequivalenzrelationen
- injection /56990 _(▾ Verständnisfrage: Wie viele lineare Äquivalenzrelationen auf einer Grundmenge MM gibt es?)_
- injection /57015 _▾ Beweis: (Äquivalenzrelationen induzieren eine Zerlegung)_
- injection /57020 _▾ Beweis: (Jede Zerlegung induziert eine Äquivalenzrelation)_ 

All fail with `{"kind":"error","errorData":{"code":200}}`
e.g. https://frontend.serlo.org/api/frontend/de/57020

does happen in staging

---

~https://de.serlo.org/mathe/stochastik/grundbegriffe-methoden/baumdiagramm-vierfeldertafel/vierfeldertafel~
~injection /21332 (bottom _▾ Weitere Übungsaufgaben_)~
~error: https://frontend.serlo.org/api/frontend/de/21332~
~`{"kind":"error","errorData":{"code":500,"message":"Error while fetching data: Cannot read property 'text' of undefined"}}`~
~does not happen in staging~
(should be fixed in staging #464)

**Comment by elbotho** [comment]
might be because api does not allow the frontend to load grouped exercises?
#490

**Comment by Entkenntnis** [comment]
Hm, these injections are failing because the are not matching any knowing type:

https://github.com/serlo/frontend/blob/cf6f565e0a9fed5f582036dd2207c60150a6fa36/src/fetcher/fetch-page-data.ts#L341

@elbotho Could you look at the uuid and see what's happening? Maybe its a new, unknown content type?

**Comment by elbotho** [comment]
:D okay, we found type `Solution` in the wild. 
Don't know how often that happens, but we should probably just implement it I guess.
What do you think @Entkenntnis ?

**Comment by Entkenntnis** [comment]
Ah, makes sense, yes, we should just implement them.

**Comment by inyono** [comment]
Hm... I'm not sure if we want to support that, to be honest. The linked example is definitely an anti-pattern. There should be no reason to inject the solution itself (without the exercise) and instead of an extra view for the solution, we can just redirect to the exercise itself.

**Comment by Entkenntnis** [comment]
I have asked @kathongi what she thinks about it.

**Comment by Entkenntnis** [comment]
Result: We don't need to inject solutions, because there are other possibilities to achieve the same effect, e.g. injecting the exercise and removing the spoiler, etc..

I will adapt #515 for this.
