### ISSUE TITLE
License-information leads to "Schwerwiegender Fehler" or 500 error

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#520]
In es.serlo.org the "Informacion"-button for the license under an article redirects to https://de.serlo.org/license/detail/14 where "Ein Schwerwiegender Fehler ist aufgetreten" is shown. Also in the german-version it the button leads to https://de.serlo.org/license/detail/1 what gives out a 500-error

**Comment by elbotho** [comment]
thanks for reporting.
Relates to #518. 

es license link should probably target https://es.serlo.org/license/detail/14 that kind of works (no content, but side loads).
