### ISSUE TITLE
improve timeago i18n

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#531]
Find a solution for react timeago to dynamically load only language info for current instance. At the moment I just import all the language files. ~and build into reusable component. Currently we use it for comments, notifications and revisions.~

**Comment by elbotho** [comment]
@Entkenntnis do you have an idea how we should approach this?

**Comment by Entkenntnis** [comment]
Not really, yet. The language file consists of js-function, so we can't pass it around as json. Maybe we can use the async `import()` statement to handle this? https://webpack.js.org/api/module-methods/#import-1
