### ISSUE TITLE
Anchor and Mailto links break 

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#537]
Visit https://frontend.serlo.org/mathe/geometrie/dreiecke,-vierecke,-kreise-andere-ebene-figuren/kreise-kreisteile/berechnungen-kreis

Click on one of the links.

Expected: Page jumps to position.

Actual: 500 Error Page.

**Comment by elbotho** [comment]
link to mailto:de@serlo.org also results in 500

**Comment by elbotho** [comment]
mailto fixed in 4d1ff3b …
