### ISSUE TITLE
Alias with special characters (%, &, +) are broken [cf]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#546]
~~An ampersand in the alias is causing pages to break. Investigate where this can be fixed, e.g. api, cf-worker or frontend.~~

Update: Special charaters are not encoded by the API (other characters are encoded). This causes problems with the frontend and the url that the cloudflare worker redirects to.

Broken URLs:
~~https://de.serlo-staging.dev/chemie/stoffe-&-stoffeigenschaften/stoffeigenschaften/optische-aktivit%C3%A4t~~ (title changed to "Stoffe und Stoffeigenschaften")
~~https://de.serlo-staging.dev/chemie/stoffmenge/stoffmenge-&-mol/mol~~ (title changed to "Stoffmenge und Mol")

https://de.serlo-staging.dev/153302 -> https://de.serlo-staging.dev/community/blog-beitr%C3%A4ge-(archiv)/2014-06-29-f%C3%B6rderung-hans-sauer-stiftung-&-zeidler-foschungs-stiftung :zap: 

https://de.serlo-staging.dev/154087 -> https://de.serlo-staging.dev/community/blog-archiv/2013-10-01-scrum-entwicklung-form-&-code :zap: 

https://de.serlo-staging.dev/146991 -> https://de.serlo-staging.dev/mathe/deutschland/bayern/realschule/jahrgangsstufentest-8.-klasse/2018/zweig-ii+iii :zap: 

https://de.serlo-staging.dev/170950 -> https://de.serlo-staging.dev/mathe/deutschland/bayern/realschule/jahrgangsstufentest-8.-klasse/2019/zweig-ii+iii/171662 :zap: 

In general, the API should also encode these characters.

**Comment by Entkenntnis** [comment]
Ok, the API is currently returning unescaped aliases (it should encode it according to https://github.com/serlo/frontend/pull/288, but it isn't in the staging).

The cloudflare-worker is therefore redirecting to an not-encoded URL and as soon as a special character is encountered (&, +), the frontend gets a broken alias.

This is unfortunately breaking a lot of pages, e.g. https://de.serlo-staging.dev/mathe/deutschland/bayern/realschule/jahrgangsstufentest-8.-klasse/2019/zweig-ii+iii/171662

**Comment by Entkenntnis** [comment]
Update: Umlaute are encoded and working.

**Comment by kulla** [comment]
@Entkenntnis Do you expect the alias in the frontend to be decoded or not decoded? In api.serlo.org I have added code like https://github.com/serlo/api.serlo.org/compare/decode-path-catch-error?expand=1#diff-a64e0f65b8c72d89b36834c8d75d8032R23-R32 so that it works regardless whether the legacy systems returns encoded or not encoded strings...

**Comment by Entkenntnis** [comment]
I would expect the API to encode the alias, e.g. & -> %26, + -> %2B

The cloudflare worker should then also redirect to an encoded path, then the frontend should render the page properly.

**Comment by kulla** [comment]
I have found the bug: https://community.cloudflare.com/t/possible-bug-new-url-changes-url-by-decoding-2b-and-26/214961 (which is a bug in the cloudflare worker)

**Comment by kulla** [comment]
@Entkenntnis At staging and development there is a fix online. Can you test it? See for example

* https://de.serlo-development.dev/153302
* https://de.serlo-development.dev/154087

**Comment by Entkenntnis** [comment]
Thank you, looks good!

**Comment by Entkenntnis** [comment]
The links in this issue are still loaded from the old alias system. I would expect them to change to the shorter version.

**Comment by inyono** [comment]
This is the case (modulo caching), see also the API responses that report the correct alias, e.g.:
- https://de.serlo-staging.dev/153302 -> https://de.serlo-staging.dev/community/153302/2014-06-29-f%C3%B6rderung-hans-sauer-stiftung-zeidler-foschungs-stiftung
- https://de.serlo-staging.dev/154087 > https://de.serlo-staging.dev/community/154087/2013-10-01-scrum-entwicklung-form-code

**Comment by kulla** [comment]
> The links in this issue are still loaded from the old alias system. I would expect them to change to the shorter version.

The fix of @inyono overwrite my fix for this issue I still work on. Now I have finished my PR and staging has the fix of inyono from today + the fix of this PR. Links like https://de.serlo-staging.dev/153302 now work as expected.

**Comment by Entkenntnis** [comment]
Thank you two! It's working now.

**Comment by kulla** [comment]
Let's wait until the PR got merged into master :smiley:
