### ISSUE TITLE
Taxonomy Topic

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#55]
https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras

![grafik](https://user-images.githubusercontent.com/13507950/78389875-ce74ab80-75e3-11ea-8372-de7646b39274.png)

Props:

title: string
description: ReactComponent
courses: Link[]
article: Link[]
...

Link has title und url

**Comment by Entkenntnis** [comment]
The same component should also be able to be displayed in "compat mode" like here https://de.serlo.org/mathe/geometrie: 

![grafik](https://user-images.githubusercontent.com/13507950/78390196-77bba180-75e4-11ea-9d41-adb45bccf0ff.png)

**Comment by Entkenntnis** [comment]
The categories are: course, article, video, applet, exercise and folder (see image below):

![grafik](https://user-images.githubusercontent.com/13507950/78390393-c5380e80-75e4-11ea-8b89-aee658f945e7.png)

**Comment by Entkenntnis** [comment]
Here my draft how the input might could like:

```tsx
interface Link {
  title: string
  url: string
}

interface Topic {
  title: string
  description: React.Component
  subfolders: Topic[]
  courses: Link[]
  articles: Link[]
  videos: Link[]
  applets: Link[]
  excercises: Link[]
}
```

**Comment by theMetalkate** [comment]
cool thanks for the overview 👍
