### ISSUE TITLE
Fix display of "Lösungsplan"

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#555]
https://de.serlo.org/mathe/funktionen/anwendungszusammenh%C3%A4nge-anderes/anwendungsaufgaben-differential--integralrechnung/anwendungsaufgaben-differential--integralrechnung/162734.

Expected (legacy):

![grafik](https://user-images.githubusercontent.com/13507950/92217399-f1a7cd80-ee97-11ea-89ba-c592d359a881.png)

Actual (frontend):

![grafik](https://user-images.githubusercontent.com/13507950/92217437-fa989f00-ee97-11ea-92dc-5b9386024415.png)

**Comment by elbotho** [comment]
content problem, was no real list just looked like one 😉

**Comment by Entkenntnis** [comment]
tricky :grinning:
