### ISSUE TITLE
Translations are missing

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#558]
#533 added some new strings that are (yet) missing, adding them to crowdin should work out.

![grafik](https://user-images.githubusercontent.com/13507950/92240964-bae4ae00-eebd-11ea-8b32-8625e88e65e5.png)

**Comment by elbotho** [comment]
Translated now. PR will be updated soon (any hopefully the merge conflict will disappear :)

(sidenode: it's expected behaviour. New features have to wait in staging to be translated before merging currently.)

**Comment by elbotho** [comment]
Merged new german translations
