### ISSUE TITLE
Redirection to solution while editing

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#569]
If you are editing a solution, e.g. https://de.serlo-staging.dev/entity/repository/add-revision/168352, and you save it, you will get redirected to a page with a solution entity. As the frontend is not supporting solutions, this leads to a 404.

Some ideas:

- The cf-worker redirects to the corresponding exercise
- The legacy system is redirection to the exercise directly
- The frontend supports solutions, anyway.

New:

- Don't allow editing an single solution. (remove entry from menu or point to to parent)

**Comment by elbotho** [comment]
imo it should not be possible to just edit an solution anyway. that should solve this problem as well.

**Comment by Entkenntnis** [comment]
@elbotho This sounds like a good idea, I will think about it.
