### ISSUE TITLE
Show User Tools on medium devices

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#575]
Currenty, we show the "Inhalt überarbeiten"-Button and "Weitere Tools" only on large devices. This could be problematic for some medium devices, like tablets or chromebooks, or a split screen on desktops.

I would suggest to show theses two buttons also on medium devices and use the same breakpoint as the main menu.

**Comment by elbotho** [comment]
I agree. Needs some rewriting of `UserTools`.
