### ISSUE TITLE
Fix link for editing pages that are converted

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#578]
Editing e.g. https://de.serlo-staging.dev/chemie points to the old editor, although the content is using edtr-io. The correct link would be https://de.serlo-staging.dev/page/revision/create/24706/162211

**Comment by elbotho** [comment]
currently edit link is fixed to`/page/revision/create-old/${data.id}/${data.revisionId || ''}`
but should be `/page/revision/create/${data.id}/${data.revisionId || ''}`

Should be fixed in 7f9fa6e1f41a98a7415df5265c9a3e2445a8131c
