### ISSUE TITLE
Compat case for nested paragraphs

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#579]
This is happening on https://de.serlo-staging.dev/chemie:

![grafik](https://user-images.githubusercontent.com/13507950/92405125-42882200-f135-11ea-8c6d-03a3f69ff757.png)

(edtr-io, p within p, unnesting would fix layout)

**Comment by elbotho** [comment]
would make layout a bit better – ps within a Li element looks awkward anyway :)

**Comment by elbotho** [comment]
In a66e807 I now don't use the p element when there is any child that is a p. Let's see if that works out.

**Comment by Entkenntnis** [comment]
Works now - and I agree that this looks a bit awkward :grin:
