### ISSUE TITLE
Deleted pages in course get still shown in new frontend

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#585]
Affected course: https://en.serlo.org/community/organise-serlo-community/start-new-language-community/welcome!

If I stay on one of the affected course-pages and log in (switch to new frontend), then it says as it should "content is marked for deletion".

**Comment by Entkenntnis** [comment]
Thank you for reporting this, looks like a bug in our fetcher. We'll investigate this.

**Comment by elbotho** [comment]
okay with cfd43b1 the course navigation gets filtered and all trashed entities that are directly accessed have a warning.
![image](https://user-images.githubusercontent.com/1258870/93071116-fe8aa500-f67f-11ea-85f3-f813cc281b42.png)

**Comment by elbotho** [comment]
@Entkenntnis maybe you can have a look at cfd43b1 was ment as a PR but commited to staging directly.

**Comment by Entkenntnis** [comment]
I noticed that the 'next' - button has some wrong links, e.g. https://en.serlo-staging.dev/community/organise-serlo-community/start-new-language-community/find-first-team-member(s) is skipping page 4 and 5
