### ISSUE TITLE
Optimize print stylesheet

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#589]
Compared with the legacy system, the print stylesheet still needs some optimization (e.g. don't show navigation, don't show hroizon, ...)

**Comment by elbotho** [comment]
Sounded easy, but I realised that with our heavy use of lazy loading (which is a good thing) we have a problem providing this.
e.g. https://stackoverflow.com/questions/43707762/how-to-lazy-load-images-and-make-them-available-for-print

Basically there is not a great way to go about this. We might offer a dedicated printable version using a flag.

**Comment by Entkenntnis** [comment]
Ups, that's a feature that we somehow forgot until now.

I would suggest, that we start with adding some print-media query, e.g. to hide navigation and horizon.

@elbotho: As far as I see, if you scroll through the page once before you print, you will get all content. We can start with show a warning in the print version, like "Please scroll once here before print to include this image."

For the dedicated print-version I would first ask the community how important this feature is and how people use it.

**Comment by elbotho** [comment]
Follow up here: #602
