### ISSUE TITLE
Update InputChallgene

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#590]
The improvements of https://github.com/edtr-io/edtr-io/pull/320 need to be added to https://github.com/serlo/frontend/blob/89666b9a24ccfc36919b1a1193ea515386512e42/src/components/content/exercises/input-exercise.tsx#L50-L74 (unit tests should also be written for this component).

@elbotho @Entkenntnis I want to give this task to one of the new developers in our team so please let this issue open :smile:

**Comment by elbotho** [comment]
@kulla just a reminder that this still exists :)

**Comment by Entkenntnis** [comment]
Another thing: I have forgot to pass the feedback value down to the component. This will be fixed soon (#860) and we can show the feedback that is stored in the exercise.

**Comment by Entkenntnis** [comment]
@kulla Is is ok if we fix this issue now? I don't want to keep this too long around. I think we can surely find some other good first issues in this repo :)

**Comment by kulla** [comment]
> @kulla Is is ok if we fix this issue now? I don't want to keep this too long around. I think we can surely find some other good first issues in this repo :)

Yes of course :-) For the future: It's okay for me when you fix any issue for a community developer when it is older than 2-3 weeks and nothing have been done.
