### ISSUE TITLE
Update fetcher for not existing uuids

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#591]
Follow up when https://github.com/serlo/api.serlo.org/pull/83 got merged (it fixes https://github.com/serlo/api.serlo.org/issues/50): The api returns `{ data: { uuid: null } }` when the uuid does not exist (i.e. a 404 should be shown). This can be implemented in the fetcher. The line https://github.com/serlo/frontend/blob/staging/src/fetcher/fetch-page-data.ts#L44 should not be necessary

**Comment by Entkenntnis** [comment]
follow up of #403

**Comment by elbotho** [comment]
ran into api-errors when requesting unknown paths and certain ids. will test again when https://github.com/serlo/api.serlo.org/pull/83 and https://github.com/serlo/api.serlo.org/pull/84 is merged and deployed.

**Comment by Entkenntnis** [comment]
23e8f0b951b4d3737217ec9a22f2d4b439912ca1 solves this issue
