### ISSUE TITLE
Add support for blockquote plugin

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#594]
The block "Unsere Vision ist freie Bildung, die von einer offenen und unabhängigen Gemeinschaft [...]" is missing in the new frontend, probably a legacy node that we currently do not support.

If it's not too much work, we can add support for this.

**Comment by Entkenntnis** [comment]
de.serlo.org/presse

**Comment by elbotho** [comment]
It's the currently unsupported blockquote plugin.
Should be easy to implement, but I'll start on it after #545 is merged to avoid further conflicts.
