### ISSUE TITLE
Show number of unrevised revisions

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#595]
Follow up when https://github.com/serlo/api.serlo.org/pull/87 is merged: The number of unrevised revisions can be shown for all types implementing `AbstractRepository` (type of `AbstractEntity` like `Article`, `Video`, ... and `Page`):

![grafik](https://user-images.githubusercontent.com/13507950/90784104-2f85ed00-e301-11ea-960e-9b6322083a0e.png)

The api query will be:

```graphql
query {
  uuid(...) {
    ...
    revisions(unrevised: true) {
      totalCount
    }
  }
}
```

**Comment by Entkenntnis** [comment]
@kulla 

I am currently trying this out and have stumbled across an error:

![image](https://user-images.githubusercontent.com/13507950/98116388-7e770380-1ea8-11eb-8c1a-8d72a782a496.png)

Am I doing something wrong here? The article is supposed to have 3 unrevised revisions.

Edit: Adding `(unrevised:true)` leads to the same error message.

**Comment by kulla** [comment]
> Am I doing something wrong here? The article is supposed to have 3 unrevised revisions.

Have you tested it at https://api.serlo-staging.dev/___graphql? There I do not get an error:

![2020-11-06-100613_929x589_scrot](https://user-images.githubusercontent.com/1327215/98347462-b781b600-2017-11eb-8878-36cbc48feefb.png)

**Comment by Entkenntnis** [comment]
Thanks for checking, it now works!

**Comment by Entkenntnis** [comment]
@kulla 
`revisions` is working for 1781 now, but I got an exception again on another article. I have added a revision to de.serlo-staging.dev/1619 just now, and requesting the API is giving a `map of undefined...` exception. :roll_eyes: 

In addition, I have this error (is this related?):

![grafik](https://user-images.githubusercontent.com/13507950/98687508-1a51b500-236a-11eb-81fe-83de82122dc1.png)

**Comment by kulla** [comment]
> `revisions` is working for 1781 now, but I got an exception again on another article. I have added a revision to de.serlo-staging.dev/1619 just now, and requesting the API is giving a `map of undefined...` exception. roll_eyes

I need to investigate it... See https://github.com/serlo/api.serlo.org/issues/119 for tracking it.

> In addition, I have this error (is this related?):

After two hours you need to reload the playground because afterwards the login token expires...
