### ISSUE TITLE
Secondary navigation

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#6]
![2020-03-11-195454_221x456_scrot](https://user-images.githubusercontent.com/1327215/76453039-63fc9100-63d2-11ea-99c1-9bb1f7db284a.png)

**Comment by elbotho** [comment]
Designentwurf – Mobile:
![image](https://user-images.githubusercontent.com/1258870/77892409-e0b4b980-7272-11ea-8c10-85d873127ee0.png)

Sobald genug Platz:
![image](https://user-images.githubusercontent.com/1258870/77892305-b5ca6580-7272-11ea-9701-4da39936b361.png)
