### ISSUE TITLE
Improve printing experience

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#602]
(follow up of #589)

Problems:
- Lazy loaded stuff does not display if user did not scroll
- Link URLs should show as footnotes

Ideas: 
**Try onbeforeprint**
> In the issue I mentioned some "research" I did.
> Even onbeforeprint doesn't look to promising, we could probably get some browsers to work, but not all.
> Same with the footnotes, we need to check if we could run some JS before the print dialog is open and the print content is set.
> Should we then just not show the URLs then for now? (Like we do currently)

**Extend lazyload implementation**
> If we change the lazy load implementation to set a state one all of them loaded we could make the UX a bit nicer.

**Add a printversion using a flag**

**Comment by Entkenntnis** [comment]
Compared to the legacy system, the frontend isn't too bad.

Some missing features I have noticed:

- links are written out (an interesting idea)
- Serlo-Logo added

Anyway, maybe we can find a way to hide the printing warning after the user scrolled to the bottom.

Just some ideas, priority is low.

**Comment by elbotho** [comment]
(hide comments)

**Comment by Entkenntnis** [comment]
Hiding comments is doable, see #869, but the rest is - as far as I can see - not achievable without a separate print version of the page - which would be a bigger feature and I'm not sure if this is currently needed.

For more context, see https://github.com/serlo/serlo.org-rfcs/issues/18
