### ISSUE TITLE
Randomize multiple choice answers

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#603]
This is the line which needs to be changed: https://github.com/serlo/frontend/blob/staging/src/components/content/exercises/sc-mc-exercise.tsx#L34 (For example with https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array )

Ping for notifications: @kathongi @metzgaria

**Comment by kulla** [comment]
This is the line which needs to be changed: https://github.com/serlo/frontend/blob/staging/src/components/content/exercises/sc-mc-exercise.tsx#L34 (For example with https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array )

**Comment by elbotho** [comment]
With this kind of preparation you might as well change it @kulla 😄

**Comment by kulla** [comment]
Sorry, wrong button... :see_no_evil: I have three other PRs open which I need to finish first :-)
