### ISSUE TITLE
Topic Matemáticas on es.serlo.org starting page with icon.

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#604]
It would be amazing, if we could have the topic Matemáticas on the es.serlo.org-starting-page (with the same icon as in de.serlo.org), so the starting page would look similar to the german one.

**Comment by kulla** [comment]
@jakobwes What is the url of the Icon? https://es.serlo.org/matem%C3%A1ticas ? What shall be the title? "Matemáticas"?

**Comment by elbotho** [comment]
SVG is directly embedded. no url public. 
@jakobwes we currently have the exact same layout all instances but the german one (as discussed). 
You sure that you want a special solution for one instance?
Should other parts of the page then also look more similar to the de or just the icon?

**Comment by jakobwes** [comment]
This instance is already fairly big and the matematicas-topic is quite developed, so we discussed with the LC that it could be useful to have also the topic on the starting-page to link users directly to the content (like we do it in de.serlo.org with the icons). I think the rest of the page can stay more or less the same, only that change would be really good to give users a better impression what is important here (if it doesn't look awful only with one topic on the starting-page). The idea would then be the bigger the language-versions grows the more their starting-pages can look similar to the German one (because more topics get started, a /donate-page exists,...)
