### ISSUE TITLE
Topic Chemie on de.serlo.org starting-page with icon

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#605]
Todos:

- [x] Create icon
- [x] convert to SVG
- [x] add animation

**Comment by kulla** [comment]
@kathongi:

* What is the subtitle?
* What shall be the target of the link?

**Comment by kathongi** [comment]
Subtitle: Chemie lernen
Target of the link: https://de.serlo.org/chemie

**Comment by elbotho** [comment]
Status: Waiting.
I requested a change from Vasiliki.
