### ISSUE TITLE
Google Custom Search

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#61]
**With Google Custom Search.**

Overview over different implementation options: 
https://support.google.com/customsearch/answer/9069107?hl=en&ctx=topic

**Full control** solution is a paid version of GCS with JSON-API access:
https://developers.google.com/custom-search/v1/site_restricted_api
(5 Dollar per 1000 Searches)
This way we could style everything ourselves, use components, [add autocomplete](https://stackoverflow.com/questions/8232367/google-custom-search-api-autocomplete) etc.
Nice [Tutorial](https://medium.com/@tony.m.pdx/adding-google-custom-search-to-a-headless-ghost-blog-with-a-react-redux-front-end-b8b79b6dfff7) if we choose this way.
 
Free **alternative** that is not as nice but is also less work uses google embeded search and a result field. I will try to implement that first.

**Example** of a pretty nice dynamic implementation:
https://www.khanacademy.org/search

**Misc**:
- Exercises are most important search filter and should come first if possible

**Comment by Entkenntnis** [comment]
Working implementation is merged

**Comment by elbotho** [comment]
Technically working, but this needs a revisit at some point.
Currently the Placeholder is the word "Placeholder" ;)

**Comment by Entkenntnis** [comment]
Let's keep this open atm, things todo:

- [ ] Add Placeholder
- [ ] Review implementation
- [ ] Review Data Privacy Statement
- [ ] Find a place to document this feature

**Comment by elbotho** [comment]
Finally we have NGO-Status again 🎉
