### ISSUE TITLE
Page can't be viewed in the new frontend

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#614]
This page here: https://es.serlo.org/matematicas-nuevo-aqui can for whatever reason not be shown in the new frontend (I get an error-message or when visiting it directly redirected to the old frontend).

**Comment by elbotho** [comment]
Seems to be an API problem. ([issue](https://github.com/serlo/api.serlo.org/issues/120)).

@jakobwes is it a relatively new page or did you change the title/path recently?

**Comment by jakobwes** [comment]
I don't think so @elbotho . We created the page a month ago and there have been no edits on it since.

**Comment by Entkenntnis** [comment]
@jakobwes It's working for me now. Feel free to reopen if it persists for you.
