### ISSUE TITLE
Add schema.org

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#63]
schema.org ( https://schema.org/ ) is a way to add metadata to html (which can be used by search engines to understand an article). For example we have the following markup for an article:

```html
<div itemscope itemtype="http://schema.org/Article">
<div class="page-header">
<h1 itemprop="name">Faktorisieren</h1>
</div>
<article itemprop="articleBody">
...
``` 

The attributes `itemprop`, `itemtype` and `itemscope` give a more detailed semantic structure for the HTML element.

**Comment by Entkenntnis** [comment]
looks quite straight forward to add

**Comment by elbotho** [comment]
@kulla do you have experience with this? 
what other attributes would make sense?

**Comment by kulla** [comment]
@elbotho Yes I have some experience with schema.org and I can help with this issue.

**Comment by Entkenntnis** [comment]
tags on legacy system:

- body -> `itemscope itemtype="http://schema.org/WebPage"`
- breadcrumb ul -> `itemscope itemtype="http://data-vocabulary.org/Breadcrumb"`, and depending on location: `itemprop="url"`, `itemprop="title"`, `itemprop="child"` (nested breadcrumb ...)
- article -> `itemscope itemtype="http://schema.org/Article"`
  - h1 -> `itemprop="name"`
  - section -> `itemprop="articleBody"`
- comments -> `itemscope itemtype="http://schema.org/Comment"`
- video -> `itemscope itemtype="http://schema.org/VideoObject"`
  - h1 -> `itemprop="name"`
  - section -> `itemprop="description"`

exercises are tagged as Articles, applets are tagged as VideoObjects

@kulla Could you review this listing? I think, we can start with the most important ones, like itemscope Article ...

**Comment by kulla** [comment]
Here an overview, what we currently is implemented:

* Course and course page -> http://schema.org/Article
* Applet -> http://schema.org/VideoObject
* Event -> http://schema.org/Event
* Article -> http://schema.org/Article
    * See 
* Video -> http://schema.org/VideoObject
    * See https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/module/Ui/templates/entity/page/video.twig
* Exercise -> http://schema.org/Article
* Discussion -> http://schema.org/Comment
* Whole website -> http://schema.org/WebPage
  
@Entkenntnis Yes, your list seems to be complete :smile:

**Comment by Entkenntnis** [comment]
Thank you @kulla 

I have added the basic schema for now. If this feature gets more relevant, we can reopen this.
