### ISSUE TITLE
Page not rendered in new frontend 

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#633]
This one here: https://de.serlo.org/chemie-community-neu-hier

ping @kathongi : this page is linked directly from the /chemie starting-page. If /chemie goes on the starting-page, maybe it is then better to take this page out of the navigation for now (if no easy fix is available)?

**Comment by elbotho** [comment]
@jakobwes Weird!
But if you convert the page (build in old editor currently) it works. Just checked in staging, but don't have the rights in production.

**Comment by kathongi** [comment]
I just converted the "Neu hier" page. Now it works. 
I also checked the other "Neu hier" pages. Looks like we also have a bug on [https://de.serlo.org/permakultur-community-neu-hier](https://de.serlo.org/permakultur-community-neu-hier).

Should I leave it this way to find the bug or correct it @elbotho ?

**Comment by elbotho** [comment]
@kathongi If it's solved by converting, I'm fine with it :) Thank you.

**Comment by elbotho** [comment]
@kathongi thanks!
