### ISSUE TITLE
Investigate last Crowdin PR

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#634]
Maybe the change in the en file resulted in already translated strings being empty.

**Comment by elbotho** [comment]
Contacted Crowdin support…
Damn, if we can't do something about that we actually need to redo this, move everything to json and hope that everything works with our approach.

**Comment by Entkenntnis** [comment]
Thank you for contacting crowdin, hope they have something planned.

**Comment by elbotho** [comment]
Okay… 
They suggested that they improved some thing and a reupload of the `ts` file might solve the problem.
I did that, had to manually rework some translations, but all in all it went ok. 
Let's see what the next change brings…
