### ISSUE TITLE
Review UI of sub licenses

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#636]
If there is some sub content (e.g. video, ...) that has a different license, it is currently not clear which part of the content has the different license. Furthermore, I'd even advocate to highlight more restrictive licenses.

**Comment by Entkenntnis** [comment]
It took a while to find a video without cc license :) so, here it is: https://frontend.serlo.org/mathe/1515/satz-des-pythagoras

![grafik](https://user-images.githubusercontent.com/13507950/107120027-68a02280-688b-11eb-88b1-3cc8fa90b5d9.png)

and an injection for an exercise with a different license:

![grafik](https://user-images.githubusercontent.com/13507950/107120058-9edda200-688b-11eb-96a3-3309f0590e0e.png)

**Comment by Entkenntnis** [comment]
@inyono More restrictive licenses are highlighted (the cc is crossed) - in addition, on hover the title is saying which content type the license is belonging to. This should make clear with part of the content is covered by that license.

So I think we can close this issue.

**Comment by inyono** [comment]
To be honest, I'm still not quite happy with the current solution. Especially the second example is confusing: Does the license refer to the exercise or the solution? If the exercise, only the last exercise or all exercises in this block?

Without knowing how Serlo injections etc. work, I have no idea where some content starts and ends. Hovering also doesn't work on mobile.

**Comment by Entkenntnis** [comment]
The current solution is not perfect, but it's still much clearer then the solution in the legacy system:

![grafik](https://user-images.githubusercontent.com/13507950/107122682-6f359680-6899-11eb-8043-1cfa11b03d45.png)

The license is hidden in the context menu - and even on hover you don't see the name.

**Comment by Entkenntnis** [comment]
We can add a new feature for this, though, see #870

**Comment by inyono** [comment]
> The current solution is not perfect, but it's still much clearer then the solution in the legacy system:

True for the exercises (for some reason we apparently only show the license of solutions in legacy). What I like better in legacy, though (not that this is a perfect solution in any way), is how licenses are handled around injections:

<img width="751" alt="Screen Shot 2021-02-06 at 16 55 05" src="https://user-images.githubusercontent.com/1508477/107123161-482c9400-689c-11eb-9c21-e7e506e3b62b.png">

The border makes it pretty clear that the license belongs to the video (and only to the video).

For non-free licenses (which are pretty rare anyways), I'd like a solution that communicates that just as well.

**Comment by Entkenntnis** [comment]
Ok, right now I'm not even sure that we need the license information at all in case of a youtube embed. The source of the video is made very clear in the player, right? Anyway, I've never seen any page where a youtube embed has an additional license notice.

So in the case of a youtube video we can even left out the notice?

**Comment by inyono** [comment]
> So in the case of a youtube video we can even left out the notice?

Personally, I don't think so. Since we claim that the learning content (that contains the video) is licensed under CC-BY SA (created by Serlo), we should be clear about anything that differs from that. In fact, we have some YouTube videos that are still licensed under CC-BY SA.

> Anyway, I've never seen any page where a youtube embed has an additional license notice.

Most pages don't claim that their content is freely licensed. Wikipedia, for example, doesn't embed YouTube videos and instead hosts videos via Wikimedia Commons (which has all the license metadata for the files).

**Comment by Entkenntnis** [comment]
It's an interesting topic, let's discuss it further in a dev meeting.
