### ISSUE TITLE
Privacy: Google custom search

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#641]
In new frontend we want to get rid of the cookie banner, 
but currently the Google custom Search (now called "Programmable Search Engine" it seems) is loaded without any any extra acceptance click.

**Comment by Entkenntnis** [comment]
Uff... any ideas how to handle this?

Idea: Maybe showing a modal when the user clicks the search bar the first time, and asking "with autocomplete" or "without autocomplete" - and then saving the choice ...

**Comment by inyono** [comment]
Good question. The consent shouldn't be too hard (e.g. show a modal the first time a user clicks the search bar and have them consent similar to our privacy wrapper). I'm not sure where we should place a way to revoke the consent later again... 

Maybe it would make sense to have some kind of global options buttons in one of the corners? Where you can view and change your current settings for external content (youtube etc., GCS, some other stuff later e.g. HotJar if we need it). Then we can revisit auto-loading videos again after the consent.

Btw: Not only autocomplete is a problem. We need a consent either way (even without autocomplete).

**Comment by elbotho** [comment]
Thanks for your suggestions. 
@inyono since revoking is not really a feature that I think anybody will use:
Could we put that in out privacy page? 

**Simplest Implementation** I can think of:
#651 uses session storage, I guess this way we can circumvent a revoke option for now

**Simple Implementation with revoke**: A link on the privacy page that resets all the saved consents in localstorage.
(Currently not possible since it's not loaded in the new frontend)

**Comment by inyono** [comment]
Gonna reopen because of the revoke part. Haven't thought too much about that, yet.

**Comment by Entkenntnis** [comment]
The current implementation is fine, but maybe we want to improve it as described in #778
