### ISSUE TITLE
Adding new topics not immediately visible [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#645]
There is currently no listener for parents of newly created topics, so it takes a while for SWR to update the entries (see #509).

@inyono Are you planning to add a listener to this?

**Comment by Entkenntnis** [comment]
See https://github.com/serlo/serlo.org/issues/560

**Comment by Entkenntnis** [comment]
Currently, we have a delay of about 5 minutes. Not perfect, but we can probably work with this.

**Comment by Entkenntnis** [comment]
In review: https://github.com/serlo/serlo.org/pull/580

hopefully fixed soon!

**Comment by elbotho** [comment]
Works 🎉 
Thanks @kulla !
