### ISSUE TITLE
Show subscription state in menu after subscribe

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#647]
Follow up of #458: Subscriptions are updated, but slowly, so subscribing content is not immediately visible in the frontend ui.

API Issue on the way: https://github.com/serlo/serlo.org/issues/514

**Comment by elbotho** [comment]
We should also show a toast notice.
([related PR](https://github.com/serlo/frontend/pull/692))

**Comment by elbotho** [comment]
Current state (far from perfect but close to okay 😄):
- uses fetch
- shows toast notice on success
- refreshes page (still too quickly so UI is in old state most of the times)

Todo:
- [x] ~Bug: fetch reports success even if user is not authenticated~
- [x] Question: Should we delay the refresh even longer, hope for the production server to be faster or manually change the menu display on reported success? What do you think @Entkenntnis ?

**Comment by Entkenntnis** [comment]
Very nice, this is getting better :+1:

More me, it would be ok if we are not doing any refresh, just let the user refresh the page manually.

**Comment by elbotho** [comment]
okay, last 3 commits (including 50ccdfc) set the state directly, so the menu reflects the change immediately.
Imo this is quite alright until we use a mutation in the long term.
