### ISSUE TITLE
In hi.serlo.org english navigation is shown

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#653]
For some reason I can't reopen the issue, but basically the same as #609. The english-navigation is shown on the page, which makes navigating the site in the new frontend impossible via the menu (it reroutes to the english-pages).

**Comment by Entkenntnis** [comment]
Thank you for keeping this up. It looks like we have completely forget to translate the hindi menu (ups).

The translation is stored in this file: https://github.com/serlo/frontend/blob/staging/src/data/hi/menu-data.ts, but is not accessible through crowdin.

I can copy the strings from the backend today to fix this. Can you confirm that this are the intended versions?

Top-Menu (left):
![grafik](https://user-images.githubusercontent.com/13507950/100327007-fa0d3180-2fca-11eb-8ac0-f05c464ebc84.png)

Footer:
![grafik](https://user-images.githubusercontent.com/13507950/100327045-05605d00-2fcb-11eb-82f6-b9b216022506.png)

**Comment by Entkenntnis** [comment]
@jakobwes Preview: https://frontend-git-add-hi-menu-data.serlo.vercel.app/hi

**Comment by jakobwes** [comment]
Just had a look at it. It looks really good now! Ty
