### ISSUE TITLE
Many 500 errors [api]

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#663]
Today, after adding revisions, there were many 500 errors, across entities. It got better throughout the day, so I think it's a caching issue. Will test it tomorrow again.

**Comment by kulla** [comment]
Can you post a screenshot of give an example query?

**Comment by Entkenntnis** [comment]
It seems that most queries are working again now.

**Comment by inyono** [comment]
Are we talking about staging or production here?

**Comment by Entkenntnis** [comment]
Staging, it got a lot better, see #669

**Comment by inyono** [comment]
Okay, that's probably fine then. Because of the alias changes, I removed the API cache of aliases, (temporarily) deactivated the Cache from CF Worker's side and deployed new versions with fixes a couple of times.
