### ISSUE TITLE
Comments are not loading for these pages

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#664]
See https://de.serlo-staging.dev/mathe/77998/zeiteinheiten, there should be two threads, but we get an error in the console.

**Comment by Entkenntnis** [comment]
Also here in the solution: https://de.serlo-staging.dev/mathe/78513/78513
and here: https://de.serlo-staging.dev/mathe/169858/169858
and here (solution): https://de.serlo-staging.dev/chemie/25361/optische-aktivit%C3%A4t

**Comment by inyono** [comment]
Can't reproduce, can you check if this is still an issue?

**Comment by elbotho** [comment]
Works in staging & production for me.
