### ISSUE TITLE
Failing to load injection

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#666]
"map of undefined": https://de.serlo-staging.dev/community/167497/beispielartikel-hier-kommt-euer-titel-hin

**Comment by Entkenntnis** [comment]
Devilish Issue :smiling_imp:

**Comment by elbotho** [comment]
Can't reproduce?
But it seems we don't have a fallback image if no image is used in `<Multimedia>`

**Comment by Entkenntnis** [comment]
Ok, I can not reproduce it, too. Probably another cache issue.
