### ISSUE TITLE
Finish profiles prototype

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#677]
PR is here: #679  ~#573~
- [x] rebase to staging
- [x] add / check comments
- [x] activities are not done api wise, so ignore for now
- [x] routing: check `/user/profile/{username}` (some info here: #576) 
- [x] routing: decide where `/user/me` and `/user/public` are handled
- [x] create issue for CFWorker to allow type user to be displayed in new FE ([issue](https://github.com/serlo/serlo.org-cloudflare-worker/issues/65))

**Comment by elbotho** [comment]
@inyono will discuss with @kulla on monday, but maybe you can already pitch in:
Where (Worker, API or Frontend) should we resolve `/user/me` and `/user/public`? 
The difficulty is, that we need the auth info to query the correct user data.

**Comment by Entkenntnis** [comment]
I am thinking about replacing the href `/user/public/` in the menu directly with `/user/profile/{username}` while rendering. We have the information at hand and don't need to use `/user/me` or `/user/public`

**Comment by elbotho** [comment]
@Entkenntnis damn, great idea 👍
