### ISSUE TITLE
Proxy threads query

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#683]
Either via new API route (if we want to do it client-side) or in our existing fetcher.

**Comment by Entkenntnis** [comment]
I will make some timing tests API vs vercel cache and decide how to handle this.

**Comment by Entkenntnis** [comment]
The cache is not really faster than api request, but I will add #737

**Comment by inyono** [comment]
Mh, that's weird. Did you also check if this is the case if both are cached? There should be a difference: If you proxy the query, Vercel can cache the GraphQL response on the edge (which is also where Vercel's SSR stuff happens). This is not the case for the non-proxied route (which will always go through the GraphQL server). So basically:
```
Proxied:
- User Client > Cloudflare Worker > Vercel Edge
- Vercel API Route > Vercel Edge
Non-proxied:
- User Client > Cloudflare Worker > GraphQL Server > Redis
- Vercel API Route > Cloudflare Worker > GraphQL Server > Redis
```

Did you pass an authorization header or didn't set the appropriate HTTP headers (you can compare that to the already existing proxied fetcher) by any chance?

**Comment by Entkenntnis** [comment]
I have underestimated the effect of the cf worker, now I have explicitly used the cache with following results:

```
Testcase 1: Vercel Cache (super fast, ~100ms)
- User Client > Vercel Edge

Testcase 2: CF + Vercel (still fast, ~300-400ms)
- User Client > Cloudflare Worker > Vercel Edge

Testcase 3: Client API Request (also fast, 200-400ms, high variance)
- User Client > Cloudflare Worker (?) > GraphQL Server > Redis
```

So testcase 3 is as fast as testcase 2, which is interesting, but the fastest is still testcase 1, which means a proxy would make sense (and the frontend is bypassing cf worker, so this would work as in testcase 1)

**Comment by inyono** [comment]
Thanks for rechecking 👍 

> (and the frontend is bypassing cf worker, so this would work as in testcase 1)

True, if you talk with frontend.serlo.org/api, you even save the CF Worker roundtrip (only SWR should do need the round trip from Vercel's perspective).

**Comment by Entkenntnis** [comment]
With this results, a request like this:

```
Hypothetical testcase 4:
User Client > GraphQL Server > Redis
```

should be as fast as vercel cache? But currently, the GraphQL Server is not publicly exposed, right?

**Comment by inyono** [comment]
It should be slightly faster compared to Testcase 3, but not as fast as Testcase 1. The difference is that Testcase 1 is a cacheable HTTP request (e.g. client makes a GET request to frontend.serlo.org/api/whatever where we set the corresponding cache headers for Vercel's cache), while Testcase 4 would still need to execute the GraphQL query, so:
```
Test Case 1
- User Client > GET to /api/foo (this is cached on Edge without any server involved)
- Background (SWR Update): Vercel (> CF Worker >) POST api.serlo.org/graphql > Redis

Test Case 4
- User Client (> CF Worker) > POST api.serlo.org/graphql > Redis
```

**Comment by Entkenntnis** [comment]
Let's see how well #774 is working out.

**Comment by elbotho** [comment]
@Entkenntnis what's your verdict? :)

**Comment by Entkenntnis** [comment]
Undecided yet. I want to wait after we have tested threads more and decide then. (there is a small performance benefit, yes - but it would split our code apart between client and server)

**Comment by Entkenntnis** [comment]
So, after some more consideration: I will close this issue, because the situation has changed a lot - we are using swr on the client and will soon enable commenting for all users. In this case, a swr-waterfall (client + proxy) is not nice to have (or at least not worth the small performance improvement).

I haven't seen any other benefit besides a latency reduction of ~0,2s to this (at the cost of more complex code). So if I have overlooked something, feel free to open a follow up issue.
