### ISSUE TITLE
Handling archived threads

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#689]
The legacy system is collapsing archived threads:

![grafik](https://user-images.githubusercontent.com/13507950/100854138-e3625100-3488-11eb-9274-ef3de1d5b33b.png)

(note the green tick and the click handler in the top right)

This feature is not implemented yet, archived threads are just hidden.

**Comment by Entkenntnis** [comment]
Some thought:



> Archivieren ist vor allem gedacht als im Sinne von "ist erledigt" oder "Frage wurde beantwortet".
Ich könnte mir schon vorstellen, dass
vor allem Autor:innen bedarfsorientiert entscheiden können, ob sie die Kommentare sehen wollen.
Angenommen über einen Inhalte wurde schon einmal ausführlich diskutiert, ob man eher A oder B noch mit reinnimmt. Am Ende wurde sich für A entschieden und die Diskussion archiviert. Dann wäre es schon super, wenn ich auch ohne Moderatorenrechte die Diskussion im Nachhinein nochmal einsehen kann.
Ich finde aktuell das Design für archivierte Kommentare noch nicht wirklcih schick und finde auch, dass sie nicht standardmäßig für alle Lernenden angezeigt werden sollten, weil sie eher in Spezialfällen interessant sind.
Spontan denke ich da z.B. an
 >Opt-in für User, ob archivierte Kommentare unter Inhalt angezeigt werden sollen (könnte man evtl auch global im Profil machen?)
 >Unter den aktuellen Kommentaren gibt es noch eine weitere Sektion Archivierte Kommentare die man bei Bedarf aufklappen kann.
Kannst ja mal schauen, ob dir das was schickes einfältt

**Comment by elbotho** [comment]
> Unter den aktuellen Kommentaren gibt es noch eine weitere Sektion Archivierte Kommentare die man bei Bedarf aufklappen kann

I like it. This seems unintrusive and easy to implement.
I propose a text link ("Show archived ▾")  under the comment section if there are archived threads.
