### ISSUE TITLE
Loading routing information dynamically

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#690]
Some links are handled by the frontend and can use CSR, other links need to be loaded from the legacy system - the handling of these links is currently hard-coded in the frontend and has to be kept in sync with the CF worker. (see previous discussion in https://github.com/serlo/frontend/issues/328)

I can offer following idea: The CF worker (or the API) provides a route where you can request a list of links/regexes that should be loaded from the legacy system. The frontend loads this data on pageload once and can then determine if a link can use CSR or not.

If we need to change routing information fast (e.g. roll up something), we only need to update this one route, the frontend will then adapt to it (modulo session storage cache).

**Comment by Entkenntnis** [comment]
How such a configuration may look like:

```regex
/privacy
/datenschutz
/imprint
/terms
/disable-frontend
/enable-frontend
/beitreten
/discussion/.*
/page/revision/revisions/[\d]+
/taxonomy/term/organize/[\d]+
```

(and so on)

**Comment by elbotho** [comment]
Just an idea:
Could we also have this file in the frontend – since it "knows" what paths it currently supports – and have it be fetched by the CF-worker periodically or at build/deploy time?
(ping @kulla)

**Comment by kulla** [comment]
> Could we also have this file in the frontend – since it "knows" what paths it currently supports – and have it be fetched by the CF-worker periodically or at build/deploy time?

Then we have it the other way around: The frontend determines which routes are supported. We have something similar at https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/utils/url.ts#L37-L42 To define the non frontend-urls might be easier. Let's discuss it at Monday.

**Comment by Entkenntnis** [comment]
Exactly such a list, either whitelist or blacklist, depending which is easier.

**Comment by Entkenntnis** [comment]
Closing this issue, as we are not coming to a definite conclusion how to handle this (there seems to be no silver bullet)
