### ISSUE TITLE
remove "Zugehörige Themen"?

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#7]
![2020-03-11-195445_222x407_scrot](https://user-images.githubusercontent.com/1327215/76453069-6e1e8f80-63d2-11ea-932c-c0feb2b0d5bf.png)

**Comment by elbotho** [comment]
There is a design draft for that area, but with Simon we decided to skip implementation until there is a better concept for how these get populated.
So yes, vote to remove.

![image](https://user-images.githubusercontent.com/1258870/77779077-3a8a6900-7052-11ea-93ca-3869d54f9157.png)
