### ISSUE TITLE
Comments: should we markup links?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#701]
e.g.
![image](https://user-images.githubusercontent.com/1258870/102224943-e593c900-3ee6-11eb-9f06-6168e4a35359.png)

**Comment by inyono** [comment]
Fine by me, might need changes for the new commenting system later, though (since we might add rich-text support there).

**Comment by Entkenntnis** [comment]
Do you mean: Fine by me -> no need for markup? :grin:

Reopen if you meant: fine by me -> go ahead and implement this :)

**Comment by inyono** [comment]
This is basically an "I don't care either way" because we'll discuss that again with the new commenting system but it won't affect us. So implement it if you want, or don't 😛
