### ISSUE TITLE
broken course 73000

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#702]
https://de.serlo-staging.dev/informatik/73000/der-roboter-klassenkarte
fails with 
`Error while fetching data: Abstract type "AbstractUuid" was resolve to a type "SingleChoiceWrongAnswerRevision" that does not exist inside schema.: {"response":{"errors":[{"message":"Abstract type \"AbstractUuid\" was resolve to a type \"SingleChoiceWrongAnswerRevision\" that does not exist inside schema.","locations":[{"line":2,"column":5}],"path":["uuid57209"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"message":"Abstract type \"AbstractUuid\" was resolve to a type \"SingleChoiceWrongAnswerRevision\" that does`

**Comment by inyono** [comment]
The problem is the uuid 57209 (which is linked to and this is probably a wrong link). We should probably cover the this case in the API though so that this returns `null` correctly (as `SingleChoiceWrongAnswerRevision` is not supported).

**Comment by elbotho** [comment]
Okay, content seems to be fixed (works in frontend now).
API issue is open.
