### ISSUE TITLE
Some profile-content gets rendered in the new frontend, some doesn't 

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#704]
If in here: https://de.serlo.org/mathe/1771/direkte-proportionalit%C3%A4t I click on "Nish" the content in the profile gets rendered as it should, whilst if i click on "Wolfgang" only the name and the comments in the profile get shown, but not Wolfgang's self-description.

Not sure if bug or just not yet implemented feature, so feel free to close the issue if it's the latter.

**Comment by Entkenntnis** [comment]
Yes, this is a bug. I think we have digged up some splish-me content the frontend is not handling:

![grafik](https://user-images.githubusercontent.com/13507950/102357000-2e628500-3fae-11eb-8642-669365acb899.png)
