### ISSUE TITLE
MathPuzzle not handled

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#705]
See https://de.serlo.org/mathe/1322/gemischte-aufgaben-zum-bruchrechnen
(e.g. look at https://de.serlo.org/api/frontend/mathe/1322/gemischte-aufgaben-zum-bruchrechnen)

**Comment by inyono** [comment]
Didn't we decide to ignore math puzzles in the new frontend? We probably should make sure that this doesn't error, though.

**Comment by Entkenntnis** [comment]
I can't reproduce this error anymore, so closing it.
