### ISSUE TITLE
Injection is trying to load absolute path

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#706]
See https://de.serlo.org/mathe/134992/aufgaben-zum-exkurs

Injections fail to load because the path is absolute.

**Comment by inyono** [comment]
Again, I try to create a db migration for such cases.

**Comment by Entkenntnis** [comment]
I will investigate how often this happen. If this is rare, than we will mark it as content problem.

**Comment by Entkenntnis** [comment]
This is not happening in converted content, so we will assume that the new editor is preventing this error.
