### ISSUE TITLE
Fetch error because image is created as injection

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#707]
I suspect that there are some images that are created as injections. Instead of a warning (like in the legacy system), we get a CORS errors, e.g. here: https://de.serlo.org/mathe/stochastik/zufallsgr%C3%B6%C3%9Fen/erwartungswert

**Comment by inyono** [comment]
I can look whether I can add a db migration for that (at least for injections containing assets.serlo.org).

**Comment by Entkenntnis** [comment]
Same here, checking how often this happens ...

**Comment by Entkenntnis** [comment]
This is only happening once in converted entities, so we regard this as content bug.
