### ISSUE TITLE
Some static pages should not display comments [api]

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#709]
> Falls noch nicht bekannt: Hab gerade entdeckt. dass im Redesign unter https://de.serlo.org/mathe Kommentare sichtbar sind, die wir im alten Design ausblenden - siehe entsprechendes static page setting "Diskussionen aktivieren".

**Comment by elbotho** [comment]
Quickfix for 25%: Disable comments on pages
Backlog: Solve issue in API/serlo.org

**Comment by Entkenntnis** [comment]
quickfix in f33c278f0888006d8fed999a04e1dd675f55dc10

**Comment by elbotho** [comment]
related api issue: https://github.com/serlo/api.serlo.org/issues/162

**Comment by Entkenntnis** [comment]
decided as wontfix
