### ISSUE TITLE
Strange failure

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#720]
This looks funny: https://de.serlo.org/api/frontend/97880

**Comment by inyono** [comment]
Caused by wrong link in https://de.serlo.org/98615.

**Comment by Entkenntnis** [comment]
Fixed in f20191d3fc38638496d9c8a5718a0d2724452918

**Comment by inyono** [comment]
I'd change that logic so that it is future-proof (i.e. instead of checking the length, I'd check if this is a 32bit signed integer).
