### ISSUE TITLE
Use new edtr redirect hashes to display notices [legacy]

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#730]
~If https://github.com/serlo/serlo.org/issues/553 is merged we can use the hashes to display notices in the frontend and maybe purge the cache and reload.~

**Status**: There seems to be a bug in staging prevents us from testing this.

> Closes #553
> 
> This PR implements (ping @elbotho ):
> 
> Adds #revision-saved when a revision is saved but needs to be reviewed
> Adds #revision-accepted when a revision was successfully checkout out / accepted
> Adds #revision-rejected when a revision was successfully rejected
> Adds #revision-saved-accepted when a revision was successfully saved and accepted

**Comment by Entkenntnis** [comment]
Waiting for staging fix for editing content before we can integrate this.

**Comment by elbotho** [comment]
Merged it to staging yesterday, @Entkenntnis if you want to check out the code it's [this PR](https://github.com/serlo/frontend/pull/792) and some [ugly direct commits](https://github.com/serlo/frontend/commits/staging) to staging late last night to try out different redirects.
UI is not perfect (mutations will obviously be nicer, no reload etc.) but works quite well.

Short note for testing, since @inyono increased staging server resources content can actually be saved again :)
But stay away from trusty 1565 and maybe other long articles. Not sure what's going on there, but everything else should work.
