### ISSUE TITLE
Client-side cache for comment queries

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#737]
Add a session storage cache for client-side comments to reduce server load. (probably with swr for authenticated users)

**Comment by elbotho** [comment]
What are the downsides to using SWR for all users?
test pr at #774

**Comment by Entkenntnis** [comment]
Anyway, with all the refactoring this week, I have to rethink our caching approach, but feel free to use SWR, it looks like a solid and small lib.

**Comment by Entkenntnis** [comment]
#774 will solve this issue
