### ISSUE TITLE
Investigate chunk optimization

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#746]
next.js has changed their chunk optimization in the latest release. But an analysis of our chunks revealed that they are not optimal.

The reason could be that we are loading all pages, static and dynamic, from one catch-all page. Maybe this is irritating the optimizer. Idea: Use separate pages for static pages to give optimizer better hints.

**Comment by Entkenntnis** [comment]
After some testing it seems that splitting into separate pages is the only way to improve chunking.

**Comment by elbotho** [comment]
How do we handle routing/catchall then?

**Comment by Entkenntnis** [comment]
preferably with default next.js tools like filesystem routing + static page generation. Still a lot work in progress
