### ISSUE TITLE
Discussion: Go to 100% for mobile users?

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#748]
Reasoning:
- UX is better on mobile with frontend enabled. 
- Features for logged in users are currently in development or testing, but we don't need them on mobile anyway
- Since we don't collect in depth data (analytics) any more we don't really need a reference group.
- -> Better for users to go to 100% on devices that the CFWorker can identify as mobile / small screen

Opinions?
Something not working currently?

**Comment by elbotho** [comment]
CF offers [this](https://developers.cloudflare.com/workers/examples/conditional-response) for enterprise plans:
``` ts
  // On Device Type
  // Requires Enterprise "CF-Device-Type Header" zone setting or
  // Page Rule with "Cache By Device Type" setting applied.
  const device = request.headers.get("CF-Device-Type")
  if (device === "mobile") {
    return Response.redirect("https://mobile.example.com")
  }
 ```

**Comment by Entkenntnis** [comment]
Supporting this. I think we can do this check right beforce setting the cookie: Mobile user will not get a random number, but 0 instead.

**Comment by inyono** [comment]
FYI: we are not on the enterprise plan, so `CF-Device-Type` won't work. We could add some other kind of detection, though.

**Comment by elbotho** [comment]
(note)
okay then something super simplified that should work _sometimes_:
`userAgent.match(/iPhone|Android|webOS/i) ? 'Yes' : 'No';` ([source](https://gist.github.com/vdbelt/083207890e9ce6ed543a29545fea98ff))
or something bigger like https://github.com/faisalman/ua-parser-js or https://github.com/lancedikson/bowser

**Comment by elbotho** [comment]
**Update**
(wow, what a week 🎉)

- Mobile testing didn't show any bigger problems with new frontend (mostly content problems and latex rendering stuff).
- CFWorker [can now change probabilities for mobile separately](https://github.com/serlo/serlo.org-cloudflare-worker/pull/130). 
- New database layer is deployed and SWR Queue seems to be stable.

**Comment by Entkenntnis** [comment]
Timeline:

-> 25/01: 100% for mobile users
-> 01/02: 100% for all non logged in users

**Comment by Entkenntnis** [comment]
Decided, see #780
