### ISSUE TITLE
New changes in api.serlo.org: Can query be optimized

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#753]
There are some changes in api.serlo.org with which the query might be changed or can be optimized:

* `alias` is now a property of `AbstractUuid`: https://github.com/serlo/api.serlo.org/blob/master/src/schema/uuid/abstract-uuid/types.graphql#L1-L5
* `threads` is moved from interface `AbstractUuid` to `ThreadAware`: https://github.com/serlo/api.serlo.org/blob/master/src/schema/uuid/thread/types.graphql#L27-L34
* There is a new Interface `InstanceAware`. All types implementing it have the property `instance`.

**Comment by inyono** [comment]
~`ThreadAware` isn't live yet (since this is also a breaking change). Will come in the next deployment and then probably in staging first with a corresponding PR in frontend that resolves the breaking change.~ It's live now.

**Comment by elbotho** [comment]
We have `ThreadAware` now ([see here](https://github.com/serlo/frontend/blob/staging/src/components/comments/comments.tsx)), thanks @inyono.
@Entkenntnis I don't see any other changes/improvements atm. Do you?

**Comment by Entkenntnis** [comment]
Our query looks fine.
