### ISSUE TITLE
add placeholder image for donation form, improve privacy wrapper mobile layout

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#766]
(maybe even think about a popup for mobile users that has the info and consent button, because currently the info covers most of the images…)

**Comment by simonkoehl** [comment]
Would this be an option:
- rebuild the first level of the form (actually only buttons, we are planning to get rid of the slider)
- only ask for consent, if users click on our first level
- deliver this information to the form for further steps
?

**Comment by elbotho** [comment]
@simonkoehl  is the concept ready how you want to change the first level?
I need to check but adding info to the form should/could work.

**Comment by elbotho** [comment]
@simonkoehl I made some [improvements for mobile](https://de.serlo-staging.dev/serlo) and added [a quick fix](https://de.serlo-staging.dev/spenden) for the donation page. 
Will probably not work on this until our next milestone, but feel free to add the infos etc.

**Comment by simonkoehl** [comment]
great temporary solution @elbotho thank you!
