### ISSUE TITLE
Remember privacy consent and adding revoke option

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#778]
We are currently not persisting the privacy conset, so closing the tab or opening a new tab will reset this information.

A slightly improved way to do this would be to store the consent on the client and add some information in our privacy agreement how to reset it, e.g. a special link

Edit: E.g. in localStorage for 14 days?

**Comment by elbotho** [comment]
For search we currently save it to `sessionStorage` at least.
@inyono did you think about this solution? Do you consider it okay as an interim solution?

If yes, I'd suggest adding this logic to the privacy wrapper as well. That would be a easy next step towards the real feature.

**Comment by inyono** [comment]
Remembering the consent is fine as long as users have an easy way to revoke their consent later:

> The data subject shall have the right to withdraw his or her consent at any time.

Maybe https://www.privacypolicies.com/blog/gdpr-consent-examples/#The_Sixth_Element_Of_Consent_Easily_Withdrawn is  also helpful.

**Comment by Entkenntnis** [comment]
We have a special situation with the search, because we already have an extra layer of protection: The search is only loaded when the user clicks it. This behaviour will not change if the user has given consent.

So: The purpose of our banner is just to give notice that the search is powered by an external provider. The "actual" consent it giving by actively using the search. Revoke in this sense would mean: Just don't use the search if you do not agree.

With this argument, we can actually store the acceptance of the banner permanently (-> localstorage), maybe with timestamp, so we can reshow the banner if our agreement changes.

@elbotho @inyono Do you think this makes sense here?

**Comment by elbotho** [comment]
@Entkenntnis I get your point, and the same could be said for the embeds (they also don't load before click).
But imo having a feature for revoking consent is a good idea anyway to be on the safe side.
I think the option to revoke is no disadvantage ux wise and not overly complex if we handle it only in the frontend and we should just write that code :)

(I maybe should be doing other things, but I could draft something today, if you don't want to do it)

**Comment by inyono** [comment]
> So: The purpose of our banner is just to give notice that the search is powered by an external provider. The "actual" consent it giving by actively using the search. Revoke in this sense would mean: Just don't use the search if you do not agree.

Not sure if I understand your correctly, but: we need a button that says "Zustimmen" or something like that. The pattern "By using the search you agree you consent to the privacy policy" is explicitly not enough (which is the reason for all the horrendous cookie banners).

> With this argument, we can actually store the acceptance of the banner permanently (-> localstorage), maybe with timestamp, so we can reshow the banner if our agreement changes.

Same as for embed: as long as we don't ask for the consent each time and persist the consent instead, we need an easy way for the user to revoke the consent.

**Comment by Entkenntnis** [comment]
The banner is still shown the first time, if the user clicks "Zustimmen", the banner wil not show again. But the search is still not loaded automatically, but only if the user clicks it.

@elbotho Feel free to add a draft. We may how no third-party cookies now, but may use them in the future.

**Comment by inyono** [comment]
> The banner is still shown the first time, if the user clicks "Zustimmen", the banner wil not show again. But the search is still not loaded automatically, but only if the user clicks it.

Still: if you don't ask for _explicit_ consent each time, we need a revoke option.
