### ISSUE TITLE
Math issues on mobile

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#779]
- [x] https://frontend.serlo.org/mathe/177495/177495
- [x] https://frontend.serlo.org/1503
- [x] ~https://frontend.serlo.org/25634~   -> bitte Gleichungsplugin nutzen
- [x] ~https://frontend.serlo.org/mathe/9701/9701 (Lösung, Teilaufgabe 4)~   (nicht schön, aber inhaltlich ok)
- [x] ~https://frontend.serlo.org/mathe/3133/3133 (Lösung a)~ (nicht schön, aber inhaltlich ok)
~In der Lösung: Formeln brechen um, machen keinen Sinn mehr~

- [x] ~https://frontend.serlo.org/mathe/3203/3203~ -> Gleichungsplugin kann hier helfen
~Lösung a. Überlagerung in den Formeln bei bestimmen Breiten~

- [x] https://frontend.serlo.org/mathe/3459/3459 (Lösung)
Vertikale Überlappungen in der Tabelle

- [x] https://frontend.serlo.org/mathe/3199/3199 (Lösung) (man kann bei der letzten großen Formel auch array nutzen, um nicht umzubrechen
- [x] https://frontend.serlo.org/mathe/3261/3261 (Lösung, weit unten) 
Viel zu großer  Abstand, Überlappungen

**Comment by Entkenntnis** [comment]
Most Issues can be solved by #833

**Comment by Entkenntnis** [comment]
The last url is depending on https://github.com/serlo/api.serlo.org/issues/215

**Comment by elbotho** [comment]
Nice! Thanks for investigating and fixing those 👍
