### ISSUE TITLE
Frontend logged-in, but not in legacy

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#782]
It happens regularly that I am logged-in in the frontend, but not on the legacy server, so if I edit a page, I have to log in first. Also, notifications are not loading.

Steps to reproduce:

- Log in on staging (frontend + legacy).
- Come back after a day.
- Frontend is logged-in, but not legacy anymore.

**Comment by inyono** [comment]
Mh... Did you check the "remember me" box when logging in? IIRC, the current behavior is:
- Legacy: If you check "remember me", your session will last 28 days (legacy system) by setting a cookie that expires after 28 days. If you don't, your session will only persisted in a session cookie.
- Hydra will issue an refresh token that expires after 30 days. This will be used to refresh your id token (which expires after 1 hour).

**Comment by Entkenntnis** [comment]
Production is working fine. Only on staging, I get logged out regularly.

**Comment by inyono** [comment]
Ah, that's not a bug then. Remember that we reset the staging database every night (and therefore invalidate all sessions).

**Comment by Entkenntnis** [comment]
Makes sense!
