### ISSUE TITLE
Use next.config.js strict mode

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#783]
We can switch to https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode.

**Comment by elbotho** [comment]
> strict mode should now be active, but I could not find any warning, which makes me suspicious ;) (from #796)

**Comment by Entkenntnis** [comment]
The double call should indicate it's working:

![grafik](https://user-images.githubusercontent.com/13507950/105504459-13c7ae00-5cc8-11eb-9993-7f3b3b8b424e.png)

Source: 

```jsx
import React, { useState } from 'react'

export default function Page() {
  const [data, setData] = useState(() => {
    console.dir('Getting initial state...')

    return {}
  })

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  )
}
```

(true, difficult to tell :grinning:)
