### ISSUE TITLE
Hyphenization of comments not working

### ISSUE THREAD

**Issue by Knorrke** [serlo/frontend#784]
Hey :-) 
The content does display correctly hyphenized, but in the comments it doesn't work.
E.g. see the comments of https://de.serlo.org/mathe/9535/9535
Example screen shot:
![grafik](https://user-images.githubusercontent.com/11499926/104969466-c659f100-59e8-11eb-80d6-c76014bcce05.png)

`hyphens:auto;` is set in the css, so I don't really know why this is happening.... But for mobile users it would be really nice to fix this. With the small screen width there's a lot of wrapping otherwise.

The frontend looks amazing btw :-) great work :tada:

**Comment by elbotho** [comment]
Damn, fixed something just last week that obviously broke this.
Thanks for reporting and the praise 😊
