### ISSUE TITLE
Remove quickfix for removing undefined values

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#790]
next.js is strictly checking props and is not allowing the value undefined. We have a lot of optional props, so we should delete the attribute. A quick way to do this was:

https://github.com/serlo/frontend/blob/60caceee9619ffc5992f6d8cdee2b94e17f3bb35/src/pages/%5B...slug%5D.tsx#L89

Replace with a better method.

**Comment by Entkenntnis** [comment]
This would suffice: https://stackoverflow.com/a/38340730

**Comment by elbotho** [comment]
@Entkenntnis after looking at this and may solutions I'm not convinced that others are better than your hack. at least it's simple :) I think in the future this will change in nextjs. 
Possible optimisation would be to apply this filter only to the fields where we actually might need it in `fetch-page-data` directly. but that also error prone…

Are you mostly concerned with performance?

**Comment by Entkenntnis** [comment]
Reference https://github.com/vercel/next.js/issues/17215

The current hack is probable fine, at least in the current situation.
