### ISSUE TITLE
Some formulas are cut off

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#791]
This is a strange and tricky issue: Some formulas are somehow just a little bit too high, so they get cut off, like https://frontend.serlo.org/4409:

![grafik](https://user-images.githubusercontent.com/13507950/105167394-f1dbf900-5b18-11eb-8212-3558fc947105.png)

Preferable we can find a real fix for it, otherwise, we have to do some heuristics and add som padding to the wrapper.

**Comment by elbotho** [comment]
This case can be solved by adding `padding-top: 2px;` to the wrapper… that's fine if we do it globally imo.

**Comment by Entkenntnis** [comment]
In the case of https://frontend.serlo.org/96285, adding padding would make the choices look misaligned, e.g. it looks way better if there is no padding. But generally, formulas in multiple-choice look a bit off, like here (https://frontend.serlo.org/88987):

![grafik](https://user-images.githubusercontent.com/13507950/105172669-4040c600-5b20-11eb-8375-016135adfdb4.png)

Is there an easy fix to make the checkbox at baseline instead of top? Then adding the padding would not be a problem.

**Comment by elbotho** [comment]
`align-items: center;` to StyledLabel should do the trick,
