### ISSUE TITLE
Do we want to support single comment view?

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#799]
Just noticed that urls like https://de.serlo.org/191548 are not implemented at all.

Is this something that we want to add - or just let legacy handle this?

**Comment by elbotho** [comment]
Okay, not sure what the use case is here thb. Where do those links occur? 

 I'd prefer a link to the comment in context (under the relevant content, just as an anchor link), that would be a nice enhancement.

 Might be a bit tricky with lazy loading…

**Comment by kulla** [comment]
We have decided that it makes no sense to display single comments (currently there is also no possibility to get a single comment from the api - when you request the `uuid` endpoint with the id of a comment `null` is always returned).

My suggestion: We add a redirect from the comment view to the article as we redirect solutions to its exercise. All right?

**Comment by elbotho** [comment]
@kulla ~could you also redirect to `article#comment-{commentId}` ?~
Nevermind, jup I like your suggestion. We can generate and use the version with anchor links inside the frontend.
(see https://github.com/serlo/frontend/pull/803)

**Comment by kulla** [comment]
Okay, here is the follow up issue: https://github.com/serlo/serlo.org-cloudflare-worker/issues/152
