### ISSUE TITLE
Enable revisions in production

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#802]
The new revision view is ready (and as good as the existing view). Todo: Take a look that everything is fine and then enable in production (-> create cf issue)

**Comment by elbotho** [comment]
see https://github.com/serlo/serlo.org-cloudflare-worker/pull/151 as preparation (while we test).

**Comment by kulla** [comment]
https://github.com/serlo/serlo.org-cloudflare-worker/pull/151 is merged in deployed at staging. Happy testing :smile:

**Comment by elbotho** [comment]
Thank you!

**Comment by Entkenntnis** [comment]
Some weird behavior when opening this page: https://de.serlo-staging.dev/32769

**Comment by Entkenntnis** [comment]
Can we maybe hide meta-changes (title, description) if they are empty? Because I'm not seeing this fields in legacy very often?

**Comment by elbotho** [comment]
> Can we maybe hide meta-changes (title, description) if they are empty?

Yeah good idea

**Comment by Entkenntnis** [comment]
Not working for grouped exercises: https://frontend.serlo.org/entity/repository/compare/0/193382
and solutions: https://frontend.serlo.org/entity/repository/compare/0/193383

**Comment by elbotho** [comment]
@Entkenntnis thanks for checking this! This means all other content types work?

**Comment by elbotho** [comment]
what a goose chase… `convert-edtr-io-state` does not support `exercise`. -_-

**Comment by Entkenntnis** [comment]
Oh right, there is a separate create-exercise handler for this because exercises are complex.

**Comment by Entkenntnis** [comment]
A side note: Showing the revision of solution is not very useful without the exercise, but if you change the exercise and the solution, the solution revision can't find the corresponding exercise revision (because it's not accepted yet) ... which makes reviewing exercises at times annoying. But this is also happening on legacy now...

Quickfix: Maybe we can at least link to the exercise in a solution or the exercise-group for a grouped exercise. (I can help here, because I think revisions are quite important for authors)

**Comment by elbotho** [comment]
> and solutions

@Entkenntnis I have a vage memory that we wanted to only support editing exercise and solution at the same time?

**Comment by Entkenntnis** [comment]
Immediate follow-up issue is #919.
