### ISSUE TITLE
Investigate dynamic imports and only make non-trival modules dynamic

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#810]
Dynamic imports have their overhead I I think we are overusing them in some places ...

**Comment by Entkenntnis** [comment]
For reference: the real weight of all our routes:

![grafik](https://user-images.githubusercontent.com/13507950/105732752-14af4880-5f31-11eb-843b-4aa7bf514bc5.png)

(this is closer to the amount of js users will load)

**Comment by Entkenntnis** [comment]
And this entangles mess is our dependancy graph :)

![grafik](https://user-images.githubusercontent.com/13507950/105733356-c3538900-5f31-11eb-9b41-868f3fc01dc0.png)

**Comment by elbotho** [comment]
pretty nice looking mess :)
Is that the output of `yarn analyze` or did you change something?

**Comment by Entkenntnis** [comment]
I have temporary disabled all dynamic components, so this is the upper bound - will readd them step by step and see when we arrive at a good level.

**Comment by Entkenntnis** [comment]
#809 is definitively helpful here.

**Comment by elbotho** [comment]
> #809 is definitively helpful here.

already on it 👍

**Comment by Entkenntnis** [comment]
So, I have learned alot about what webpack and the chunk optimizations it is doing (and how to debug this). I will try to apply my new knowledge. Places our code base could improve:

- Reduce split points and make them more "expressive", so that the optimizer can help us better.
- Prioritize use cases better and decide which modules can load async (without e.g. layout shift, etc.)

All in all: A lot of exciting refactorings :) and hopefully, the code base will become more efficient.

**Comment by elbotho** [comment]
Could you share your insights in a short meet session?

**Comment by Entkenntnis** [comment]
See slack :)
