### ISSUE TITLE
Notification count behaviour

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#815]
Test notification count. The display never seems to be right…

**Comment by elbotho** [comment]
Will continue working on this after https://github.com/serlo/api.serlo.org/issues/167 is fixed.
Manually revalidating the SWR cache  for the notification count after setting notifs to read is probably enough.

```
    void mutate('notificationsCount')
```

**Comment by inyono** [comment]
You probably want to use the unread filter here: https://github.com/serlo/frontend/blob/7abf7cf647df1548ac73e447ba87c4a7b6242ca4/src/components/user-tools/unread-notifications-count.tsx#L18.

**Comment by inyono** [comment]
Since this is already handled using `swr`, I'd be surprised if you actually have to do any cache invalidation yourself.

**Comment by elbotho** [comment]
> Since this is already handled using swr, I'd be surprised if you actually have to do any cache invalidation yourself.

Will check. Afaik requests with different keys don't trigger each.

**Comment by inyono** [comment]
> Will check. Afaik requests with different keys don't trigger each.

True. If the 60s invalidation is not enough, you'd might to invalidate it manually.

**Comment by elbotho** [comment]
> You probably want to use the unread filter here

Phew, was not as stupid as I thought :) I use the filter, that was just the type up there…

**Comment by elbotho** [comment]
probably caused by https://github.com/serlo/api.serlo.org/issues/235
