### ISSUE TITLE
Exercise has no breadcrumbs

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#817]
This https://frontend.serlo.org/mathe/139124/139124 has no breadcrumbs, but it should be part of

 Mathematik Abitur Bayern 2019 Geometrie, Teil B, Aufgabengruppe 1 Textaufgabe.

**Comment by elbotho** [comment]
Did some digging.
Data arrives.
Gets filtered out by this compat case:
https://github.com/serlo/frontend/blob/8ba21a7330a78f5a716dd8f0dfbf18c27ef866f8/src/fetcher/create-breadcrumbs.tsx#L33-L39

Not quite sure what is does so I'd leave the fix to you if that's alright :)

**Comment by Entkenntnis** [comment]
Ah yes, I remember that special case. I will investige this and see if it's still relevant.

**Comment by Entkenntnis** [comment]
The compat case is still necessary - but in case the breadcrumbs are empty, use this value instead of showing nothing.
