### ISSUE TITLE
Display topic groups in taxonomy view

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#818]
In legacy serlo.org viewing a taxonomy lists topic groups next to entities:

![Screenshot from 2021-01-22 10-50-06](https://user-images.githubusercontent.com/1327215/105729696-c64c7a80-5f2d-11eb-8c72-349ac7ba2e97.png)

It's about

![2021-01-21-173402_301x81_scrot](https://user-images.githubusercontent.com/1327215/105729721-cc425b80-5f2d-11eb-8ff4-1331c64e6957.png)

In the new frontend it is not shown:

![Screenshot from 2021-01-22 10-51-16](https://user-images.githubusercontent.com/1327215/105729752-d49a9680-5f2d-11eb-8830-92b1beec020e.png)

**Comment by Entkenntnis** [comment]
I remember a discussion that we don't want to mix content and taxonomy, e.g. we don't want to have exercises within topics, only in topicFolders.

**Comment by kulla** [comment]
That's true. This is about displaying a link to the topic group inside the taxonomy (the topic group has exercises, though).

**Comment by Entkenntnis** [comment]
The taxonomy can be confusing sometimes! What do you mean by "topic group"? Fracciones is a topic and should have no exercises (but it has, in this case) - and the link is pointing to "Fracciones".

The issue can be solved by adding a topicFolder inside of "Fracciones" and move the exercises there. This will show up in the taxonomy. Would this work in this case?

**Comment by kulla** [comment]
> The taxonomy can be confusing sometimes! What do you mean by "topic group"? Fracciones is a topic and should have no exercises (but it has, in this case) - and the link is pointing to "Fracciones".
> 
> The issue can be solved by adding a topicFolder inside of "Fracciones" and move the exercises there. This will show up in the taxonomy. Would this work in this case?

Yeah, that's the issue. Ping @jakobwes for the solution (create a new topic folder where you store the exercises in)
