### ISSUE TITLE
Overlong title is overflowing

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#834]
On mobile, this page https://de.serlo-staging.dev/community/145470/veranstaltungs%C3%BCbersicht has a title that overflows the page.

**Comment by elbotho** [comment]
Can't reproduce, could you add details / a screenshot?

**Comment by Entkenntnis** [comment]
Firefox (Desktop + Mobile):

![grafik](https://user-images.githubusercontent.com/13507950/106038067-c1c3c580-60d7-11eb-8420-d6eb5f109c58.png)
