### ISSUE TITLE
Div can't appear as descendant of p

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#839]
See here: http://localhost:3000/1697, related to lists, paragraphs and a math wrapper.

**Comment by elbotho** [comment]
I'm confused, shouldn't it be rendered as inline `Math` anyway?

**Comment by Entkenntnis** [comment]
I have a new branch where this issue is fixed (some buggy edge case of the converter)

**Comment by Entkenntnis** [comment]
This one is very bad: http://localhost:3000/1907, though

**Comment by Entkenntnis** [comment]
(also fixed on that branch)
