### ISSUE TITLE
Serlo-logo on /spenden-page not clickable

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#847]
Just a minor thing, but everywhere else on the page clicking on the Serlo-logo brings you to the homepage. I think for the sake of consistency this should also be the case on serlo.org/spenden.

**Comment by elbotho** [comment]
This is actually a "feature". The spenden page was once intentionally designed to make it a little bit hard to navigate away from.
I'm very open to change that but you should discuss this with @simonkoehl first.

**Comment by elbotho** [comment]
Closing this until there is an actionable todo :)
