### ISSUE TITLE
Default React import not needed any more

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#848]
According to [this](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) we could kick some `import React from 'react'` if we update some of our deps and config.

We might get `performance improvements and simplifications` 🚀 💥 

---

Also in future versions there will not be a default export any more, so changing to `import * as React from 'react'` or the (preferred) `import { useState } from 'react'` now is encouraged.

**Comment by Entkenntnis** [comment]
![grafik](https://user-images.githubusercontent.com/13507950/106356421-be128780-62ff-11eb-89b3-c45c71ec1df9.png)

We are good to go.
