### ISSUE TITLE
Content: ids for headers

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#85]
All headers (h1 to at least h4) should get an id automatically so they can be linked to directly. 

This is not a very common feature, but at least some internal links make use of that, so we should make sure to create the same ids as currently.

Example here: https://de.serlo.org/nachhaltigkeit/anbau/anzucht-aussaat/pflanzzeiten

**Comment by Entkenntnis** [comment]
yup, I will implement this - all existing ids should be working in the frontend.

**Comment by elbotho** [comment]
I can also try if you're still busy with the content types. Sounds doable :)

**Comment by inyono** [comment]
This is only true for content created with the legacy editor, though. Content created with the new editor does not have auto-generated ids (intentionally, since we have the anchor plugin for that)

**Comment by elbotho** [comment]
So what you're saying is that we could/should just not add it to the redesign?
Or how is the conversion going? :)

**Comment by Entkenntnis** [comment]
I will add this to the converter that parses the legacy state, this will lead to same behaviour on serlo.org
