### ISSUE TITLE
Review auth

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#851]
- [ ] When using multiple tabs, the actually used token may be stale (e.g. if it is was refreshed in another tab earlier). We should probably sync it with the current cookie value before doing the request.
- [ ] The login state itself should be a state instead of a ref (so that changes to it trigger a React update)

**Comment by Entkenntnis** [comment]
List of (imho minor) problems:

- If I log in from a tab, other tabs will sync after reload or navigation, same for logout. I haven't encounter strange states.
- Mutations (e.g. create comment) will fail, but show a message that you need to login

Nothing dramatic. I am not really sure how to fix these cases without actively polling the cookie: For the user, the mutation will fail anyway, the difference would be only if the client is handling it or the server response ...

Opinions here?

**Comment by elbotho** [comment]
Currently If I log in in one tab, the other tab just hides the user menu completely. 
Reload fixes it, but navigation not. Logout actually works better.
![image](https://user-images.githubusercontent.com/1258870/117970050-7e106700-b328-11eb-9239-abf5f24b763c.png)
Maybe we could solve that particular issue instead, but atm. it's … strange :)

**Comment by inyono** [comment]
Can look into that after the db layer bug hunting.

**Comment by Entkenntnis** [comment]
@elbotho Can confirm, this is happening in production - really strange. I have opened a separate issue for this and will close this general discussion.

(Feel free to open new issues for specific UX bugs)

**Comment by elbotho** [comment]
There is also a bug, where I'm logged in but the frontend does not show it. 
Not sure how to reproduce it yet.
