### ISSUE TITLE
Review Privacy Policy

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#86]
Things that might change (please add):

- [x] Google Web Fonts (self hosting is probably preferred and necessary for karmilla atm, Keep it for now!)
- [x] Matamo
- [x] Vercel
- [x] Cloudflare
- [x] GCS Integration

Who has experience with that? Who worked on it so far?

**Comment by inyono** [comment]
Apart from ZEIT Now, we already have everything in the privacy policy.

**Comment by kulla** [comment]
I can help with updating the privacy policy.

**Comment by elbotho** [comment]
@inyono Do you know that cloudflare and google custom search don't need to be there?
Couldn't find them.

**Comment by inyono** [comment]
You're right, they are missing. So yeah, we need those, too.

**Comment by inyono** [comment]
* Matomo

**Comment by kulla** [comment]
@elbotho There is currently a section with "Google Web Fonts". Did you mean in your first post to change it?

**Comment by elbotho** [comment]
@kulla in the redesign we will probably not use Google Fonts any more, but since we still use it's more of an backlog thing that we might remove it at some point.

**Comment by Entkenntnis** [comment]
Vercel Privacy Policy:

![grafik](https://user-images.githubusercontent.com/13507950/81020682-a4740a80-8e69-11ea-8740-76907256501b.png)
