### ISSUE TITLE
Lighthouse audit notes

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#87]
just a super quick summary. not complete.

---

**SEO**
should be enough:
- [x] increase footer tap target size: aim for 48x48px
- [x] [robots.txt](https://de.serlo.org/robots.txt)
- [ ] meta and graph tags ( see #64)

---

**Performance**
- i think biggest problem by far are images. Solutions: different sizes(!), maybe webp, and of course lots of svgs :)
- less dom elements! I think Katex is the biggest problem here.
- Katex: Do we lazy load formulas (@Entkenntnis)? Maybe even defer font loading with `rel="prefetch"` so browsers get it if they have time
- Main thread work: well… hard to improve right?
- TTFB sometimes quite long

--- 

**Accessibility**
- Too low contrast on all buttons is indeed a problem
- [Nice guide](https://developers.google.com/web/fundamentals/accessibility/how-to-review?utm_source=lighthouse&utm_medium=devtools) to check accessibility

---

**Best Practices***
💯 👍 

---

PWA looks good, would be doable.

**Comment by Entkenntnis** [comment]
Follow up for performance: #182, the remaining points are already handled in other issues, so closing this one
