### ISSUE TITLE
Include the complete cohesive exercise groups

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#882]
After https://github.com/serlo/serlo.org/pull/595 got merged and deployed: When an cohesive exercise group is included via an injection not only the exercise but also its subtasks and their solutions.

**Comment by Entkenntnis** [comment]
Nice! Do you also need some kind of visual indicator that the exercise group is cohesive?

**Comment by kulla** [comment]
> Nice! Do you also need some kind of visual indicator that the exercise group is cohesive?

Yes, we end up with changing the ordering from `<ul>` to `<ol>` in the subtasks

**Comment by Entkenntnis** [comment]
Some background info: Injections are using the same data fetching method as entity pages. This way, if we change the behaviour of a normal page view, injections will change in sync.

So the proposed change would be not to load a subexercise of a cohesive exercise (if accessed by id), but load the whole exercise instead. This can be achieved by a change in https://github.com/serlo/frontend/blob/staging/src/fetcher/request-page.ts (simliar to Course of Solution)

Hope this helps.

**Comment by kulla** [comment]
Actually when an exercise group is injected, always the full exercise with all sub exercises are injected. Thus we do not have to change anything :tada:
