### ISSUE TITLE
History view crashes if currentRevision is not present

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#885]
It currently happens here: https://frontend.serlo.org/entity/repository/history/3407 (see console.log)

**Comment by elbotho** [comment]
This content is deleted and trying to see the revision history of it also fails in legacy.
https://de.serlo.org/entity/repository/history/3405
So I guess the correct way to handle this is: Hide the button on deleted stuff?

**Comment by elbotho** [comment]
Can you remember how you got to that link?
In legacy I get redirected to https://de.serlo.org/mathe/3405/3405 (which is deleted).

**Comment by Entkenntnis** [comment]
I have constructed it manually because the history view is not yet activated.

**Comment by Entkenntnis** [comment]
Yeah, I have been working on this content, so the content is probably deleted now...

**Comment by elbotho** [comment]
I see! Could you add another id where this happens when you stumble upon one?

**Comment by Entkenntnis** [comment]
Follow up: #930
