### ISSUE TITLE
When to use new auth in frontend

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#886]
Currently, the frontend only allows using the old auth system in production. Now, we want to use the new auth also in production.

The frontend needs to know whether the user should get the old auth or the new auth, because the routes are different. We will probably use a placeholder for ssr and then check on the client if the frontend-cookie is available.

**Comment by inyono** [comment]
You should actually be able to use the new auth (even in production) since logging in via Hydra also logs you in via legacy auth.

**Comment by Entkenntnis** [comment]
Oh, I was probably a bit unclear ... the issue is about the `shouldUseNewAuth` feature flag that is controlling which auth system we are using. It's currently hard-coded to be false in production, we will need to add some more logic there. Otherwise I think the new auth system will work out fine in production.

**Comment by Entkenntnis** [comment]
Fixed with d2536a37e88a44799e89bf2f7cd3a65f1807b956
