### ISSUE TITLE
Comments are not immediately visible

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#890]
Starting threads is working very well know, but writing comments is not yet perfect: If you add a new comment, the answer is not immediately visible, but you have to reload to page (or trigger any other update). Happens consistently on staging for me.

**Comment by elbotho** [comment]
~wow, never saw that behaviour, will test as well.~
Hmm, can't reproduce... it's surprisingly fast for me. Random staging lag maybe? Could you try again?

**Comment by Entkenntnis** [comment]
It's not happening now for me anymore - looks like a random lag.
