### ISSUE TITLE
Invisible content and SEO

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#892]
At the moment, content that is not visible is also not rendered to html, e.g. solutions and spoilers.

This is very good for performance, but I am wondering if problems arise for SEO?

An alternative would be to render the content in the background, but hide it with css, so that crawlers can index all content.

Are there opinions about this?

**Comment by elbotho** [comment]
At this point I'd actually prefer the current behaviour. As I said in the call, I think we usually have enough keywords/content.
I guess the real question here is how many some users want to end up in exercise folders directly and not in articles for example.

**Comment by Entkenntnis** [comment]
I agree, the current solution has very good performance, especially for large topic folders (and we still have meta descriptions, etc...) - so let's leave it this way.
