### ISSUE TITLE
Bug in feedback rendering

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#893]
I think one of my refactoring has led to a regression at https://frontend.serlo.org/mathe/25621/aufgaben-zur-kombinatorik-im-typischen-sinn:

![grafik](https://user-images.githubusercontent.com/13507950/107743916-0ffcd980-6d12-11eb-9952-3c5e92b4efec.png)

Feedback is rendered as Paragraph, but is expected to be more span-like.

**Comment by Entkenntnis** [comment]
@elbotho The feedback can be any content I think, so can we modify `feedback.tsx` so that it also works for block content?

**Comment by elbotho** [comment]
Thb I'd prefer some restrictions in edtr.io here. This should be a single line.
Maybe with a link, but def. nothing else.

**Comment by Entkenntnis** [comment]
Sometimes math formulas or images can be useful, though - I think atm there is no restriction.

**Comment by elbotho** [comment]
I think the feedback should emotional (funny, encouraging, motivating) first of all. Maybe a little hint on wrong answers.
But then is probably not the right place for this discussion.

**Comment by Entkenntnis** [comment]
I checked again, the feedback is limited to a text-block already in the new edtr-io, so we are good to go here.

Edit: Ok, sadly not quite, because the text-plugin allows multi-line content.

**Comment by elbotho** [comment]
Alright, I can work with that 😄  👍
