### ISSUE TITLE
Implement "Einstieg für Lehrkräfte" and "Einstieg für Eltern"-buttons on es.serlo.org starting-page (similar to de.serlo-org-one)

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#904]
- "Einstieg für Eltern": "Información para los padres" - page: ~~https://es.serlo.org/19504~~ https://es.serlo.org/195616/p%C3%A1gina-de-inicio-para-padres
- "Einstieg für Lehrer:innen": "Información para docentes" - page: ~~https://es.serlo.org/195043~~ https://es.serlo.org/195618/p%C3%A1gina-de-inicio-para-docentes

Pages are ~~nearly~~ ready ~~and will be finalized in the next days~~.

**Comment by LinaMaria-ES** [comment]
Thank you, it looks amazing!
- Lina
