### ISSUE TITLE
show secondary menu on static/taxonomy pages

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#91]
include subject sub menu in
- taxonomy views
- static pages within subjects

don't include it in any content page

**Comment by inyono** [comment]
The API exposes the navigation data (of the active "subject") now via `navigation.data` on TaxonomyTerm as serialized JSON, e.g.
```graphql
{
  uuid(id:1855) {
    ...on Article {
      taxonomyTerms {
        navigation {
          data
        }
      }
    }
  }
}
```
