### ISSUE TITLE
Bug: Input Exercise does not accept right answer

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#911]
https://de.serlo.org/188902 Teilaufgabe d)

In the legacy system the answer gets accepted
![Screenshot_2021-02-23 Die Länge](https://user-images.githubusercontent.com/46370375/108816913-54f8f980-75b7-11eb-90e6-536b452dd1a8.png)

The now frontend does not
![Screenshot_2021-02-23 Die Länge - lernen mit Serlo ](https://user-images.githubusercontent.com/46370375/108816932-5f1af800-75b7-11eb-94bc-c85bd1cd26e1.png)

**Comment by Entkenntnis** [comment]
Yes, confirmed.

**Comment by elbotho** [comment]
@yolo-bird thanks for reporting this. 
there are answers for both "2,5" and "2,50" which is:
- unnecessary
- confuses our implementation
but obviously:  
- should not confuse our implementation ;)
- will be fixed soon.

**Comment by Entkenntnis** [comment]
is fixed: https://de.serlo-staging.dev/mathe/188902/188902
