### ISSUE TITLE
highlight first taxonomy "parent" more

### ISSUE THREAD

**Issue by simonkoehl** [serlo/frontend#92]
on mobile screen size the first taxonomy "parent" already is highlighted as a kind of button

it should also be highlighted on bigger screen sizes where we show the complet taxonomy.

An content pages we could additionally communicate the role of the first taxonomy "parent" e.g. like this:

"Zur Themenübersicht: _taxonomy title_"

**Comment by simonkoehl** [comment]
@Entkenntnis I put some more thought into this:
A) the only important and may be frequent use case for "walking up" the taxonomy is from learning content on step up to the "topic overview"
B) Generally I think it will offer orientation to our users if they can differentiate between taxonomy and content pages.

Thus imo we should highlight the next taxonomy parent only in case of A and then we should highlight it strongly. My suggestion is to display the taxonomy parent like on mobile as button and in new line also on desktop. Also lets not highlight any taxonomy parents on taxonomy pages. I think you build this solution already in one of your first drafts, that we discussed on Slack.

![image](https://user-images.githubusercontent.com/3379377/80534238-3928c500-899f-11ea-9422-de6d0e63d2a3.png)

**Comment by Entkenntnis** [comment]
moved to #415
