### ISSUE TITLE
Remaining 500 errors

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#929]
This is the current list of ids that are not available:

- [x] Error Code 500 { id: '1605', converted: false }
- [x] Error Code 500 { id: '1631', converted: true }
- [x] Error Code 500 { id: '1641', converted: false }
- [x] Error Code 500 { id: '1649', converted: false }
- [x] Error Code 500 { id: '1885', converted: false }
- [x] Error Code 500 { id: '1963', converted: false }
- [x] Error Code 500 { id: '3357', converted: true }
- [x] Error Code 500 { id: '4973', converted: false }
- [x] Error Code 500 { id: '4995', converted: true }
- [x] Error Code 500 { id: '6797', converted: true }
- [x] Error Code 500 { id: '7281', converted: true }
- [x] Error Code 500 { id: '7849', converted: true }
- [x] Error Code 500 { id: '7875', converted: true }
- [x] Error Code 500 { id: '9049', converted: false }
- [x] Error Code 500 { id: '9137', converted: false }
- [x] Error Code 500 { id: '9295', converted: false }
- [x] Error Code 500 { id: '10791', converted: true }
- [x] Error Code 500 { id: '13205', converted: true }
- [x] Error Code 500 { id: '13217', converted: true }
- [x] Error Code 500 { id: '13261', converted: true }
- [x] Error Code 500 { id: '13355', converted: true }
- [x] Error Code 500 { id: '18822', converted: true }
- [x] Error Code 500 { id: '22266', converted: false }
- [x] Error Code 500 { id: '22289', converted: false }
- [x] Error Code 500 { id: '22292', converted: false }
- [x] Error Code 500 { id: '24405', converted: true }
- [x] Error Code 500 { id: '32573', converted: true }
- [x] Error Code 500 { id: '33998', converted: false }
- [x] Error Code 500 { id: '34009', converted: false }
- [x] Error Code 500 { id: '39391', converted: true }
- [x] Error Code 500 { id: '39540', converted: true }
- [x] Error Code 500 { id: '43433', converted: false }
- [x] Error Code 500 { id: '43455', converted: false }
- [x] Error Code 500 { id: '50994', converted: true }
- [x] Error Code 500 { id: '52806', converted: true }
- [x] Error Code 500 { id: '57486', converted: false }
- [x] Error Code 500 { id: '58302', converted: true }
- [x] Error Code 500 { id: '61509', converted: true }
- [x] Error Code 500 { id: '61743', converted: true }
- [x] Error Code 500 { id: '68137', converted: false }
- [x] Error Code 500 { id: '69587', converted: false }
- [x] Error Code 500 { id: '74888', converted: false }
- [x] Error Code 500 { id: '75055', converted: false }
- [x] Error Code 500 { id: '75632', converted: false }
- [x] Error Code 500 { id: '75755', converted: true }
- [x] Error Code 500 { id: '76032', converted: true }
- [x] Error Code 500 { id: '81591', converted: true }
- [x] Error Code 500 { id: '82313', converted: true }
- [x] Error Code 500 { id: '82315', converted: true }
- [x] Error Code 500 { id: '88461', converted: true }
- [x] Error Code 500 { id: '89266', converted: true }
- [x] Error Code 500 { id: '91254', converted: true }
- [x] Error Code 500 { id: '100199', converted: true }
- [x] Error Code 500 { id: '103048', converted: true }
- [x] Error Code 500 { id: '106986', converted: false }
- [x] Error Code 500 { id: '106989', converted: false }
- [x] Error Code 500 { id: '106994', converted: false }
- [x] Error Code 500 { id: '106999', converted: false }
- [x] Error Code 500 { id: '107013', converted: false }
- [x] Error Code 500 { id: '107241', converted: false }
- [x] Error Code 500 { id: '108286', converted: true }
- [x] Error Code 500 { id: '113632', converted: true }
- [x] Error Code 500 { id: '114042', converted: false }
- [x] Error Code 500 { id: '127832', converted: true }
- [x] Error Code 500 { id: '128444', converted: true }
- [x] Error Code 500 { id: '128636', converted: false }
- [x] Error Code 500 { id: '129359', converted: true }
- [x] Error Code 500 { id: '143571', converted: true }
- [x] Error Code 500 { id: '159668', converted: true }
- [x] Error Code 500 { id: '160616', converted: true }
- [x] Error Code 500 { id: '166219', converted: true }
- [x] Error Code 500 { id: '174987', converted: true }
- [x] Error Code 500 { id: '175764', converted: true }
- [x] Error Code 500 { id: '179741', converted: true }
- [x] Error Code 500 { id: '183235', converted: true }
- [x] Error Code 500 { id: '185671', converted: true }
- [x] Error Code 500 { id: '187487', converted: true }
- [x] Error Code 500 { id: '193828', converted: true }

**Comment by inyono** [comment]
All fixed.

**Comment by Entkenntnis** [comment]
Wow, very nice :rocket:
