### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#93]
Simple guide to get started:
https://developers.google.com/web/fundamentals/accessibility/how-to-review?utm_source=lighthouse&utm_medium=devtools

Tool:
https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp

**Comment by Entkenntnis** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Accessibility

**Comment by elbotho** [comment]
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

**Comment by Entkenntnis** [comment]
We should probably define subgoals, like: ensure keyboard navigation works, or: tests frontend with screenreader software, ...

**Comment by Entkenntnis** [comment]
One follow up issue: #416. Otherwise, this issue is quite general and can be closed.
