### ISSUE TITLE
course icon not supported

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#931]
In the legacy system, courses has an additional icon property for every course page, e.g. explanation, exercise, etc.

This is currently not supported in the frontend. Do we want to include this feature? I'm not quite sure, because it's something barely noticable.

**Comment by elbotho** [comment]
what do you mean by "additional icon property"? Could you add a screenshot?

**Comment by Entkenntnis** [comment]
https://de.serlo-staging.dev/mathe/43180/%C3%BCbersicht

![grafik](https://user-images.githubusercontent.com/13507950/109943977-0560af00-7cd6-11eb-8cd9-7e0f8c9d558e.png)

**Comment by elbotho** [comment]
ah thanks! 
always found that feature confusing in the old design tbh. 
I'd leave it out.

**Comment by Entkenntnis** [comment]
Decision was to leave them out.
