### ISSUE TITLE
In several language versions when clicking on the top right menu I get rerouted to the english-pages

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#937]
Eg. in fr.serlo.org when clicking on the top-right menu I am still in the french version, but the english /serlo-page is shown, instead of the french one (https://fr.serlo.org/serlo). Same behavior in ~hi.serlo.org~ and ta.serlo.org (there it is maybe okay), but not in Spanish as far as I know.

**Comment by elbotho** [comment]
@jakobwes This can easily be changed.
The French menu in defined here:
https://github.com/serlo/frontend/blob/staging/src/data/fr/menu-data.ts

Currently it's supposed to use the english version. 
You can send me a list of links that have versions in the target language and I'll update them, or you have a go at editing this yourself :)

Other language files: https://github.com/serlo/frontend/tree/staging/src/data

**Comment by jakobwes** [comment]
Oh I didn't know about these config-files. I thought the menu was still done via the backend. 

I just created three PRs updating the ids/links in different language-versions. When merged then everything should be up-to-date (maybe only in Hindi some translations were added to the Crowdin-files, so we could also update those). Hope I made no mistake/misunderstodd no parameter :)

**Comment by elbotho** [comment]
@jakobwes Thank you very much! Just merged your PRs, looked good.
Feel free to suggest changes to those files any time.

This means it should be testable on http://serlo-staging.dev/ 
Next deployment to production will probably be on Monday.

Translations should be up to date (This happend semi-automatic).
 Are you missing something that happened more than a few hours ago?

**Comment by Entkenntnis** [comment]
@jakobwes Welcome to the frontend :grinning:
