### ISSUE TITLE
https://de.serlo.org/biologie/26201/kompetenzen-in-der-biologie is linked at several places, but clicking on it gives error

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#938]
Eg. in https://de.serlo.org/biologie/71166/aufgaben-richtig-bearbeiten if one clicks on the taxonomy-tree or here: https://de.serlo.org/biologie/23362/biologie if one clicks on the item

**Comment by elbotho** [comment]
Also works for me, maybe cache issue.
 Does it work for you now?

**Comment by jakobwes** [comment]
Hmm weird now it works for me again. Maybe really cache.
