### ISSUE TITLE
Highlight solution strategy in exercises

### ISSUE THREAD

**Issue by kathongi** [serlo/frontend#939]
For pupils there is no destinction between solution strategy and the solution itself in exercise solutions. This leads to some strange wording and repeating solutions e.g https://de.serlo.org/69128 

We need some kind of highlighting for the solution strategy. I thought of a box around the strategy and a small title "Lösungsstrategie". But maybe Botho has a better idea.

**Comment by elbotho** [comment]
Sorry, I don't get it. In this example – what is the solution and what the solution strategy?
And is that a technical distinction or one created by the authors according to the guidelines?

**Comment by kathongi** [comment]
Click "edit" and you'll see it. 

![image](https://user-images.githubusercontent.com/44167220/111353010-22599280-8685-11eb-9334-83c9a512b95b.png)

Authors have the possibility to write a solution strategy in an extra field above the solution itself. In this example the strategy is "Versuche das Vieleck in Formen zu zerlegen, deren Flächeninhalt du leicht berechnen kannst." and the solution starts below. In the saved version there is no visual separation between those 2 fields.

**Comment by Entkenntnis** [comment]
Solution strategy is also not highlighted by edtr-io renderer (and I'm not aware of any design drafts for it)

Maybe another candidate for https://trello.com/b/M2QlFMxN/serlo-softwarew%C3%BCnsche and ask the community about there opinion.
@kathongi @yolo-bird

**Comment by kathongi** [comment]
Why has the issue been closed? We often see that authors use the wrong field to fill in their solution, by mistake. Reviewers (and authors) can't see those mistakes because the strategy isn't highlighted. It's important for our quality management to be able to distinguish between these fields - not only in the editor.

**Comment by Entkenntnis** [comment]
@kathongi At the moment nobody is working on this issue (and it's not a bug) - so I have closed it. But you can add it to the trello board, so we can keep track of it, otherwise it will just linger here. If we start working on it, we can reopen this issue.

**Comment by Entkenntnis** [comment]
As this issue is somewhat annoying, I have added a (rather simple) quickfix. This is only for the frontend and reusing existing elements, in this case the important plugin, will be live soon.

Note: Not visible in edtr-io and therefore in the legacy system or while reviewing, so limiting the usability of the quickfix. Adding it to the edtr-io is out of the scope of this repo, in this case the issue should be transfered.

**Comment by kathongi** [comment]
Sounds great @Entkenntnis!
