### ISSUE TITLE
https://de.serlo.org/mathe/146870/schlau-werkstatt can't be shown in new frontend

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#941]
I get redirected to the old one.

**Comment by elbotho** [comment]
works for me, could you check again?
Maybe in a new private window to make sure you are not logged in or have a cookie set?

**Comment by jakobwes** [comment]
Super weird. I checked in a private tab, but when rechecking now it works again. I also had a similar encounter in es.serlo.org today and on some other Serlo-pages in the last days, where some links give an error sometimes, but then when reloading/when checking after some time the page it is there. Nothing that seems systematic yet, but maybe something to observe,

**Comment by elbotho** [comment]
thanks for reporting, feel free to post links if it occurs again.
might be related to a bug we have with the new database layer. closing this for now since there is nothing we can do about it in the frontend for now.
