### ISSUE TITLE
Syntax highlighting in code missing

### ISSUE THREAD

**Issue by Knorrke** [serlo/frontend#947]
The edtr.io code plugin did have syntax highlighting but it's missing in the new frontend. 
see e.g. https://de.serlo.org/59135

Legacy System:
![working syntax highlighting](https://user-images.githubusercontent.com/11499926/111900384-a23f7e00-8a32-11eb-8210-e16551c94145.png)

New Frontend:
![Missing syntax highlighting ](https://user-images.githubusercontent.com/11499926/111900416-c4390080-8a32-11eb-95c1-f9d3e299ebb5.png)|

Is the plugin reimplemented somewhere here? IIRC edtr.io is dynamically loading the syntax definition and color scheme, maybe that is also causing problems in the new setup.

**Comment by inyono** [comment]
Looking at https://github.com/serlo/frontend/blob/545e906bc3170574188face5bd24c849520a1ada/src/components/content/code.tsx, it seems like the frontend implementation doesn't have syntax highlighting yet.

**Comment by Entkenntnis** [comment]
Added the syntaxhighlighter into the frontend: https://frontend-git-add-syntax-highlighting-serlo.vercel.app/59135

@Knorrke @elbotho Do you have feedback? I have mixed up both designs.

**Comment by elbotho** [comment]
Did not find many test cases.
But this one looks good 👍 thank you.

**Comment by Knorrke** [comment]
@Entkenntnis Thank you! Looks great :-)

For reference here is another test case with java: https://frontend-git-add-syntax-highlighting-serlo.vercel.app/70106 (Solutions to exercises c, e, h, and i)
