### ISSUE TITLE
Embedding of subject channels from community.serlo.org into serlo.org

### ISSUE THREAD

**Issue by kathongi** [serlo/frontend#950]
At the moment authors have problems finding specific subject channels in the community chat like [#mathe](https://community.serlo.org/channel/mathe) or [#nachhaltigkeit](https://community.serlo.org/channel/nachhaltigkeit). After several positive feedback from our community we want to test a new feature. We want to test if more authors will join our chat and/or specific channels in the community chat by embedding the chats #mathe and #nachhaltigkeit via iframe into serlo.org. 

The navigation panel on the left in the subject "Mathe" und "Angewandte Nachhaltigkeit" should be extended by the navigation item "Chat für Mathe-Autor\*innen" respectively "Chat für Nachhaltigkeits-Autor\*innen". With a click on the button users can see #mathe/#nachhaltigkeit via iframe integration on serlo.org. 

**Mockup**
![Fachchat Integration auf serlo org](https://user-images.githubusercontent.com/44167220/112457715-522b2900-8d5c-11eb-902c-b3a677879a28.png)

More information: https://docs.google.com/document/d/1YewUkZTx2GU7lEaNeLdau2dOE7kesw3IAkOnaTPpfDo/edit#

**Comment by elbotho** [comment]
I will have a look at this.
@kathongi should I direct questions at you or at kulla?
Ah and I probably need access to the rocket chat settings.

**Comment by kulla** [comment]
> @kathongi should I direct questions at you or at kulla?

Technical questions to me. Questions about the implementations to @kathongi

**Comment by kulla** [comment]
@kathongi: we will only implement this feature in the new design. Thus, currently only not logged in user would see this. Is this okay for the test or is it necessary that also logged in user see the chat?

**Comment by elbotho** [comment]
@kathongi okay first test is up (mathe only):
https://frontend-git-chat-integration-mockup-serlo.vercel.app/mathe/chat

**Comment by kathongi** [comment]
We don't need to implement the feature in the old design. But for our test it's also important that users can write in the chat and that is only possible if you are logged in with your serlo account. Therefore we test what is possible and for the rest we wait for the new frontend for logged in users. 

I also tested the first implementation:

1. I had a problem if I'm not logged in and wanted to join the chat. This happened https://www.loom.com/share/daca3b9468664e7da5472afca22e34ed 
(and now I can't join the chat again... -.- @elbotho did you change some settings? or is it a rocket chat bug?)

2. If I'm logged in I don't want to have the option to change the channels or write a private message in the embedded chat. Instead I'd like to switch to a new tab if I leave #mathe.

**Comment by elbotho** [comment]
Currently this is not possible across browsers because of an Issue with Rocket.Chat and new chrome security settings around third party cookies: https://github.com/RocketChat/Rocket.Chat/issues/15616
Weirdly the issue only occurs for users that are not logged in in Rocket.Chat already.

Since it would probably affect most of the users I don't think a test would be very useful.

**Comment by kathongi** [comment]
Damn.. What are the next steps now? Do we have to wait for a rocket chat update? Are there any other options for users that are not logged in we could try?

**Comment by elbotho** [comment]
Yes, we have to wait or do a lot more work than I think is feasible at this point (fix the bug ourselves / do some fancy auto-logging in magic?).

**Comment by kulla** [comment]
> Yes, we have to wait or do a lot more work than I think is feasible at this point (fix the bug ourselves / do some fancy auto-logging in magic?).

How about adding the link to the navigation which opens the url https://community.serlo.org/channel/mathe directly instead of having a page with an iframe? For a mvp this would be already an easy solution and we can fire a simple analytics event whenever the link is opened to get feedback

**Comment by kathongi** [comment]
> > Yes, we have to wait or do a lot more work than I think is feasible at this point (fix the bug ourselves / do some fancy auto-logging in magic?).
> 
> How about adding the link to the navigation which opens the url https://community.serlo.org/channel/mathe directly instead of having a page with an iframe? For a mvp this would be already an easy solution and we can fire a simple analytics event whenever the link is opened to get feedback

@elbotho suggested the same. I will discuss it with Corinna and Anne but for a MVP I think it's ok.

**Comment by kathongi** [comment]
We talked about the MVP today. Just a link to the chat channel in the navigation is fine for the first test. Am I right that I can change the navigation in de.serlo.org/backend or is there anything else we need to change?

**Comment by elbotho** [comment]
Yes I think that should work!
Thanks for the compromise, if the test is successful we can think about a deeper integration again and hopefully the bug is fixed by then or we have a better understanding of it :)

**Comment by kathongi** [comment]
I close the issue now and open or reopen it for a deeper integration when the first tests are positive (and the bugs are hopefully fixed)
