### ISSUE TITLE
Add noindex meta-tag for content in "Sandkasten"

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#952]
Avoid google indexing unfinished or unpolished content of the playground by adding a noindex meta-tag.

**Comment by elbotho** [comment]
I think it would be easier. to add it to robots.txt instead.
atm. still part of serlo.org repo:
https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/public/robots.txt

**Comment by Entkenntnis** [comment]
In principle, yes, but with the new alias system, we can't tell if a path is within the sandkasten or not, because they all belong to "/community/"

**Comment by elbotho** [comment]
I see!
