### ISSUE TITLE
Add activity log for content sites

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#953]
After https://github.com/serlo/serlo.org-database-layer/issues/84 and https://github.com/serlo/api.serlo.org/pull/299 got merged / closed: The activity log for content site can be implemented. You can use one the endpoint `AbstractUuid.events` for this https://github.com/serlo/api.serlo.org/blob/21670a88749e3b62dd1c5896d92ca3f8bf441bc3/src/schema/uuid/abstract-uuid/types.graphql#L5-L12

Current example: https://de.serlo.org/event/history/1627
![2021-04-08-185811_1110x758_scrot](https://user-images.githubusercontent.com/1327215/114066781-61ea5780-989c-11eb-8b20-c8aeda9fc27a.png)

**Comment by Entkenntnis** [comment]
~This is now live.~

Ups - it's available in the API, but is not yet implemented in the database layer. -> still pending

**Comment by Entkenntnis** [comment]
As far as I can see, this is not part of any priority list, so I am closing this.
