### ISSUE TITLE
Add page with last activities (event log)

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#954]
After serlo/serlo.org-database-layer#84 and serlo/api.serlo.org#299 got merged / closed: The page with the last activities (currently https://de.serlo.org/event/history ) can be implemented. Here you can use the endpoint https://github.com/serlo/api.serlo.org/blob/21670a88749e3b62dd1c5896d92ca3f8bf441bc3/src/schema/notification/types.graphql#L16-L24

![2021-04-08-190051_999x804_scrot](https://user-images.githubusercontent.com/1327215/114067127-c1486780-989c-11eb-9b4a-47f576dd9985.png)

**Comment by Entkenntnis** [comment]
~This is now live.~

Ups - it's available in the API, but is not yet implemented in the database layer. -> still pending

**Comment by kulla** [comment]
> ~~
> 
> Ups - it's available in the API, but is not yet implemented in the database layer. -> still pending

Yep: https://github.com/serlo/serlo.org-database-layer/issues/84 is the remaining blocker

**Comment by Entkenntnis** [comment]
This looks like a part of https://github.com/serlo/frontend/issues/935,

Beside that, it's not part of our current priority.
