### ISSUE TITLE
show edit button for unrevised content

### ISSUE THREAD

**Issue by kathongi** [serlo/frontend#956]
In "Begleitung" we decided to show an edit button for unrevised content in the reviewer view. The edit button should be visible for all logged in users just like the regular edit button is shown for other (revised) entities. The feature helps reviewers and authors to navigate more easily because it isn't self explanatory that the top left arrow "<" leads to the editing history where you can edit the latest version.

It should look similiar to this: 
![edit in review mode](https://user-images.githubusercontent.com/44167220/114181772-3621ad00-9942-11eb-9e34-378890233a21.png)
(except changes in the reviewer view in general)

**Comment by Entkenntnis** [comment]
This feature wouldn't be to hard to add, maybe someone can add to to "Geplant" in https://trello.com/b/M2QlFMxN/serlo-softwarew%C3%BCnsche.

@kathongi @yolo-bird

**Comment by kathongi** [comment]
finished: https://trello.com/c/mpAMB6Eo/20-editieren-aus-der-reviewansicht-f%C3%BCr-noch-nicht-freigegebene-inhalte

**Comment by elbotho** [comment]
@kathongi the feature you are talking about is the "Erstelle eine Bearbeitung von dieser Bearbeitung aus" in the revision overview, right?

**Comment by kathongi** [comment]
Probably. Don't know what the revision overview is. Where can I find it?

**Comment by elbotho** [comment]
Sorry, "Bearbeitungsverlauf": http://serlo.org/entity/repository/history/1495

**Comment by kathongi** [comment]
Ah! :D The feature has the same functionality as "Erstelle eine Bearbeitug von dieser Bearbeitung aus" but the button is on a different page visible - not only in the "Bearbeitungsverlauf", also in the unrevised version of the content.

**Comment by elbotho** [comment]
Thank you for clarifying! Should we also show it for the accepted revision (as we do in the overview)?

**Comment by kathongi** [comment]
Yes, sounds good to me. 👍 

I'm not sure about it but I think Wolfgang and Kulla also discussed this feature yesterday. Do you want to add some feature details? @kulla @yolo-bird

**Comment by elbotho** [comment]
Okay, feature is on the way! ([Example](https://frontend-git-edit-on-revision-preview-serlo.vercel.app/entity/repository/compare/1555/150196)). But it will take some time before actually use the frontend version of this page for authors.

**Comment by ghost** [comment]
@elbotho In the discussion with @kulla yesterday, it turned out that there are actually some tricky corner cases involved with this button. I'm little short on time today to get all details down in an understable way. Might we talk after the dev meeting next monday about this?
