### ISSUE TITLE
Spoiler content breaks layout

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#957]
Opening first spoiler ("Welches Dateiformat ist das Richtige?") on https://de.serlo.org/90412 breaks layout.

**Comment by elbotho** [comment]
@Entkenntnis could you replicate the changes I did [in staging](https://de.serlo-staging.dev/community/90412/bilder-und-grafiken) (move spoiler and the textline below out of the multimedia box) in production (I don't have the rights)?
I think this manual fix is quite okay in this case (super wide table in half width column is just not a good idea).

**Comment by Entkenntnis** [comment]
Thanks for the hint - I have fixed this on production.

Agree - flexbox and super-wide content is sometimes messy :)
