### ISSUE TITLE
formulas in spoiler heading

### ISSUE THREAD

**Issue by kathongi** [serlo/frontend#958]
We need formulas in spoiler headings for subjects like math, chemistry and physics. At the moment it's only possible to write text in the heading.

**Comment by elbotho** [comment]
Is this a frontend or edtr issue?

**Comment by inyono** [comment]
> Is this a frontend or edtr issue?

Since Frontend does its own rendering, this will definitely also be an Frontend issue. IIRC correctly, Edtr.io has the spoiler title as a string (instead of rich text), so this is an Edtr.io feature request, too.

**Comment by Entkenntnis** [comment]
It's probably good to put this into https://trello.com/b/M2QlFMxN/serlo-softwarew%C3%BCnsche

**Comment by kathongi** [comment]
@yolo-bird what do you think? It's rather a small bug fix than an interesting feature for authors.
