### ISSUE TITLE
Font size problem on mobile

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#970]
e.g. https://de.serlo.org/173573. Different zooming levels of text:

![grafik](https://user-images.githubusercontent.com/13507950/115056022-9a181880-9ee2-11eb-8657-cfe682c1fde6.png)

**Comment by elbotho** [comment]
can't reproduce. can someone reproduce and add browser/device info?

**Comment by Entkenntnis** [comment]
@kathongi Is this still happening for you? It's maybe a one-time glitch.

**Comment by kathongi** [comment]
I opened the page above just now and it looked perfectly fine. Font sizes seemed normal. Maybe some bugs just need some time to die naturally :D

**Comment by elbotho** [comment]
That's the kind of evolution we like ;)
