### ISSUE TITLE
Show breadcrumb when showing standalone video, applet, course

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#99]
Show breadcrumbs in standalone view:

e.g.
https://frontend.dal123.now.sh/mathe/zahlen-gr%C3%B6%C3%9Fen/proportionalit%C3%A4t-dreisatz/direkte-proportionalit%C3%A4t---mathematisch,-bananisch

**Comment by elbotho** [comment]
Tried to solve, but no breadcrumb-entries coming from API for those types.
@Entkenntnis do you know if they are just not exported or if we don't save them?

**Comment by Entkenntnis** [comment]
will take a look!

**Comment by inyono** [comment]
The API exposes the breadcrumbs via `taxonomyTerms.path`, e.g.
```
{
  uuid(alias: {instance:de, path:"/mathe/zahlen-größen/proportionalität-dreisatz/direkte-proportionalität---mathematisch,-bananisch"}) {
    id
    ... on Video {
      taxonomyTerms {
        path {
          id
          name
        }
      }
    }
  }
}
```
In the next API release, this will also contain the navigation
