### ISSUE TITLE
New API currentUserHasSubscribed()

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#999]
In staging the new API is deployed:

```graphql
extend type Query {
  subscription: SubscriptionQuery!
}

type SubscriptionQuery {
  currentUserHasSubscribed(id: Int!): Boolean!
}
```

This might be used to shorten some requests in the frontend. See also 
![2021-05-10-101102_896x572_scrot](https://user-images.githubusercontent.com/1327215/117634614-60ec6480-b17f-11eb-80b2-b3b3d4dbbb07.png)

**Comment by elbotho** [comment]
Thank you @kulla
